Repository eProsima/Fast-DDS, pull requests merged in 2020-12, with the labels that each got.

#1636 Fix path on boost qnxnto.hpp
  thirdparty/boost/include/boost/config/platform/qnxnto.hpp
Labels: skip-ci

#1642 Add new APIs returning unsupported [10143]
  include/dds/core/detail/InstanceHandle.hpp
  include/fastdds/dds/core/Entity.hpp
  include/fastdds/dds/core/policy/QosPolicies.hpp
  include/fastdds/dds/core/status/DeadlineMissedStatus.hpp
  include/fastdds/dds/core/status/LivelinessChangedStatus.hpp
  include/fastdds/dds/core/status/PublicationMatchedStatus.hpp
  include/fastdds/dds/core/status/SampleRejectedStatus.hpp
  include/fastdds/dds/core/status/SubscriptionMatchedStatus.hpp
  include/fastdds/dds/domain/DomainParticipant.hpp
  include/fastdds/dds/publisher/DataWriter.hpp
  include/fastdds/dds/publisher/Publisher.hpp
  include/fastdds/dds/subscriber/DataReader.hpp
  include/fastdds/dds/subscriber/SampleInfo.hpp
  include/fastdds/dds/subscriber/Subscriber.hpp
  include/fastdds/dds/subscriber/qos/DataReaderQos.hpp
  include/fastdds/dds/topic/TopicDataType.hpp
  include/fastdds/dds/topic/TypeSupport.hpp
  include/fastrtps/TopicDataType.h
  include/fastrtps/qos/DeadlineMissedStatus.h
  include/fastrtps/qos/LivelinessChangedStatus.h
  include/fastrtps/qos/SampleRejectedStatus.hpp
  src/cpp/fastdds/domain/DomainParticipant.cpp
  src/cpp/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/fastdds/domain/DomainParticipantImpl.hpp
  src/cpp/fastdds/publisher/DataWriter.cpp
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/publisher/DataWriterImpl.hpp
  src/cpp/fastdds/subscriber/DataReader.cpp
  src/cpp/fastdds/topic/TypeSupport.cpp
Labels: no-aarch, no-test

#1654 Set all log levels to Error in examples
  examples/C++/DDS/HelloWorldExampleSharedMem/HelloWorld_main.cpp
  examples/C++/DDS/SecureHelloWorldExample/HelloWorld_main.cpp
  examples/C++/DynamicHelloWorldExample/HelloWorld_main.cpp
  examples/C++/HelloWorldExampleSharedMem/HelloWorld_main.cpp
  examples/C++/SecureHelloWorldExample/HelloWorld_main.cpp
Labels: no-test
