Repository eProsima/Fast-DDS, pull requests merged in 2020-10, with the labels that each got.

#1436 Clear changes to release [9483]
  src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
Labels: no-test

#1431 Server is acked by default in DDB [9470]
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryEndpointInfo.hpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantInfo.hpp
  src/cpp/rtps/builtin/discovery/database/DiscoverySharedInfo.cpp
  src/cpp/rtps/builtin/discovery/database/DiscoverySharedInfo.hpp
Labels: no-test

#1432 Server DATA(p) acked just checked when necessary [9472]
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
Labels: no-test

#1440 Server dedicated thread for routine processing [9488]
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPServer2.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPServerListeners2.cpp
  src/cpp/rtps/builtin/discovery/participant/DServerEvent2.cpp
  src/cpp/rtps/builtin/discovery/participant/DServerEvent2.hpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer2.hpp
  src/cpp/rtps/builtin/discovery/participant/PDPServerListener2.cpp
Labels: no-test

#1459 Quick fix in is_writer and is_reader in DDB
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
Labels: no-test

#1442 Server periodic announcements [9490]
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataQueueInfo.hpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryEndpointInfo.hpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantChangeData.hpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantInfo.cpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantInfo.hpp
  src/cpp/rtps/builtin/discovery/database/DiscoverySharedInfo.cpp
  src/cpp/rtps/builtin/discovery/database/DiscoverySharedInfo.hpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPServerListeners2.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer2.hpp
  src/cpp/rtps/builtin/discovery/participant/PDPServerListener2.cpp
Labels: no-test

#1445 Server DDB: Check sample id on ack [9496]
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
Labels: no-test

#1462 Discovery Server: Removed unnecessary find in create_readers/writers_from_change
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
Labels: no-test

#1449 Discovery Server: New design for process disposals [9499]
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryEndpointInfo.hpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantInfo.cpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantInfo.hpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantsAckStatus.cpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantsAckStatus.hpp
  src/cpp/rtps/builtin/discovery/database/DiscoverySharedInfo.hpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
Labels: no-test

#1467 [Discovery Server] Identify writers and readers only with values valid in RTPS specification
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
Labels: no-test

#1447 Do not relay on first reader only to decode encrypted message [9502]
  include/fastdds/rtps/messages/MessageReceiver.h
  src/cpp/rtps/messages/MessageReceiver.cpp
Labels: no-test

#1476 RTPS reader creation with custom payload pool [9494]
  include/fastdds/rtps/RTPSDomain.h
  include/fastdds/rtps/history/IPayloadPool.h
  src/cpp/rtps/RTPSDomain.cpp
  src/cpp/rtps/RTPSDomainImpl.hpp
  src/cpp/rtps/history/TopicPayloadPool.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.h
  test/blackbox/common/RTPSBlackboxTestsPools.cpp
  test/blackbox/common/RTPSWithRegistrationReader.hpp
  test/blackbox/common/RTPSWithRegistrationWriter.hpp
  test/unittest/rtps/writer/RTPSWriterTests.cpp
Labels: no-test

#1483 Documentation corrections for TopicPayloadPool branch
  include/fastdds/rtps/history/History.h
  include/fastdds/rtps/history/IPayloadPool.h
  test/mock/rtps/WriterHistory/fastdds/rtps/history/WriterHistory.h
Labels: no-test

#1480 [Discovery Server] Remove change in History comparing instance handle
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
Labels: no-test

#1477 [Discovery Server] Connect remote servers [9596]
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPServer2.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPServerListeners2.cpp
  src/cpp/rtps/builtin/discovery/participant/DServerEvent2.cpp
  src/cpp/rtps/builtin/discovery/participant/DServerEvent2.hpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer2.hpp
  src/cpp/rtps/builtin/discovery/participant/PDPServerListener2.cpp
Labels: no-test

#1488 Use topic payload pool on user created endpoints [9605]
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/publisher/DataWriterImpl.hpp
  src/cpp/fastdds/subscriber/DataReaderImpl.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.hpp
  src/cpp/fastrtps_deprecated/participant/ParticipantImpl.cpp
  src/cpp/fastrtps_deprecated/publisher/PublisherImpl.cpp
  src/cpp/fastrtps_deprecated/publisher/PublisherImpl.h
  src/cpp/fastrtps_deprecated/subscriber/SubscriberImpl.cpp
  src/cpp/fastrtps_deprecated/subscriber/SubscriberImpl.h
  src/cpp/rtps/history/CacheChangePool.cpp
  src/cpp/rtps/history/PoolConfig.h
  test/mock/rtps/RTPSDomain/fastdds/rtps/RTPSDomain.h
  test/mock/rtps/ReaderHistory/fastdds/rtps/history/ReaderHistory.h
  test/unittest/dds/status/CMakeLists.txt
  test/unittest/rtps/history/BasicPoolsTests.cpp
  test/unittest/rtps/history/CacheChangePoolTests.cpp
Labels: no-test

#1493 [Discovery Server] Fix intra-participant endpoint discovery
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
Labels: no-test

#1460 Fixes profile section to allow multiple profiles in different order.
  resources/xsd/fastRTPS_profiles.xsd
Labels: no-test

#1473 [Discovery Server] Propagation to other servers using virtual topics [9582]
  include/fastdds/rtps/common/EntityId_t.hpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryEndpointInfo.hpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantChangeData.hpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantInfo.hpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServerListener2.cpp
Labels: no-test

#1257 Fix in EDP because wasn't setting first QoS correctly [8703]
  src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/blackbox/api/dds-pim/PubSubWriter.hpp
  test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
  test/blackbox/api/fastrtps_deprecated/PubSubWriter.hpp
  test/blackbox/common/BlackboxTestsDiscovery.cpp
Labels: no-test

#1482 Added methods to get qos defined in XML Profile [9607]
  include/fastdds/dds/domain/DomainParticipant.hpp
  include/fastdds/dds/domain/DomainParticipantFactory.hpp
  include/fastdds/dds/publisher/Publisher.hpp
  include/fastdds/dds/subscriber/Subscriber.hpp
  src/cpp/fastdds/domain/DomainParticipant.cpp
  src/cpp/fastdds/domain/DomainParticipantFactory.cpp
  src/cpp/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/fastdds/domain/DomainParticipantImpl.hpp
  src/cpp/fastdds/publisher/Publisher.cpp
  src/cpp/fastdds/publisher/PublisherImpl.cpp
  src/cpp/fastdds/publisher/PublisherImpl.hpp
  src/cpp/fastdds/subscriber/Subscriber.cpp
  src/cpp/fastdds/subscriber/SubscriberImpl.cpp
  src/cpp/fastdds/subscriber/SubscriberImpl.hpp
  test/unittest/dds/participant/ParticipantTests.cpp
  test/unittest/dds/profiles/test_xml_profiles.xml
  test/unittest/dds/publisher/PublisherTests.cpp
  test/unittest/dds/subscriber/SubscriberTests.cpp
Labels: doc-pending, ready

#1509 Routine is restarted till server is acked by all
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
Labels: no-test

#1503 Add module and option to detect and enable linking with -latomic in environments that need it (#1495)
  cmake/modules/CheckLibatomic.cmake
  src/cpp/CMakeLists.txt
Labels: no-aarch, no-test

#1514 Backport Quality Declaration to <2.0.x> [9723]
  PLATFORM_SUPPORT.md
  Public_API_foonathan_memory.md
  QUALITY.md
  Quality_Declaration_foonathan_memory.md
  README.md
Labels: skip-ci

#1518 Fix compile error on mac [9737]
  include/fastdds/rtps/writer/StatefulWriter.h
Labels: no-aarch

#1519 Solved possible CMake variable shadowing issue
  cmake/common/gtest.cmake
Labels: no-test

#1524 Correct Doxygen typos
  include/fastdds/rtps/history/ReaderHistory.h
  include/fastdds/rtps/history/WriterHistory.h
Labels: skip-ci

#1527 Fix undefined OStreamConsumer reference error
  test/unittest/security/accesscontrol/CMakeLists.txt
Labels: no-aarch

#1526 <2.0.x> Fix Clang 12.0 warnings [9767]
  test/blackbox/BlackboxTestsDeadlineQos.cpp
  test/blackbox/BlackboxTestsDiscovery.cpp
  test/blackbox/BlackboxTestsLifespanQoS.cpp
  test/blackbox/BlackboxTestsLivelinessQos.cpp
  test/blackbox/BlackboxTestsPubSubBasic.cpp
  test/blackbox/BlackboxTestsPubSubFlowControllers.cpp
  test/blackbox/BlackboxTestsPubSubFragments.cpp
  test/blackbox/BlackboxTestsPubSubHistory.cpp
  test/blackbox/BlackboxTestsRealtimeAllocations.cpp
  test/blackbox/BlackboxTestsSecurity.cpp
  test/blackbox/BlackboxTestsVolatile.cpp
  test/blackbox/RTPSBlackboxTestsBasic.cpp
  test/blackbox/RTPSBlackboxTestsPersistence.cpp
  test/blackbox/RTPSBlackboxTestsVolatile.cpp
  test/unittest/dynamic_types/idl/Basic.cxx
  test/unittest/dynamic_types/idl/Basic.h
  test/unittest/dynamic_types/idl/BasicPubSubTypes.cxx
  test/unittest/dynamic_types/idl/BasicPubSubTypes.h
  test/unittest/transport/SharedMemTests.cpp
Labels: no-aarch, no-test
