Repository eProsima/Fast-DDS, pull requests merged in 2020-11, with the labels that each got.

#1544 Fix warning: change unsigned for signed comparison
  test/unittest/logging/LogTests.cpp
Labels: no-aarch, no-test

#1357 fixed warnings [9193]
  include/fastdds/dds/core/policy/ParameterTypes.hpp
  include/fastdds/dds/core/policy/QosPolicies.hpp
  include/fastdds/rtps/common/CacheChange.h
  include/fastdds/rtps/common/SequenceNumber.h
  include/fastdds/rtps/messages/CDRMessage.hpp
  include/fastrtps/types/AnnotationParameterValue.h
  include/fastrtps/utils/collections/ResourceLimitedVector.hpp
  include/fastrtps/utils/fixed_size_bitmap.hpp
  src/cpp/dynamic-types/DynamicTypeBuilderFactory.cpp
  src/cpp/fastdds/core/policy/ParameterSerializer.hpp
  src/cpp/fastdds/core/policy/QosPoliciesSerializer.hpp
  test/mock/dds/QosPolicies/fastdds/dds/core/policy/QosPolicies.hpp
Labels: no-aarch

#1542 Fixed TopicPayloadPoolRegistryTests [9801]
  src/cpp/rtps/history/TopicPayloadPoolRegistry.cpp
  test/mock/rtps/TopicPayloadPoolProxy/rtps/history/TopicPayloadPoolRegistry_impl/TopicPayloadPoolProxy.hpp
  test/unittest/rtps/history/CMakeLists.txt
  test/unittest/rtps/history/TopicPayloadPoolRegistryTests.cpp
Labels: skip-ci

#1548 Fixed package.xml [9832]
  package.xml
Labels: skip-ci

#1549 Added package.xml <2.0.x> [9836]
  package.xml
Labels: skip-ci

#1557 Removing some dependencies from package.xml <2.0.x>
  package.xml
Labels: skip-ci

#1555 [Discovery Server] Features for Backup Mode <2.0.x>
  include/fastdds/dds/core/policy/ParameterTypes.hpp
  include/fastdds/rtps/builtin/discovery/participant/PDP.h
  include/fastdds/rtps/common/GuidPrefix_t.hpp
  include/fastdds/rtps/common/InstanceHandle.h
  include/fastdds/rtps/common/Locator.h
  include/fastdds/rtps/common/RemoteLocators.hpp
  include/fastdds/rtps/common/Time_t.h
  include/fastdds/rtps/common/Types.h
  src/cpp/CMakeLists.txt
  src/cpp/fastrtps_deprecated/Domain.cpp
  src/cpp/rtps/builtin/BuiltinProtocols.cpp
  src/cpp/rtps/builtin/data/ParticipantProxyData.cpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryEndpointInfo.hpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantChangeData.hpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantInfo.cpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantInfo.hpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantsAckStatus.cpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantsAckStatus.hpp
  src/cpp/rtps/builtin/discovery/database/DiscoverySharedInfo.cpp
  src/cpp/rtps/builtin/discovery/database/DiscoverySharedInfo.hpp
  src/cpp/rtps/builtin/discovery/database/backup/SharedBackupFunctions.cpp
  src/cpp/rtps/builtin/discovery/database/backup/SharedBackupFunctions.hpp
  src/cpp/rtps/builtin/discovery/database/backup/json.hpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPServer2.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPServer2.hpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPServerListeners2.cpp
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer2.hpp
  src/cpp/rtps/builtin/discovery/participant/PDPServerListener2.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServerListener2.hpp
  src/cpp/rtps/persistence/PersistenceFactory.cpp
  src/cpp/rtps/persistence/PersistenceService.h
  src/cpp/rtps/persistence/SQLite3PersistenceService.cpp
  src/cpp/rtps/persistence/SQLite3PersistenceService.h
  src/cpp/rtps/persistence/SQLite3PersistenceServiceStatements.h
  src/cpp/rtps/writer/PersistentWriter.cpp
  test/unittest/rtps/persistence/PersistenceTests.cpp
  tools/fds/server.cpp
Labels: skip-ci

#1551 Bump version to 2.0.2
  configure.ac
  fastrtps.repos
  package.xml
  versions.md
Labels: skip-ci

#1558 Resolve unused variable warning
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
Labels: skip-ci

#1559 Removing some dependencies from package.xml <master> [9858]
  package.xml
Labels: skip-ci

#1560 Fixed unit tests with BUILD_SECURITY=OFF
  test/unittest/dds/participant/ParticipantTests.cpp
  test/unittest/dds/publisher/DataWriterTests.cpp
  test/unittest/dds/publisher/PublisherTests.cpp
  test/unittest/dds/status/ListenerTests.cpp
  test/unittest/dds/subscriber/DataReaderTests.cpp
  test/unittest/dds/subscriber/SubscriberTests.cpp
  test/unittest/dds/topic/TopicTests.cpp
Labels: no-aarch, no-test

#1561 Improve dependencies on package.xml [9887]
  package.xml
Labels: skip-ci

#1362 Delete continue in MessageReceiver::willAReaderAcceptMsgDirectedTo [9213]
  src/cpp/rtps/messages/MessageReceiver.cpp
Labels: no-aarch

#1565 Release notes and repos for 2.1.0 [9936]
  fastrtps.repos
  versions.md
Labels: skip-ci

#1574 Add coverage shield to README.md [9998]
  README.md
Labels: skip-ci

#1576 Negative clauses Coverage for XMLElementParser methods
  src/cpp/rtps/xmlparser/XMLElementParser.cpp
  test/unittest/xmlparser/XMLElementParserTests.cpp
  test/unittest/xmlparser/wrapper/XMLParserTest.hpp
Labels: skip-ci

#1575 XMLElementParser add methods nacho
  test/unittest/xmlparser/XMLElementParserTests.cpp
  test/unittest/xmlparser/wrapper/XMLParserTest.hpp
Labels: skip-ci

#1578 Added negative tests for DataWriter/DataReader QoS and InitialAnnouncementsConfig
  test/unittest/xmlparser/XMLElementParserTests.cpp
  test/unittest/xmlparser/mock/XMLMockConsumer.h
Labels: skip-ci

#1579 Feature/coverage/xml element parser nacho
  test/unittest/xmlparser/XMLElementParserTests.cpp
  test/unittest/xmlparser/wrapper/XMLParserTest.hpp
Labels: skip-ci

#1580 Negative error clauses in XMLElementParser methods
  src/cpp/rtps/xmlparser/XMLElementParser.cpp
  test/unittest/xmlparser/XMLElementParserTests.cpp
  test/unittest/xmlparser/wrapper/XMLParserTest.hpp
Labels: skip-ci

#1584 Share mutex in MockLockConsumer condition variable
  src/cpp/rtps/xmlparser/XMLElementParser.cpp
  test/unittest/xmlparser/XMLElementParserTests.cpp
  test/unittest/xmlparser/mock/XMLMockConsumer.h
Labels: skip-ci

#1588 Add positive cases
  test/unittest/xmlparser/XMLElementParserTests.cpp
Labels: skip-ci

#1586 Positive cases for getXMLEnum
  test/unittest/xmlparser/XMLElementParserTests.cpp
Labels: skip-ci

#1585 Added positive tests for the durability qos policy kind
  test/unittest/xmlparser/XMLElementParserTests.cpp
Labels: skip-ci

#1591 Extend TopicDataType interface
  include/fastdds/dds/topic/TopicDataType.hpp
  versions.md
Labels: no-test

#1595 Added tests for XMLParser functions
  test/unittest/xmlparser/XMLParserTests.cpp
  test/unittest/xmlparser/wrapper/XMLParserTest.hpp
Labels: skip-ci

#1599 Feature/coverage/xml parser nacho
  src/cpp/rtps/xmlparser/XMLParser.cpp
  test/unittest/xmlparser/XMLParserTests.cpp
  test/unittest/xmlparser/wrapper/XMLParserTest.hpp
Labels: skip-ci

#1596 Code coverage policy [10005]
  CONTRIBUTING.md
  QUALITY.md
Labels: skip-ci

#1610 Upgrade to QL1
  QUALITY.md
  Quality_Declaration_foonathan_memory.md
  README.md
  versions.md
Labels: skip-ci
