Repository eProsima/Fast-DDS, pull requests merged in 2021-04, with the labels that each got.

#1879 [11056] Fix building errors in Windows when `FASTDDS_STATISTICS` CMake option is enabled
  src/cpp/statistics/types/types.cxx
  test/unittest/statistics/dds/CMakeLists.txt
  test/unittest/statistics/rtps/RTPSStatisticsTests.cpp
Labels: no-aarch, no-test

#1887 Action for coverage [11098]
  .github/actions/fetch-fastdds-repos/action.yml
  .github/actions/install-apt-packages/action.yml
  .github/actions/install-gtest/action.yml
  .github/actions/install-python-packages/action.yml
  .github/workflows/colcon.meta
  .github/workflows/test.yml
  codecov.yml
Labels: skip-ci

#1892 Enable statistics tests [11098]
  .github/workflows/colcon.meta
Labels: skip-ci

#1930 Remove copied RST text
  README.md
Labels: skip-ci

#1888 Correct comparison of MAC addresses <2.2.x>
  include/fastrtps/utils/IPFinder.h
Labels: ready

#1893 Free used buffers in SHM on zombie ports <2.2.x> [11127]
  src/cpp/rtps/transport/shared_mem/SharedMemChannelResource.hpp
  src/cpp/rtps/transport/shared_mem/SharedMemGlobal.hpp
  src/cpp/rtps/transport/shared_mem/SharedMemManager.hpp
  test/communication/CMakeLists.txt
  test/communication/PubSubMain.cpp
  test/communication/Subscriber.cpp
  test/communication/Subscriber.hpp
  test/communication/SubscriberMain.cpp
  test/communication/shm_communication_subscriber_dies_while_processing_message.py
  test/communication/shm_communication_subscriber_dies_while_processing_message.xml
Labels: ready

#1899 Fix read_next_sample and take_next_sample <2.2.x> [11145]
  include/fastdds/dds/core/UserAllocatedSequence.hpp
  include/fastdds/rtps/history/ReaderHistory.h
  src/cpp/fastdds/subscriber/DataReaderImpl.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.hpp
  src/cpp/fastdds/subscriber/DataReaderImpl/DataReaderLoanManager.hpp
  src/cpp/fastdds/subscriber/DataReaderImpl/ReadTakeCommand.hpp
  src/cpp/rtps/history/ReaderHistory.cpp
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
  test/blackbox/common/BlackboxTestsLifespanQoS.cpp
  test/blackbox/common/DDSBlackboxTestsDataSharing.cpp
  test/mock/rtps/ReaderHistory/fastdds/rtps/history/ReaderHistory.h
  test/unittest/dds/subscriber/DataReaderTests.cpp
  test/unittest/dds/subscriber/FooType.hpp
Labels: ready

#1894 Free used buffers in SHM on zombie ports <2.1.x> [11126]
  src/cpp/rtps/transport/shared_mem/SharedMemChannelResource.hpp
  src/cpp/rtps/transport/shared_mem/SharedMemGlobal.hpp
  src/cpp/rtps/transport/shared_mem/SharedMemManager.hpp
  test/communication/CMakeLists.txt
  test/communication/PubSubMain.cpp
  test/communication/Subscriber.cpp
  test/communication/Subscriber.hpp
  test/communication/SubscriberMain.cpp
  test/communication/shm_communication_subscriber_dies_while_processing_message.py
  test/communication/shm_communication_subscriber_dies_while_processing_message.xml
Labels: ready

#1895 Free used buffers in SHM on zombie ports <2.0.x> [11125]
  src/cpp/rtps/transport/shared_mem/SharedMemChannelResource.hpp
  src/cpp/rtps/transport/shared_mem/SharedMemGlobal.hpp
  src/cpp/rtps/transport/shared_mem/SharedMemManager.hpp
  test/communication/CMakeLists.txt
  test/communication/PubSubMain.cpp
  test/communication/Subscriber.cpp
  test/communication/Subscriber.hpp
  test/communication/SubscriberMain.cpp
  test/communication/shm_communication_subscriber_dies_while_processing_message.py
  test/communication/shm_communication_subscriber_dies_while_processing_message.xml
Labels: ready

#1931 Correctly update memory policy on writers and readers [11348]
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.cpp
  test/blackbox/api/dds-pim/PubSubWriter.hpp
  test/blackbox/api/fastrtps_deprecated/PubSubWriter.hpp
  test/blackbox/common/BlackboxTestsPubSubHistory.cpp
Labels: no-aarch

#1872 Avoid using reference after removing item on LivelinessManager <2.0.x> [11018]
  src/cpp/rtps/writer/LivelinessManager.cpp
Labels: ready

#1873 Avoid using reference after removing item on LivelinessManager [11019]
  src/cpp/rtps/writer/LivelinessManager.cpp
Labels: ready

#1874 Avoid using reference after removing item on LivelinessManager <2.2.x> [11020]
  src/cpp/rtps/writer/LivelinessManager.cpp
Labels: ready, skip-ci

#1875 Avoid using reference after removing item on LivelinessManager <2.1.x> [11021]
  src/cpp/rtps/writer/LivelinessManager.cpp
Labels: ready, skip-ci

#1935 Update package.xml
  package.xml
Labels: skip-ci

#1922 Enable/Disable statistics datawriter implementation [10807]
  .github/workflows/colcon.meta
  .github/workflows/test.yml
  include/fastdds/statistics/dds/domain/DomainParticipant.hpp
  src/cpp/CMakeLists.txt
  src/cpp/fastdds/domain/DomainParticipantFactory.cpp
  src/cpp/fastdds/domain/DomainParticipantImpl.hpp
  src/cpp/fastdds/publisher/DataWriterImpl.hpp
  src/cpp/statistics/fastdds/domain/DomainParticipant.cpp
  src/cpp/statistics/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/statistics/fastdds/domain/DomainParticipantImpl.hpp
  src/cpp/statistics/fastdds/publisher/qos/DataWriterQos.cpp
  test/blackbox/CMakeLists.txt
  test/blackbox/StatisticsDomainParticipant.xml
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/blackbox/common/DDSBlackboxTestsStatisticsDomainParticipant.cpp
  test/mock/dds/DomainParticipantImpl/fastdds/domain/DomainParticipantImpl.hpp
  test/mock/dds/Publisher/fastdds/dds/publisher/Publisher.hpp
  test/unittest/dds/status/CMakeLists.txt
  test/unittest/statistics/dds/CMakeLists.txt
  test/unittest/statistics/dds/StatisticsDomainParticipantMockTests.cpp
  test/unittest/statistics/dds/StatisticsDomainParticipantTests.cpp
  test/unittest/statistics/dds/StatisticsQosTests.cpp
Labels: no-aarch, no-test

#1938 Bump version to 2.3.1
  configure.ac
  package.xml
Labels: skip-ci

#1900 datasharing refactor <2.2.x> [11134]
  include/fastdds/dds/topic/TypeSupport.hpp
  include/fastdds/rtps/reader/StatefulReader.h
  include/fastdds/rtps/reader/StatelessReader.h
  include/fastdds/rtps/writer/RTPSWriter.h
  include/fastdds/rtps/writer/StatefulWriter.h
  include/fastdds/rtps/writer/StatelessWriter.h
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/publisher/DataWriterImpl.hpp
  src/cpp/fastdds/subscriber/DataReaderImpl/ReadTakeCommand.hpp
  src/cpp/fastdds/topic/TypeSupport.cpp
  src/cpp/rtps/DataSharing/DataSharingListener.cpp
  src/cpp/rtps/DataSharing/DataSharingListener.hpp
  src/cpp/rtps/DataSharing/DataSharingNotification.cpp
  src/cpp/rtps/DataSharing/DataSharingNotification.hpp
  src/cpp/rtps/DataSharing/DataSharingNotifier.hpp
  src/cpp/rtps/DataSharing/DataSharingPayloadPool.cpp
  src/cpp/rtps/DataSharing/DataSharingPayloadPool.hpp
  src/cpp/rtps/DataSharing/IDataSharingListener.hpp
  src/cpp/rtps/DataSharing/IDataSharingNotifier.hpp
  src/cpp/rtps/DataSharing/ReaderPool.hpp
  src/cpp/rtps/DataSharing/WriterPool.hpp
  src/cpp/rtps/reader/StatefulReader.cpp
  src/cpp/rtps/reader/StatelessReader.cpp
  src/cpp/rtps/reader/WriterProxy.cpp
  src/cpp/rtps/reader/WriterProxy.h
  src/cpp/rtps/writer/StatefulWriter.cpp
  src/cpp/rtps/writer/StatelessWriter.cpp
  test/blackbox/common/BlackboxTestsPubSubHistory.cpp
  test/blackbox/common/DDSBlackboxTestsDataSharing.cpp
  test/mock/rtps/DataSharingPayloadPool/rtps/DataSharing/DataSharingPayloadPool.hpp
  test/mock/rtps/DataSharingPayloadPool/rtps/DataSharing/ReaderPool.hpp
  test/unittest/dds/subscriber/DataReaderTests.cpp
Labels: ready
