Repository eProsima/Fast-DDS, pull requests merged in 2021-03, with the labels that each got.

#1732 Fix read_next_sample and take_next_sample [10480]
  include/fastdds/dds/core/UserAllocatedSequence.hpp
  include/fastdds/rtps/history/ReaderHistory.h
  src/cpp/fastdds/subscriber/DataReaderImpl.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.hpp
  src/cpp/fastdds/subscriber/DataReaderImpl/DataReaderLoanManager.hpp
  src/cpp/fastdds/subscriber/DataReaderImpl/ReadTakeCommand.hpp
  src/cpp/rtps/history/ReaderHistory.cpp
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
  test/blackbox/common/BlackboxTestsLifespanQoS.cpp
  test/blackbox/common/DDSBlackboxTestsDataSharing.cpp
  test/mock/rtps/ReaderHistory/fastdds/rtps/history/ReaderHistory.h
  test/unittest/dds/subscriber/DataReaderTests.cpp
  test/unittest/dds/subscriber/FooType.hpp
Labels: ready

#1803 [10700] Add FASTDDS_STATISTICS CMake option
  CMakeLists.txt
  include/fastrtps/config.h.in
  versions.md
Labels: no-test

#1763 New Discovery-Server SUPER_CLIENT participant type [10607]
  include/fastdds/rtps/attributes/RTPSParticipantAttributes.h
  include/fastrtps/xmlparser/XMLParserCommon.h
  resources/xsd/fastRTPS_profiles.xsd
  src/cpp/rtps/builtin/BuiltinProtocols.cpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantChangeData.hpp
  src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPClient.h
  src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServerListener.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/xmlparser/XMLElementParser.cpp
  src/cpp/rtps/xmlparser/XMLParserCommon.cpp
  test/unittest/xmlparser/XMLElementParserTests.cpp
Labels: ready

#1805 Fix fastrtps API test compilation [10480]
  test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
Labels: no-aarch, no-test

#1794 Explicitly set reliability
  test/performance/latency/CMakeLists.txt
  test/performance/latency/latency_tests.py
  test/performance/throughput/CMakeLists.txt
  test/performance/throughput/throughput_tests.py
Labels: skip-ci

#1830 Add an explicit build dependency on libssl-dev
  package.xml
Labels: no-test

#1836 [10715] Hotfix: remove case NONE from IDL
  include/fastdds/statistics/types.idl
  src/cpp/statistics/types/types.h
Labels: no-test

#1812 [10790] Hotfix GuidPrefix serialization
  include/fastdds/rtps/common/GuidPrefix_t.hpp
Labels: no-aarch

#1813 [10790] Fix GuidPrefix serialization <2.1.x>
  include/fastdds/rtps/common/GuidPrefix_t.hpp
Labels: no-aarch

#1814 [10790] Fix GuidPrefix serialization <2.0.x>
  include/fastdds/rtps/common/GuidPrefix_t.hpp
Labels: no-aarch

#1838 [10922] Extend SystemInfo class to provide a method to get environment variables
  src/cpp/utils/SystemInfo.hpp
  test/unittest/utils/CMakeLists.txt
  test/unittest/utils/SystemInfoTests.cpp
Labels: ready

#1822 [10712] Statistics module Fast DDS layer API
  CMakeLists.txt
  include/fastdds/statistics/dds/domain/DomainParticipant.hpp
  include/fastdds/statistics/dds/publisher/qos/DataWriterQos.hpp
  include/fastdds/statistics/dds/subscriber/qos/DataReaderQos.hpp
  include/fastdds/statistics/topic_names.hpp
  src/cpp/CMakeLists.txt
  src/cpp/statistics/fastdds/domain/DomainParticipant.cpp
  src/cpp/statistics/fastdds/publisher/qos/DataWriterQos.cpp
  src/cpp/statistics/fastdds/subscriber/qos/DataReaderQos.cpp
Labels: no-aarch, no-test, ready

#1839 New flow controller public API [10943]
  include/fastdds/dds/core/policy/QosPolicies.hpp
  include/fastdds/dds/domain/qos/DomainParticipantQos.hpp
  include/fastdds/rtps/flowcontrol/FlowControllerConsts.hpp
  include/fastdds/rtps/flowcontrol/FlowControllerDescriptor.hpp
  include/fastdds/rtps/flowcontrol/FlowControllerSchedulerPolicy.hpp
  src/cpp/CMakeLists.txt
  src/cpp/rtps/flowcontrol/FlowController.cpp
  src/cpp/rtps/flowcontrol/FlowControllerConsts.cpp
  test/blackbox/api/dds-pim/PubSubWriter.hpp
  test/unittest/dds/status/CMakeLists.txt
  test/unittest/dynamic_types/CMakeLists.txt
  test/unittest/rtps/builtin/CMakeLists.txt
  test/unittest/rtps/discovery/CMakeLists.txt
  test/unittest/xmlparser/CMakeLists.txt
Labels: ready

#1844 Mirror master branch onto 2.3.x
  .github/workflows/mirror.yml
Labels: skip-ci

#1849 Do not fail ProxyData deserialization when TypeObject deserialization fails <2.0.x> [10962]
  src/cpp/fastdds/core/policy/QosPoliciesSerializer.hpp
  test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
Labels: skip-ci

#1843 Fixes #1840
  src/cpp/utils/IPFinder.cpp
Labels: no-aarch, no-test

#1816 [10787] Fix doxygen documentation
  include/fastdds/dds/domain/DomainParticipant.hpp
  include/fastdds/dds/publisher/DataWriter.hpp
  include/fastdds/dds/subscriber/DataReader.hpp
  include/fastdds/rtps/participant/RTPSParticipant.h
  src/cpp/fastdds/publisher/DataWriterImpl.hpp
Labels: ready, skip-ci

#1860 Fix doxygen documentation
  include/fastdds/rtps/common/Time_t.h
Labels: no-aarch, no-test, skip-ci

#1863 Fix heartbeat and ACKs issues <2.2.x> [11004]
  include/fastdds/rtps/transport/shared_mem/SharedMemTransportDescriptor.h
  src/cpp/rtps/network/ReceiverResource.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/reader/StatefulReader.cpp
  test/blackbox/common/BlackboxTestsPubSubBasic.cpp
Labels: skip-ci

#1864 Fix heartbeat and ACKs issues <2.1.x> [11005]
  include/fastdds/rtps/transport/shared_mem/SharedMemTransportDescriptor.h
  src/cpp/rtps/network/ReceiverResource.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/reader/StatefulReader.cpp
  test/blackbox/common/BlackboxTestsPubSubBasic.cpp
Labels: skip-ci

#1868 Fix C++ 20 issue with explicit use of operator
  include/fastrtps/types/TypesBase.h
Labels: no-aarch, no-test

#1866 Fix heartbeat and ACKs issues <1.8.x> [11007]
  src/cpp/rtps/network/ReceiverResource.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  test/blackbox/BlackboxTestsPubSubBasic.cpp
Labels: no-aarch, no-test

#1865 Fix heartbeat and ACKs issues <2.0.x> [11006]
  include/fastdds/rtps/transport/shared_mem/SharedMemTransportDescriptor.h
  src/cpp/rtps/network/ReceiverResource.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/reader/StatefulReader.cpp
  test/blackbox/BlackboxTestsPubSubBasic.cpp
Labels: skip-ci

#1858 [10991] Statistics QoS implementation
  src/cpp/statistics/fastdds/publisher/qos/DataWriterQos.cpp
  src/cpp/statistics/fastdds/subscriber/qos/DataReaderQos.cpp
  test/unittest/statistics/dds/StatisticsQosTests.cpp
Labels: no-aarch, no-test
