Repository eProsima/Fast-DDS, pull requests merged in 2021-02, with the labels that each got.

#1725 Update some files to new product name [10454]
  doc/README.html.in
  utils/doxygen/pages/mainpage.dox
Labels: skip-ci

#1736 Remove log error on receive crypto message from unmatched endpoint <2.1.x> [10487]
  src/cpp/rtps/security/SecurityManager.cpp
Labels: no-test

#1735 Remove log error on receive crypto message from unmatched endpoint <master> [10486]
  src/cpp/rtps/security/SecurityManager.cpp
Labels: no-test

#1734 Remove log error on receive crypto message from unmatched endpoint <2.0.x> [10485]
  src/cpp/rtps/security/SecurityManager.cpp
Labels: no-test

#1728 Update fastdds dockers usage in README.md [10474]
  README.md
Labels: skip-ci

#1744 add boost platform config for qnx
  thirdparty/boost/include/boost/config/platform/qnxnto.hpp
Labels: no-aarch, no-test

#1771 Stop listener thread on reader destructor <master> [10618]
  src/cpp/rtps/reader/RTPSReader.cpp
  src/cpp/rtps/reader/StatefulReader.cpp
  src/cpp/rtps/reader/StatelessReader.cpp
Labels: skip-ci

#1768 Implementation of unique locators request feature for readers [10497]
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.h
  test/blackbox/api/dds-pim/PubSubParticipant.hpp
  test/blackbox/api/fastrtps_deprecated/PubSubParticipant.hpp
  test/blackbox/common/BlackboxTestsNetworkConf.cpp
  test/blackbox/common/BlackboxTestsPubSubBasic.cpp
Labels: no-aarch

#1657 Load default XML only once [10188]
  include/fastrtps/xmlparser/XMLParser.h
  include/fastrtps/xmlparser/XMLProfileManager.h
  src/cpp/xmlparser/XMLParser.cpp
  src/cpp/xmlparser/XMLParserImpl.hpp
  src/cpp/xmlparser/XMLProfileManager.cpp
  test/unittest/logging/mock/MockConsumer.h
  test/unittest/xmlparser/CMakeLists.txt
  test/unittest/xmlparser/XMLLoadFileTests.cpp
Labels: no-aarch, no-test

#1773 Use ftruncate on QNX <master>
  thirdparty/boost/include/boost/interprocess/shared_memory_object.hpp
Labels: no-test

#1776 provide an alternative path for robustlock files under QNX
  src/cpp/rtps/transport/shared_mem/RobustLock.hpp
Labels: skip-ci

#1759 [10387] Update Performance Throughput Testing to support: data sharing, loans and zero copy
  test/performance/throughput/CMakeLists.txt
  test/performance/throughput/ThroughputPublisher.cpp
  test/performance/throughput/ThroughputPublisher.hpp
  test/performance/throughput/ThroughputSubscriber.cpp
  test/performance/throughput/ThroughputSubscriber.hpp
  test/performance/throughput/ThroughputTypes.cpp
  test/performance/throughput/ThroughputTypes.hpp
  test/performance/throughput/main_ThroughputTest.cpp
  test/performance/throughput/payloads_demands.csv
  test/performance/throughput/throughput_tests.py
  test/performance/throughput/xml/interprocess_best_effort_shm.xml
  test/performance/throughput/xml/interprocess_best_effort_tcp.xml
  test/performance/throughput/xml/interprocess_best_effort_udp.xml
  test/performance/throughput/xml/interprocess_reliable_shm.xml
  test/performance/throughput/xml/interprocess_reliable_tcp.xml
  test/performance/throughput/xml/interprocess_reliable_udp.xml
  test/performance/throughput/xml/intraprocess_best_effort.xml
  test/performance/throughput/xml/intraprocess_reliable.xml
Labels: skip-ci

#1775 [10637] Restore smart default logging for multiconfig generators
  CMakeLists.txt
  include/fastdds/dds/log/Log.hpp
  include/fastrtps/config.h.in
  test/unittest/logging/LogTests.cpp
  test/unittest/logging/log_macros/LogMacrosAllActiveTests.cpp
  test/unittest/logging/log_macros/LogMacrosInternalDebugOffTests.cpp
  test/unittest/logging/log_macros/LogMacrosNoErrorTests.cpp
  test/unittest/logging/log_macros/LogMacrosNoInfoTests.cpp
  test/unittest/logging/log_macros/LogMacrosNoWarningTests.cpp
Labels: no-aarch

#1741 Fixed typos in comments
  examples/C++/DDS/DynamicHelloWorldExample/HelloWorldSubscriber.h
  examples/C++/DDS/HelloWorldExample/HelloWorldSubscriber.h
  examples/C++/DDS/HelloWorldExampleDataSharing/HelloWorldSubscriber.h
  examples/C++/DDS/HelloWorldExampleSharedMem/HelloWorldSubscriber.h
  examples/C++/DDS/HelloWorldExampleTCP/HelloWorldSubscriber.h
  examples/C++/DDS/LivelinessQoS/LivelinessSubscriber.h
  examples/C++/DDS/SecureHelloWorldExample/HelloWorldSubscriber.h
  examples/C++/DDS/StaticHelloWorldExample/HelloWorldSubscriber.h
  examples/C++/DDS/TypeLookupService/TypeLookupSubscriber.h
  examples/C++/DynamicHelloWorldExample/HelloWorldSubscriber.h
  examples/C++/HelloWorldExample/HelloWorldSubscriber.h
  examples/C++/HelloWorldExampleSharedMem/HelloWorldSubscriber.h
  examples/C++/HelloWorldExampleTCP/HelloWorldSubscriber.h
  examples/C++/LivelinessQoS/LivelinessSubscriber.h
  examples/C++/SecureHelloWorldExample/HelloWorldSubscriber.h
  examples/C++/StaticHelloWorldExample/HelloWorldSubscriber.h
  include/fastdds/dds/builtin/typelookup/TypeLookupManager.hpp
  include/fastdds/dds/core/status/DeadlineMissedStatus.hpp
  include/fastdds/dds/log/Log.hpp
  include/fastdds/dds/publisher/DataWriterListener.hpp
  include/fastdds/rtps/attributes/HistoryAttributes.h
  include/fastdds/rtps/attributes/RTPSParticipantAllocationAttributes.hpp
  include/fastdds/rtps/attributes/ReaderAttributes.h
  include/fastdds/rtps/builtin/data/ParticipantProxyData.h
  include/fastdds/rtps/builtin/data/ReaderProxyData.h
  include/fastdds/rtps/builtin/liveliness/WLP.h
  include/fastdds/rtps/common/EntityId_t.hpp
  include/fastdds/rtps/common/InstanceHandle.h
  include/fastdds/rtps/common/PortParameters.h
  include/fastdds/rtps/common/SequenceNumber.h
  include/fastdds/rtps/common/Time_t.h
  include/fastdds/rtps/history/ReaderHistory.h
  include/fastdds/rtps/reader/RTPSReader.h
  include/fastdds/rtps/reader/ReaderListener.h
  include/fastdds/rtps/reader/StatefulReader.h
  include/fastdds/rtps/reader/StatelessReader.h
  include/fastdds/rtps/security/cryptography/CryptoKeyFactory.h
  include/fastdds/rtps/security/cryptography/CryptoTransform.h
  include/fastdds/rtps/writer/RTPSWriter.h
  include/fastdds/rtps/writer/WriterListener.h
  include/fastrtps/publisher/PublisherHistory.h
  include/fastrtps/publisher/PublisherListener.h
  include/fastrtps/subscriber/SubscriberHistory.h
  src/cpp/dynamic-types/DynamicData.cpp
  src/cpp/fastdds/domain/DomainParticipantImpl.hpp
  src/cpp/fastrtps_deprecated/participant/ParticipantImpl.h
  src/cpp/rtps/builtin/data/ProxyDataFilters.hpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
  src/cpp/rtps/history/TopicPayloadPool.hpp
  src/cpp/rtps/transport/shared_mem/SharedMemLog.hpp
  src/cpp/utils/IPLocator.cpp
  test/profiling/allocations/AllocTestSubscriber.h
  test/unittest/utils/LocatorTests.cpp
  tools/fastdds/fastdds.py
Labels: no-test

#1780 [10646] Fix various CMake issues
  cmake/modules/FindAtomic.cmake
  include/fastrtps/config.h.in
  src/cpp/CMakeLists.txt
Labels: no-aarch, no-test

#1787 Fixed with and easily typos
  include/fastdds/rtps/common/CacheChange.h
  include/fastdds/rtps/common/LocatorSelectorEntry.hpp
Labels: no-aarch, no-test

#1786 Bump version to 2.3.0
  configure.ac
  fastrtps.repos
  package.xml
  versions.md
Labels: no-aarch, no-test

#1733 Change SOVERSION to <major>.<minor> [10489]
  src/cpp/CMakeLists.txt
Labels: ready

#1764 Add more verbosity to discovery CLI [10611]
  include/fastdds/rtps/attributes/RTPSParticipantAttributes.h
  include/fastdds/rtps/attributes/ServerAttributes.h
  include/fastdds/rtps/builtin/discovery/participant/PDP.h
  include/fastdds/rtps/common/GuidPrefix_t.hpp
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
  test/blackbox/common/BlackboxTestsPubSubBasic.cpp
  test/blackbox/common/RTPSBlackboxTestsPersistenceGuid.cpp
  test/blackbox/utils/check_guid.py
  tools/fds/server.cpp
Labels: no-aarch, ready
