Repository eProsima/Fast-DDS, pull requests merged in 2021-01, with the labels that each got.

#1675 Update fastrtps.repos to reference master branches
  fastrtps.repos
Labels: no-aarch, no-test

#1690 Fix Doxygen typo in DataReader.hpp [10318]
  include/fastdds/dds/subscriber/DataReader.hpp
Labels: skip-ci

#1697 BuiltinTopicData classes [10324]
  include/fastdds/dds/builtin/topic/BuiltinTopicKey.hpp
  include/fastdds/dds/builtin/topic/ParticipantBuiltinTopicData.hpp
  include/fastdds/dds/builtin/topic/PublicationBuiltinTopicData.hpp
  include/fastdds/dds/builtin/topic/SubscriptionBuiltinTopicData.hpp
  include/fastdds/dds/builtin/topic/TopicBuiltinTopicData.hpp
Labels: skip-ci

#1702 Fix doxygen typos
  include/fastdds/dds/core/LoanableCollection.hpp
  include/fastdds/dds/core/LoanableSequence.hpp
  include/fastdds/dds/core/StackAllocatedSequence.hpp
Labels: skip-ci

#1152 share project section README.md <master>
  README.md
Labels: no-test, skip-ci

#1695 DomainParticipant new methods [10310]
  include/fastdds/dds/domain/DomainParticipant.hpp
  src/cpp/fastdds/domain/DomainParticipant.cpp
  test/unittest/dds/participant/ParticipantTests.cpp
Labels: skip-ci

#1706 [10341] Library changes required for PR #1705
  include/fastdds/dds/core/status/StatusMask.hpp
  src/cpp/CMakeLists.txt
Labels: skip-ci

#1711 Fix misspelled words in the doxygen [10408]
  include/fastdds/dds/publisher/DataWriter.hpp
  include/fastdds/dds/publisher/Publisher.hpp
  include/fastdds/dds/subscriber/DataReader.hpp
  include/fastrtps/utils/fixed_size_bitmap.hpp
  src/cpp/fastdds/subscriber/DataReaderImpl.cpp
  src/cpp/fastrtps_deprecated/subscriber/SubscriberImpl.cpp
Labels: skip-ci

#1713 Fix Doxygen online documentation link. [10412]
  doc/README.html.in
Labels: skip-ci

#1692 Changed the Asio linkage to fit the THIRDPARTY option and set a minimum version [10322]
  CMakeLists.txt
  cmake/common/eprosima_libraries.cmake
  cmake/modules/FindAsio.cmake
  examples/C++/DDS/DeadlineQoSExample/CMakeLists.txt
  examples/C++/DeadlineQoSExample/CMakeLists.txt
  src/cpp/CMakeLists.txt
  test/blackbox/CMakeLists.txt
  test/communication/CMakeLists.txt
  test/dds/communication/CMakeLists.txt
  test/performance/CMakeLists.txt
  test/profiling/CMakeLists.txt
  test/unittest/dynamic_types/CMakeLists.txt
  test/unittest/rtps/flowcontrol/CMakeLists.txt
  test/unittest/rtps/network/CMakeLists.txt
  test/unittest/rtps/resources/timedevent/CMakeLists.txt
  test/unittest/rtps/security/CMakeLists.txt
  test/unittest/rtps/writer/CMakeLists.txt
  test/unittest/security/accesscontrol/CMakeLists.txt
  test/unittest/security/authentication/CMakeLists.txt
  test/unittest/transport/CMakeLists.txt
  test/unittest/xtypes/CMakeLists.txt
  test/xtypes/CMakeLists.txt
Labels: no-test, skip-ci

#1714 Bump version to 2.2.0 [10347]
  configure.ac
  fastrtps.repos
  versions.md
Labels: skip-ci

#1710 Zero copy example [10404]
  examples/C++/DDS/CMakeLists.txt
  examples/C++/DDS/ZeroCopyExample/CMakeLists.txt
  examples/C++/DDS/ZeroCopyExample/LoanableHelloWorld.cxx
  examples/C++/DDS/ZeroCopyExample/LoanableHelloWorld.h
  examples/C++/DDS/ZeroCopyExample/LoanableHelloWorld.idl
  examples/C++/DDS/ZeroCopyExample/LoanableHelloWorldPubSubMain.cxx
  examples/C++/DDS/ZeroCopyExample/LoanableHelloWorldPubSubTypes.cxx
  examples/C++/DDS/ZeroCopyExample/LoanableHelloWorldPubSubTypes.h
  examples/C++/DDS/ZeroCopyExample/LoanableHelloWorldPublisher.cxx
  examples/C++/DDS/ZeroCopyExample/LoanableHelloWorldPublisher.h
  examples/C++/DDS/ZeroCopyExample/LoanableHelloWorldSubscriber.cxx
  examples/C++/DDS/ZeroCopyExample/LoanableHelloWorldSubscriber.h
  examples/C++/DDS/ZeroCopyExample/README.txt
Labels: no-test

#1717 Fix generation of config.cmake for Windows installers [10428]
  src/cpp/CMakeLists.txt
Labels: skip-ci

#1721 Set Fast DDS version in repos
  fastrtps.repos
Labels: skip-ci
