Repository eProsima/Fast-DDS, pull requests merged in 2021-09, with the labels that each got.

#2182 Keep changes inside instances sorted by source timestamp [12421]
  include/fastdds/rtps/history/ReaderHistory.h
  src/cpp/fastrtps_deprecated/subscriber/SubscriberHistory.cpp
  src/cpp/rtps/history/ReaderHistory.cpp
  src/cpp/utils/collections/sorted_vector_insert.hpp
  test/blackbox/common/BlackboxTestsPubSubHistory.cpp
  test/mock/rtps/ReaderHistory/fastdds/rtps/history/ReaderHistory.h
Labels: first-to-merge

#2194 Fixed DataReaderHistory [12471]
  src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
Labels: no-aarch

#2206 Remove not implemented warning on doxygen [12358]
  include/fastdds/dds/core/policy/QosPolicies.hpp
  include/fastdds/dds/domain/qos/DomainParticipantQos.hpp
  include/fastdds/rtps/flowcontrol/FlowControllerDescriptor.hpp
Labels: skip-ci

#2208 Hotfix: fix doxydoc
  include/fastdds/rtps/builtin/discovery/endpoint/EDPStatic.h
Labels: skip-ci

#2209 Hotfix: add DomainParticipantQos::flow_controllers doxygen documentation
  include/fastdds/dds/domain/qos/DomainParticipantQos.hpp
Labels: skip-ci

#2214 Fix DDS Late Joiners example
  examples/C++/DDS/LateJoiners/latejoiners.cpp
Labels: no-test, no-aarch
