Repository eProsima/Fast-DDS, pull requests merged in 2021-12, with the labels that each got.

#2344 [13179] Fix doxygen documentation
  include/fastdds/rtps/common/InstanceHandle.h
  include/fastdds/rtps/history/ReaderHistory.h
  include/fastdds/rtps/reader/StatefulReader.h
  include/fastdds/rtps/writer/ReaderProxy.h
Labels: no-test, skip-ci, no-aarch

#2103 Add transport interface to concatenate transports [12290]
  examples/C++/RTPSTest_as_socket/TestReaderSocket.h
  examples/C++/RTPSTest_as_socket/TestWriterSocket.h
  include/fastdds/rtps/network/NetworkFactory.h
  include/fastdds/rtps/network/SenderResource.h
  include/fastdds/rtps/transport/ChainingTransport.h
  include/fastdds/rtps/transport/ChainingTransportDescriptor.h
  include/fastdds/rtps/transport/TransportDescriptorInterface.h
  include/fastdds/rtps/transport/TransportInterface.h
  include/fastdds/rtps/transport/TransportReceiverInterface.h
  include/fastdds/rtps/transport/UDPv6TransportDescriptor.h
  include/fastrtps/rtps/network/NetworkFactory.h
  include/fastrtps/transport/TransportInterface.h
  include/fastrtps/transport/UDPv4TransportDescriptor.h
  include/fastrtps/transport/UDPv6TransportDescriptor.h
  include/fastrtps/transport/test_UDPv4TransportDescriptor.h
  include/fastrtps/utils/StringMatching.h
  src/cpp/CMakeLists.txt
  src/cpp/rtps/network/NetworkFactory.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/transport/ChainingReceiverResource.hpp
  src/cpp/rtps/transport/ChainingSenderResource.hpp
  src/cpp/rtps/transport/ChainingTransport.cpp
  src/cpp/rtps/transport/TCPTransportInterface.cpp
  src/cpp/rtps/transport/TCPTransportInterface.h
  src/cpp/rtps/transport/UDPTransportInterface.cpp
  src/cpp/rtps/transport/UDPTransportInterface.h
  src/cpp/rtps/transport/shared_mem/SharedMemTransport.cpp
  src/cpp/rtps/transport/shared_mem/SharedMemTransport.h
  src/cpp/utils/StringMatching.cpp
  test/blackbox/common/BlackboxTestsTransportCustom.cpp
  test/unittest/rtps/network/mock/MockTransport.cpp
  test/unittest/rtps/network/mock/MockTransport.h
Labels: ready

#2354 [13283] Add chaining transports feature to versions.md
  versions.md
Labels: skip-ci

#2245 Adds profile loading from XML string [12821]
  include/fastdds/dds/domain/DomainParticipantFactory.hpp
  include/fastrtps/Domain.h
  include/fastrtps/xmlparser/XMLProfileManager.h
  src/cpp/fastdds/domain/DomainParticipantFactory.cpp
  src/cpp/fastrtps_deprecated/Domain.cpp
  src/cpp/rtps/xmlparser/XMLProfileManager.cpp
  test/unittest/dds/profiles/test_xml_profiles_for_string.xml
  test/unittest/dds/publisher/CMakeLists.txt
  test/unittest/dds/publisher/PublisherTests.cpp
Labels: ready

#2345 [12821] Hotfix: add xml string feature to versions
  versions.md
Labels: skip-ci

#2336 Add participant locators if new network interfaces are found [12753]
  src/cpp/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.h
  src/cpp/rtps/transport/test_UDPv4Transport.cpp
  src/cpp/rtps/transport/test_UDPv4Transport.h
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/blackbox/api/dds-pim/PubSubWriter.hpp
  test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
  test/blackbox/api/fastrtps_deprecated/PubSubWriter.hpp
  test/blackbox/common/DDSBlackboxTestsDiscovery.cpp
  test/blackbox/common/RTPSBlackboxTestsBasic.cpp
  test/blackbox/common/RTPSWithRegistrationReader.hpp
  test/blackbox/common/RTPSWithRegistrationWriter.hpp
Labels: no-test, no-aarch

#2360 [13291] Hotfix: doxygen documentation
  include/fastdds/rtps/transport/ChainingTransport.h
Labels: skip-ci

#2216 Support of disable_heartbeat_piggyback through XML and DDS API [12533]
  include/fastdds/dds/publisher/qos/DataWriterQos.hpp
  include/fastdds/dds/publisher/qos/WriterQos.hpp
  include/fastrtps/attributes/PublisherAttributes.h
  include/fastrtps/xmlparser/XMLParserCommon.h
  resources/xsd/fastRTPS_profiles.xsd
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/publisher/PublisherImpl.cpp
  src/cpp/fastrtps_deprecated/participant/ParticipantImpl.cpp
  src/cpp/rtps/xmlparser/XMLElementParser.cpp
  src/cpp/rtps/xmlparser/XMLParserCommon.cpp
  test/blackbox/api/dds-pim/PubSubWriter.hpp
  test/blackbox/api/fastrtps_deprecated/PubSubWriter.hpp
  test/blackbox/common/BlackboxTests.hpp
  test/blackbox/common/BlackboxTestsReliability.cpp
  test/blackbox/utils/data_generators.cpp
  test/unittest/xmlparser/XMLElementParserTests.cpp
Labels: ready

#1998 Only export public symbols on non-windows platforms [11754]
  src/cpp/CMakeLists.txt
  src/cpp/libfastrtps.version
Labels: ready

#2258 Reservation of EntityId in DDS layer [12669]
  include/fastdds/rtps/RTPSDomain.h
  include/fastdds/rtps/attributes/EndpointAttributes.h
  include/fastdds/rtps/participant/RTPSParticipant.h
  src/cpp/fastdds/domain/DomainParticipantImpl.hpp
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/publisher/DataWriterImpl.hpp
  src/cpp/fastdds/publisher/PublisherImpl.hpp
  src/cpp/fastdds/subscriber/DataReaderImpl.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.hpp
  src/cpp/fastdds/subscriber/SubscriberImpl.hpp
  src/cpp/rtps/RTPSDomain.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.h
  src/cpp/statistics/fastdds/publisher/DataWriterImpl.hpp
  test/mock/dds/DomainParticipantImpl/fastdds/domain/DomainParticipantImpl.hpp
  test/mock/rtps/RTPSDomain/fastdds/rtps/RTPSDomain.h
  test/mock/rtps/RTPSParticipantImpl/rtps/participant/RTPSParticipantImpl.h
  test/unittest/dds/publisher/DataWriterTests.cpp
  test/unittest/dds/subscriber/DataReaderTests.cpp
Labels: ready

#2363 DataReaderHistory [12400]
  include/fastdds/dds/subscriber/SampleInfo.hpp
  include/fastdds/rtps/common/CacheChange.h
  include/fastdds/rtps/history/ReaderHistory.h
  include/fastrtps/subscriber/SubscriberHistory.h
  include/fastrtps/utils/collections/ResourceLimitedVector.hpp
  src/cpp/CMakeLists.txt
  src/cpp/fastdds/subscriber/DataReaderImpl.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.hpp
  src/cpp/fastdds/subscriber/DataReaderImpl/ReadTakeCommand.hpp
  src/cpp/fastdds/subscriber/history/DataReaderCacheChange.hpp
  src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
  src/cpp/fastdds/subscriber/history/DataReaderHistory.hpp
  src/cpp/fastdds/subscriber/history/DataReaderInstance.hpp
  src/cpp/fastrtps_deprecated/subscriber/SubscriberHistory.cpp
  src/cpp/rtps/history/ReaderHistory.cpp
  src/cpp/rtps/reader/StatefulReader.cpp
  src/cpp/rtps/reader/StatelessReader.cpp
  src/cpp/utils/SystemInfo.cpp
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/mock/rtps/ReaderHistory/fastdds/rtps/history/ReaderHistory.h
  test/unittest/dds/publisher/CMakeLists.txt
  test/unittest/dds/status/CMakeLists.txt
  test/unittest/dds/subscriber/DataReaderTests.cpp
  test/unittest/statistics/dds/CMakeLists.txt
  test/unittest/utils/ResourceLimitedVectorTests.cpp
  versions.md
Labels: first-to-merge

#2122 New DDS example: Basic Configuration HelloWorld [12329]
  examples/C++/DDS/BasicConfigurationExample/BasicConfigurationPublisher.cpp
  examples/C++/DDS/BasicConfigurationExample/BasicConfigurationPublisher.h
  examples/C++/DDS/BasicConfigurationExample/BasicConfigurationSubscriber.cpp
  examples/C++/DDS/BasicConfigurationExample/BasicConfigurationSubscriber.h
  examples/C++/DDS/BasicConfigurationExample/BasicConfiguration_main.cpp
  examples/C++/DDS/BasicConfigurationExample/CMakeLists.txt
  examples/C++/DDS/BasicConfigurationExample/HelloWorld.cxx
  examples/C++/DDS/BasicConfigurationExample/HelloWorld.h
  examples/C++/DDS/BasicConfigurationExample/HelloWorld.idl
  examples/C++/DDS/BasicConfigurationExample/HelloWorldPubSubTypes.cxx
  examples/C++/DDS/BasicConfigurationExample/HelloWorldPubSubTypes.h
  examples/C++/DDS/BasicConfigurationExample/README.md
  examples/C++/DDS/BasicConfigurationExample/arg_configuration.h
  examples/C++/DDS/BasicConfigurationExample/optionparser.h
  examples/C++/DDS/BasicConfigurationExample/types.hpp
  examples/C++/DDS/CMakeLists.txt
Labels: no-test, skip-ci, no-aarch

#2371 Fix #2370
  src/cpp/CMakeLists.txt
Labels: no-test, no-aarch
