Repository eProsima/Fast-DDS, pull requests merged in 2021-11, with the labels that each got.

#2305 Removing unused macro to avoid naming clashes
  include/fastrtps/xmlparser/XMLParserCommon.h
Labels: no-test, no-aarch

#2253 Periodic heartbeat also depending on ReaderProxy's low_mark [12642]
  include/fastdds/rtps/writer/ReaderProxy.h
  src/cpp/rtps/writer/ReaderProxy.cpp
  src/cpp/rtps/writer/StatefulWriter.cpp
Labels: ready

#2246 Discovery Server fix reconnection [12522]
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPClient.h
  src/cpp/rtps/builtin/discovery/participant/PDPServerListener.cpp
Labels: ready

#2326 Bump version to 2.4.1 [13029]
  CMakeLists.txt
  Public_API_foonathan_memory.md
  Quality_Declaration_foonathan_memory.md
  README.md
  package.xml
Labels: skip-ci

#2329 Fixes for DDS Examples
  examples/C++/DDS/Configurability/CMakeLists.txt
  examples/C++/DDS/Configurability/ConfigurabilityPublisher.cpp
  examples/C++/DDS/Configurability/ConfigurabilitySubscriber.cpp
  examples/C++/DDS/Configurability/README.txt
  examples/C++/DDS/WriterLoansExample/CMakeLists.txt
  examples/C++/DDS/ZeroCopyExample/CMakeLists.txt
  examples/C++/OwnershipStrengthQoSExample/.gitignore
  examples/C++/OwnershipStrengthQoSExample/Makefile
  examples/C++/StaticHelloWorldExample/CMakeLists.txt
Labels: skip-ci

#2331 Prepare for 2.5.x [13085]
  .github/workflows/mirror.yml.disabled
  CMakeLists.txt
  package.xml
  versions.md
Labels: skip-ci

#2319 python bindings fixes [11914]
  include/fastdds/dds/domain/qos/DomainParticipantQos.hpp
  include/fastrtps/types/TypesBase.h
Labels: ready

#2316 Allow zero-valued InstanceHandle_t [12942]
  include/fastdds/rtps/common/InstanceHandle.h
  test/unittest/dds/subscriber/DataReaderTests.cpp
  versions.md
Labels: no-test
