Repository eProsima/Fast-DDS, pull requests merged in 2021-05, with the labels that each got.

#1951 [11498] updating scripts for CMake 3.17
  cmake/packaging/windows/fastrtps-config.cmake
  src/cpp/CMakeLists.txt
Labels: no-test

#1975 Update from fastrtpsgen to fastddsgen
  fastrtps.repos
Labels: no-aarch, no-test, skip-ci

#1979 [11596] Update to ROS 2 Galactic
  README.md
Labels: no-aarch, no-test, skip-ci

#1942 Extend README.md quick demo with real example
  README.md
Labels: skip-ci
