Repository eProsima/Fast-DDS, pull requests merged in 2021-08, with the labels that each got.

#2111 [12196] Add empty api
  include/fastdds/rtps/participant/RTPSParticipant.h
  src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer.hpp
  src/cpp/rtps/participant/RTPSParticipant.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.h
Labels: no-test

#2108 Apply setting subscriber's partition to empty set [12317]
  include/fastdds/dds/core/policy/QosPolicies.hpp
  src/cpp/fastdds/subscriber/SubscriberImpl.cpp
  src/cpp/fastdds/subscriber/qos/ReaderQos.cpp
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
  test/blackbox/common/BlackboxTestsDiscovery.cpp
  test/unittest/dds/subscriber/SubscriberTests.cpp
Labels: ready

#2140 Configure Discovery Server using names [12349]
  src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
  src/cpp/rtps/xmlparser/XMLElementParser.cpp
  test/blackbox/common/BlackboxTestsDiscovery.cpp
  tools/fds/README.txt
  tools/fds/server.cpp
  tools/fds/server.h
Labels: skip-ci

#2143 Bump version to 2.4.0
  configure.ac
  package.xml
Labels: skip-ci

#2141 Fix wrong iterator after vector reallocation ln LivelinessManager [12362]
  src/cpp/rtps/writer/LivelinessManager.cpp
Labels: skip-ci

#1992 Add load persistence_guid from UserData [11689]
  include/fastdds/rtps/builtin/discovery/endpoint/EDPStatic.h
  src/cpp/rtps/builtin/discovery/endpoint/EDPStatic.cpp
  test/blackbox/CMakeLists.txt
  test/blackbox/PubSubReaderPersistence.xml.in
  test/blackbox/PubSubWriterPersistence.xml.in
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/blackbox/common/BlackboxTestsDiscovery.cpp
  test/blackbox/common/DDSBlackboxTestsPersistence.cpp
Labels: ready
