Repository eProsima/Fast-DDS, pull requests merged in 2021-07, with the labels that each got.

#2060 Fix segfault on deprecated tests. [12044]
  test/blackbox/api/fastrtps_deprecated/PubSubWriter.hpp
Labels: no-test

#2068 Fixes #2066.
  examples/C++/DDS/DeadlineQoSExample/CMakeLists.txt
  examples/C++/DeadlineQoSExample/CMakeLists.txt
Labels: no-test

#2102 Fix LateJoiners example
  examples/C++/DDS/LateJoiners/latejoiners.cpp
Labels: no-aarch, no-test

#2104 Bump version to 2.3.4
  configure.ac
  fastrtps.repos
  package.xml
Labels: skip-ci

#2087 Disable mirror workflow
  .github/workflows/mirror.yml.disabled
Labels: no-aarch, no-test
