Repository eProsima/Fast-DDS, pull requests merged in 2022-09, with the labels that each got.

#2937 [15477] Update BasicConfigurationExample to allow set up TTL
  examples/cpp/dds/BasicConfigurationExample/BasicConfigurationPublisher.cpp
  examples/cpp/dds/BasicConfigurationExample/BasicConfigurationPublisher.h
  examples/cpp/dds/BasicConfigurationExample/BasicConfigurationSubscriber.cpp
  examples/cpp/dds/BasicConfigurationExample/BasicConfigurationSubscriber.h
  examples/cpp/dds/BasicConfigurationExample/BasicConfiguration_main.cpp
  examples/cpp/dds/BasicConfigurationExample/CMakeLists.txt
  examples/cpp/dds/BasicConfigurationExample/README.md
  examples/cpp/dds/BasicConfigurationExample/arg_configuration.h
Labels: no-test

#2914 [15417] Group set_qos_from_attributes free functions into a separate file
  src/cpp/CMakeLists.txt
  src/cpp/fastdds/domain/DomainParticipantFactory.cpp
  src/cpp/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/fastdds/publisher/PublisherImpl.cpp
  src/cpp/fastdds/subscriber/SubscriberImpl.cpp
  src/cpp/fastdds/utils/QosConverters.cpp
  src/cpp/fastdds/utils/QosConverters.hpp
  test/unittest/dds/publisher/CMakeLists.txt
  test/unittest/dds/status/CMakeLists.txt
  test/unittest/statistics/dds/CMakeLists.txt
Labels: ready

#2940 Update script for generating idl files [15483]
  test/unittest/dynamic_types/DynamicComplexTypesTests.cpp
  utils/scripts/update_generated_code_from_idl.sh
Labels: ready

#2960 add missing dep python3 to package.xml
  package.xml
Labels: skip-ci

#2947 Implement Advanced Configuration Example with partitions and ownership
  examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfigurationPublisher.cpp
  examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfigurationPublisher.h
  examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfigurationSubscriber.cpp
  examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfigurationSubscriber.h
  examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfiguration_main.cpp
  examples/cpp/dds/AdvancedConfigurationExample/CMakeLists.txt
  examples/cpp/dds/AdvancedConfigurationExample/HelloWorld.cxx
  examples/cpp/dds/AdvancedConfigurationExample/HelloWorld.h
  examples/cpp/dds/AdvancedConfigurationExample/HelloWorld.idl
  examples/cpp/dds/AdvancedConfigurationExample/HelloWorldPubSubTypes.cxx
  examples/cpp/dds/AdvancedConfigurationExample/HelloWorldPubSubTypes.h
  examples/cpp/dds/AdvancedConfigurationExample/README.md
  examples/cpp/dds/AdvancedConfigurationExample/arg_configuration.h
  examples/cpp/dds/AdvancedConfigurationExample/types.hpp
  examples/cpp/dds/CMakeLists.txt
Labels: no-test

#2951 [15212] hotfix of BasicConfigurationExample cli
  examples/cpp/dds/BasicConfigurationExample/BasicConfigurationPublisher.cpp
  examples/cpp/dds/BasicConfigurationExample/BasicConfigurationSubscriber.cpp
  examples/cpp/dds/BasicConfigurationExample/BasicConfiguration_main.cpp
  examples/cpp/dds/BasicConfigurationExample/arg_configuration.h
  examples/cpp/dds/HelloWorldExample/HelloWorld_main.cpp
Labels: no-test, no-aarch, ci-pending

#2912 Add Guid info to BasicConfiguration Example cout [15244]
  examples/cpp/dds/BasicConfigurationExample/BasicConfigurationPublisher.cpp
  examples/cpp/dds/BasicConfigurationExample/BasicConfigurationSubscriber.cpp
Labels: no-test, no-aarch, ci-pending

#2967 [15628] XML configuration for Ownership QoS
  include/fastdds/dds/publisher/qos/WriterQos.hpp
  include/fastdds/dds/subscriber/qos/ReaderQos.hpp
  src/cpp/rtps/xmlparser/XMLElementParser.cpp
  test/unittest/xmlparser/XMLElementParserTests.cpp
  test/unittest/xmlparser/wrapper/XMLParserTest.hpp
  versions.md
Labels: skip-ci

#2997 [15600] Update roadmap
  roadmap.md
Labels: skip-ci

#2995 [15600] Correct initialization order warning in DomainParticipantImpl mock
  test/mock/dds/DomainParticipantImpl/fastdds/domain/DomainParticipantImpl.hpp
Labels: no-test, no-aarch, ci-pending

#2996 [15745] External locators feature
  include/fastrtps/xmlparser/XMLParser.h
  include/fastrtps/xmlparser/XMLParserCommon.h
  resources/xsd/fastRTPS_profiles.xsd
  src/cpp/CMakeLists.txt
  src/cpp/fastdds/builtin/typelookup/TypeLookupManager.cpp
  src/cpp/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.cpp
  src/cpp/fastdds/utils/QosConverters.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPSimple.cpp
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPListener.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServerListener.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
  src/cpp/rtps/builtin/liveliness/WLP.cpp
  src/cpp/rtps/network/ExternalLocatorsProcessor.cpp
  src/cpp/rtps/network/ExternalLocatorsProcessor.hpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/reader/WriterProxy.cpp
  src/cpp/rtps/security/SecurityManager.cpp
  src/cpp/rtps/writer/StatefulWriter.cpp
  src/cpp/rtps/writer/StatelessWriter.cpp
  src/cpp/rtps/xmlparser/XMLElementParser.cpp
  src/cpp/rtps/xmlparser/XMLParser.cpp
  src/cpp/rtps/xmlparser/XMLParserCommon.cpp
  test/mock/rtps/ExternalLocatorsProcessor/rtps/network/ExternalLocatorsProcessor.hpp
  test/mock/rtps/ParticipantProxyData/fastdds/rtps/builtin/data/ParticipantProxyData.h
  test/unittest/dds/publisher/CMakeLists.txt
  test/unittest/rtps/discovery/CMakeLists.txt
  test/unittest/rtps/network/CMakeLists.txt
  test/unittest/rtps/network/ExternalLocatorsProcessorTests.cpp
  test/unittest/rtps/reader/CMakeLists.txt
  test/unittest/statistics/dds/CMakeLists.txt
  test/unittest/xmlparser/XMLProfileParserTests.cpp
  test/unittest/xmlparser/test_xml_profiles.xml
  versions.md
Labels: no-aarch, ci-pending
