Repository eProsima/Fast-DDS, pull requests merged in 2022-03, with the labels that each got.

#2171 Separate initialization and enabling of BuiltinProtocols [12388]
  include/fastdds/rtps/builtin/BuiltinProtocols.h
  include/fastdds/rtps/builtin/discovery/participant/PDP.h
  src/cpp/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/rtps/builtin/BuiltinProtocols.cpp
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPListener.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/statistics/fastdds/domain/DomainParticipantImpl.cpp
Labels: ready

#2563 [14046] Dynamic network empty interfaces refactor
  include/fastdds/rtps/network/NetworkFactory.h
  include/fastdds/rtps/transport/ChainingTransport.h
  include/fastdds/rtps/transport/TransportInterface.h
  src/cpp/rtps/network/NetworkFactory.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/transport/TCPTransportInterface.cpp
  src/cpp/rtps/transport/TCPTransportInterface.h
  src/cpp/rtps/transport/UDPTransportInterface.h
  src/cpp/rtps/transport/UDPv4Transport.h
  src/cpp/rtps/transport/UDPv6Transport.cpp
  src/cpp/rtps/transport/UDPv6Transport.h
  src/cpp/rtps/transport/shared_mem/SharedMemTransport.h
  test/unittest/rtps/network/mock/MockTransport.h
  versions.md
Labels: ready, doc-pending

#2536 Remove constructor exports for factory created entities [13947]
  include/fastdds/dds/core/Entity.hpp
  include/fastdds/dds/domain/DomainParticipant.hpp
  include/fastdds/dds/publisher/DataWriter.hpp
  include/fastdds/dds/publisher/Publisher.hpp
  include/fastdds/dds/subscriber/DataReader.hpp
  include/fastdds/dds/subscriber/Subscriber.hpp
  include/fastdds/dds/topic/Topic.hpp
  versions.md
Labels: ready, skip-ci

#2555 [13944] Feature: modify remote servers locators
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  test/dds/discovery/client_server_dynamic_discovery.py
  versions.md
Labels: skip-ci

#2560 Cleanup on several APIs [14031]
  include/fastdds/dds/core/status/IncompatibleQosStatus.hpp
  include/fastdds/dds/publisher/DataWriter.hpp
  include/fastdds/dds/subscriber/DataReader.hpp
  src/cpp/fastdds/publisher/DataWriter.cpp
  src/cpp/fastdds/subscriber/DataReader.cpp
  test/unittest/dds/publisher/DataWriterTests.cpp
  versions.md
Labels: skip-ci, first-to-merge

#2552 [13966] Adding RTPS API extensions to support additional features
  include/fastdds/dds/builtin/typelookup/TypeLookupManager.hpp
  include/fastdds/dds/core/policy/QosPolicies.hpp
  include/fastdds/rtps/attributes/RTPSParticipantAllocationAttributes.hpp
  include/fastdds/rtps/attributes/WriterAttributes.h
  include/fastdds/rtps/builtin/BuiltinProtocols.h
  include/fastdds/rtps/builtin/data/ContentFilterProperty.hpp
  include/fastdds/rtps/builtin/data/ReaderProxyData.h
  include/fastdds/rtps/builtin/discovery/endpoint/EDP.h
  include/fastdds/rtps/common/CacheChange.h
  include/fastdds/rtps/participant/RTPSParticipant.h
  include/fastdds/rtps/reader/ReaderListener.h
  include/fastdds/rtps/writer/RTPSWriter.h
  include/fastdds/rtps/writer/StatefulWriter.h
  include/fastdds/rtps/writer/StatelessWriter.h
  include/fastdds/rtps/writer/WriterListener.h
  src/cpp/fastrtps_deprecated/subscriber/SubscriberImpl.h
  src/cpp/rtps/builtin/BuiltinProtocols.cpp
  src/cpp/rtps/builtin/data/ReaderProxyData.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPServerListeners.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPSimple.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPSimpleListeners.h
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServerListener.cpp
  src/cpp/rtps/builtin/liveliness/WLP.cpp
  src/cpp/rtps/participant/RTPSParticipant.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.h
  src/cpp/rtps/security/SecurityManager.cpp
  src/cpp/rtps/writer/ReaderProxy.cpp
  test/mock/rtps/RTPSParticipant/fastdds/rtps/participant/RTPSParticipant.h
  test/mock/rtps/ReaderProxyData/fastdds/rtps/builtin/data/ReaderProxyData.h
  test/mock/rtps/StatefulWriter/fastdds/rtps/writer/StatefulWriter.h
  versions.md
Labels: skip-ci

#2568 Fix not exported function on DataReader [14077]
  include/fastdds/dds/subscriber/DataReader.hpp
Labels: no-test, no-aarch

#2535 Make $<INSTALL_INTERFACE... use INCLUDE_INSTALL_DIR, and install headers to include/${PROJECT_NAME}
  CMakeLists.txt
  src/cpp/CMakeLists.txt
Labels: no-test, doc-pending, no-aarch

#2554 Add support for octet vectors on XML parser [14011]
  include/fastrtps/xmlparser/XMLParser.h
  resources/xsd/fastRTPS_profiles.xsd
  src/cpp/rtps/xmlparser/XMLElementParser.cpp
  src/cpp/rtps/xmlparser/XMLParser.cpp
  test/unittest/xmlparser/XMLElementParserTests.cpp
  test/unittest/xmlparser/XMLParserTests.cpp
  test/unittest/xmlparser/test_xml_profiles.xml
Labels: ready

#2572 [8789] Fix doxygen documentation
  include/fastdds/rtps/common/Locator.h
  include/fastdds/rtps/transport/ChainingTransport.h
  include/fastdds/rtps/transport/SocketTransportDescriptor.h
  include/fastdds/rtps/transport/TCPTransportDescriptor.h
  include/fastdds/rtps/transport/TCPv4TransportDescriptor.h
  include/fastdds/rtps/transport/TCPv6TransportDescriptor.h
  include/fastdds/rtps/transport/TransportInterface.h
  include/fastdds/rtps/transport/UDPTransportDescriptor.h
  include/fastdds/rtps/transport/UDPv4TransportDescriptor.h
  include/fastdds/rtps/transport/UDPv6TransportDescriptor.h
  include/fastdds/rtps/transport/test_UDPv4TransportDescriptor.h
  src/cpp/rtps/transport/TCPTransportInterface.h
  src/cpp/rtps/transport/TCPv4Transport.h
  src/cpp/rtps/transport/TCPv6Transport.h
  src/cpp/rtps/xmlparser/XMLElementParser.cpp
  src/cpp/security/authentication/PKIDH.cpp
Labels: ready, skip-ci

#2576 [14093] Update ContentFilter test TypeObject using upcoming Fast DDS-Gen v2.1.2
  test/unittest/dds/topic/DDSSQLFilter/data_types/ContentFilterTestType.cxx
  test/unittest/dds/topic/DDSSQLFilter/data_types/ContentFilterTestTypeTypeObject.cxx
  test/unittest/dds/topic/DDSSQLFilter/data_types/ContentFilterTestTypeTypeObject.h
Labels: ready

#2575 [14094] Update roadmap
  roadmap.md
Labels: skip-ci

#2350 Add new exchange format to Static Discovery [13266]
  include/fastdds/rtps/builtin/discovery/endpoint/EDPStatic.h
  src/cpp/rtps/RTPSDomain.cpp
  src/cpp/rtps/builtin/BuiltinProtocols.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPStatic.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.h
  test/blackbox/common/BlackboxTestsDiscovery.cpp
Labels: ready

#2578 [14124] Update README and ROS 2 references
  Quality_Declaration_foonathan_memory.md
  README.md
Labels: skip-ci

#2585 [13791] Several doxydoc improvements
  include/fastdds/dds/subscriber/DataReader.hpp
  include/fastdds/dds/topic/ContentFilteredTopic.hpp
  include/fastdds/dds/topic/IContentFilterFactory.hpp
  include/fastdds/dds/topic/Topic.hpp
  include/fastdds/dds/topic/TopicDescription.hpp
  include/fastdds/rtps/reader/RTPSReader.h
Labels: no-test, no-aarch
