Repository eProsima/Fast-DDS, pull requests merged in 2022-02, with the labels that each got.

#2453 Twitter shield [13539]
  README.md
Labels: skip-ci

#2419 Tests for DDSSQLFilter::DDSFilterFactory [13543]
  src/cpp/CMakeLists.txt
  src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterFactory.cpp
  src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterFactory.hpp
  test/unittest/CMakeLists.txt
  test/unittest/dds/publisher/CMakeLists.txt
  test/unittest/dds/status/CMakeLists.txt
  test/unittest/dds/topic/DDSSQLFilter/CMakeLists.txt
  test/unittest/dds/topic/DDSSQLFilter/DDSSQLFilterTests.cpp
  test/unittest/dds/topic/DDSSQLFilter/data_types/ContentFilterTestType.cxx
  test/unittest/dds/topic/DDSSQLFilter/data_types/ContentFilterTestType.h
  test/unittest/dds/topic/DDSSQLFilter/data_types/ContentFilterTestType.idl
  test/unittest/dds/topic/DDSSQLFilter/data_types/ContentFilterTestTypePubSubTypes.cxx
  test/unittest/dds/topic/DDSSQLFilter/data_types/ContentFilterTestTypePubSubTypes.h
  test/unittest/dds/topic/DDSSQLFilter/data_types/ContentFilterTestTypeTypeObject.cxx
  test/unittest/dds/topic/DDSSQLFilter/data_types/ContentFilterTestTypeTypeObject.h
Labels: no-test, no-aarch

#2471 Add Pkcs11Provider.cpp to Statistics unit test CMakelists.txt [13808]
  test/unittest/statistics/dds/CMakeLists.txt
Labels: no-test, no-aarch

#2405 Enable memory protection on DataSharing readers [13457]
  examples/C++/DDS/ZeroCopyExample/LoanableHelloWorldSubscriber.cxx
  include/fastdds/dds/core/LoanableSequence.hpp
  include/fastdds/dds/core/LoanableTypedCollection.hpp
  src/cpp/rtps/DataSharing/ReaderPool.hpp
  src/cpp/utils/shared_memory/SharedMemSegment.hpp
Labels: ready

#2459 [13563] Release lifecycle
  RELEASE_SUPPORT.md
Labels: skip-ci

#2481 [13365] Fix memory leak in DH key generation
  src/cpp/security/authentication/PKIDH.cpp
Labels: ready

#2508 [13884] Use a single optionparser header for all tools and examples
  .github/workflows/statistics_coverage.yml
  CMakeLists.txt
  cmake/packaging/Config.cmake.in
  examples/C++/DDS/BasicConfigurationExample/CMakeLists.txt
  examples/C++/DDS/BasicConfigurationExample/arg_configuration.h
  examples/C++/DDS/BasicConfigurationExample/optionparser.h
  examples/C++/DDS/HelloWorldExampleTCP/CMakeLists.txt
  examples/C++/DDS/HelloWorldExampleTCP/HelloWorld_main.cpp
  examples/C++/DDS/HelloWorldExampleTCP/optionparser.h
  examples/C++/HelloWorldExampleTCP/CMakeLists.txt
  examples/C++/HelloWorldExampleTCP/HelloWorld_main.cpp
  examples/C++/HelloWorldExampleTCP/optionparser.h
  src/cpp/CMakeLists.txt
  test/performance/latency/CMakeLists.txt
  test/performance/optionarg.hpp
  test/performance/optionparser.h
  test/performance/throughput/CMakeLists.txt
  test/performance/video/CMakeLists.txt
  test/performance/video/main_VideoTest.cpp
  test/profiling/CMakeLists.txt
  test/profiling/main_MemoryTest.cpp
  test/profiling/optionparser.h
  test/unittest/dds/publisher/CMakeLists.txt
  test/unittest/dds/status/CMakeLists.txt
  test/unittest/dynamic_types/CMakeLists.txt
  test/unittest/logging/CMakeLists.txt
  test/unittest/security/accesscontrol/CMakeLists.txt
  test/unittest/statistics/dds/CMakeLists.txt
  test/unittest/xmlparser/CMakeLists.txt
  thirdparty/optionparser/CMakeLists.txt
  thirdparty/optionparser/optionparser.hpp
  thirdparty/optionparser/optionparser/optionparser.h
  tools/fds/CMakeLists.txt
  tools/fds/server.cpp
  tools/fds/server.h
Labels: ready

#2526 Always include local optionparser.h [13785]
  thirdparty/optionparser/optionparser.hpp
Labels: no-test, no-aarch

#2477 Port fastdds-discovery-server to DDS API [13782]
  tools/fds/server.cpp
Labels: skip-ci

#2472 [13579] Add issues and PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/pull_request_template.md
  CONTRIBUTING.md
  PLATFORM_SUPPORT.md
Labels: skip-ci

#2529 [13785] Isolate 2.5.x from master
  .github/workflows/mirror.yml
  fastrtps.repos
Labels: skip-ci

#2531 Fixup #2529
  fastrtps.repos
Labels: skip-ci

#2528 [13785] Bump version to 2.6.0
  .github/workflows/mirror.yml
  CMakeLists.txt
  package.xml
Labels: no-test, no-aarch

#2532 Rename mirror workflow
  .github/workflows/mirror.yml
Labels: skip-ci

#2484 [13784] Bump to version 1.7.3
  configure.ac
Labels: skip-ci

#2491 [13784] Bump version to 1.8.5
  configure.ac
  fastrtps.repos
Labels: skip-ci

#2499 [13784] Bump to version 2.2.1
  configure.ac
  fastrtps.repos
  package.xml
Labels: skip-ci
