Repository eProsima/Fast-DDS, pull requests merged in 2022-05, with the labels that each got.

#2672 [14470] Improve doxygen documentation related to Locator classes.
  include/fastdds/rtps/common/Locator.h
  include/fastdds/rtps/common/LocatorList.hpp
  include/fastdds/rtps/common/LocatorListComparisons.hpp
  include/fastdds/rtps/common/LocatorsIterator.hpp
Labels: ready

#2698 [14615] Add tests for DomainParticipant::find_topic
  test/blackbox/common/DDSBlackboxTestsFindTopic.cpp
  test/unittest/dds/participant/ParticipantTests.cpp
Labels: no-test, no-aarch

#2706 Migrate coverage badge to pass/no-pass [14702]
  README.md
Labels: skip-ci
