Repository eProsima/Fast-DDS, pull requests merged in 2022-08, with the labels that each got.

#2896 Fix spelling mistakes.
  src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
Labels: skip-ci

#2907 Fix cmake_minimum_required due to target_link_options [15378]
  CMakeLists.txt
Labels: no-test

#2900 Add script to generate idl files [15348]
  utils/scripts/update_generated_code_from_idl.sh
Labels: ready, skip-ci
