Repository eProsima/Fast-DDS, pull requests merged in 2022-10, with the labels that each got.

#3001 Refs 15852: Fixing ReadConditions missing header on DataReader header
  include/fastdds/dds/subscriber/DataReader.hpp
  test/unittest/dds/subscriber/DataReaderTests.cpp
Labels: no-test

#3022 [15970] Fix null Dereference Parse XML Enum Dynamic Type
  src/cpp/rtps/xmlparser/XMLDynamicParser.cpp
  test/unittest/xmlparser/XMLParserTests.cpp
  test/unittest/xmlparser/regressions/15344.xml
Labels: ci-pending

#3029 Add 2.8.x to RELEASE_SUPPORT
  RELEASE_SUPPORT.md
Labels: skip-ci

#3012 [15915] Send GAPs correctly when using separate sending
  include/fastdds/rtps/writer/StatefulWriter.h
  src/cpp/rtps/writer/StatefulWriter.cpp
  test/blackbox/common/RTPSBlackboxTestsBasic.cpp
  test/blackbox/common/RTPSWithRegistrationReader.hpp
  test/blackbox/common/RTPSWithRegistrationWriter.hpp
Labels: ci-pending

#3038 [16002] Install public statistics .idl
  src/cpp/CMakeLists.txt
Labels: ready, no-test, no-aarch
