Repository eProsima/Fast-DDS, pull requests merged in 2022-04, with the labels that each got.

#2626 [14349] Fix inconsistent ReaderProxy state on intra-process
  src/cpp/rtps/writer/ReaderProxy.cpp
  test/blackbox/common/BlackboxTestsPubSubBasic.cpp
Labels: first-to-merge

#2622 [14285] Add sanitizer workflow
  .github/workflows/thread-sanitizer.yaml
Labels: skip-ci

#2613 Fix Log Macros test compilation error [14263]
  test/unittest/logging/log_macros/LogMacrosDefaultTests.cpp
Labels: no-test, no-aarch

#2632 [14351] Bump version to 2.4.2
  CMakeLists.txt
  fastrtps.repos
  package.xml
Labels: skip-ci

#2633 [14354] Fixed sanitizers workflow to use current branch
  .github/workflows/thread-sanitizer.yaml
Labels: skip-ci

#2634 [14361] Improve ParticipantTests with ContentFilteredTopic
  test/unittest/dds/participant/ParticipantTests.cpp
Labels: ready

#2647 [14386] Fix oss-fuzz 43650
  src/cpp/rtps/xmlparser/XMLDynamicParser.cpp
  test/unittest/xmlparser/XMLParserTests.cpp
  test/unittest/xmlparser/regressions/13513.xml
Labels: ready
