Repository eProsima/Fast-DDS, pull requests merged in 2022-07, with the labels that each got.

#2793 [15024 ] Added bulk notification interface to RTPS reader listener
  include/fastdds/rtps/reader/ReaderListener.h
Labels: no-test, no-aarch

#2673 DBQueue move Push and Pop methods [14537]
  include/fastrtps/utils/DBQueue.h
  src/cpp/fastdds/log/Log.cpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
  src/cpp/rtps/transport/shared_mem/SharedMemLog.hpp
Labels: enhancement

#2748 [14630] Adding configuration data for external locators feature
  include/fastdds/dds/core/policy/QosPolicies.hpp
  include/fastdds/rtps/attributes/EndpointAttributes.h
  include/fastdds/rtps/attributes/ExternalLocators.hpp
  include/fastdds/rtps/attributes/RTPSParticipantAttributes.h
  include/fastdds/rtps/common/LocatorWithMask.hpp
  include/fastrtps/attributes/PublisherAttributes.h
  include/fastrtps/attributes/SubscriberAttributes.h
Labels: no-test, no-aarch

#2804 [15049] Fix duration cast on FileWatch
  thirdparty/filewatch/FileWatch.hpp
Labels: no-test, no-aarch

#2806 [14910] Update release related information
  RELEASE_SUPPORT.md
  roadmap.md
  versions.md
Labels: skip-ci

#2820 [15025] Improvements thread sanitizer workflow
  .github/workflows/thread-sanitizer.yaml
Labels: skip-ci

#2830 Fix windows build with GTEST_INDIVIDUAL unset
  test/blackbox/CMakeLists.txt
Labels: skip-ci

#2825 [15118] Adding DataReader::get_unread_count (bool mark_as_read)
  include/fastdds/dds/subscriber/DataReader.hpp
  include/fastdds/rtps/reader/RTPSReader.h
  src/cpp/fastdds/subscriber/DataReader.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.hpp
  src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
  src/cpp/fastdds/subscriber/history/DataReaderHistory.hpp
  src/cpp/rtps/reader/RTPSReader.cpp
  test/mock/rtps/RTPSReader/fastdds/rtps/reader/RTPSReader.h
  test/unittest/dds/subscriber/DataReaderTests.cpp
Labels: no-aarch

#2850 [15161] Bump version to 2.5.2 (EOL)
  CMakeLists.txt
  package.xml
Labels: skip-ci

#2815 [15017] Adding empty implementation for ExternalLocatorsProcessor
  src/cpp/CMakeLists.txt
  src/cpp/rtps/network/ExternalLocatorsProcessor.cpp
  src/cpp/rtps/network/ExternalLocatorsProcessor.hpp
  test/unittest/dds/publisher/CMakeLists.txt
  test/unittest/statistics/dds/CMakeLists.txt
Labels: no-test, no-aarch

#2852 [15163] Backport #2054 to <2.1.x>
  cmake/common/gtest.cmake
  cmake/modules/FindGMock.cmake
  colcon.pkg
  examples/C++/DDS/DeadlineQoSExample/CMakeLists.txt
  examples/C++/DeadlineQoSExample/CMakeLists.txt
  test/CMakeLists.txt
  test/blackbox/CMakeLists.txt
  test/communication/CMakeLists.txt
  test/performance/CMakeLists.txt
  test/performance/latency/CMakeLists.txt
  test/performance/throughput/CMakeLists.txt
  test/performance/video/CMakeLists.txt
  test/profiling/CMakeLists.txt
  test/realtime/CMakeLists.txt
  test/realtime/mutex_testing_tool/CMakeLists.txt
  test/unittest/CMakeLists.txt
  test/unittest/dds/participant/CMakeLists.txt
  test/unittest/dds/publisher/CMakeLists.txt
  test/unittest/dds/status/CMakeLists.txt
  test/unittest/dds/subscriber/CMakeLists.txt
  test/unittest/dds/topic/CMakeLists.txt
  test/unittest/dynamic_types/CMakeLists.txt
  test/unittest/logging/CMakeLists.txt
  test/unittest/rtps/builtin/CMakeLists.txt
  test/unittest/rtps/common/CMakeLists.txt
  test/unittest/rtps/discovery/CMakeLists.txt
  test/unittest/rtps/flowcontrol/CMakeLists.txt
  test/unittest/rtps/history/CMakeLists.txt
  test/unittest/rtps/network/CMakeLists.txt
  test/unittest/rtps/persistence/CMakeLists.txt
  test/unittest/rtps/reader/CMakeLists.txt
  test/unittest/rtps/resources/timedevent/CMakeLists.txt
  test/unittest/rtps/security/CMakeLists.txt
  test/unittest/rtps/writer/CMakeLists.txt
  test/unittest/security/accesscontrol/CMakeLists.txt
  test/unittest/security/authentication/CMakeLists.txt
  test/unittest/security/cryptography/CMakeLists.txt
  test/unittest/security/logging/CMakeLists.txt
  test/unittest/transport/CMakeLists.txt
  test/unittest/utils/CMakeLists.txt
  test/unittest/xmlparser/CMakeLists.txt
  test/unittest/xtypes/CMakeLists.txt
  test/xtypes/CMakeLists.txt
Labels: no-test

#2864 [15163] Bump to version 2.1.2
  configure.ac
  fastrtps.repos
  package.xml
Labels: skip-ci

#2869 [15163] Fix fastrtps version
  fastrtps.repos
Labels: skip-ci

#2868 Fix wrong pointer access [15227]
  src/cpp/fastdds/domain/DomainParticipantImpl.cpp
Labels: no-test, no-aarch

#2866 Quick fix warnings against openssl 3.0 [15225]
  test/unittest/security/authentication/BuiltinPKIDHTests.cpp
Labels: no-test, no-aarch

#2867 [15160] Bump version to 2.3.5
  configure.ac
  package.xml
Labels: skip-ci

#2873 [15162] Bump version to 2.6.2
  CMakeLists.txt
  package.xml
Labels: skip-ci

#2880 [14849] Fix file(DOWNLOAD) by providing a relative path
  CMakeLists.txt
Labels: no-test

#2842 [15168] Notify changes in bulk on RTPS readers
  src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
  src/cpp/fastrtps_deprecated/subscriber/SubscriberHistory.cpp
  src/cpp/rtps/common/ChangeComparison.hpp
  src/cpp/rtps/history/ReaderHistory.cpp
  src/cpp/rtps/reader/StatefulReader.cpp
  src/cpp/rtps/reader/StatelessReader.cpp
  test/unittest/rtps/history/ReaderHistoryTests.cpp
Labels: no-aarch

#2879 [14686] Fix doxygen documentation to clearly state which API is unsupported
  include/fastdds/dds/domain/DomainParticipant.hpp
  include/fastdds/dds/domain/DomainParticipantFactory.hpp
  include/fastdds/dds/publisher/DataWriter.hpp
  include/fastdds/dds/publisher/Publisher.hpp
  include/fastdds/dds/subscriber/DataReader.hpp
  include/fastdds/dds/subscriber/Subscriber.hpp
  include/fastdds/dds/topic/Topic.hpp
Labels: no-test

#2878 [15159] Bump to version 2.7.1
  CMakeLists.txt
  package.xml
Labels: skip-ci

#2882 [15159] Remove unsupported note from supported methods
  include/fastdds/dds/domain/DomainParticipantFactory.hpp
  include/fastdds/dds/publisher/DataWriter.hpp
Labels: skip-ci

#2891 Set fixed versions on fastrtps.repos <2.7.x>
  fastrtps.repos
Labels: skip-ci

#2890 Turn master into 2.8.x
  .github/workflows/mirror.yml
  CMakeLists.txt
  package.xml
  versions.md
Labels: skip-ci

#2841 Add API to createRTPSWriter with a custom change pool [14951]
  include/fastdds/rtps/RTPSDomain.h
  src/cpp/rtps/RTPSDomain.cpp
Labels: no-test, high-priority
