Repository eProsima/Fast-DDS, pull requests merged in 2022-06, with the labels that each got.

#2584 [14147] Fix documentation installation
  CMakeLists.txt
Labels: skip-ci

#2661 Fix missing return in WLP::remove_local_writer() [14751]
  src/cpp/rtps/builtin/liveliness/WLP.cpp
Labels: ready

#2282 Sample lost status implementation [12721]
  include/fastdds/rtps/reader/RTPSReader.h
  include/fastdds/rtps/writer/ReaderProxy.h
  src/cpp/fastdds/subscriber/DataReader.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.hpp
  src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
  src/cpp/rtps/reader/StatefulReader.cpp
  src/cpp/rtps/reader/StatelessReader.cpp
  src/cpp/rtps/reader/WriterProxy.cpp
  src/cpp/rtps/reader/WriterProxy.h
  src/cpp/rtps/writer/ReaderProxy.cpp
  src/cpp/rtps/writer/StatefulWriter.cpp
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/blackbox/api/dds-pim/PubSubWriter.hpp
  test/blackbox/common/DDSBlackboxTestsListeners.cpp
  test/unittest/dds/subscriber/DataReaderTests.cpp
  test/unittest/rtps/reader/WriterProxyTests.cpp
  test/unittest/rtps/writer/ReaderProxyTests.cpp
  versions.md
Labels: ready, no-aarch

#2685 [14749] Solving sanitizer issue 4139 <master>
  include/fastdds/rtps/writer/LivelinessManager.h
  include/fastrtps/utils/collections/ResourceLimitedVector.hpp
  src/cpp/rtps/writer/LivelinessManager.cpp
Labels: no-test, no-aarch

#2530 Refs #13972: Fix GuidPrefix fail case in >>operator [13972]
  include/fastdds/rtps/common/GuidPrefix_t.hpp
Labels: bug

#2519 [galactic] Fix: gap not being sent with heartbeat [14676]
  include/fastdds/rtps/writer/ReaderProxy.h
  src/cpp/rtps/writer/ReaderProxy.cpp
  src/cpp/rtps/writer/StatefulWriter.cpp
Labels: skip-ci

#2712 Fix WLP deadlock and EDP discovery performance improvement [14450][14457]
  src/cpp/rtps/reader/StatefulReader.cpp
  src/cpp/rtps/reader/StatelessReader.cpp
  src/cpp/rtps/transport/UDPTransportInterface.cpp
  src/cpp/rtps/transport/UDPTransportInterface.h
  src/cpp/rtps/transport/UDPv4Transport.cpp
  src/cpp/rtps/transport/UDPv6Transport.cpp
  src/cpp/rtps/writer/StatefulWriter.cpp
  src/cpp/rtps/writer/StatelessWriter.cpp
Labels: first-to-merge

#2733 [14579] Bump version to 2.6.1
  CMakeLists.txt
  package.xml
  versions.md
Labels: skip-ci

#2735 [14824] Prepare for 2.7.x
  .github/workflows/mirror.yml
  CMakeLists.txt
  package.xml
  versions.md
Labels: skip-ci

#2666 [13150] Implementation of DataWriter `_w timestamp` methods
  include/fastdds/dds/publisher/DataWriter.hpp
  include/fastdds/rtps/common/WriteParams.h
  src/cpp/fastdds/publisher/DataWriter.cpp
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/publisher/DataWriterImpl.hpp
  src/cpp/rtps/history/WriterHistory.cpp
  test/blackbox/common/DDSBlackboxTestsDataWriter.cpp
  test/unittest/dds/publisher/DataWriterTests.cpp
  versions.md
Labels: skip-ci

#2704 [14681] Fixing thread sanitizer issue 4169 <feature/tsan/fixes>
  include/fastdds/rtps/builtin/discovery/endpoint/EDP.h
  include/fastdds/rtps/builtin/discovery/endpoint/EDPSimple.h
  include/fastdds/rtps/builtin/discovery/participant/PDP.h
  include/fastdds/rtps/common/EntityId_t.hpp
  include/fastrtps/utils/ProxyPool.hpp
  src/cpp/fastdds/builtin/typelookup/TypeLookupManager.cpp
  src/cpp/fastdds/publisher/qos/WriterQos.cpp
  src/cpp/fastdds/subscriber/qos/ReaderQos.cpp
  src/cpp/rtps/RTPSDomain.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPServer.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPServerListeners.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPSimple.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPSimpleListeners.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPSimpleListeners.h
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
  src/cpp/rtps/builtin/liveliness/WLP.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.h
  src/cpp/rtps/security/SecurityManager.cpp
  test/mock/rtps/PDP/fastdds/rtps/builtin/discovery/participant/PDP.h
  test/mock/rtps/RTPSParticipantImpl/rtps/participant/RTPSParticipantImpl.h
  test/mock/rtps/RTPSReader/fastdds/rtps/reader/RTPSReader.h
  test/mock/rtps/StatefulWriter/fastdds/rtps/writer/StatefulWriter.h
  test/mock/rtps/StatelessWriter/fastdds/rtps/writer/StatelessWriter.h
  test/unittest/rtps/security/SecurityHandshakeProcessTests.cpp
  test/unittest/rtps/security/SecurityTests.cpp
  test/unittest/rtps/writer/CMakeLists.txt
  test/unittest/statistics/rtps/RTPSStatisticsTests.cpp
Labels: no-test

#2747 [14579] Update repos file to 2.6.x.
  fastrtps.repos
Labels: skip-ci

#2749 [14849] Fixing CMakeLists.txt to avoid using curl (fails on windows installer ci
  CMakeLists.txt
Labels: skip-ci

#2708 [14770] SampleRejectedStatus feature
  include/fastdds/rtps/common/CacheChange.h
  include/fastdds/rtps/history/ReaderHistory.h
  include/fastdds/rtps/reader/ReaderListener.h
  src/cpp/fastdds/subscriber/DataReader.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.hpp
  src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
  src/cpp/fastdds/subscriber/history/DataReaderHistory.hpp
  src/cpp/rtps/reader/StatefulReader.cpp
  src/cpp/rtps/reader/WriterProxy.cpp
  src/cpp/rtps/reader/WriterProxy.h
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/blackbox/common/DDSBlackboxTestsListeners.cpp
  test/mock/rtps/ReaderHistory/fastdds/rtps/history/ReaderHistory.h
  test/unittest/dds/subscriber/DataReaderTests.cpp
  versions.md
Labels: no-aarch

#2751 Recover old coverage badge [14854]
  README.md
Labels: skip-ci

#2754 Fix build failure with GCC 12 [14891]
  src/cpp/security/cryptography/AESGCMGMAC_KeyExchange.cpp
Labels: no-test, no-aarch

#2741 [14834] Fixing tsan issue 4192 (DDSSimpleCommunicationTypeDiscovery refactor) <feature/tsan/fixes>
  test/dds/communication/SubscriberDynamic.cpp
Labels: no-test

#2783 [15007] Add dll support to Dynamic Types API
  include/fastrtps/types/DynamicTypeMember.h
  include/fastrtps/types/TypeDescriptor.h
  src/cpp/dynamic-types/DynamicDataHelper.cpp
Labels: no-test, no-aarch

#2738 [14833] DiscoveryServer list access deadlock fix <feature/tsan/fixes>
  include/fastdds/rtps/attributes/ServerAttributes.h
  include/fastdds/rtps/builtin/BuiltinProtocols.h
  src/cpp/CMakeLists.txt
  src/cpp/rtps/RTPSDomain.cpp
  src/cpp/rtps/builtin/BuiltinProtocols.cpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
  src/cpp/rtps/builtin/discovery/participant/ServerAttributes.cpp
  src/cpp/rtps/builtin/discovery/participant/timedevent/DSClientEvent.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/utils/SystemInfo.cpp
  src/cpp/utils/SystemInfo.hpp
  test/blackbox/CMakeLists.txt
  test/unittest/dds/participant/CMakeLists.txt
  test/unittest/dds/participant/ParticipantTests.cpp
  test/unittest/dds/publisher/CMakeLists.txt
  test/unittest/statistics/dds/CMakeLists.txt
  test/unittest/utils/SystemInfoTests.cpp
  thirdparty/filewatch/FileWatch.hpp
Labels: no-test

#2787 Fix doxygen for SampleRejectedStatus
  include/fastdds/dds/core/status/SampleRejectedStatus.hpp
Labels: skip-ci

#2778 [14925] Add interfaces for ReadCondition
  include/fastdds/dds/subscriber/DataReader.hpp
  include/fastdds/dds/subscriber/ReadCondition.hpp
  src/cpp/CMakeLists.txt
  src/cpp/fastdds/subscriber/DataReader.cpp
  src/cpp/fastdds/subscriber/ReadCondition.cpp
  test/unittest/dds/participant/ParticipantTests.cpp
  test/unittest/dds/subscriber/DataReaderTests.cpp
  test/unittest/dds/subscriber/SubscriberTests.cpp
Labels: no-test, no-aarch

#2762 Fix SharedMemWatchdog datarace (issue 1049) [14916] <master>
  src/cpp/utils/shared_memory/SharedMemWatchdog.hpp
Labels: no-test

#2798 fix c++11 support for fast discovery server tool
  tools/fds/CMakeLists.txt
Labels: no-test, no-aarch
