Repository eProsima/Fast-DDS, pull requests merged in 2022-12, with the labels that each got.

#3074 Bump to 2.6.3
  CMakeLists.txt
  package.xml
Labels: ready-to-merge

#3122 [16362] Fix Windows StatistisQosTests.cpp linkage and Failed test
  test/unittest/statistics/dds/StatisticsQosTests.cpp
Labels: needs-review

#3103 Fix recurrent minor data races from tests [16344]
  include/fastdds/rtps/common/EntityId_t.hpp
  include/fastdds/rtps/common/GuidPrefix_t.hpp
  include/fastdds/rtps/common/InstanceHandle.h
  src/cpp/rtps/transport/test_UDPv4Transport.cpp
  src/cpp/rtps/transport/test_UDPv4Transport.h
  test/blackbox/CMakeLists.txt
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
  test/blackbox/common/DDSBlackboxTestsOwnershipQos.cpp
  test/blackbox/common/RTPSAsSocketReader.hpp
  test/blackbox/common/RTPSWithRegistrationReader.hpp
Labels: ci-pending

#3078 [16329] Several fixes to remove warnings in Ubuntu Jammy (22.04)
  doxyfile.in
  roadmap.md
  src/cpp/rtps/transport/TCPAcceptorSecure.h
  src/cpp/rtps/transport/TCPChannelResourceSecure.h
  src/cpp/rtps/transport/TCPTransportInterface.h
  test/unittest/statistics/rtps/RTPSStatisticsTests.cpp
Labels: ready-to-merge, no-test

#3120 [14758] Disable XMLProfileManager error when Participant profile is not found
  src/cpp/fastdds/domain/DomainParticipantFactory.cpp
Labels: ready-to-merge

#3135 [16328] Set FASTDDS_STATISTICS CMake option to ON
  CMakeLists.txt
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/statistics/rtps/StatisticsBase.cpp
  src/cpp/statistics/rtps/reader/StatisticsReaderImpl.cpp
  src/cpp/statistics/rtps/writer/StatisticsWriterImpl.cpp
  test/blackbox/api/dds-pim/PubSubParticipant.hpp
  test/unittest/statistics/dds/StatisticsQosTests.cpp
  versions.md
Labels: doc-pending, ci-pending

#1781 Time t operators [10652]
  include/fastdds/rtps/common/Time_t.h
  test/unittest/rtps/common/CMakeLists.txt
  test/unittest/rtps/common/TimeTests.cpp
Labels: ci-pending

#3146 [16440] Set enabled statistics writers mask on new endpoints
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/statistics/rtps/StatisticsBase.cpp
  src/cpp/statistics/rtps/StatisticsBase.hpp
  test/unittest/statistics/rtps/RTPSStatisticsTests.cpp
Labels: first-to-merge

#3147 [16440] Update ContentFilteredTopicExample TypeObject
  examples/cpp/dds/ContentFilteredTopicExample/HelloWorld.cxx
  examples/cpp/dds/ContentFilteredTopicExample/HelloWorldTypeObject.h
  utils/scripts/update_generated_code_from_idl.sh
Labels: skip-ci

#3089 Protect DomainParticipant set_listener [16040]
  include/fastdds/dds/domain/DomainParticipant.hpp
  src/cpp/fastdds/domain/DomainParticipant.cpp
  src/cpp/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/fastdds/domain/DomainParticipantImpl.hpp
  test/mock/dds/DomainParticipantImpl/fastdds/domain/DomainParticipantImpl.hpp
  test/unittest/dds/participant/ParticipantTests.cpp
Labels: ci-pending

#3097 Fix datarace on WriterProxy stop while TimedEvent being triggered [16341]
  include/fastdds/rtps/reader/StatefulReader.h
  include/fastdds/rtps/resources/TimedEvent.h
  src/cpp/rtps/reader/StatefulReader.cpp
  src/cpp/rtps/reader/WriterProxy.cpp
  src/cpp/rtps/reader/WriterProxy.h
  src/cpp/rtps/resources/TimedEvent.cpp
  test/mock/rtps/StatefulReader/fastdds/rtps/reader/StatefulReader.h
  test/mock/rtps/TimedEvent/fastdds/rtps/resources/TimedEvent.h
  test/unittest/rtps/history/CMakeLists.txt
  test/unittest/rtps/reader/CMakeLists.txt
  test/unittest/rtps/reader/WriterProxyStopTest.cpp
  test/unittest/rtps/reader/WriterProxyTests.cpp
  test/unittest/rtps/resources/timedevent/TimedEventTests.cpp
  test/unittest/rtps/resources/timedevent/mock/MockEvent.cpp
  test/unittest/rtps/resources/timedevent/mock/MockEvent.h
Labels: ci-pending

#3070 Discovery Server TSAN fixes [16106]
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataQueueInfo.hpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantsAckStatus.hpp
  src/cpp/rtps/builtin/discovery/database/DiscoverySharedInfo.hpp
Labels: ci-pending

#3104 Protect creation/destruction of boost's named_mutex [16273]
  src/cpp/rtps/transport/shared_mem/SharedMemGlobal.hpp
  src/cpp/rtps/transport/shared_mem/SharedMemLog.hpp
  src/cpp/utils/shared_memory/SharedMemSegment.hpp
  test/unittest/transport/SharedMemTests.cpp
  test/unittest/transport/mock/SharedMemGlobalMock.hpp
Labels: ci-pending

#3149 [16440] Update Fast DDS roadmap, and release and platform support
  PLATFORM_SUPPORT.md
  RELEASE_SUPPORT.md
  roadmap.md
Labels: skip-ci

#3148 [16430] Manifest installation fix.
  src/cpp/CMakeLists.txt
Labels: no-test

#3115 [16166] Fixing deadlock in WLP
  src/cpp/rtps/builtin/liveliness/WLP.cpp
  test/blackbox/api/dds-pim/PubSubWriterReader.hpp
  test/blackbox/api/fastrtps_deprecated/PubSubWriterReader.hpp
  test/blackbox/common/BlackboxTestsLivelinessQos.cpp
Labels: ci-pending

#3169 [16597] Fix assertion when built with statistics
  src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
Labels: no-test

#3170 [16501] PKI exchange finished
  include/fastdds/rtps/builtin/discovery/participant/PDP.h
  include/fastdds/rtps/common/EntityId_t.hpp
  src/cpp/CMakeLists.txt
  src/cpp/rtps/builtin/discovery/participant/DS/DiscoveryServerPDPEndpointsSecure.hpp
  src/cpp/rtps/builtin/discovery/participant/DS/FakeWriter.hpp
  src/cpp/rtps/builtin/discovery/participant/DS/PDPSecurityInitiatorListener.cpp
  src/cpp/rtps/builtin/discovery/participant/DS/PDPSecurityInitiatorListener.hpp
  src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPClient.h
  src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer.hpp
  src/cpp/rtps/messages/RTPSMessageGroup.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.h
  src/cpp/rtps/security/SecurityManager.cpp
  test/mock/rtps/PDP/fastdds/rtps/builtin/discovery/participant/PDP.h
  test/mock/rtps/RTPSParticipantImpl/rtps/participant/RTPSParticipantImpl.h
  test/unittest/dds/publisher/CMakeLists.txt
  test/unittest/rtps/security/CMakeLists.txt
  test/unittest/statistics/dds/CMakeLists.txt
Labels: no-test
