Repository eProsima/Fast-DDS, pull requests merged in 2022-11, with the labels that each got.

#3045 Add SANITIZE cmake option and ASAN github action
  .github/actions/install-apt-packages/action.yml
  .github/actions/install-gtest-linux/action.yml
  .github/actions/install-python-packages/action.yml
  .github/workflows/asan.yml
  .github/workflows/asan_colcon.meta
  .github/workflows/asan_log_parser.py
  CMakeLists.txt
Labels: no-test, no-aarch

#3060 Avoid sanitizer warning message if option not set
  CMakeLists.txt
Labels: no-test, no-aarch

#3034 [15997] Construct with decltype when inserting to map on FlowControllerFactory
  src/cpp/rtps/flowcontrol/FlowControllerFactory.cpp
Labels: no-test, no-aarch

#3077 [15964] Skip ASAN job if skip-ci or no-test label is set
  .github/workflows/asan.yml
Labels: ready, no-test, skip-ci

#3083 Revert changes from #3046
  include/fastdds/rtps/resources/TimedEvent.h
  src/cpp/rtps/reader/WriterProxy.cpp
  src/cpp/rtps/reader/WriterProxy.h
  src/cpp/rtps/resources/TimedEvent.cpp
  test/mock/rtps/TimedEvent/fastdds/rtps/resources/TimedEvent.h
  test/unittest/rtps/resources/timedevent/TimedEventTests.cpp
  test/unittest/rtps/resources/timedevent/mock/MockEvent.cpp
  test/unittest/rtps/resources/timedevent/mock/MockEvent.h
Labels: no-test, no-aarch

#2976 [15766] Update shared_mutex thirdparty to don't prioritize writers
  CMakeLists.txt
  cmake/common/gtest.cmake
  cmake/modules/check_shared_mutex_priority.cpp
  include/fastrtps/utils/ProxyPool.hpp
  include/fastrtps/utils/shared_mutex.hpp
  src/cpp/CMakeLists.txt
  src/cpp/rtps/history/TopicPayloadPool.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.h
  test/blackbox/common/DDSBlackboxTestsBasic.cpp
  test/unittest/utils/CMakeLists.txt
  test/unittest/utils/shared_mutex_tests.cpp
Labels: ready

#3076 [16076] Bump version to 2.8.1
  CMakeLists.txt
  package.xml
Labels: skip-ci

#3084 Add ASAN CI tests for fastdds and Discovery Server [16116]
  .github/actions/install-python-packages/action.yml
  .github/workflows/asan.yml
  .github/workflows/asan/asan_colcon.meta
  .github/workflows/asan_log_parser.py
  .github/workflows/sanitizer-tests.yaml
  .github/workflows/utils/log_parser.py
  .github/workflows/utils/specific_errors_filter.sh
Labels: skip-ci

#3099 [16076] Mirror master onto both 2.8.x & 2.9.x
  .github/workflows/mirror.yml
Labels: skip-ci

#3114 Added ignore_participant_flags() to Blackbox_FastRTPS PubSubReader.
  test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
Labels: no-aarch

#3102 [16271] Fix Deadlock in remove_participant (ResourceEvent thread) when compiled WITH_SECURITY
  include/fastdds/rtps/resources/ResourceEvent.h
  src/cpp/rtps/resources/ResourceEvent.cpp
  test/blackbox/common/BlackboxTestsSecurity.cpp
  test/certs/governance_helloworld_disable_liveliness.smime
  test/certs/governance_helloworld_disable_liveliness.xml
  test/unittest/rtps/resources/timedevent/TimedEventTests.cpp
Labels: ci-pending

#3110 Fix failed tests when compiling with statistics enabled
  src/cpp/rtps/transport/UDPTransportInterface.h
  test/blackbox/api/fastrtps_deprecated/PubSubWriter.hpp
  test/blackbox/common/BlackboxTestsPubSubBasic.cpp
  test/unittest/transport/UDPv4Tests.cpp
  test/unittest/transport/UDPv6Tests.cpp
Labels: ci-pending

#3101 [16076] Bump version to 2.9.0
  .github/workflows/mirror.yml
  CMakeLists.txt
  package.xml
  versions.md
Labels: skip-ci

#3108 [16214] Set PREALLOCATED_WITH_REALLOC as default
  include/fastdds/dds/core/policy/QosPolicies.hpp
  include/fastdds/rtps/attributes/HistoryAttributes.h
  include/fastrtps/attributes/PublisherAttributes.h
  include/fastrtps/attributes/SubscriberAttributes.h
  src/cpp/rtps/history/CacheChangePool.h
  src/cpp/rtps/security/SecurityManager.cpp
  test/blackbox/api/dds-pim/PubSubParticipant.hpp
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/blackbox/api/dds-pim/PubSubWriter.hpp
  test/blackbox/api/dds-pim/PubSubWriterReader.hpp
  test/blackbox/api/dds-pim/ReqRepHelloWorldReplier.cpp
  test/blackbox/api/dds-pim/ReqRepHelloWorldRequester.cpp
  test/blackbox/api/fastrtps_deprecated/PubSubParticipant.hpp
  test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
  test/blackbox/api/fastrtps_deprecated/PubSubWriter.hpp
  test/blackbox/api/fastrtps_deprecated/PubSubWriterReader.hpp
  test/blackbox/api/fastrtps_deprecated/ReqRepHelloWorldReplier.cpp
  test/blackbox/api/fastrtps_deprecated/ReqRepHelloWorldRequester.cpp
  test/blackbox/common/RTPSAsSocketReader.hpp
  test/blackbox/common/RTPSAsSocketWriter.hpp
  test/blackbox/common/RTPSBlackboxTestsPersistence.cpp
  test/blackbox/common/RTPSBlackboxTestsPersistenceNonIntraprocess.cpp
  test/blackbox/common/TCPReqRepHelloWorldReplier.cpp
  test/blackbox/common/TCPReqRepHelloWorldRequester.cpp
  test/unittest/dds/participant/ParticipantTests.cpp
  test/unittest/dds/publisher/DataWriterTests.cpp
  test/unittest/dds/publisher/PublisherTests.cpp
  test/unittest/dds/status/ListenerTests.cpp
  test/unittest/dds/subscriber/SubscriberTests.cpp
  test/unittest/dds/topic/TopicTests.cpp
  test/unittest/statistics/dds/StatisticsDomainParticipantTests.cpp
  versions.md
Labels: ready-to-merge

#3109 [16284] Avoid statistics calculations for not enabled statistics DataWriters
  include/fastdds/rtps/participant/RTPSParticipant.h
  include/fastdds/rtps/reader/RTPSReader.h
  include/fastdds/rtps/writer/RTPSWriter.h
  include/fastdds/statistics/rtps/StatisticsCommon.hpp
  src/cpp/rtps/participant/RTPSParticipant.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.h
  src/cpp/rtps/reader/RTPSReader.cpp
  src/cpp/rtps/writer/RTPSWriter.cpp
  src/cpp/statistics/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/statistics/fastdds/domain/DomainParticipantStatisticsListener.cpp
  src/cpp/statistics/fastdds/domain/DomainParticipantStatisticsListener.hpp
  src/cpp/statistics/rtps/StatisticsBase.cpp
  src/cpp/statistics/rtps/StatisticsBase.hpp
  src/cpp/statistics/rtps/reader/StatisticsReaderImpl.cpp
  src/cpp/statistics/rtps/writer/StatisticsWriterImpl.cpp
  test/mock/rtps/RTPSParticipant/fastdds/rtps/participant/RTPSParticipant.h
  test/unittest/statistics/rtps/RTPSStatisticsTests.cpp
  versions.md
Labels: ready-to-merge, skip-ci
