Repository eProsima/Fast-DDS, pull requests merged in 2023-03, with the labels that each got.

#3208 Update ubuntu version in ASAN tests [17250]
  .github/actions/fetch-fastdds-repos/action.yml
  .github/actions/install-gtest-linux/action.yml
  .github/workflows/sanitizer-tests.yaml
  .github/workflows/utils/log_parser.py
Labels: in progress

#3337 Update RELEASE_SUPPORT with dates for 2.10.x
  RELEASE_SUPPORT.md
Labels: ready-to-merge, skip-ci

#3309 [17004] Fix performance tests - Overflow in received samples
  test/performance/throughput/ThroughputPublisher.cpp
  test/performance/throughput/ThroughputSubscriber.cpp
  test/performance/throughput/ThroughputSubscriber.hpp
  test/performance/throughput/ThroughputTypes.cpp
  test/performance/throughput/ThroughputTypes.hpp
Labels: bug, ready-to-merge

#3335 [17297] Avoid creation of DynamicTypes on example
  examples/cpp/dds/DynamicHelloWorldExample/HelloWorldSubscriber.cpp
  examples/cpp/dds/DynamicHelloWorldExample/HelloWorldSubscriber.h
Labels: ready-to-merge, skip-ci

#3246 Fix compilation on old compilers [16901]
  src/cpp/rtps/transport/ChainingTransport.cpp
Labels: no-test

#3348 [17514] Fixed ASAN detected leaks
  test/blackbox/common/DDSBlackboxTestsListeners.cpp
Labels: ci-pending

#3328 [17350] Removed Boost singleton references from mock
  test/mock/rtps/SharedMemSegment/utils/shared_memory/SharedMemSegment.hpp
Labels: ready-to-merge

#3142 [16334] Make network headers private
  include/fastdds/rtps/builtin/BuiltinProtocols.h
  include/fastdds/rtps/builtin/data/ReaderProxyData.h
  include/fastdds/rtps/builtin/data/WriterProxyData.h
  include/fastdds/rtps/network/SenderResource.h
  include/fastdds/rtps/transport/SenderResource.h
  include/fastdds/rtps/transport/TransportInterface.h
  include/fastrtps/rtps/network/NetworkFactory.h
  include/fastrtps/rtps/network/ReceiverResource.h
  include/fastrtps/rtps/network/SenderResource.h
  src/cpp/rtps/builtin/data/ParticipantProxyData.cpp
  src/cpp/rtps/builtin/data/ReaderProxyData.cpp
  src/cpp/rtps/builtin/data/WriterProxyData.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPSimpleListeners.cpp
  src/cpp/rtps/network/NetworkFactory.cpp
  src/cpp/rtps/network/NetworkFactory.h
  src/cpp/rtps/network/ReceiverResource.cpp
  src/cpp/rtps/network/ReceiverResource.h
  src/cpp/rtps/participant/RTPSParticipantImpl.h
  src/cpp/rtps/security/SecurityManager.cpp
  src/cpp/rtps/transport/ChainingSenderResource.hpp
  src/cpp/rtps/transport/TCPSenderResource.hpp
  src/cpp/rtps/transport/UDPSenderResource.hpp
  src/cpp/rtps/transport/UDPv4Transport.cpp
  src/cpp/rtps/transport/UDPv6Transport.cpp
  src/cpp/rtps/transport/shared_mem/SharedMemSenderResource.hpp
  src/cpp/rtps/transport/shared_mem/SharedMemTransport.cpp
  test/mock/rtps/NetworkFactory/rtps/network/NetworkFactory.h
  test/mock/rtps/RTPSParticipantImpl/rtps/participant/RTPSParticipantImpl.h
  test/mock/rtps/ReceiverResource/rtps/network/ReceiverResource.h
  test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
  test/unittest/rtps/network/NetworkFactoryTests.cpp
  test/unittest/rtps/security/SecurityHandshakeProcessTests.cpp
  test/unittest/transport/TCPv6Tests.cpp
  test/unittest/transport/UDPv4Tests.cpp
  test/unittest/transport/UDPv6Tests.cpp
  test/unittest/transport/mock/MockReceiverResource.h
  versions.md
Labels: ready-to-merge, no-test

#3355 [17290] Fix Fast DDS docs CI when workflow dispatch event
  .github/workflows/documentation-tests.yaml
Labels: ready-to-merge

#3311 [17267] Added missing mutex to WLP::remove_local_reader
  src/cpp/rtps/builtin/liveliness/WLP.cpp
Labels: ready-to-merge

#3274 Implement a validity check for firstSN
  fuzz/C++/fuzz_processCDRMsg/fuzz_processCDRMsg_seed_corpus/input_issue3236
  src/cpp/rtps/messages/MessageReceiver.cpp
Labels: ready-to-merge

#3324 Fix crash when disable_positive_acks is enable and the remote reader is best-effort [17338]
  src/cpp/rtps/writer/StatefulWriter.cpp
  test/blackbox/common/BlackboxTestsAcknackQos.cpp
Labels: ready-to-merge

#3228 Improve doxygen documentation for ResourceLimitsQos [16814]
  include/fastdds/dds/core/policy/QosPolicies.hpp
Labels: ready-to-merge, no-test

#3363 [17559] Update Fast DDS profiles schema with troubleshooting errors
  resources/xsd/fastRTPS_profiles.xsd
  test/communication/liveliness_assertion.120.xml
  test/communication/liveliness_assertion.360.xml
  test/communication/liveliness_assertion.xml
  test/communication/shm_communication_subscriber_dies_while_processing_message.xml
  test/communication/simple_besteffort.xml
  test/communication/simple_reliable.xml
  test/communication/simple_reliable_besteffort.xml
  test/communication/simple_secure_besteffort_pub.xml
  test/communication/simple_secure_besteffort_sub.xml
  test/dds/communication/simple_besteffort.xml
  test/dds/communication/simple_besteffort_zerocopy.xml
  test/dds/communication/simple_reliable.xml
  test/dds/communication/simple_reliable_zerocopy.xml
  test/performance/latency/xml/intraprocess_best_effort.xml
  test/performance/latency/xml/intraprocess_reliable.xml
  test/performance/throughput/xml/interprocess_best_effort_shm.xml
  test/performance/throughput/xml/interprocess_reliable_shm.xml
  test/performance/throughput/xml/intraprocess_best_effort.xml
  test/performance/throughput/xml/intraprocess_reliable.xml
  test/system/tools/xmlvalidation/XMLTesterExample.xml
  test/system/tools/xmlvalidation/librarySettings_profile.xml
  test/system/tools/xmlvalidation/profileAll.xml
  test/system/tools/xmlvalidation/profileDomainParticipant.xml
  test/system/tools/xmlvalidation/topic_profile.xml
  test/unittest/dds/profiles/test_xml_profiles.xml
  test/unittest/dds/profiles/test_xml_profiles_for_string.xml
  test/unittest/xmlparser/test_xml_profiles.xml
  test/unittest/xmlparser/test_xml_root_library_settings_profile.xml
Labels: ready-to-merge

#3354 [17509] Feature: Ignore empty API
  include/fastdds/dds/domain/DomainParticipant.hpp
  include/fastdds/dds/domain/DomainParticipantListener.hpp
  include/fastdds/rtps/builtin/discovery/participant/PDP.h
  include/fastdds/rtps/participant/ParticipantDiscoveryInfo.h
  include/fastdds/rtps/participant/RTPSParticipant.h
  include/fastdds/rtps/participant/RTPSParticipantListener.h
  include/fastdds/rtps/reader/ReaderDiscoveryInfo.h
  include/fastdds/rtps/writer/WriterDiscoveryInfo.h
  src/cpp/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/fastdds/domain/DomainParticipantImpl.hpp
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  src/cpp/rtps/participant/RTPSParticipant.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.h
  test/mock/rtps/RTPSParticipantImpl/rtps/participant/RTPSParticipantImpl.h
  versions.md
Labels: ready-to-merge

#3369 [17291] Add tests to check that remote builtin endpoints are honored
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/blackbox/api/dds-pim/PubSubWriter.hpp
  test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
  test/blackbox/api/fastrtps_deprecated/PubSubWriter.hpp
  test/blackbox/common/BlackboxTestsDiscovery.cpp
Labels: ready-to-merge

#3002 Include the right header when building for iOS
  src/cpp/utils/IPFinder.cpp
Labels: ci-pending

#3360 Add support for QNX 7.1 build
  .gitignore
  CMakeLists.txt
  build_qnx/Makefile
  build_qnx/common.mk
  build_qnx/nto/Makefile
  build_qnx/nto/aarch64/Makefile
  build_qnx/nto/aarch64/le/Makefile
  build_qnx/nto/x86_64/Makefile
  build_qnx/nto/x86_64/o/Makefile
  build_qnx/qnx.nto.toolchain.cmake
  build_qnx/qnx_patches/asio_qnx.patch
  build_qnx/qnx_patches/fastcdr_qnx.patch
  build_qnx/qnx_patches/googletest_qnx.patch
  build_qnx/qnx_patches/tinyxml2_qnx.patch
  cmake/modules/FindAsio.cmake
  cmake/modules/FindThreads.cmake
  src/cpp/utils/shared_memory/SharedDir.hpp
  test/CMakeLists.txt
  test/unittest/CMakeLists.txt
  test/unittest/dds/publisher/CMakeLists.txt
  test/unittest/dds/publisher/DataWriterTests.cpp
  test/unittest/dds/status/CMakeLists.txt
  test/unittest/dynamic_types/CMakeLists.txt
  test/unittest/rtps/builtin/CMakeLists.txt
  test/unittest/rtps/common/CMakeLists.txt
  test/unittest/rtps/discovery/CMakeLists.txt
  test/unittest/rtps/network/CMakeLists.txt
  test/unittest/rtps/writer/CMakeLists.txt
  test/unittest/rtps/writer/ReaderProxyTests.cpp
  test/unittest/security/accesscontrol/CMakeLists.txt
  test/unittest/security/authentication/CMakeLists.txt
  test/unittest/statistics/dds/CMakeLists.txt
  test/unittest/statistics/rtps/CMakeLists.txt
  test/unittest/transport/CMakeLists.txt
  test/unittest/utils/CMakeLists.txt
  test/unittest/xmlparser/CMakeLists.txt
  versions.md
Labels: ready-to-merge

#3410 Fix CMake warning [17884]
  test/unittest/statistics/dds/CMakeLists.txt
Labels: skip-ci

#3411 Fix asio dependency
  examples/cpp/dds/DeadlineQoSExample/CMakeLists.txt
  examples/cpp/dds/DeadlineQoSExample/deadlinepayloadPubSubMain.cxx
Labels: skip-ci

#3418 [17941] Fix regression introduced by #3396
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.cpp
  test/blackbox/common/DDSBlackboxTestsDiscovery.cpp
Labels: needs-review
