Repository eProsima/Fast-DDS, pull requests merged in 2023-01, with the labels that each got.

#3175 [16603] Secure PDP exchange
  include/fastdds/rtps/builtin/discovery/participant/PDP.h
  src/cpp/rtps/builtin/discovery/endpoint/EDPClient.cpp
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPClient.h
  src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer.hpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  test/communication/secure_ds_simple_secure_msg_crypto_pub.xml
  test/communication/secure_ds_simple_secure_msg_crypto_sub.xml
Labels: no-test, no-aarch

#3197 [16522] Add backports to PR checklist
  .github/pull_request_template.md
Labels: skip-ci

#3206 Fix versions.md
  versions.md
Labels: skip-ci

#3205 [16736] Add DataWriterListener on_unacknowledged_sample_removed callback
  include/fastdds/dds/publisher/DataWriterListener.hpp
  versions.md
Labels: no-test

#3211 Public RTPS API: RTPSWriter::has_been_delivered()
  include/fastdds/rtps/writer/RTPSWriter.h
  versions.md
Labels: skip-ci

#3185 [16647] Use shared_ptr for internal singletons
  cmake/modules/FindThirdpartyBoost.cmake
  include/fastdds/dds/domain/DomainParticipantFactory.hpp
  include/fastdds/dds/log/Log.hpp
  include/fastdds/rtps/RTPSDomain.h
  include/fastdds/rtps/participant/RTPSParticipant.h
  src/cpp/fastdds/domain/DomainParticipantFactory.cpp
  src/cpp/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/fastdds/log/Log.cpp
  src/cpp/fastdds/log/LogResources.hpp
  src/cpp/fastrtps_deprecated/Domain.cpp
  src/cpp/rtps/RTPSDomain.cpp
  src/cpp/rtps/RTPSDomainImpl.hpp
  src/cpp/utils/shared_memory/BoostAtExitRegistry.hpp
  src/cpp/utils/shared_memory/RobustInterprocessCondition.hpp
  src/cpp/utils/shared_memory/SharedMemSegment.hpp
  test/mock/rtps/RTPSDomain/fastdds/rtps/RTPSDomain.h
  test/mock/rtps/RTPSDomainImpl/rtps/RTPSDomainImpl.hpp
  test/unittest/security/authentication/AuthenticationPluginTests.hpp
  thirdparty/boost/include/boost/interprocess/detail/intermodule_singleton_common.hpp
  thirdparty/boost/include/boost/interprocess/detail/workaround.hpp
  thirdparty/boost/include/boostconfig.hpp
Labels: ci-pending

#3203 [16608] Fix total_unread_ consistent with reader's history upon get_first_untaken_info()
  src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/blackbox/api/dds-pim/PubSubWriter.hpp
  test/blackbox/common/DDSBlackboxTestsBasic.cpp
  test/blackbox/common/DDSBlackboxTestsDataReader.cpp
Labels: ci-pending

#3214 Select Discovery Server branch on sanitizers action
  .github/workflows/sanitizer-tests.yaml
Labels: skip-ci

#3216 [16801] Bump version to 2.6.4
  CMakeLists.txt
  package.xml
Labels: skip-ci

#3165 [16315] Doxygen documentation: add deprecation notice to ThroughputControllerDescriptor
  include/fastdds/dds/core/policy/QosPolicies.hpp
  include/fastdds/dds/publisher/qos/DataWriterQos.hpp
  include/fastdds/rtps/attributes/RTPSParticipantAttributes.h
  include/fastdds/rtps/attributes/WriterAttributes.h
  include/fastdds/rtps/flowcontrol/ThroughputControllerDescriptor.h
Labels: skip-ci

#3177 Fix deadlock on TLS closure [16288]
  src/cpp/rtps/transport/TCPChannelResourceSecure.cpp
  src/cpp/rtps/transport/tcp/RTCPMessageManager.cpp
  test/blackbox/common/BlackboxTestsTransportTCP.cpp
Labels: ready-to-merge

#3223 Fix total_unread_ consistent with reader's history after get_first_untaken_info
  src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/blackbox/api/dds-pim/PubSubWriter.hpp
  test/blackbox/common/DDSBlackboxTestsDataReader.cpp
Labels: ready-to-merge

#3229 [16802] Bump version to 2.9.1
  CMakeLists.txt
  package.xml
Labels: ready-to-merge, skip-ci

#3232 [16802] Fix versions in fastrtps.repos
  fastrtps.repos
Labels: skip-ci

#3231 [16802] Branch out 2.10.x
  .github/workflows/mirror.yml
  CMakeLists.txt
  package.xml
Labels: ready-to-merge, skip-ci, first-to-merge

#3209 Remove odr-violation ASAN warning
  include/fastdds/rtps/attributes/ServerAttributes.h
  test/blackbox/CMakeLists.txt
  test/blackbox/common/DDSBlackboxTestsDiscovery.cpp
  test/unittest/dds/participant/CMakeLists.txt
Labels: ready-to-merge

#3245 [16740] Simple secure scenario additional tests
  test/certs/governance_disable_discovery_disable_rtps_helloworld_all_enable.smime
  test/certs/governance_disable_discovery_disable_rtps_helloworld_all_enable.xml
  test/certs/governance_disable_discovery_helloworld_all_enable.smime
  test/certs/governance_disable_discovery_helloworld_all_enable.xml
  test/certs/governance_disable_rtps_helloworld_all_enable.smime
  test/certs/governance_disable_rtps_helloworld_all_enable.xml
  test/communication/CMakeLists.txt
  test/communication/secure_ds_simple_secure_no_discovery_no_rtps_protection_pub.xml
  test/communication/secure_ds_simple_secure_no_discovery_no_rtps_protection_sub.xml
  test/communication/secure_ds_simple_secure_no_discovery_protection_pub.xml
  test/communication/secure_ds_simple_secure_no_discovery_protection_sub.xml
  test/communication/secure_ds_simple_secure_no_rtps_protection_pub.xml
  test/communication/secure_ds_simple_secure_no_rtps_protection_sub.xml
  test/communication/secure_simple_ds_server_no_discovery_no_rtps_protection.xml
  test/communication/secure_simple_ds_server_no_discovery_protection.xml
  test/communication/secure_simple_ds_server_no_rtps_protection.xml
Labels: ci-pending

#3235 [16671] Fixed StatisticsSubmessageData unaligned access
  include/fastdds/rtps/common/Time_t.h
  src/cpp/rtps/common/Time_t.cpp
  src/cpp/statistics/rtps/messages/RTPSStatisticsMessages.hpp
Labels: ready-to-merge

#3171 Add Windows linkage to get_inconsistent_topic_status.
  include/fastdds/dds/topic/Topic.hpp
Labels: ready-to-merge

#3249 [16880] Fix simple test scenarios
  src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPClient.h
  test/communication/CMakeLists.txt
Labels: ci-pending

#3255 [16904] Bump version to v2.1.3
  configure.ac
  package.xml
Labels: ready-to-merge, skip-ci

#3248 [16909] Update pull request template
  .github/pull_request_template.md
Labels: ready-to-merge, skip-ci

#3233 [16736] RTPSWriter::has_been_fully_delivered tests
  include/fastdds/rtps/writer/RTPSWriter.h
  test/blackbox/common/RTPSBlackboxTestsBasic.cpp
  test/blackbox/common/RTPSWithRegistrationWriter.hpp
Labels: no-test, ci-pending

#3210 [16736] On unacknowledged sample removed tests
  test/blackbox/api/dds-pim/PubSubWriter.hpp
  test/blackbox/common/DDSBlackboxTestsListeners.cpp
Labels: no-test, ci-pending
