Repository eProsima/Fast-DDS, pull requests merged in 2023-02, with the labels that each got.

#3173 New Request-Reply example [16607]
  examples/cpp/dds/CMakeLists.txt
  examples/cpp/dds/ClientServerTest/.gitignore
  examples/cpp/dds/ClientServerTest/CMakeLists.txt
  examples/cpp/dds/ClientServerTest/ClientServerTypes.cpp
  examples/cpp/dds/ClientServerTest/ClientServerTypes.h
  examples/cpp/dds/ClientServerTest/EprosimaClient.cpp
  examples/cpp/dds/ClientServerTest/EprosimaClient.h
  examples/cpp/dds/ClientServerTest/EprosimaClientTest.cpp
  examples/cpp/dds/ClientServerTest/EprosimaClientTest.h
  examples/cpp/dds/ClientServerTest/EprosimaServer.cpp
  examples/cpp/dds/ClientServerTest/EprosimaServer.h
  examples/cpp/dds/ClientServerTest/README.txt
  examples/cpp/dds/ClientServerTest/main_ClientServerTestFastRTPS.cpp
  examples/cpp/dds/RequestReplyExample/CMakeLists.txt
  examples/cpp/dds/RequestReplyExample/Calculator.cxx
  examples/cpp/dds/RequestReplyExample/Calculator.h
  examples/cpp/dds/RequestReplyExample/Calculator.idl
  examples/cpp/dds/RequestReplyExample/CalculatorClient.cpp
  examples/cpp/dds/RequestReplyExample/CalculatorPubSubTypes.cxx
  examples/cpp/dds/RequestReplyExample/CalculatorPubSubTypes.h
  examples/cpp/dds/RequestReplyExample/CalculatorServer.cpp
  examples/cpp/dds/RequestReplyExample/README.md
Labels: ready-to-merge, no-test

#3260 [16905] Bump version to v2.7.2
  CMakeLists.txt
  package.xml
Labels: skip-ci

#3240 [16737] On unacknowledged sample removed implementation
  include/fastdds/rtps/writer/RTPSWriter.h
  include/fastdds/rtps/writer/ReaderProxy.h
  include/fastdds/rtps/writer/StatefulWriter.h
  include/fastdds/rtps/writer/StatelessWriter.h
  src/cpp/fastdds/publisher/DataWriterHistory.cpp
  src/cpp/fastdds/publisher/DataWriterHistory.hpp
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/publisher/DataWriterImpl.hpp
  src/cpp/rtps/writer/ReaderProxy.cpp
  src/cpp/rtps/writer/StatefulWriter.cpp
  src/cpp/rtps/writer/StatelessWriter.cpp
  test/blackbox/common/DDSBlackboxTestsListeners.cpp
  test/blackbox/common/RTPSBlackboxTestsBasic.cpp
  test/blackbox/common/RTPSWithRegistrationWriter.hpp
  test/mock/rtps/PublisherHistory/fastdds/publisher/DataWriterHistory.hpp
  test/mock/rtps/RTPSWriter/fastdds/rtps/writer/RTPSWriter.h
  test/mock/rtps/StatefulWriter/fastdds/rtps/writer/StatefulWriter.h
  test/unittest/rtps/writer/ReaderProxyTests.cpp
  versions.md
Labels: ci-pending

#3295 [17123] Update foonathan_memory quality declaration
  Quality_Declaration_foonathan_memory.md
Labels: skip-ci

#3298 [16979] Moved boost at_exit registration to RTPSDomainImpl
  src/cpp/rtps/RTPSDomainImpl.hpp
  src/cpp/utils/shared_memory/RobustInterprocessCondition.hpp
  src/cpp/utils/shared_memory/SharedMemSegment.hpp
Labels: ci-pending

#3267 [16910] Remove check 'Documentation builds and test pass locally' from pull request template
  .github/actions/install-apt-packages-documentation/action.yml
  .github/actions/install-apt-packages/action.yml
  .github/pull_request_template.md
  .github/workflows/documentation-tests.yaml
Labels: needs-review

#3308 [17125] Add milestone check to PR template.
  .github/pull_request_template.md
Labels: ready-to-merge, skip-ci

#3312 [17274] Using functors in StatefulWriter.cpp for_matched_readers
  src/cpp/rtps/writer/StatefulWriter.cpp
Labels: ci-pending

#3196 Compilation error due to test [16371]
  test/unittest/dds/topic/DDSSQLFilter/CMakeLists.txt
Labels: ready-to-merge

#3329 [17351] Remove 2.7.x branch from Mergifyio suggestions
  .github/pull_request_template.md
Labels: skip-ci

#3313 [17206] Restore participant domainID tag in XML profile
  resources/xsd/fastRTPS_profiles.xsd
  test/system/tools/xmlvalidation/XMLTesterExample.xml
  test/system/tools/xmlvalidation/profileAll.xml
  test/system/tools/xmlvalidation/profileDomainParticipant.xml
  tools/fastdds/fastdds.py
Labels: ready-to-merge
