Repository eProsima/Fast-DDS, pull requests merged in 2023-09, with the labels that each got.

#3754 [18071] Update classes to implement interfaces
  include/fastdds/rtps/builtin/discovery/participant/PDP.h
  include/fastdds/rtps/participant/RTPSParticipant.h
  include/fastdds/statistics/rtps/monitor_service/interfaces/IStatusQueryable.hpp
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.h
  src/cpp/statistics/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/statistics/fastdds/domain/DomainParticipantImpl.hpp
  src/cpp/statistics/rtps/monitor-service/MonitorService.cpp
  test/mock/dds/Publisher/fastdds/dds/publisher/Publisher.hpp
  test/mock/rtps/BuiltinProtocols/fastdds/rtps/builtin/BuiltinProtocols.h
  test/mock/rtps/EDP/fastdds/rtps/builtin/discovery/endpoint/EDP.h
  test/mock/rtps/RTPSParticipantImpl/rtps/participant/RTPSParticipantImpl.h
  test/mock/rtps/ReaderProxyData/fastdds/rtps/builtin/data/ReaderProxyData.h
  test/mock/rtps/SecurityManager/rtps/security/SecurityManager.h
  test/mock/rtps/TypeLookupManager/fastdds/dds/builtin/typelookup/TypeLookupManager.hpp
  test/mock/rtps/WLP/fastdds/rtps/builtin/liveliness/WLP.h
  test/mock/rtps/WriterHistory/fastdds/rtps/history/WriterHistory.h
  test/mock/rtps/WriterProxyData/fastdds/rtps/builtin/data/WriterProxyData.h
  test/unittest/rtps/discovery/CMakeLists.txt
  test/unittest/rtps/discovery/PDPTests.cpp
  test/unittest/statistics/dds/StatisticsDomainParticipantMockTests.cpp
  test/unittest/statistics/dds/StatisticsDomainParticipantMockTests/mock/statistics/fastdds/publisher/PublisherImpl.hpp
  test/unittest/statistics/rtps/CMakeLists.txt
  test/unittest/statistics/rtps/RTPSStatisticsTests.cpp
Labels: no-test

#3823 [17492] Platform implementations for set_name_to_current_thread
  src/cpp/utils/SystemInfo.cpp
  src/cpp/utils/threading.hpp
  src/cpp/utils/threading/threading_osx.ipp
  src/cpp/utils/threading/threading_pthread.ipp
  src/cpp/utils/threading/threading_win32.ipp
Labels: ready-to-merge

#3831 [19461] Fix Fast DDS nightly jobs
  .github/workflows/config/coverage.repos
  .github/workflows/config/default_ci.repos
  .github/workflows/config/nightly.repos
  .github/workflows/sanitizer-tests.yaml
  .github/workflows/statistics_coverage.yml
  .github/workflows/thread-sanitizer.yaml
  fastrtps.repos
Labels: ready-to-merge

#3837 [19461] Fix ASAN nightly jobs
  .github/workflows/sanitizer-tests.yaml
Labels: skip-ci

#3735 Fix real-time in Flow Controller
  include/fastdds/rtps/history/History.h
  include/fastdds/rtps/history/ReaderHistory.h
  include/fastdds/rtps/history/WriterHistory.h
  include/fastdds/rtps/messages/RTPSMessageGroup.h
  include/fastdds/rtps/writer/LocatorSelectorSender.hpp
  include/fastdds/rtps/writer/RTPSWriter.h
  include/fastdds/rtps/writer/StatefulPersistentWriter.h
  include/fastdds/rtps/writer/StatefulWriter.h
  include/fastdds/rtps/writer/StatelessPersistentWriter.h
  include/fastdds/rtps/writer/StatelessWriter.h
  include/fastrtps/attributes/LibrarySettingsAttributes.h
  include/fastrtps/publisher/PublisherHistory.h
  include/fastrtps/utils/TimedConditionVariable.hpp
  src/cpp/fastdds/publisher/DataWriterHistory.cpp
  src/cpp/fastdds/publisher/DataWriterHistory.hpp
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
  src/cpp/fastdds/subscriber/history/DataReaderHistory.hpp
  src/cpp/fastrtps_deprecated/publisher/PublisherHistory.cpp
  src/cpp/rtps/flowcontrol/FlowController.hpp
  src/cpp/rtps/flowcontrol/FlowControllerImpl.hpp
  src/cpp/rtps/history/History.cpp
  src/cpp/rtps/history/ReaderHistory.cpp
  src/cpp/rtps/history/WriterHistory.cpp
  src/cpp/rtps/messages/RTPSMessageGroup.cpp
  src/cpp/rtps/messages/SendBuffersManager.cpp
  src/cpp/rtps/messages/SendBuffersManager.hpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.h
  src/cpp/rtps/writer/RTPSWriter.cpp
  src/cpp/rtps/writer/StatefulPersistentWriter.cpp
  src/cpp/rtps/writer/StatefulWriter.cpp
  src/cpp/rtps/writer/StatelessPersistentWriter.cpp
  src/cpp/rtps/writer/StatelessWriter.cpp
  test/mock/rtps/RTPSMessageGroup/fastdds/rtps/messages/RTPSMessageGroup.h
  test/mock/rtps/ReaderHistory/fastdds/rtps/history/ReaderHistory.h
  test/mock/rtps/WriterHistory/fastdds/rtps/history/WriterHistory.h
  test/realtime/UserThreadNonBlockedTest.cpp
  test/realtime/mutex_testing_tool/Mutex.cpp
  test/realtime/mutex_testing_tool/Mutex.hpp
  test/realtime/mutex_testing_tool/TMutex.cpp
  test/realtime/mutex_testing_tool/TMutex.hpp
  test/unittest/rtps/flowcontrol/FlowControllerPublishModesOnAsyncTests.cpp
  test/unittest/rtps/flowcontrol/FlowControllerPublishModesOnLimitedAsyncTests.cpp
  test/unittest/rtps/flowcontrol/FlowControllerPublishModesOnSyncTests.cpp
Labels: ready-to-merge

#3741 Remove warning on Win32 architecture
  test/blackbox/api/dds-pim/PubSubReader.hpp
Labels: ready-to-merge

#3846 Fix .repos branches
  fastrtps.repos
Labels: skip-ci

#3503 [18503] Use eProsima-CI external actions for mirror workflow [WIP]
  .github/workflows/mirror.yml
Labels: skip-ci

#3739 [19208] Fix ParameterPropertyList increment operators
  include/fastdds/dds/core/policy/ParameterTypes.hpp
  test/unittest/dds/core/CMakeLists.txt
  test/unittest/dds/core/policy/CMakeLists.txt
  test/unittest/dds/core/policy/ParameterPropertyList.cpp
Labels: ready-to-merge

#3732 [19208] Improve script portability
  test/profiling/allocations/test.sh
  test/profiling/allocations/test_with_memory_tool.sh
  tools/fastdds/fastdds
  tools/fastdds/ros-discovery
  utils/scripts/update_generated_code_from_idl.sh
Labels: needs-review

#3841 [19505] Process environment variables on XML
  include/fastrtps/xmlparser/XMLParserCommon.h
  src/cpp/rtps/xmlparser/XMLElementParser.cpp
  src/cpp/rtps/xmlparser/XMLEndpointParser.cpp
  src/cpp/rtps/xmlparser/XMLParser.cpp
  src/cpp/rtps/xmlparser/XMLParserCommon.cpp
  src/cpp/rtps/xmlparser/XMLParserUtils.hpp
  src/cpp/utils/SystemInfo.cpp
  test/unittest/common/env_var_utils.hpp
  test/unittest/xmlparser/CMakeLists.txt
  test/unittest/xmlparser/XMLElementParserTests.cpp
  test/unittest/xmlparser/XMLProfileParserTests.cpp
  test/unittest/xmlparser/test_xml_profile_env_var.xml
  versions.md
Labels: ci-pending

#3856 [19546] Use FASTRTPS_NO_LIB on unittest root folder
  test/unittest/CMakeLists.txt
  test/unittest/dds/collections/CMakeLists.txt
  test/unittest/dds/core/condition/CMakeLists.txt
  test/unittest/dds/core/entity/CMakeLists.txt
  test/unittest/dds/participant/CMakeLists.txt
  test/unittest/dds/publisher/CMakeLists.txt
  test/unittest/dds/status/CMakeLists.txt
  test/unittest/dds/subscriber/CMakeLists.txt
  test/unittest/dds/topic/CMakeLists.txt
  test/unittest/dds/topic/DDSSQLFilter/CMakeLists.txt
  test/unittest/dynamic_types/CMakeLists.txt
  test/unittest/logging/CMakeLists.txt
  test/unittest/logging/log_macros/CMakeLists.txt
  test/unittest/rtps/DataSharing/CMakeLists.txt
  test/unittest/rtps/builtin/CMakeLists.txt
  test/unittest/rtps/common/CMakeLists.txt
  test/unittest/rtps/discovery/CMakeLists.txt
  test/unittest/rtps/flowcontrol/CMakeLists.txt
  test/unittest/rtps/history/CMakeLists.txt
  test/unittest/rtps/network/CMakeLists.txt
  test/unittest/rtps/persistence/CMakeLists.txt
  test/unittest/rtps/reader/CMakeLists.txt
  test/unittest/rtps/resources/timedevent/CMakeLists.txt
  test/unittest/rtps/security/CMakeLists.txt
  test/unittest/rtps/writer/CMakeLists.txt
  test/unittest/security/accesscontrol/CMakeLists.txt
  test/unittest/security/authentication/CMakeLists.txt
  test/unittest/security/cryptography/CMakeLists.txt
  test/unittest/security/logging/CMakeLists.txt
  test/unittest/statistics/dds/CMakeLists.txt
  test/unittest/statistics/rtps/CMakeLists.txt
  test/unittest/transport/CMakeLists.txt
  test/unittest/utils/CMakeLists.txt
  test/unittest/xmlparser/CMakeLists.txt
  test/unittest/xtypes/CMakeLists.txt
Labels: no-test

#3733 Fix asymmetric whitelist matching [19035]
  include/fastdds/dds/core/policy/ParameterTypes.hpp
  include/fastdds/rtps/attributes/RTPSParticipantAttributes.h
  include/fastdds/rtps/builtin/BuiltinProtocols.h
  include/fastdds/rtps/builtin/data/NetworkConfiguration.hpp
  include/fastdds/rtps/builtin/data/ParticipantProxyData.h
  include/fastdds/rtps/builtin/data/ReaderProxyData.h
  include/fastdds/rtps/builtin/data/WriterProxyData.h
  include/fastdds/rtps/common/Types.h
  include/fastdds/rtps/transport/ChainingTransport.h
  include/fastdds/rtps/transport/TransportInterface.h
  include/fastrtps/qos/ParameterTypes.h
  src/cpp/fastdds/core/policy/ParameterSerializer.hpp
  src/cpp/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/rtps/builtin/BuiltinProtocols.cpp
  src/cpp/rtps/builtin/data/ParticipantProxyData.cpp
  src/cpp/rtps/builtin/data/ReaderProxyData.cpp
  src/cpp/rtps/builtin/data/WriterProxyData.cpp
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
  src/cpp/rtps/network/NetworkFactory.cpp
  src/cpp/rtps/network/NetworkFactory.h
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/transport/TCPAcceptor.cpp
  src/cpp/rtps/transport/TCPAcceptorBasic.cpp
  src/cpp/rtps/transport/TCPTransportInterface.cpp
  src/cpp/rtps/transport/TCPTransportInterface.h
  src/cpp/rtps/transport/TCPv6Transport.cpp
  src/cpp/rtps/transport/TCPv6Transport.h
  src/cpp/rtps/transport/UDPTransportInterface.cpp
  src/cpp/rtps/transport/UDPTransportInterface.h
  src/cpp/rtps/transport/shared_mem/SharedMemTransport.cpp
  src/cpp/rtps/transport/shared_mem/SharedMemTransport.h
  test/blackbox/common/BlackboxTestsNetworkConf.cpp
  test/blackbox/common/BlackboxTestsTransportTCP.cpp
  test/blackbox/common/BlackboxTestsTransportUDP.cpp
  test/mock/rtps/NetworkFactory/rtps/network/NetworkFactory.h
  test/unittest/rtps/network/mock/MockTransport.h
  test/unittest/transport/SharedMemTests.cpp
  test/unittest/transport/TCPv6Tests.cpp
  test/unittest/transport/UDPv6Tests.cpp
Labels: ready-to-merge

#3858 [19590] Change history remove change return statement
  include/fastdds/rtps/history/History.h
  src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
  src/cpp/rtps/history/History.cpp
  src/cpp/rtps/history/ReaderHistory.cpp
  src/cpp/rtps/history/WriterHistory.cpp
  test/blackbox/common/BlackboxTestsPubSubHistory.cpp
  test/mock/rtps/ReaderHistory/fastdds/rtps/history/ReaderHistory.h
Labels: ci-pending

#3598 [18913] Expose payload pool in DDS layer example
  examples/cpp/dds/CMakeLists.txt
  examples/cpp/dds/CustomPayloadPoolExample/CMakeLists.txt
  examples/cpp/dds/CustomPayloadPoolExample/CustomPayloadPool.hpp
  examples/cpp/dds/CustomPayloadPoolExample/CustomPayloadPoolData.cxx
  examples/cpp/dds/CustomPayloadPoolExample/CustomPayloadPoolData.h
  examples/cpp/dds/CustomPayloadPoolExample/CustomPayloadPoolData.idl
  examples/cpp/dds/CustomPayloadPoolExample/CustomPayloadPoolDataCdrAux.hpp
  examples/cpp/dds/CustomPayloadPoolExample/CustomPayloadPoolDataCdrAux.ipp
  examples/cpp/dds/CustomPayloadPoolExample/CustomPayloadPoolDataPubSubTypes.cxx
  examples/cpp/dds/CustomPayloadPoolExample/CustomPayloadPoolDataPubSubTypes.h
  examples/cpp/dds/CustomPayloadPoolExample/CustomPayloadPoolDataPublisher.cpp
  examples/cpp/dds/CustomPayloadPoolExample/CustomPayloadPoolDataPublisher.h
  examples/cpp/dds/CustomPayloadPoolExample/CustomPayloadPoolDataSubscriber.cpp
  examples/cpp/dds/CustomPayloadPoolExample/CustomPayloadPoolDataSubscriber.h
  examples/cpp/dds/CustomPayloadPoolExample/CustomPayloadPool_main.cpp
  examples/cpp/dds/CustomPayloadPoolExample/README.md
Labels: no-test, ci-pending

#3714 [19089] Fix HelloWorld DataSharing example idl
  examples/cpp/dds/HelloWorldExampleDataSharing/HelloWorld.cxx
  examples/cpp/dds/HelloWorldExampleDataSharing/HelloWorld.h
  examples/cpp/dds/HelloWorldExampleDataSharing/HelloWorld.idl
  examples/cpp/dds/HelloWorldExampleDataSharing/HelloWorldCdrAux.hpp
  examples/cpp/dds/HelloWorldExampleDataSharing/HelloWorldPubSubTypes.h
Labels: no-test, ci-pending

#3891 Not checking for C++11 on fast-discovery-server CMakeLists.txt
  tools/fds/CMakeLists.txt
Labels: no-test

#3887 [19490] Fix Github windows CI
  .github/workflows/config/default_ci_2.10.x.repos
  .github/workflows/config/default_ci_2.11.x.repos
  .github/workflows/config/default_ci_2.6.x.repos
  .github/workflows/config/default_ci_master.repos
  .github/workflows/config/nightly_2.10.x.repos
  .github/workflows/config/nightly_2.11.x.repos
  .github/workflows/config/nightly_2.6.x.repos
  .github/workflows/config/nightly_master.repos
  .github/workflows/nightly-windows-ci.yml
  .github/workflows/reusable-windows-ci.yml
  .github/workflows/windows-ci.yml
Labels: ci-pending

#3893 Maintain xtypes serialization to previous encoding version to maintain interop [19625]
  examples/cpp/dds/ContentFilteredTopicExample/HelloWorldTypeObject.cxx
  src/cpp/dynamic-types/AnnotationParameterValue.cpp
  src/cpp/dynamic-types/BuiltinAnnotationsTypeObject.cpp
  src/cpp/dynamic-types/DynamicTypeBuilderFactory.cpp
  src/cpp/dynamic-types/TypeIdentifier.cpp
  src/cpp/dynamic-types/TypeIdentifierTypes.cpp
  src/cpp/dynamic-types/TypeObject.cpp
  src/cpp/dynamic-types/TypeObjectFactory.cpp
  src/cpp/fastdds/builtin/common/RPCHeadersImpl.cpp
  src/cpp/fastdds/builtin/typelookup/TypeLookupManager.cpp
  src/cpp/fastdds/builtin/typelookup/common/TypeLookupTypes.cpp
  src/cpp/fastdds/core/policy/QosPoliciesSerializer.hpp
  test/blackbox/types/HelloWorldTypeObject.cxx
  test/blackbox/types/TestIncludeRegression3361TypeObject.cxx
  test/blackbox/types/TestRegression3361TypeObject.cxx
  test/unittest/dds/topic/DDSSQLFilter/data_types/ContentFilterTestTypeTypeObject.cxx
  test/unittest/dynamic_types/DynamicComplexTypesTests.cpp
  test/unittest/dynamic_types/idl/BasicTypeObject.cxx
  test/unittest/dynamic_types/idl/TestTypeObject.cxx
  test/unittest/dynamic_types/idl/new_features_4_2TypeObject.cxx
  test/unittest/xtypes/idl/TypesTypeObject.cxx
  test/unittest/xtypes/idl/WideEnumTypeObject.cxx
  test/xtypes/idl/TypesTypeObject.cxx
Labels: ci-pending

#3881 Prepare for Release Fast DDS v2.12.0
  PLATFORM_SUPPORT.md
  RELEASE_SUPPORT.md
  cmake/packaging/Config.cmake.in
  examples/cpp/dds/AdvancedConfigurationExample/CMakeLists.txt
  examples/cpp/dds/BasicConfigurationExample/CMakeLists.txt
  examples/cpp/dds/Configurability/CMakeLists.txt
  examples/cpp/dds/ContentFilteredTopicExample/CMakeLists.txt
  examples/cpp/dds/CustomListenerExample/CMakeLists.txt
  examples/cpp/dds/CustomPayloadPoolExample/CMakeLists.txt
  examples/cpp/dds/DeadlineQoSExample/CMakeLists.txt
  examples/cpp/dds/DisablePositiveACKs/CMakeLists.txt
  examples/cpp/dds/DiscoveryServerExample/CMakeLists.txt
  examples/cpp/dds/DynamicHelloWorldExample/CMakeLists.txt
  examples/cpp/dds/Filtering/CMakeLists.txt
  examples/cpp/dds/FlowControlExample/CMakeLists.txt
  examples/cpp/dds/HelloWorldExample/CMakeLists.txt
  examples/cpp/dds/HelloWorldExampleDataSharing/CMakeLists.txt
  examples/cpp/dds/HelloWorldExampleSharedMem/CMakeLists.txt
  examples/cpp/dds/HelloWorldExampleTCP/CMakeLists.txt
  examples/cpp/dds/HistoryKind/CMakeLists.txt
  examples/cpp/dds/Keys/CMakeLists.txt
  examples/cpp/dds/LateJoiners/CMakeLists.txt
  examples/cpp/dds/LifespanQoSExample/CMakeLists.txt
  examples/cpp/dds/LivelinessQoS/CMakeLists.txt
  examples/cpp/dds/OwnershipStrengthQoSExample/CMakeLists.txt
  examples/cpp/dds/RequestReplyExample/CMakeLists.txt
  examples/cpp/dds/SampleConfig_Controller/CMakeLists.txt
  examples/cpp/dds/SampleConfig_Events/CMakeLists.txt
  examples/cpp/dds/SampleConfig_Multimedia/CMakeLists.txt
  examples/cpp/dds/SecureHelloWorldExample/CMakeLists.txt
  examples/cpp/dds/StaticHelloWorldExample/CMakeLists.txt
  examples/cpp/dds/TypeLookupService/CMakeLists.txt
  examples/cpp/dds/WriterLoansExample/CMakeLists.txt
  examples/cpp/dds/ZeroCopyExample/CMakeLists.txt
  examples/cpp/rtps/AsSocket/CMakeLists.txt
  examples/cpp/rtps/Persistent/CMakeLists.txt
  examples/cpp/rtps/Registered/CMakeLists.txt
  fuzz/C++/fuzz_XMLProfiles/CMakeLists.txt
  fuzz/C++/fuzz_processCDRMsg/CMakeLists.txt
  roadmap.md
  tools/fds/CMakeLists.txt
  versions.md
Labels: skip-ci
