Repository eProsima/Fast-DDS, pull requests merged in 2023-12, with the labels that each got.

#3996 [19837] TypeObjectRegistry implementation
  include/fastdds/dds/xtypes/common.hpp
  include/fastdds/dds/xtypes/type_representation/TypeObjectRegistry.hpp
  include/fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp
  src/cpp/CMakeLists.txt
  src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.cpp
  src/cpp/fastdds/xtypes/type_representation/TypeObjectUtils.cpp
  src/cpp/fastdds/xtypes/type_representation/dds_xtypes_typeobjectCdrAux.ipp
  src/cpp/fastdds/xtypes/type_representation/dds_xtypes_typeobjectPubSubTypes.cxx
  test/unittest/dds/publisher/CMakeLists.txt
  test/unittest/dds/status/CMakeLists.txt
  test/unittest/dds/xtypes/type_representation/CMakeLists.txt
  test/unittest/dds/xtypes/type_representation/TypeObjectRegistryTests.cpp
  test/unittest/dds/xtypes/type_representation/TypeObjectUtilsTests.cpp
  test/unittest/statistics/dds/CMakeLists.txt
  utils/scripts/update_generated_code_from_idl.sh
Labels: no-test, doc-pending, ci-pending

#4094 [20024] Better handling of trigger events in docs CI
  .github/workflows/documentation-tests.yaml
Labels: ready-to-merge

#4061 [20019] Add Autofill port to TCP Transport
  src/cpp/rtps/transport/TCPAcceptor.cpp
  src/cpp/rtps/transport/TCPTransportInterface.cpp
  src/cpp/rtps/transport/TCPTransportInterface.h
  src/cpp/rtps/transport/TCPv4Transport.cpp
  src/cpp/rtps/transport/TCPv6Transport.cpp
  test/blackbox/CMakeLists.txt
  test/blackbox/common/BlackboxTestsTransportTCP.cpp
  test/unittest/transport/TCPv4Tests.cpp
  test/unittest/transport/TCPv6Tests.cpp
Labels: ready-to-merge

#4091 [20025] Fix branch selection on Github CI
  .github/workflows/documentation-tests.yaml
  .github/workflows/reusable-windows-ci.yml
Labels: ci-pending

#4078 [20068] Mark on_participant_discovery overload removal
  include/fastdds/dds/domain/DomainParticipantListener.hpp
Labels: no-test

#4057 Improve IgnoreNonExistentSegment test (backport #4036)
  test/blackbox/common/BlackboxTestsTransportSHM.cpp
Labels: ready-to-merge

#3973 [19780] Add interface whitelist by name
  include/fastrtps/xmlparser/XMLParserCommon.h
  resources/xsd/fastRTPS_profiles.xsd
  src/cpp/rtps/transport/TCPv4Transport.cpp
  src/cpp/rtps/transport/TCPv6Transport.cpp
  src/cpp/rtps/transport/UDPv4Transport.cpp
  src/cpp/rtps/transport/UDPv6Transport.cpp
  src/cpp/rtps/xmlparser/XMLParser.cpp
  src/cpp/rtps/xmlparser/XMLParserCommon.cpp
  test/blackbox/common/BlackboxTestsNetworkConf.cpp
  test/system/tools/xmlvalidation/transportDescriptor_profile.xml
  test/unittest/transport/TCPv4Tests.cpp
  test/unittest/xmlparser/XMLParserTests.cpp
  versions.md
Labels: ci-pending

#4047 [19967] Define a super client by environment variable
  include/fastdds/rtps/attributes/ServerAttributes.h
  src/cpp/rtps/RTPSDomain.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
  test/unittest/dds/participant/ParticipantTests.cpp
Labels: ci-pending

#4014 [19851] Fix missing mandatory attribute check in XML parser struct type (backport #3995)
  src/cpp/rtps/xmlparser/XMLDynamicParser.cpp
  test/unittest/xmlparser/XMLParserTests.cpp
  test/unittest/xmlparser/regressions/19851_profile_bin.xml
Labels: ready-to-merge

#4121 New AnnotationDescriptor API [20115]
  include/fastdds/dds/xtypes/dynamic_types/AnnotationDescriptor.hpp
  src/cpp/fastdds/xtypes/dynamic_types/AnnotationDescriptorImpl.hpp
Labels: skip-ci

#4125 [20117] Fix setaffinity directive for Android
  src/cpp/utils/threading/threading_pthread.ipp
Labels: no-test, ci-pending

#4099 [19939] TCP deadlock on channel reuse
  src/cpp/rtps/transport/TCPTransportInterface.cpp
  test/blackbox/common/BlackboxTestsTransportTCP.cpp
  test/blackbox/common/TCPReqRepHelloWorldReplier.cpp
  test/blackbox/common/TCPReqRepHelloWorldReplier.hpp
Labels: ci-pending

#4054 [19794] Added idl file and generated types for typelookup service.
  include/fastdds/dds/xtypes/type_representation/detail/dds-xtypes_typeobject.idl
  src/cpp/CMakeLists.txt
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupManager.cpp
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupManager.hpp
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupReplyListener.cpp
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupRequestListener.cpp
  src/cpp/fastdds/builtin/type_lookup_service/common/RPCHeadersImpl.cpp
  src/cpp/fastdds/builtin/type_lookup_service/common/RPCHeadersImplCdrAux.ipp
  src/cpp/fastdds/builtin/type_lookup_service/common/ReplyHeader.hpp
  src/cpp/fastdds/builtin/type_lookup_service/common/RequestHeader.hpp
  src/cpp/fastdds/builtin/type_lookup_service/common/TypeLookupTypes.cpp
  src/cpp/fastdds/builtin/type_lookup_service/common/TypeLookupTypes.hpp
  src/cpp/fastdds/builtin/type_lookup_service/common/TypeLookupTypesCdrAux.ipp
  src/cpp/fastdds/builtin/type_lookup_service/common/Types.hpp
  src/cpp/fastdds/builtin/type_lookup_service/detail/TypeLookupTypes.hpp
  src/cpp/fastdds/builtin/type_lookup_service/detail/TypeLookupTypes.idl
  src/cpp/fastdds/builtin/type_lookup_service/detail/TypeLookupTypesCdrAux.hpp
  src/cpp/fastdds/builtin/type_lookup_service/detail/TypeLookupTypesCdrAux.ipp
  src/cpp/fastdds/builtin/type_lookup_service/detail/TypeLookupTypesPubSubTypes.cxx
  src/cpp/fastdds/builtin/type_lookup_service/detail/TypeLookupTypesPubSubTypes.h
  src/cpp/fastdds/builtin/type_lookup_service/detail/rpc_types.hpp
  src/cpp/fastdds/builtin/type_lookup_service/detail/rpc_types.idl
  src/cpp/fastdds/builtin/type_lookup_service/detail/rpc_typesCdrAux.hpp
  src/cpp/fastdds/builtin/type_lookup_service/detail/rpc_typesCdrAux.ipp
  src/cpp/fastdds/builtin/type_lookup_service/detail/rpc_typesPubSubTypes.cxx
  src/cpp/fastdds/builtin/type_lookup_service/detail/rpc_typesPubSubTypes.h
  src/cpp/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.cpp
  test/mock/rtps/TypeLookupManager/fastdds/builtin/type_lookup_service/TypeLookupManager.hpp
  test/unittest/dds/publisher/CMakeLists.txt
  test/unittest/statistics/dds/CMakeLists.txt
  utils/scripts/update_generated_code_from_idl.sh
Labels: no-test

#4092 [20062] Created TypeObjectRegistryObserver
  include/fastdds/dds/domain/DomainParticipantFactory.hpp
  include/fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupReplyListener.cpp
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupReplyListener.hpp
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupRequestListener.cpp
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupRequestListener.hpp
  src/cpp/fastdds/domain/DomainParticipantFactory.cpp
  src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.cpp
  src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.hpp
  src/cpp/fastdds/xtypes/type_representation/TypeObjectUtils.cpp
  src/cpp/rtps/RTPSDomain.cpp
  src/cpp/rtps/RTPSDomainImpl.hpp
  src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  test/mock/dds/QosPolicies/fastdds/dds/core/policy/QosPolicies.hpp
  test/mock/rtps/RTPSDomainImpl/rtps/RTPSDomainImpl.hpp
  test/unittest/dds/status/CMakeLists.txt
  test/unittest/rtps/discovery/CMakeLists.txt
  test/unittest/rtps/reader/CMakeLists.txt
Labels: no-test, ci-pending

#4097 [20021] TCP support for Discovery server CLI and env. var.
  examples/cpp/dds/DiscoveryServerExample/DiscoveryServerPublisher.cpp
  examples/cpp/dds/DiscoveryServerExample/DiscoveryServerServer.cpp
  examples/cpp/dds/DiscoveryServerExample/DiscoveryServerSubscriber.cpp
  examples/cpp/dds/DiscoveryServerExample/DiscoveryServer_main.cpp
  examples/cpp/dds/DiscoveryServerExample/README.md
  examples/cpp/dds/DiscoveryServerExample/arg_configuration.h
  examples/cpp/dds/DiscoveryServerExample/common.h
  include/fastdds/rtps/attributes/ServerAttributes.h
  include/fastdds/rtps/common/Locator.h
  src/cpp/rtps/RTPSDomain.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
  test/blackbox/common/BlackboxTestsDiscovery.cpp
  test/unittest/utils/LocatorTests.cpp
  tools/fds/server.cpp
  tools/fds/server.h
  versions.md
Labels: ready-to-merge

#4137 Fix dns filter in CMakeLists file
  test/unittest/dds/participant/CMakeLists.txt
Labels: ci-pending

#4131 [20134] Change serialize function default behaviour to omit the data representation
  include/fastdds/dds/topic/TopicDataType.hpp
  src/cpp/CMakeLists.txt
  src/cpp/fastdds/topic/TopicDataType.cpp
  test/unittest/dds/publisher/CMakeLists.txt
  test/unittest/dds/status/CMakeLists.txt
  test/unittest/dds/subscriber/CMakeLists.txt
  test/unittest/dds/topic/DDSSQLFilter/CMakeLists.txt
  test/unittest/dynamic_types/CMakeLists.txt
  test/unittest/rtps/builtin/CMakeLists.txt
  test/unittest/rtps/discovery/CMakeLists.txt
  test/unittest/rtps/network/CMakeLists.txt
  test/unittest/statistics/dds/CMakeLists.txt
  test/unittest/statistics/rtps/CMakeLists.txt
  test/unittest/xmlparser/CMakeLists.txt
  test/unittest/xtypes/CMakeLists.txt
Labels: ci-pending

#4141 New DynamicType API [20139]
  include/fastdds/dds/xtypes/dynamic_types/DynamicType.hpp
  include/fastdds/dds/xtypes/dynamic_types/DynamicTypeMember.hpp
  include/fastdds/dds/xtypes/dynamic_types/Types.hpp
  src/cpp/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/fastdds/xtypes/dynamic_types/DynamicTypeImpl.hpp
Labels: no-test

#4158 [20055] Fix compilation of Fast DDS Python tests
  include/fastdds/dds/topic/TopicDataType.hpp
Labels: skip-ci

#4156 [20055] Fix build with TLS, but not security.
  test/blackbox/common/BlackboxTests.cpp
  test/blackbox/common/BlackboxTests.hpp
  test/blackbox/common/BlackboxTestsSecurity.cpp
Labels: no-test

#4076 [20060] Fix data race on writer destruction while sending hearbeat
  src/cpp/rtps/writer/RTPSWriter.cpp
  test/blackbox/common/DDSBlackboxTestsDataWriter.cpp
Labels: ci-pending

#4126 [20116] Create async_get_type method and remove typelookup settings
  examples/cpp/dds/DynamicHelloWorldExample/HelloWorldPublisher.cpp
  examples/cpp/dds/DynamicHelloWorldExample/HelloWorldSubscriber.cpp
  examples/cpp/dds/DynamicHelloWorldExample/HelloWorldSubscriber.h
  examples/cpp/dds/TypeLookupService/TypeLookupPublisher.cpp
  examples/cpp/dds/TypeLookupService/TypeLookupSubscriber.cpp
  examples/cpp/dds/TypeLookupService/TypeLookupSubscriber.h
  include/fastdds/dds/domain/DomainParticipant.hpp
  include/fastdds/dds/domain/DomainParticipantListener.hpp
  include/fastdds/dds/topic/TopicDataType.hpp
  include/fastdds/rtps/attributes/RTPSParticipantAttributes.h
  include/fastdds/rtps/builtin/BuiltinProtocols.h
  include/fastdds/rtps/builtin/discovery/participant/PDP.h
  include/fastdds/rtps/participant/RTPSParticipant.h
  include/fastdds/rtps/participant/RTPSParticipantListener.h
  include/fastrtps/attributes/TopicAttributes.h
  include/fastrtps/xmlparser/XMLParser.h
  include/fastrtps/xmlparser/XMLParserCommon.h
  resources/xsd/fastRTPS_profiles.xsd
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupManager.cpp
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupManager.hpp
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupReplyListener.cpp
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupReplyListener.hpp
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupRequestListener.cpp
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupRequestListener.hpp
  src/cpp/fastdds/domain/DomainParticipant.cpp
  src/cpp/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/fastdds/domain/DomainParticipantImpl.hpp
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.cpp
  src/cpp/rtps/builtin/BuiltinProtocols.cpp
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
  src/cpp/rtps/participant/RTPSParticipant.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.h
  src/cpp/rtps/xmlparser/XMLElementParser.cpp
  src/cpp/rtps/xmlparser/XMLParserCommon.cpp
  test/dds/communication/PublisherDynamic.cpp
  test/dds/communication/SubscriberDynamic.cpp
  test/mock/dds/DomainParticipantImpl/fastdds/domain/DomainParticipantImpl.hpp
  test/mock/rtps/TypeLookupManager/fastdds/builtin/type_lookup_service/TypeLookupManager.hpp
  test/system/tools/xmlvalidation/all_profile.xml
  test/system/tools/xmlvalidation/domainParticipant_profile.xml
  test/unittest/dds/participant/ParticipantTests.cpp
  test/unittest/xmlparser/XMLElementParserTests.cpp
  test/unittest/xmlparser/XMLParserTests.cpp
  test/unittest/xmlparser/XMLProfileParserTests.cpp
  test/unittest/xmlparser/test_xml_deprecated.xml
  test/unittest/xmlparser/test_xml_profile.xml
  test/unittest/xmlparser/test_xml_profile_env_var.xml
  test/unittest/xmlparser/test_xml_rooted_deprecated.xml
  test/unittest/xmlparser/test_xml_rooted_profile.xml
  test/unittest/xmlparser/wrapper/XMLParserTest.hpp
  test/xtypes/TestPublisher.cpp
  test/xtypes/TestPublisher.h
  test/xtypes/TestSubscriber.cpp
  test/xtypes/TestSubscriber.h
Labels: no-test, doc-pending

#4176 [20020] Remove SHM locator from metatrafficUnicastLocList in LARGE_DATA
  src/cpp/rtps/attributes/RTPSParticipantAttributes.cpp
Labels: skip-ci

#4170 New DynamicTypeBuilderFactory API [20158]
  include/fastdds/dds/xtypes/dynamic_types/DynamicTypeBuilder.hpp
  include/fastdds/dds/xtypes/dynamic_types/DynamicTypeBuilderFactory.hpp
  include/fastdds/dds/xtypes/dynamic_types/Types.hpp
  src/cpp/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/fastdds/xtypes/dynamic_types/DynamicTypeBuilderFactoryImpl.hpp
  src/cpp/fastdds/xtypes/dynamic_types/TypeDescriptorImpl.hpp
Labels: no-test

#4140 [20131] Update TypeInformationParameter to contain xtype
  include/fastdds/dds/core/policy/QosPolicies.hpp
  include/fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp
  include/fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp
  include/fastdds/rtps/builtin/discovery/endpoint/EDP.h
  include/fastdds/rtps/builtin/discovery/participant/PDP.h
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupRequestListener.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
  test/mock/dds/QosPolicies/fastdds/dds/core/policy/QosPolicies.hpp
  test/unittest/rtps/builtin/CMakeLists.txt
  test/unittest/rtps/history/CMakeLists.txt
  test/unittest/rtps/persistence/CMakeLists.txt
  test/unittest/rtps/writer/CMakeLists.txt
  test/xtypes/TestPublisher.cpp
  test/xtypes/TestPublisher.h
  test/xtypes/TestSubscriber.cpp
  test/xtypes/TestSubscriber.h
  test/xtypes/XTypesTests.cpp
Labels: no-test, doc-pending

#4195 [20176] Bump version to 2.13.1
  CMakeLists.txt
  package.xml
Labels: skip-ci

#4196 [20022] Bump version to 2.6.7
  CMakeLists.txt
  RELEASE_SUPPORT.md
  package.xml
  versions.md
Labels: skip-ci
