Repository eProsima/Fast-DDS, pull requests merged in 2023-06, with the labels that each got.

#3531 [18673] Fix version and FastCDR patch file in QNX build files
  build_qnx/common.mk
  build_qnx/qnx_patches/fastcdr_qnx.patch
Labels: no-test, skip-ci

#3551 [18725] Added documentation version fallback
  CMakeLists.txt
Labels: skip-ci

#3516 Mod: correct the overhead time unit
  test/performance/latency/LatencyTestPublisher.cpp
Labels: ready-to-merge, skip-ci

#3583 [18917] Bump to version v2.6.5
  CMakeLists.txt
  package.xml
Labels: skip-ci

#1881 Fix rpmbuild issues
  CMakeLists.txt
  include/fastrtps/utils/md5.h
  tools/fastdds/fastdds
  tools/fastdds/ros-discovery
  tools/fds/CMakeLists.txt
Labels: ready-to-merge

#2611 [14260] Fixed exported symbols on ContentFilteredTopic
  include/fastdds/dds/topic/ContentFilteredTopic.hpp
  versions.md
Labels: ready-to-merge, no-test

#3554 Add configuration by profile to AdvanceConfigurationExample [18694]
  examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfigurationPublisher.cpp
  examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfigurationPublisher.h
  examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfigurationSubscriber.cpp
  examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfigurationSubscriber.h
  examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfiguration_main.cpp
  examples/cpp/dds/AdvancedConfigurationExample/CMakeLists.txt
  examples/cpp/dds/AdvancedConfigurationExample/README.md
  examples/cpp/dds/AdvancedConfigurationExample/arg_configuration.h
  examples/cpp/dds/AdvancedConfigurationExample/shm_off.xml
Labels: no-test, ci-pending

#3565 [18763] Improve content filter expression parameters checks and verbosity.
  src/cpp/fastdds/core/policy/ParameterSerializer.hpp
  src/cpp/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/fastdds/topic/ContentFilteredTopicImpl.cpp
  test/unittest/dds/participant/ParticipantTests.cpp
  test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
Labels: ready-to-merge

#2924 Implement Discovery Server Example [15464]
  examples/cpp/dds/CMakeLists.txt
  examples/cpp/dds/DiscoveryServerExample/CMakeLists.txt
  examples/cpp/dds/DiscoveryServerExample/DiscoveryServerPublisher.cpp
  examples/cpp/dds/DiscoveryServerExample/DiscoveryServerPublisher.h
  examples/cpp/dds/DiscoveryServerExample/DiscoveryServerServer.cpp
  examples/cpp/dds/DiscoveryServerExample/DiscoveryServerServer.h
  examples/cpp/dds/DiscoveryServerExample/DiscoveryServerSubscriber.cpp
  examples/cpp/dds/DiscoveryServerExample/DiscoveryServerSubscriber.h
  examples/cpp/dds/DiscoveryServerExample/DiscoveryServer_main.cpp
  examples/cpp/dds/DiscoveryServerExample/README.md
  examples/cpp/dds/DiscoveryServerExample/arg_configuration.h
  examples/cpp/dds/DiscoveryServerExample/common.h
  examples/cpp/dds/DiscoveryServerExample/types/HelloWorld.cxx
  examples/cpp/dds/DiscoveryServerExample/types/HelloWorld.h
  examples/cpp/dds/DiscoveryServerExample/types/HelloWorld.idl
  examples/cpp/dds/DiscoveryServerExample/types/HelloWorldPubSubTypes.cxx
  examples/cpp/dds/DiscoveryServerExample/types/HelloWorldPubSubTypes.h
Labels: ready-to-merge

#3270 Fix tests with Log: wait for Log background thread initialization on the first queued entry [16948]
  src/cpp/fastdds/log/Log.cpp
Labels: ready-to-merge

#2776 check endianness of TCPControlMsgHeader&TCPHeader
  src/cpp/rtps/transport/TCPTransportInterface.cpp
  src/cpp/rtps/transport/TCPTransportInterface.h
  src/cpp/rtps/transport/tcp/RTCPHeader.h
  src/cpp/rtps/transport/tcp/RTCPMessageManager.cpp
  src/cpp/rtps/transport/tcp/RTCPMessageManager.h
  test/unittest/transport/TCPv4Tests.cpp
Labels: ready-to-merge

#3282 Fix static variable data race access [17163]
  include/fastdds/rtps/builtin/discovery/participant/PDP.h
  include/fastdds/rtps/builtin/discovery/participant/PDPSimple.h
  include/fastdds/rtps/common/WriteParams.h
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPClient.h
  src/cpp/rtps/builtin/discovery/participant/PDPServer.hpp
  src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
Labels: ready-to-merge

#2737 Add BitmapRange UT
  test/unittest/utils/BitmapRangeTests.cpp
Labels: ready-to-merge

#3065 Fix data_count = 0 when using datasharing [16060]
  src/cpp/rtps/writer/StatelessWriter.cpp
Labels: ready-to-merge

#2886 Support to run in parallel some tests [15290]
  cmake/common/test_wrapper.cmake
  src/cpp/rtps/history/TopicPayloadPool.hpp
  src/cpp/utils/shared_memory/RobustInterprocessCondition.hpp
  test/CMakeLists.txt
  test/CTestCustom.cmake.in
  test/blackbox/CMakeLists.txt
  test/blackbox/common/BlackboxTests.hpp
  test/blackbox/common/DDSBlackboxTestsPersistenceGuid.cpp
  test/blackbox/common/RTPSBlackboxTestsPersistenceGuid.cpp
  test/blackbox/persistence_profile.xml
  test/communication/CMakeLists.txt
  test/unittest/dds/participant/ParticipantTests.cpp
  test/unittest/dds/subscriber/CMakeLists.txt
  test/unittest/dds/subscriber/DataReaderTests.cpp
  test/unittest/rtps/flowcontrol/FlowControllerPublishModesOnLimitedAsyncTests.cpp
  test/unittest/rtps/persistence/CMakeLists.txt
  test/unittest/rtps/persistence/PersistenceTests.cpp
  test/unittest/transport/SharedMemTests.cpp
Labels: ready-to-merge

#3133 Avoid auto-linkage using cmake [16415]
  src/cpp/CMakeLists.txt
Labels: ready-to-merge

#3479 [18259] Calling old `on_participant_discovery` overload
  include/fastdds/dds/domain/DomainParticipantListener.hpp
  src/cpp/fastdds/domain/DomainParticipantImpl.cpp
  versions.md
Labels: ready-to-merge

#3559 Distinguished names comparator [18789]
  src/cpp/CMakeLists.txt
  src/cpp/rtps/security/SecurityManager.cpp
  src/cpp/security/accesscontrol/DistinguishedName.cpp
  src/cpp/security/accesscontrol/DistinguishedName.h
  src/cpp/security/accesscontrol/Permissions.cpp
  test/unittest/dds/publisher/CMakeLists.txt
  test/unittest/security/accesscontrol/CMakeLists.txt
  test/unittest/security/accesscontrol/DistinguishedNameTests.cpp
  test/unittest/statistics/dds/CMakeLists.txt
Labels: ready-to-merge

#3404 Add XSD for static discovery [17842]
  CMakeLists.txt
  examples/cpp/dds/StaticHelloWorldExample/HelloWorldPublisher_static_disc.xml
  examples/cpp/dds/StaticHelloWorldExample/HelloWorldSubscriber_static_disc.xml
  resources/xsd/fastdds_static_discovery.xsd
  test/blackbox/PubSubReaderPersistence_static_disc.xml.in
  test/blackbox/PubSubReader_static_disc.xml.in
  test/blackbox/PubSubWriterPersistence_static_disc.xml.in
  test/blackbox/PubSubWriter_static_disc.xml.in
  test/system/tools/fastdds/CMakeLists.txt
  test/system/tools/xmlvalidation/discovery_static_disc.xml
  versions.md
Labels: ready-to-merge, skip-ci

#3281 Fix load profiles TSAN issue [17162]
  include/fastdds/dds/domain/DomainParticipantFactory.hpp
  src/cpp/fastdds/domain/DomainParticipantFactory.cpp
  test/blackbox/common/BlackboxTestsDiscovery.cpp
Labels: ci-pending

#3441 [18004] Added length checks to prevent nullptr memcpy calls
  include/fastdds/rtps/messages/CDRMessage.hpp
  test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
Labels: ci-pending

#3617 Fix AdvancedConfigurationExample --xml-profile option
  examples/cpp/dds/AdvancedConfigurationExample/arg_configuration.h
Labels: no-test

#3614 [19054] Fix communication tests not runned
  cmake/common/test_wrapper.cmake
  cmake/common/test_wrapper.cmake.in
  test/communication/CMakeLists.txt
  tools/fastdds/CMakeLists.txt
Labels: ci-pending

#3619 Add unsupported note to new ignore DomainPartListener callbacks
  include/fastdds/dds/domain/DomainParticipantListener.hpp
Labels: ready-to-merge, skip-ci

#3633 [18910] Update versions.md
  versions.md
Labels: skip-ci

#3624 Fix bug with SHM interoperability with previous versions
  src/cpp/utils/shared_memory/RobustInterprocessCondition.hpp
Labels: ci-pending
