Repository eProsima/Fast-DDS, pull requests merged in 2023-07, with the labels that each got.

#3648 [18910] Update roadmap date
  roadmap.md
Labels: skip-ci

#3635 [18072] Monitor Service Data Model
  include/fastdds/statistics/monitorservice_types.idl
  src/cpp/CMakeLists.txt
  src/cpp/statistics/types/monitorservice_types.cxx
  src/cpp/statistics/types/monitorservice_types.h
  src/cpp/statistics/types/monitorservice_typesPubSubTypes.cxx
  src/cpp/statistics/types/monitorservice_typesPubSubTypes.h
  utils/scripts/update_generated_code_from_idl.sh
Labels: no-test, ci-pending

#3606 [13608] Dynamic memory topic payload pool properly handle Zero sized payloads
  include/fastdds/rtps/history/IPayloadPool.h
  src/cpp/rtps/history/TopicPayloadPool.hpp
  src/cpp/rtps/history/TopicPayloadPool_impl/Dynamic.hpp
  src/cpp/rtps/history/TopicPayloadPool_impl/DynamicReusable.hpp
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/blackbox/api/dds-pim/PubSubWriter.hpp
  test/blackbox/common/DDSBlackboxTestsDiscovery.cpp
  test/unittest/rtps/history/TopicPayloadPoolTests.cpp
Labels: ready-to-merge

#3594 [18825] Explicitly register type object in ContentFilteredTopicExample
  examples/cpp/dds/ContentFilteredTopicExample/ContentFilteredTopicExamplePublisher.cpp
  examples/cpp/dds/ContentFilteredTopicExample/ContentFilteredTopicExampleSubscriber.cpp
Labels: no-test

#3666 Fix spelling mistake: SUBSTRACTION to SUBTRACTION
  examples/cpp/dds/RequestReplyExample/Calculator.h
  examples/cpp/dds/RequestReplyExample/Calculator.idl
  examples/cpp/dds/RequestReplyExample/CalculatorClient.cpp
  examples/cpp/dds/RequestReplyExample/CalculatorServer.cpp
Labels: ready-to-merge

#3667 [19139] Avoid double definition of FASTDDS_ENFORCE_LOG_INFO
  include/fastrtps/config.h.in
Labels: ready-to-merge

#3678 Apply eProsima brand style to Fast DDS repo
  README.md
  doc/images/fastdds_github_banner.png
Labels: ready-to-merge, no-test, skip-ci

#3670 [19116] Improve validation on PID_PROPERTY_LIST deserialization
  src/cpp/fastdds/core/policy/ParameterSerializer.hpp
Labels: ready-to-merge

#3655 Fix StatelessWriter locators filtering [18950]
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.h
  src/cpp/rtps/transport/test_UDPv4Transport.cpp
  test/blackbox/common/DDSBlackboxTestsTransportSHMUDP.cpp
Labels: ready-to-merge

#3662 [18069] Add monitor service RTPS interfaces
  include/fastdds/statistics/rtps/monitor_service/Interfaces.hpp
  include/fastdds/statistics/rtps/monitor_service/interfaces/IConnectionsObserver.hpp
  include/fastdds/statistics/rtps/monitor_service/interfaces/IConnectionsQueryable.hpp
  include/fastdds/statistics/rtps/monitor_service/interfaces/IEDPObserver.hpp
  include/fastdds/statistics/rtps/monitor_service/interfaces/IProxyQueryable.hpp
  include/fastdds/statistics/rtps/monitor_service/interfaces/IStatusListerner.hpp
  include/fastdds/statistics/rtps/monitor_service/interfaces/IStatusQueryable.hpp
Labels: no-test

#3671 [18073] Monitor Service & Monitor Service Listener API
  src/cpp/CMakeLists.txt
  src/cpp/statistics/rtps/monitor-service/MonitorService.cpp
  src/cpp/statistics/rtps/monitor-service/MonitorService.hpp
  src/cpp/statistics/rtps/monitor-service/MonitorServiceListener.cpp
  src/cpp/statistics/rtps/monitor-service/MonitorServiceListener.hpp
Labels: no-test

#3693 [18074] Bugfix/connection namespace
  include/fastdds/statistics/rtps/monitor_service/interfaces/IConnectionsQueryable.hpp
Labels: no-test, skip-ci

#3687 [19127] Revert parallel testing SemaphoreNode changes
  src/cpp/utils/shared_memory/RobustInterprocessCondition.hpp
Labels: ready-to-merge

#3692 [19089] Correct CONTRIBUTING.md typo
  CONTRIBUTING.md
Labels: ready-to-merge, no-test

#3640 [18966] Refactor of regenerate_port.
  src/cpp/rtps/transport/shared_mem/SharedMemManager.hpp
Labels: ready-to-merge

#3639 [18966] Improved shm listener status update mechanism
  src/cpp/rtps/transport/shared_mem/SharedMemGlobal.hpp
Labels: ready-to-merge, skip-ci

#3690 [19171] Added missing cstdint include
  include/fastdds/dds/core/status/StatusMask.hpp
Labels: no-test, ci-pending

#3694 [18074] Unit tests for the Monitor Service main class
  test/unittest/statistics/rtps/CMakeLists.txt
  test/unittest/statistics/rtps/MonitorServiceTests.cpp
Labels: ready-to-merge

#3684 [19166] Deserialization methods for Monitor Service
  include/fastdds/rtps/builtin/data/ParticipantProxyData.h
  include/fastdds/rtps/builtin/data/ReaderProxyData.h
  include/fastdds/rtps/builtin/data/WriterProxyData.h
  include/fastdds/rtps/participant/RTPSParticipant.h
  include/fastdds/statistics/dds/domain/DomainParticipant.hpp
  src/cpp/rtps/builtin/data/ParticipantProxyData.cpp
  src/cpp/rtps/builtin/data/ReaderProxyData.cpp
  src/cpp/rtps/builtin/data/WriterProxyData.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPSimpleListeners.cpp
  src/cpp/rtps/builtin/discovery/participant/DS/PDPSecurityInitiatorListener.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPListener.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServerListener.cpp
  src/cpp/rtps/participant/RTPSParticipant.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.h
  src/cpp/statistics/fastdds/domain/DomainParticipant.cpp
  src/cpp/statistics/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/statistics/fastdds/domain/DomainParticipantImpl.hpp
  test/blackbox/CMakeLists.txt
  test/mock/rtps/RTPSParticipant/fastdds/rtps/participant/RTPSParticipant.h
  test/unittest/dds/publisher/CMakeLists.txt
  test/unittest/dds/status/CMakeLists.txt
  test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
  test/unittest/statistics/dds/CMakeLists.txt
Labels: ready-to-merge

#3717 Refs 19117. Refixing OpenSSL search on installer
  src/cpp/CMakeLists.txt
Labels: ready-to-merge, no-test

#3720 Prepare branch out for 2.12.x
  .github/pull_request_template.md
  .github/workflows/mirror.yml
  CMakeLists.txt
  RELEASE_SUPPORT.md
  package.xml
Labels: skip-ci

#3723 [19217] Bump to version v2.9.2
  CMakeLists.txt
  package.xml
Labels: skip-ci

#3742 Remove merging conflicts tag from versions.md
  versions.md
Labels: skip-ci

#3719 [19023] Custom Payload pools test implementation
  include/fastdds/dds/publisher/Publisher.hpp
  include/fastdds/dds/subscriber/Subscriber.hpp
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/publisher/DataWriterImpl.hpp
  src/cpp/fastdds/publisher/Publisher.cpp
  src/cpp/fastdds/publisher/PublisherImpl.cpp
  src/cpp/fastdds/publisher/PublisherImpl.hpp
  src/cpp/fastdds/subscriber/DataReaderImpl.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.hpp
  src/cpp/fastdds/subscriber/Subscriber.cpp
  src/cpp/fastdds/subscriber/SubscriberImpl.cpp
  src/cpp/fastdds/subscriber/SubscriberImpl.hpp
  src/cpp/statistics/fastdds/publisher/DataWriterImpl.hpp
  src/cpp/statistics/fastdds/publisher/PublisherImpl.hpp
  src/cpp/statistics/fastdds/subscriber/DataReaderImpl.hpp
  src/cpp/statistics/fastdds/subscriber/SubscriberImpl.hpp
  test/blackbox/api/dds-pim/CustomPayloadPool.hpp
  test/blackbox/common/DDSBlackboxTestsBasic.cpp
  test/unittest/common/CustomPayloadPool.hpp
  test/unittest/dds/publisher/DataWriterTests.cpp
  test/unittest/dds/subscriber/DataReaderTests.cpp
  test/unittest/statistics/dds/StatisticsDomainParticipantMockTests/mock/statistics/fastdds/publisher/PublisherImpl.hpp
  versions.md
Labels: no-test

#3744 Fix PDP Doxygen comments typos
  include/fastdds/rtps/builtin/discovery/participant/PDP.h
Labels: skip-ci

#3745 [19256] Remove mutex from TimedEventImpl
  src/cpp/rtps/resources/TimedEventImpl.cpp
  src/cpp/rtps/resources/TimedEventImpl.h
Labels: ready-to-merge

#3743 [19247] Improve performance on intraprocess + data-sharing
  src/cpp/rtps/reader/StatefulReader.cpp
  src/cpp/rtps/reader/StatelessReader.cpp
  test/blackbox/common/DDSBlackboxTestsDataSharing.cpp
Labels: ready-to-merge

#3760 [19266] Added atomic time_point initialization
  src/cpp/rtps/resources/TimedEventImpl.cpp
Labels: ready-to-merge
