Repository eProsima/Fast-DDS, pull requests merged in 2023-10, with the labels that each got.

#3879 [19576] Updatable disable_positive_acks period
  include/fastdds/dds/core/policy/QosPolicies.hpp
  include/fastdds/dds/publisher/qos/DataWriterQos.hpp
  include/fastdds/rtps/writer/StatefulWriter.h
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.cpp
  src/cpp/rtps/writer/StatefulWriter.cpp
  test/blackbox/api/dds-pim/PubSubWriter.hpp
  test/blackbox/common/DDSBlackboxTestsAckPositive.cpp
  test/blackbox/common/RTPSAsSocketReader.hpp
  test/blackbox/common/RTPSAsSocketWriter.hpp
  test/blackbox/common/RTPSBlackboxTestsPositiveAck.cpp
Labels: ready-to-merge

#3904 [19642] Use STL implementation of Timed/RecursiveTimedMutex when MSVC >= 19.36
  include/fastrtps/utils/TimedMutex.hpp
Labels: needs-review, ci-pending

#3924 [19638] Log error message upon receiver resource creation failure
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
Labels: no-test, ci-pending

#3942 Mark LTS releases on RELEASE_SUPPORT.md
  RELEASE_SUPPORT.md
Labels: skip-ci

#3954 [19773] Rework log upon receiver resource creation failure
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.h
Labels: ci-pending

#3932 [19665] Hotfix TCP sender resources creation
  include/fastrtps/utils/IPLocator.h
  src/cpp/rtps/transport/ChainingSenderResource.hpp
  src/cpp/rtps/transport/TCPSenderResource.hpp
  src/cpp/rtps/transport/TCPTransportInterface.cpp
  src/cpp/rtps/transport/UDPSenderResource.hpp
  src/cpp/rtps/transport/shared_mem/SharedMemSenderResource.hpp
  src/cpp/utils/IPLocator.cpp
  test/blackbox/common/BlackboxTestsTransportCustom.cpp
Labels: ready-to-merge

#3968 [19728] Update README CI badges with last completed build (avoid 'running' case)
  README.md
Labels: ready-to-merge, skip-ci
