Repository eProsima/Fast-DDS, pull requests merged in 2023-05, with the labels that each got.

#3492 [18186] Update endpoint qos XML schema
  resources/xsd/fastRTPS_profiles.xsd
  test/system/tools/xmlvalidation/all_profile.xml
  test/system/tools/xmlvalidation/dataReader_profile.xml
Labels: ready-to-merge

#3488 Forward compatibility with boost interprocess 1.74+
  src/cpp/utils/shared_memory/RobustInterprocessCondition.hpp
Labels: ready-to-merge

#3508 [18431] Fix missing includes
  include/fastdds/rtps/transport/TransportDescriptorInterface.h
  include/fastrtps/types/TypeNamesGenerator.h
Labels: ready-to-merge, no-test

#3502 [18449] Revert #3134 in 2.10.x
  cmake/packaging/Config.cmake.in
  src/cpp/CMakeLists.txt
Labels: no-test

#3385 [17294] Honor allow_unauthenticated_participants flag
  include/fastdds/rtps/builtin/discovery/endpoint/EDP.h
  include/fastdds/rtps/builtin/discovery/endpoint/EDPSimple.h
  include/fastdds/rtps/builtin/discovery/endpoint/EDPStatic.h
  include/fastdds/rtps/builtin/discovery/participant/PDP.h
  include/fastdds/rtps/builtin/discovery/participant/PDPSimple.h
  include/fastdds/rtps/builtin/liveliness/WLP.h
  include/fastdds/rtps/security/accesscontrol/EndpointSecurityAttributes.h
  src/cpp/rtps/builtin/discovery/endpoint/EDPSimple.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPStatic.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPClient.h
  src/cpp/rtps/builtin/discovery/participant/PDPListener.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer.hpp
  src/cpp/rtps/builtin/discovery/participant/PDPServerListener.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
  src/cpp/rtps/builtin/discovery/participant/timedevent/DSClientEvent.cpp
  src/cpp/rtps/builtin/liveliness/WLP.cpp
  src/cpp/rtps/security/SecurityManager.cpp
  src/cpp/rtps/security/SecurityManager.h
  src/cpp/security/accesscontrol/Permissions.cpp
  src/cpp/security/authentication/PKIDH.cpp
  test/blackbox/common/BlackboxTestsSecurity.cpp
  test/certs/certs/AE7BAD8C075AEAF8.pem
  test/certs/ecdsaparam
  test/certs/governance_allow_unauth_all_disabled_access_none.smime
  test/certs/governance_allow_unauth_all_disabled_access_none.xml
  test/certs/governance_allow_unauth_all_disabled_access_none_other_ca.smime
  test/certs/governance_allow_unauth_all_disabled_read_write_enabled.smime
  test/certs/governance_allow_unauth_all_disabled_read_write_enabled.xml
  test/certs/governance_allow_unauth_all_disabled_read_write_enabled_other_ca.smime
  test/certs/governance_allow_unauth_rtps_encrypt.smime
  test/certs/governance_allow_unauth_rtps_encrypt.xml
  test/certs/index_other.txt
  test/certs/othercacert.pem
  test/certs/othercacert.txt
  test/certs/othercaconf.cnf
  test/certs/othercakey.pem
  test/certs/othersub.cnf
  test/certs/othersubcert.pem
  test/certs/othersubcert.txt
  test/certs/othersubkey.pem
  test/certs/othersubreq.pem
  test/certs/permissions_helloworld_securehelloworld.smime
  test/certs/permissions_helloworld_securehelloworld.xml
  test/certs/permissions_helloworld_securehelloworld_other_ca.smime
  test/certs/permissions_helloworld_securehelloworld_other_ca.xml
  test/certs/serial_other
  test/communication/CMakeLists.txt
  test/communication/simple_allow_unauthenticated_sub_profile.xml
  test/communication/simple_secure_allow_unauthenticated_pub_profile.xml
  test/mock/rtps/PDP/fastdds/rtps/builtin/discovery/participant/PDP.h
  test/mock/rtps/PDPSimple/fastdds/rtps/builtin/discovery/participant/PDPSimple.h
  test/unittest/rtps/discovery/EdpTests.cpp
  test/unittest/rtps/security/SecurityHandshakeProcessTests.cpp
  test/unittest/rtps/security/SecurityTests.cpp
  test/unittest/rtps/security/SecurityValidationRemoteTests.cpp
Labels: ready-to-merge

#3519 [18438] Bump version to 2.1.4
  configure.ac
  package.xml
Labels: ready-to-merge

#3399 Support missing tags in XSD [17823]
  resources/xsd/fastRTPS_profiles.xsd
  test/system/tools/xmlvalidation/dataReader_profile.xml
  test/system/tools/xmlvalidation/dataWriter_profile.xml
Labels: ready-to-merge

#3525 [18436] Remove 2.1.x from the supported branches
  RELEASE_SUPPORT.md
Labels: ready-to-merge, no-test, skip-ci

#3534 [18674] Fixes on XML schema
  resources/xsd/fastRTPS_profiles.xsd
  test/system/tools/xmlvalidation/all_profile.xml
  test/system/tools/xmlvalidation/dataReader_profile.xml
Labels: needs-review

#3484 Print output Dynamic Types inline
  include/fastrtps/types/DynamicDataHelper.hpp
  src/cpp/dynamic-types/DynamicDataHelper.cpp
Labels: ready-to-merge

#3528 [18632] Capture all fastcdr exceptions
  src/cpp/dynamic-types/DynamicPubSubType.cpp
  src/cpp/fastdds/builtin/typelookup/common/TypeLookupTypes.cpp
  src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterExpression.cpp
  src/cpp/rtps/transport/tcp/TCPControlMessage.cpp
  src/cpp/security/cryptography/AESGCMGMAC_Transform.cpp
Labels: ready-to-merge
