Repository eProsima/Fast-DDS, pull requests merged in 2023-11, with the labels that each got.

#3979 [19839] Fix flow controllers utests compilation when using Fast CDR from thirdparty
  test/unittest/rtps/flowcontrol/CMakeLists.txt
Labels: skip-ci

#3987 [19645] Fix doxygen
  include/fastdds/rtps/transport/PortBasedTransportDescriptor.hpp
Labels: skip-ci

#3975 [19354] Add XML parser bit_bound bounds check
  src/cpp/rtps/xmlparser/XMLDynamicParser.cpp
  test/unittest/xmlparser/XMLParserTests.cpp
  test/unittest/xmlparser/regressions/19354_2_profile_bin.xml
  test/unittest/xmlparser/regressions/19354_profile_bin.xml
Labels: ci-pending

#3995 [19851] Fix missing mandatory attribute check in XML parser struct type
  src/cpp/rtps/xmlparser/XMLDynamicParser.cpp
  test/unittest/xmlparser/XMLParserTests.cpp
  test/unittest/xmlparser/regressions/19851_profile_bin.xml
Labels: ready-to-merge

#3994 [19870] PubSubAsReliable test fix
  include/fastdds/rtps/transport/test_UDPv4TransportDescriptor.h
  src/cpp/rtps/transport/test_UDPv4Transport.cpp
  src/cpp/rtps/transport/test_UDPv4Transport.h
  test/blackbox/common/BlackboxTestsPubSubHistory.cpp
Labels: ready-to-merge

#3992 [19869] SHM transport: ignore non-existing segment on pop
  src/cpp/rtps/transport/shared_mem/SharedMemChannelResource.hpp
  src/cpp/rtps/transport/shared_mem/SharedMemManager.hpp
  test/blackbox/common/BlackboxTestsTransportSHM.cpp
Labels: ci-pending

#3983 Fix: mac address overflow on windows
  src/cpp/utils/IPFinder.cpp
Labels: ci-pending

#4016 [19889] FileWatchTest fix for github windows ci
  test/unittest/utils/SystemInfoTests.cpp
Labels: ready-to-merge

#4017 [19913] Make `test_UDPv4TransportDescriptor` non-copyable and non-moveable
  include/fastdds/rtps/transport/test_UDPv4TransportDescriptor.h
Labels: no-test

#4027 [19860] Bump version to 2.13.0
  .github/workflows/mirror.yml
  CMakeLists.txt
  RELEASE_SUPPORT.md
  package.xml
Labels: skip-ci

#4037 Fix uninitialized member
  include/fastdds/rtps/attributes/RTPSParticipantAttributes.h
Labels: skip-ci

#3971 Usage of gtest_discover_tests [19810]
  .github/workflows/config/asan_colcon.meta
  .github/workflows/config/default_ci.meta
  .github/workflows/config/nightly.meta
  .github/workflows/config/tsan_colcon.meta
  cmake/common/gtest.cmake
  cmake/testing/GoogleTest.cmake
  cmake/testing/android_test_run.bash
  cmake/testing/generate_google_test_win_wrapper.cmake
  test/CMakeLists.txt
  test/blackbox/CMakeLists.txt
  test/blackbox/XFAIL_DDS_PIM.list
  test/blackbox/XFAIL_DDS_PIM_SECURITY.list
  test/blackbox/common/BlackboxTests.cpp
  test/blackbox/common/BlackboxTestsDiscovery.cpp
  test/blackbox/xfail_tests.cmake
  test/realtime/CMakeLists.txt
  test/realtime/mutex_testing_tool/CMakeLists.txt
  test/unittest/dds/collections/CMakeLists.txt
  test/unittest/dds/core/condition/CMakeLists.txt
  test/unittest/dds/core/entity/CMakeLists.txt
  test/unittest/dds/core/policy/CMakeLists.txt
  test/unittest/dds/participant/CMakeLists.txt
  test/unittest/dds/publisher/CMakeLists.txt
  test/unittest/dds/status/CMakeLists.txt
  test/unittest/dds/subscriber/CMakeLists.txt
  test/unittest/dds/topic/CMakeLists.txt
  test/unittest/dds/topic/DDSSQLFilter/CMakeLists.txt
  test/unittest/dynamic_types/CMakeLists.txt
  test/unittest/logging/CMakeLists.txt
  test/unittest/logging/log_macros/CMakeLists.txt
  test/unittest/rtps/DataSharing/CMakeLists.txt
  test/unittest/rtps/attributes/CMakeLists.txt
  test/unittest/rtps/builtin/CMakeLists.txt
  test/unittest/rtps/common/CMakeLists.txt
  test/unittest/rtps/discovery/CMakeLists.txt
  test/unittest/rtps/flowcontrol/CMakeLists.txt
  test/unittest/rtps/history/CMakeLists.txt
  test/unittest/rtps/network/CMakeLists.txt
  test/unittest/rtps/persistence/CMakeLists.txt
  test/unittest/rtps/reader/CMakeLists.txt
  test/unittest/rtps/resources/timedevent/CMakeLists.txt
  test/unittest/rtps/security/CMakeLists.txt
  test/unittest/rtps/writer/CMakeLists.txt
  test/unittest/security/accesscontrol/AccessControlTests.cpp
  test/unittest/security/accesscontrol/CMakeLists.txt
  test/unittest/security/authentication/BuiltinPKIDHTests.cpp
  test/unittest/security/authentication/CMakeLists.txt
  test/unittest/security/cryptography/CMakeLists.txt
  test/unittest/security/logging/CMakeLists.txt
  test/unittest/statistics/dds/CMakeLists.txt
  test/unittest/statistics/rtps/CMakeLists.txt
  test/unittest/transport/CMakeLists.txt
  test/unittest/transport/SharedMemTests.cpp
  test/unittest/transport/XFAIL_SHM.list
  test/unittest/transport/xfail_tests.cmake
  test/unittest/utils/CMakeLists.txt
  test/unittest/xmlparser/CMakeLists.txt
  test/unittest/xtypes/CMakeLists.txt
  test/xtypes/CMakeLists.txt
Labels: ci-pending

#4052 [20017] Fix warning in Mac rewarding unnecessary lambda capture
  test/blackbox/common/BlackboxTestsTransportSHM.cpp
Labels: ready-to-merge, no-test

#3974 [19648] TypeObjectUtils class
  include/fastdds/dds/core/policy/QosPolicies.hpp
  include/fastdds/dds/domain/DomainParticipantFactory.hpp
  include/fastdds/dds/topic/TopicDataType.hpp
  include/fastdds/dds/xtypes/common.hpp
  include/fastdds/dds/xtypes/exception/Exception.hpp
  include/fastdds/dds/xtypes/type_representation/TypeObject.hpp
  include/fastdds/dds/xtypes/type_representation/TypeObjectRegistry.hpp
  include/fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp
  include/fastdds/dds/xtypes/type_representation/dds-xtypes_typeobject.idl
  include/fastdds/dds/xtypes/type_representation/detail/dds_xtypes_typeobject.hpp
  include/fastdds/dds/xtypes/type_representation/detail/dds_xtypes_typeobjectCdrAux.hpp
  include/fastdds/dds/xtypes/type_representation/detail/dds_xtypes_typeobjectPubSubTypes.h
  include/fastdds/rtps/builtin/data/ReaderProxyData.h
  include/fastdds/rtps/builtin/data/WriterProxyData.h
  include/fastdds/rtps/builtin/discovery/participant/PDP.h
  include/fastrtps/attributes/TopicAttributes.h
  include/fastrtps/qos/QosPolicies.h
  include/fastrtps/types/dds-xtypes_typeobject.idl
  src/cpp/CMakeLists.txt
  src/cpp/fastdds/core/policy/QosPoliciesSerializer.hpp
  src/cpp/fastdds/domain/DomainParticipantFactory.cpp
  src/cpp/fastdds/xtypes/exception/Exception.cpp
  src/cpp/fastdds/xtypes/type_representation/BuiltinAnnotations.hpp
  src/cpp/fastdds/xtypes/type_representation/BuiltinAnnotations.idl
  src/cpp/fastdds/xtypes/type_representation/BuiltinAnnotationsPubSubTypes.h
  src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.cpp
  src/cpp/fastdds/xtypes/type_representation/TypeObjectUtils.cpp
  src/cpp/fastdds/xtypes/type_representation/dds_xtypes_typeobjectCdrAux.ipp
  src/cpp/fastdds/xtypes/type_representation/dds_xtypes_typeobjectPubSubTypes.cxx
  src/cpp/rtps/builtin/data/ReaderProxyData.cpp
  src/cpp/rtps/builtin/data/WriterProxyData.cpp
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  test/mock/dds/QosPolicies/fastdds/dds/core/policy/QosPolicies.hpp
  test/mock/rtps/ReaderProxyData/fastdds/rtps/builtin/data/ReaderProxyData.h
  test/mock/rtps/WriterProxyData/fastdds/rtps/builtin/data/WriterProxyData.h
  test/unittest/CMakeLists.txt
  test/unittest/dds/xtypes/type_representation/CMakeLists.txt
  test/unittest/dds/xtypes/type_representation/TypeObjectUtilsTests.cpp
  utils/scripts/update_generated_code_from_idl.sh
  versions.md
Labels: no-test, doc-pending

#4053 [20043] Moved all typelookupservice files to src
  src/cpp/CMakeLists.txt
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupManager.cpp
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupManager.hpp
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupReplyListener.cpp
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupReplyListener.hpp
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupRequestListener.cpp
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupRequestListener.hpp
  src/cpp/fastdds/builtin/type_lookup_service/common/RPCHeadersImpl.cpp
  src/cpp/fastdds/builtin/type_lookup_service/common/RPCHeadersImplCdrAux.ipp
  src/cpp/fastdds/builtin/type_lookup_service/common/ReplyHeader.hpp
  src/cpp/fastdds/builtin/type_lookup_service/common/RequestHeader.hpp
  src/cpp/fastdds/builtin/type_lookup_service/common/TypeLookupTypes.cpp
  src/cpp/fastdds/builtin/type_lookup_service/common/TypeLookupTypes.hpp
  src/cpp/fastdds/builtin/type_lookup_service/common/TypeLookupTypesCdrAux.ipp
  src/cpp/fastdds/builtin/type_lookup_service/common/Types.hpp
  src/cpp/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/rtps/builtin/BuiltinProtocols.cpp
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
  test/mock/dds/DomainParticipantImpl/fastdds/domain/DomainParticipantImpl.hpp
  test/mock/rtps/TypeLookupManager/fastdds/builtin/type_lookup_service/TypeLookupManager.hpp
  test/unittest/dds/publisher/CMakeLists.txt
  test/unittest/dds/status/ListenerTests.cpp
  test/unittest/statistics/dds/CMakeLists.txt
Labels: ci-pending

#4056 [19587] Use `SO_EXCLUSIVEADDRUSE` for Win32 unicast listening sockets
  src/cpp/rtps/transport/UDPv4Transport.cpp
  src/cpp/rtps/transport/UDPv6Transport.cpp
  test/blackbox/common/BlackboxTestsNetworkConf.cpp
  test/unittest/transport/UDPv4Tests.cpp
  test/unittest/transport/UDPv6Tests.cpp
  test/unittest/transport/mock/MockReceiverResource.h
Labels: ci-pending

#4075 [20055] Fix colcon on github CI
  .github/actions/install-python-packages/action.yml
  .github/workflows/config/default_ci_2.12.x.repos
  .github/workflows/config/nightly_2.12.x.repos
  .github/workflows/documentation-tests.yaml
  .github/workflows/nightly-windows-ci.yml
  .github/workflows/reusable-windows-ci.yml
  .github/workflows/sanitizer-tests.yaml
  .github/workflows/thread-sanitizer.yaml
  .github/workflows/windows-ci.yml
Labels: ready-to-merge

#4048 Fix arm64 nightly job
  cmake/testing/GoogleTest.cmake
Labels: ready-to-merge, no-test
