Repository eProsima/Fast-DDS, pull requests merged in 2023-04, with the labels that each got.

#3412 [17873] DomainParticipant::ignore_participant implementation
  include/fastdds/dds/domain/DomainParticipant.hpp
  include/fastdds/dds/domain/DomainParticipantListener.hpp
  include/fastdds/rtps/messages/MessageReceiver.h
  include/fastdds/rtps/participant/RTPSParticipantListener.h
  src/cpp/fastdds/domain/DomainParticipant.cpp
  src/cpp/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/fastdds/domain/DomainParticipantImpl.hpp
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPListener.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServerListener.cpp
  src/cpp/rtps/messages/MessageReceiver.cpp
  src/cpp/rtps/participant/RTPSParticipant.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  test/blackbox/common/DDSBlackboxTestsBasic.cpp
  test/mock/dds/DomainParticipantImpl/fastdds/domain/DomainParticipantImpl.hpp
  test/mock/rtps/RTPSParticipant/fastdds/rtps/participant/RTPSParticipant.h
  test/unittest/dds/participant/ParticipantTests.cpp
  versions.md
Labels: ci-pending

#3419 [17832] Initial acknack backoff
  src/cpp/rtps/reader/WriterProxy.cpp
  test/mock/rtps/TimedEvent/fastdds/rtps/resources/TimedEvent.h
  test/unittest/rtps/reader/CMakeLists.txt
  test/unittest/rtps/reader/WriterProxyAcknackTests.cpp
Labels: ci-pending

#3425 [17976] Correctly assign multicast port to multicast initial peers
  src/cpp/rtps/transport/UDPTransportInterface.cpp
  test/blackbox/common/BlackboxTestsDiscovery.cpp
Labels: ci-pending

#3435 [17983] Bump to version 2.10.1
  CMakeLists.txt
  RELEASE_SUPPORT.md
  package.xml
  versions.md
Labels: ready-to-merge, skip-ci

#3436 Fix null dereference when fuzzing
  src/cpp/rtps/messages/MessageReceiver.cpp
Labels: no-test, ci-pending

#3442 [18054] Cap Thread Sanitizer memory usage to prevent runner shutdown
  .github/workflows/thread-sanitizer.yaml
Labels: ready-to-merge

#3443 Fix segfault when creating two participant with same fixed id [18051]
  src/cpp/fastdds/domain/DomainParticipantFactory.cpp
  src/cpp/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/rtps/RTPSDomain.cpp
  src/cpp/rtps/RTPSDomainImpl.hpp
  test/mock/dds/DomainParticipantImpl/fastdds/domain/DomainParticipantImpl.hpp
  test/mock/rtps/RTPSDomainImpl/rtps/RTPSDomainImpl.hpp
  test/unittest/dds/participant/ParticipantTests.cpp
Labels: ready-to-merge

#3423 [17961] Select correct listener for on_requested_deadline_missed
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  test/blackbox/common/DDSBlackboxTestsDataWriter.cpp
Labels: ready-to-merge

#3461 [17831] Fix 2.8.x branch fastrtps.repos versions
  fastrtps.repos
Labels: no-test, skip-ci

#3462 [18149] Fix build on msvc 19.36.32528
  include/fastrtps/utils/TimedMutex.hpp
Labels: ready-to-merge, no-test

#3470 [18123] Update XML schema to set Transport descriptor kind as NOT mandatory
  resources/xsd/fastRTPS_profiles.xsd
Labels: needs-review, skip-ci

#3445 [18065] Monitor service - high level empty API
  include/fastdds/dds/domain/DomainParticipant.hpp
  include/fastdds/rtps/participant/RTPSParticipant.h
  src/cpp/fastdds/domain/DomainParticipant.cpp
  src/cpp/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/fastdds/domain/DomainParticipantImpl.hpp
  src/cpp/rtps/participant/RTPSParticipant.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.h
  test/mock/dds/DomainParticipantImpl/fastdds/domain/DomainParticipantImpl.hpp
  test/mock/rtps/RTPSParticipant/fastdds/rtps/participant/RTPSParticipant.h
  versions.md
Labels: no-test, ci-pending

#3455 [17831] Removed 2.8.x from the supported platforms
  .github/pull_request_template.md
  RELEASE_SUPPORT.md
Labels: ready-to-merge, no-test, skip-ci

#3480 [18151] Participant ignore local endpoints
  src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.h
  test/blackbox/api/dds-pim/PubSubWriterReader.hpp
  test/blackbox/common/DDSBlackboxTestsBasic.cpp
  test/blackbox/common/RTPSBlackboxTestsBasic.cpp
  test/blackbox/common/RTPSWithRegistrationReader.hpp
  test/blackbox/common/RTPSWithRegistrationWriter.hpp
  test/mock/rtps/PDP/fastdds/rtps/builtin/discovery/participant/PDP.h
  test/mock/rtps/RTPSParticipantImpl/rtps/participant/RTPSParticipantImpl.h
  versions.md
Labels: ready-to-merge
