Repository eProsima/Fast-DDS, pull requests merged in 2023-08, with the labels that each got.

#3752 [19268] Replace uint64_t by 8 in alignas specifier
  src/cpp/rtps/DataSharing/DataSharingNotification.hpp
  src/cpp/rtps/DataSharing/DataSharingPayloadPool.hpp
Labels: ci-pending

#3769 [18395] Fix XMLParser null-derefence in parseLogConfig
  src/cpp/rtps/xmlparser/XMLParser.cpp
  test/unittest/xmlparser/XMLParserTests.cpp
  test/unittest/xmlparser/regressions/18395_profile_bin.xml
Labels: ci-pending

#3753 [19263 ] User configuration for SHM metatraffic
  src/cpp/rtps/network/NetworkFactory.cpp
  src/cpp/rtps/network/NetworkFactory.h
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.h
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/blackbox/api/dds-pim/PubSubWriter.hpp
  test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
  test/blackbox/api/fastrtps_deprecated/PubSubWriter.hpp
  test/blackbox/common/DDSBlackboxTestsTransportSHMUDP.cpp
  test/unittest/rtps/network/CMakeLists.txt
  test/unittest/rtps/network/NetworkFactoryTests.cpp
  test/unittest/transport/CMakeLists.txt
  test/unittest/transport/TCPv6Tests.cpp
  versions.md
Labels: skip-ci

#3771 [19315] Allow participant profiles with no rtps tag
  src/cpp/rtps/xmlparser/XMLParser.cpp
  test/unittest/xmlparser/XMLParserTests.cpp
  test/unittest/xmlparser/regressions/simple_participant_profiles_nok.xml
  test/unittest/xmlparser/regressions/simple_participant_profiles_ok.xml
Labels: ci-pending

#3755 [19265] Custom pools on DDS layer feature
  include/fastdds/dds/publisher/Publisher.hpp
  include/fastdds/dds/subscriber/Subscriber.hpp
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/publisher/DataWriterImpl.hpp
  src/cpp/fastdds/publisher/Publisher.cpp
  src/cpp/fastdds/publisher/PublisherImpl.cpp
  src/cpp/fastdds/publisher/PublisherImpl.hpp
  src/cpp/fastdds/subscriber/DataReaderImpl.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.hpp
  src/cpp/fastdds/subscriber/Subscriber.cpp
  src/cpp/fastdds/subscriber/SubscriberImpl.cpp
  src/cpp/fastdds/subscriber/SubscriberImpl.hpp
  src/cpp/statistics/fastdds/publisher/DataWriterImpl.hpp
  src/cpp/statistics/fastdds/publisher/PublisherImpl.hpp
  src/cpp/statistics/fastdds/subscriber/DataReaderImpl.hpp
  src/cpp/statistics/fastdds/subscriber/SubscriberImpl.hpp
  test/blackbox/api/dds-pim/CustomPayloadPool.hpp
  test/blackbox/common/DDSBlackboxTestsBasic.cpp
  test/unittest/common/CustomPayloadPool.hpp
  test/unittest/dds/publisher/DataWriterTests.cpp
  test/unittest/dds/subscriber/DataReaderTests.cpp
  test/unittest/statistics/dds/StatisticsDomainParticipantMockTests/mock/statistics/fastdds/publisher/PublisherImpl.hpp
  versions.md
Labels: skip-ci, versions-pending

#3785 [19324] Bump version to v2.6.6
  CMakeLists.txt
  RELEASE_SUPPORT.md
  package.xml
  versions.md
Labels: skip-ci

#3784 [19347] Fix encapsulation format in WLP
  include/fastdds/rtps/builtin/liveliness/WLPListener.h
  include/fastdds/rtps/common/CDRMessage_t.h
  include/fastdds/rtps/common/SerializedPayload.h
  include/fastdds/rtps/messages/CDRMessage.h
  include/fastdds/rtps/messages/CDRMessage.hpp
  src/cpp/rtps/builtin/liveliness/WLP.cpp
  src/cpp/rtps/builtin/liveliness/WLPListener.cpp
Labels: ci-pending

#3792 [19325] Bump version to v2.11.2
  CMakeLists.txt
  package.xml
  versions.md
Labels: skip-ci

#3786 [19359] Fix DomainParticipant::register_remote_type return when negotiating type
  include/fastdds/dds/domain/DomainParticipant.hpp
  src/cpp/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/fastdds/domain/DomainParticipantImpl.hpp
Labels: skip-ci

#3805 [19360] Bump version 2.10.2
  CMakeLists.txt
  package.xml
  versions.md
Labels: ready-to-merge

#3807 [19360] Fix versions on .repos
  fastrtps.repos
Labels: skip-ci

#3658 [18068] Monitor Service test plan implementation
  include/fastdds/rtps/builtin/data/ParticipantProxyData.h
  src/cpp/statistics/rtps/StatisticsBase.cpp
  src/cpp/statistics/rtps/StatisticsBase.hpp
  src/cpp/statistics/rtps/monitor-service/MonitorService.cpp
  test/blackbox/CMakeLists.txt
  test/blackbox/MonitorServiceConnectionList_profile.xml
  test/blackbox/MonitorServiceDomainParticipant_profile.xml
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/blackbox/common/DDSBlackboxTestsMonitorService.cpp
  test/blackbox/common/RTPSBlackboxTestsMonitorService.cpp
  test/unittest/statistics/rtps/MonitorServiceTests.cpp
Labels: ready-to-merge, no-test
