Repository eProsima/Fast-DDS, pull requests merged in 2024-07, with the labels that each got.

#5010 [21219] Fix flakyness on test with participants in the same container
  test/examples/test_configuration.py
  test/examples/test_content_filter.py
  test/examples/test_custom_payload_pool.py
  test/examples/test_delivery_mechanisms.py
  test/examples/test_delivery_mechanisms_isolated.py
  test/examples/test_hello_world.py
  test/examples/test_xtypes.py
Labels: ready-to-merge

#5008 [21272] Fix assertion in TopicPayloadPool::release_history
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
Labels: ci-pending

#5012 [21256] Manual fix for documentation generation
  include/fastrtps/types/DynamicLoanableSequence.hpp
Labels: skip-ci

#5013 [21256] Manual fix for documentation generation
  include/fastrtps/types/DynamicLoanableSequence.hpp
Labels: ready-to-merge, skip-ci

#5007 [21223] Fix parse XML member dynamic type fuzzer issue
  src/cpp/xmlparser/XMLDynamicParser.cpp
  test/unittest/xmlparser/XMLParserTests.cpp
  test/unittest/xmlparser/regressions/21223_profile_bin.xml
Labels: skip-ci

#5009 [21232] Fix flaky latency tests on mac
  src/cpp/rtps/writer/ReaderLocator.cpp
  src/cpp/rtps/writer/ReaderLocator.hpp
  src/cpp/rtps/writer/ReaderProxy.hpp
  src/cpp/rtps/writer/StatefulWriter.cpp
  test/mock/rtps/ReaderLocator/rtps/writer/ReaderLocator.hpp
  test/performance/latency/LatencyTestPublisher.cpp
  test/performance/latency/LatencyTestPublisher.hpp
  test/performance/latency/LatencyTestSubscriber.cpp
  test/performance/latency/LatencyTestSubscriber.hpp
  test/performance/latency/main_LatencyTest.cpp
Labels: ready-to-merge

#5017 [21232] Fix Latency tests - `2.x backports`
  test/performance/latency/LatencyTestPublisher.cpp
  test/performance/latency/LatencyTestPublisher.hpp
  test/performance/latency/LatencyTestSubscriber.cpp
  test/performance/latency/LatencyTestSubscriber.hpp
  test/performance/latency/main_LatencyTest.cpp
Labels: ci-pending

#5016 [21114] Remove doxygen warnings (#4700, #5011)
  include/fastdds/dds/core/policy/QosPolicies.hpp
  include/fastdds/dds/domain/DomainParticipant.hpp
  include/fastdds/dds/domain/DomainParticipantFactory.hpp
  include/fastdds/dds/domain/DomainParticipantListener.hpp
  include/fastdds/dds/publisher/DataWriter.hpp
  include/fastdds/dds/publisher/Publisher.hpp
  include/fastdds/dds/subscriber/DataReader.hpp
  include/fastdds/dds/subscriber/Subscriber.hpp
  include/fastdds/rtps/common/ChangeKind_t.hpp
  include/fastdds/rtps/common/FragmentNumber.h
  include/fastdds/rtps/common/MatchingInfo.h
  include/fastdds/rtps/common/SequenceNumber.h
  include/fastdds/rtps/common/Types.h
Labels: skip-ci, ci-pending

#5023 [21244] Migrate `2.6.x` ci jobs from nighties to weeklies
  .github/workflows/nightly-mac-ci.yml
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/nightly-windows-ci.yml
  .github/workflows/weekly-mac-ci.yml
  .github/workflows/weekly-ubuntu-ci.yml
  .github/workflows/weekly-windows-ci.yml
Labels: ready-to-merge, skip-ci

#4913 [21095] Example refactor: Discovery Server
  examples/CMakeLists.txt
  examples/cpp/dds/CMakeLists.txt
  examples/cpp/dds/DiscoveryServerExample/DiscoveryServerPublisher.h
  examples/cpp/dds/DiscoveryServerExample/DiscoveryServerServer.h
  examples/cpp/dds/DiscoveryServerExample/DiscoveryServerSubscriber.h
  examples/cpp/dds/DiscoveryServerExample/DiscoveryServer_main.cpp
  examples/cpp/dds/DiscoveryServerExample/README.md
  examples/cpp/dds/DiscoveryServerExample/arg_configuration.h
  examples/cpp/discovery_server/Application.cpp
  examples/cpp/discovery_server/Application.hpp
  examples/cpp/discovery_server/CLIParser.hpp
  examples/cpp/discovery_server/CMakeLists.txt
  examples/cpp/discovery_server/ClientPublisherApp.cpp
  examples/cpp/discovery_server/ClientPublisherApp.hpp
  examples/cpp/discovery_server/ClientSubscriberApp.cpp
  examples/cpp/discovery_server/ClientSubscriberApp.hpp
  examples/cpp/discovery_server/HelloWorld.hpp
  examples/cpp/discovery_server/HelloWorld.idl
  examples/cpp/discovery_server/HelloWorldCdrAux.hpp
  examples/cpp/discovery_server/HelloWorldCdrAux.ipp
  examples/cpp/discovery_server/HelloWorldPubSubTypes.cxx
  examples/cpp/discovery_server/HelloWorldPubSubTypes.hpp
  examples/cpp/discovery_server/HelloWorldTypeObjectSupport.cxx
  examples/cpp/discovery_server/HelloWorldTypeObjectSupport.hpp
  examples/cpp/discovery_server/Helpers.hpp
  examples/cpp/discovery_server/README.md
  examples/cpp/discovery_server/ServerApp.cpp
  examples/cpp/discovery_server/ServerApp.hpp
  examples/cpp/discovery_server/main.cpp
  test/examples/discovery_server.compose.yml
  test/examples/test_discovery_server.py
  versions.md
Labels: ready-to-merge

#5029 [21244] Label flaky tests with xfail
  test/blackbox/XFAIL_DDS_PIM.list
  test/blackbox/XFAIL_DDS_PIM_SECURITY.list
  test/blackbox/XFAIL_RTPS.list
  test/communication/CMakeLists.txt
  test/communication/XFAIL_COMMUNICATION.list
  test/dds/communication/CMakeLists.txt
  test/dds/communication/XFAIL_DDS_COMMUNICATION.list
  test/performance/CMakeLists.txt
  test/performance/latency/CMakeLists.txt
  test/performance/latency/XFAIL_LATENCY.list
  test/performance/throughput/CMakeLists.txt
  test/performance/throughput/XFAIL_THROUGHPUT.list
  test/unittest/transport/XFAIL_TCP4.list
Labels: ready-to-merge

#5027 [21244] Bump version to v2.6.9
  CMakeLists.txt
  package.xml
  versions.md
Labels: skip-ci

#5031 [21244] Update RELEASE_SUPPORT for `v2.6.9` release
  RELEASE_SUPPORT.md
Labels: ready-to-merge, skip-ci

#4988 [21245] Fix topic interference on `liveliness_changed` status
  src/cpp/rtps/builtin/liveliness/WLP.cpp
  src/cpp/rtps/reader/StatefulReader.cpp
  src/cpp/rtps/reader/StatelessReader.cpp
  test/blackbox/common/BlackboxTestsLivelinessQos.cpp
  test/blackbox/common/DDSBlackboxTestsROS2.cpp
  test/blackbox/common/ros2/Context.hpp
  test/blackbox/common/ros2/DataReaderHolder.hpp
  test/blackbox/common/ros2/DataWriterHolder.hpp
  test/blackbox/common/ros2/GenericHolder.hpp
  test/blackbox/common/ros2/Node.hpp
  test/blackbox/common/ros2/PublicationNode.hpp
  test/blackbox/common/ros2/SubscriptionNode.hpp
  test/blackbox/common/ros2/TopicHolder.hpp
Labels: needs-review, ci-pending

#5011 [21288] Remove doxygen directive @group in enumerations and typedefs
  include/fastdds/rtps/common/ChangeKind_t.hpp
  include/fastdds/rtps/common/FragmentNumber.hpp
  include/fastdds/rtps/common/MatchingInfo.hpp
  include/fastdds/rtps/common/SequenceNumber.hpp
  include/fastdds/rtps/common/Types.hpp
Labels: ready-to-merge

#5036 [21309] Fix weekly CI cron expression
  .github/workflows/weekly-mac-ci.yml
  .github/workflows/weekly-ubuntu-ci.yml
  .github/workflows/weekly-windows-ci.yml
Labels: skip-ci

#5037 [21267] Fix `2.6.x` latency security XFAIL compilation without security
  test/performance/latency/CMakeLists.txt
  test/performance/latency/XFAIL_LATENCY.list
  test/performance/latency/XFAIL_LATENCY_SECURITY.list
Labels: ready-to-merge

#5001 [19563] Fix non-defined duration Qos in configuration example
  examples/cpp/configuration/CLIParser.hpp
  examples/cpp/configuration/PublisherApp.cpp
  examples/cpp/configuration/README.md
  examples/cpp/configuration/SubscriberApp.cpp
Labels: ready-to-merge

#5040 [21335] Fix compilation on VS 2022 in Debug
  src/cpp/rtps/messages/MessageReceiver.cpp
  tools/fds/server.cpp
Labels: ci-pending

#5041 [21337] Fix doxygen on Ubuntu 24.04
  include/fastdds/dds/core/policy/QosPolicies.hpp
  include/fastdds/dds/log/Log.hpp
  include/fastdds/dds/subscriber/InstanceState.hpp
  utils/doxygen/doxyfile.in
Labels: no-test, ci-pending

#5000 Make more flexible EDP::valid_matching with TypeInformation [21260]
  src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
  test/mock/rtps/ReaderProxyData/fastdds/rtps/builtin/data/ReaderProxyData.hpp
  test/mock/rtps/WriterProxyData/fastdds/rtps/builtin/data/WriterProxyData.hpp
  test/unittest/rtps/discovery/EdpTests.cpp
Labels: ready-to-merge

#5039 fix: fix typo in CMakeLists.txt
  src/cpp/CMakeLists.txt
Labels: ready-to-merge, skip-ci

#4780 [20903] DynamicData to JSON serializer
  include/fastdds/dds/xtypes/utils.hpp
  src/cpp/CMakeLists.txt
  src/cpp/fastdds/xtypes/CMakeLists.txt
  src/cpp/fastdds/xtypes/dynamic_types/DynamicDataImpl.cpp
  src/cpp/fastdds/xtypes/dynamic_types/DynamicDataImpl.hpp
  src/cpp/fastdds/xtypes/serializers/json/dynamic_data_json.cpp
  src/cpp/fastdds/xtypes/serializers/json/dynamic_data_json.hpp
  src/cpp/fastdds/xtypes/utils.cpp
  test/unittest/CMakeLists.txt
  test/unittest/dds/xtypes/serializers/CMakeLists.txt
  test/unittest/dds/xtypes/serializers/json/CMakeLists.txt
  test/unittest/dds/xtypes/serializers/json/DynDataJSONTests.cpp
  test/unittest/dds/xtypes/serializers/json/types/comprehensive_type/ComprehensiveType.idl
  test/unittest/dds/xtypes/serializers/json/types/comprehensive_type/gen/ComprehensiveType.hpp
  test/unittest/dds/xtypes/serializers/json/types/comprehensive_type/gen/ComprehensiveTypeCdrAux.hpp
  test/unittest/dds/xtypes/serializers/json/types/comprehensive_type/gen/ComprehensiveTypeCdrAux.ipp
  test/unittest/dds/xtypes/serializers/json/types/comprehensive_type/gen/ComprehensiveTypePubSubTypes.cxx
  test/unittest/dds/xtypes/serializers/json/types/comprehensive_type/gen/ComprehensiveTypePubSubTypes.hpp
  test/unittest/dds/xtypes/serializers/json/types/comprehensive_type/gen/ComprehensiveTypeTypeObjectSupport.cxx
  test/unittest/dds/xtypes/serializers/json/types/comprehensive_type/gen/ComprehensiveTypeTypeObjectSupport.hpp
  test/unittest/dds/xtypes/serializers/json/types/comprehensive_type/implementation/ComprehensiveTypeImpl.cpp
  test/unittest/dds/xtypes/serializers/json/types/comprehensive_type/json/ComprehensiveType_Filled_EPROSIMA_1.json
  test/unittest/dds/xtypes/serializers/json/types/comprehensive_type/json/ComprehensiveType_Filled_EPROSIMA_2.json
  test/unittest/dds/xtypes/serializers/json/types/comprehensive_type/json/ComprehensiveType_Filled_EPROSIMA_3.json
  test/unittest/dds/xtypes/serializers/json/types/comprehensive_type/json/ComprehensiveType_Filled_OMG_1.json
  test/unittest/dds/xtypes/serializers/json/types/comprehensive_type/json/ComprehensiveType_Filled_OMG_2.json
  test/unittest/dds/xtypes/serializers/json/types/comprehensive_type/json/ComprehensiveType_Filled_OMG_3.json
  test/unittest/dds/xtypes/serializers/json/types/comprehensive_type/json/ComprehensiveType_Unfilled_EPROSIMA.json
  test/unittest/dds/xtypes/serializers/json/types/comprehensive_type/json/ComprehensiveType_Unfilled_OMG.json
  test/unittest/dds/xtypes/serializers/json/types/types.hpp
  utils/scripts/update_generated_code_from_idl.sh
  versions.md
Labels: first-to-merge, ci-pending

#5049 [21329] All `DataWriter::write` overload shall return `RerturnCode_t` type
  examples/cpp/configuration/PublisherApp.cpp
  examples/cpp/content_filter/PublisherApp.cpp
  examples/cpp/custom_payload_pool/PublisherApp.cpp
  examples/cpp/dds/RequestReplyExample/CalculatorClient.cpp
  examples/cpp/delivery_mechanisms/PubSubApp.cpp
  examples/cpp/delivery_mechanisms/PublisherApp.cpp
  examples/cpp/discovery_server/ClientPublisherApp.cpp
  examples/cpp/hello_world/PublisherApp.cpp
  examples/cpp/xtypes/PublisherApp.cpp
  include/fastdds/dds/publisher/DataWriter.hpp
  src/cpp/fastdds/publisher/DataWriter.cpp
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/publisher/DataWriterImpl.hpp
  test/blackbox/api/dds-pim/PubSubParticipant.hpp
  test/blackbox/api/dds-pim/PubSubWriter.hpp
  test/blackbox/api/dds-pim/PubSubWriterReader.hpp
  test/blackbox/api/dds-pim/ReqRepHelloWorldReplier.cpp
  test/blackbox/api/dds-pim/ReqRepHelloWorldRequester.cpp
  test/blackbox/api/dds-pim/TCPReqRepHelloWorldReplier.cpp
  test/blackbox/api/dds-pim/TCPReqRepHelloWorldRequester.cpp
  test/blackbox/common/DDSBlackboxTestsBasic.cpp
  test/blackbox/common/DDSBlackboxTestsDataReader.cpp
  test/blackbox/common/DDSBlackboxTestsMonitorService.cpp
  test/performance/latency/LatencyTestPublisher.cpp
  test/performance/latency/LatencyTestSubscriber.cpp
  test/performance/throughput/ThroughputPublisher.cpp
  test/performance/video/VideoTestPublisher.cpp
  test/profiling/allocations/AllocTestPublisher.cpp
  test/realtime/UserThreadNonBlockedTest.cpp
  test/unittest/dds/subscriber/DataReaderTests.cpp
  test/unittest/statistics/dds/StatisticsDomainParticipantStatusQueryableTests/mock/fastdds/publisher/DataWriterImpl.hpp
Labels: ready-to-merge

#5038 [21267] Add Ubuntu weekly ci
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/reusable-ubuntu-ci.yml
  .github/workflows/reusable-windows-ci.yml
  .github/workflows/ubuntu-ci.yml
  .github/workflows/weekly-ubuntu-ci.yml
Labels: ready-to-merge

#5035 [21233] Mitigate buffer recover test flakiness on mac
  test/unittest/transport/SharedMemTests.cpp
Labels: ready-to-merge, ci-pending

#5056 [21311] Bump version to 2.14.3
  CMakeLists.txt
  package.xml
  versions.md
Labels: skip-ci

#5057 [21311] Update 2.14 latest release in RELEASE_SUPPORT.md
  RELEASE_SUPPORT.md
Labels: skip-ci

#5051 [21327] Mitigate `LogTests.flush_n` flakiness
  src/cpp/fastdds/log/Log.cpp
Labels: ready-to-merge

#5060 [21310] Bump version to v2.13.6
  CMakeLists.txt
  package.xml
Labels: skip-ci

#5061 [21310] Set 2.13.x as EOL
  .github/pull_request_template.md
  .github/workflows/nightly-mac-ci.yml
  .github/workflows/nightly-sanitizers-ci.yml
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/nightly-windows-ci.yml
  .github/workflows/weekly-sanitizers-ci.yml
  RELEASE_SUPPORT.md
Labels: skip-ci

#5014 [21188] Example Refactor: Request-Reply
  examples/CMakeLists.txt
  examples/cpp/content_filter/CLIParser.hpp
  examples/cpp/content_filter/CustomContentFilter.hpp
  examples/cpp/content_filter/CustomContentFilterFactory.hpp
  examples/cpp/dds/CMakeLists.txt
  examples/cpp/dds/RequestReplyExample/CMakeLists.txt
  examples/cpp/dds/RequestReplyExample/Calculator.hpp
  examples/cpp/dds/RequestReplyExample/Calculator.idl
  examples/cpp/dds/RequestReplyExample/CalculatorClient.cpp
  examples/cpp/dds/RequestReplyExample/CalculatorServer.cpp
  examples/cpp/dds/RequestReplyExample/CalculatorTypeObjectSupport.cxx
  examples/cpp/dds/RequestReplyExample/README.md
  examples/cpp/request_reply/Application.cpp
  examples/cpp/request_reply/Application.hpp
  examples/cpp/request_reply/CLIParser.hpp
  examples/cpp/request_reply/CMakeLists.txt
  examples/cpp/request_reply/ClientApp.cpp
  examples/cpp/request_reply/ClientApp.hpp
  examples/cpp/request_reply/README.md
  examples/cpp/request_reply/ServerApp.cpp
  examples/cpp/request_reply/ServerApp.hpp
  examples/cpp/request_reply/app_utils.hpp
  examples/cpp/request_reply/main.cpp
  examples/cpp/request_reply/request_reply_profile.xml
  examples/cpp/request_reply/types/Calculator.hpp
  examples/cpp/request_reply/types/Calculator.idl
  examples/cpp/request_reply/types/CalculatorCdrAux.hpp
  examples/cpp/request_reply/types/CalculatorCdrAux.ipp
  examples/cpp/request_reply/types/CalculatorPubSubTypes.cxx
  examples/cpp/request_reply/types/CalculatorPubSubTypes.hpp
  examples/cpp/request_reply/types/CalculatorTypeObjectSupport.cxx
  examples/cpp/request_reply/types/CalculatorTypeObjectSupport.hpp
  include/fastdds/dds/domain/DomainParticipantFactory.hpp
  src/cpp/fastdds/domain/DomainParticipantFactory.cpp
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  test/examples/request_reply.compose.yml
  test/examples/request_reply_isolated.compose.yml
  test/examples/test_request_reply.py
  test/examples/test_request_reply_isolated.py
  test/unittest/dds/participant/ParticipantTests.cpp
  versions.md
Labels: ready-to-merge

#5080 [21334] Handle nullptr in parseXMLStructDynamicType
  src/cpp/xmlparser/XMLDynamicParser.cpp
  test/unittest/xmlparser/XMLParserTests.cpp
  test/unittest/xmlparser/regressions/21334_profile_bin.xml
Labels: ready-to-merge, skip-ci

#5047 [21279] Examples refactor: Static EDP discovery
  examples/CMakeLists.txt
  examples/cpp/dds/CMakeLists.txt
  examples/cpp/dds/StaticHelloWorldExample/CMakeLists.txt
  examples/cpp/dds/StaticHelloWorldExample/HelloWorldPublisher.cpp
  examples/cpp/dds/StaticHelloWorldExample/HelloWorldPublisher.h
  examples/cpp/dds/StaticHelloWorldExample/HelloWorldPublisher_static_disc.xml
  examples/cpp/dds/StaticHelloWorldExample/HelloWorldSubscriber.cpp
  examples/cpp/dds/StaticHelloWorldExample/HelloWorldSubscriber.h
  examples/cpp/dds/StaticHelloWorldExample/HelloWorldSubscriber_static_disc.xml
  examples/cpp/dds/StaticHelloWorldExample/HelloWorld_main.cpp
  examples/cpp/dds/StaticHelloWorldExample/README.txt
  examples/cpp/static_edp_discovery/Application.cpp
  examples/cpp/static_edp_discovery/Application.hpp
  examples/cpp/static_edp_discovery/CLIParser.hpp
  examples/cpp/static_edp_discovery/CMakeLists.txt
  examples/cpp/static_edp_discovery/HelloWorld.hpp
  examples/cpp/static_edp_discovery/HelloWorld.idl
  examples/cpp/static_edp_discovery/HelloWorldCdrAux.hpp
  examples/cpp/static_edp_discovery/HelloWorldCdrAux.ipp
  examples/cpp/static_edp_discovery/HelloWorldPubSubTypes.cxx
  examples/cpp/static_edp_discovery/HelloWorldPubSubTypes.hpp
  examples/cpp/static_edp_discovery/HelloWorldTypeObjectSupport.cxx
  examples/cpp/static_edp_discovery/HelloWorldTypeObjectSupport.hpp
  examples/cpp/static_edp_discovery/HelloWorld_static_disc.xml
  examples/cpp/static_edp_discovery/PublisherApp.cpp
  examples/cpp/static_edp_discovery/PublisherApp.hpp
  examples/cpp/static_edp_discovery/README.md
  examples/cpp/static_edp_discovery/SubscriberApp.cpp
  examples/cpp/static_edp_discovery/SubscriberApp.hpp
  examples/cpp/static_edp_discovery/main.cpp
  test/examples/static_edp_discovery.compose.yml
  test/examples/test_static_edp_discovery.py
  versions.md
Labels: ready-to-merge

#4999 [21185] Examples refactor: Flow Controller
  examples/CMakeLists.txt
  examples/cpp/dds/CMakeLists.txt
  examples/cpp/dds/FlowControlExample/.gitignore
  examples/cpp/dds/FlowControlExample/FlowControlExample.idl
  examples/cpp/dds/FlowControlExample/FlowControlExamplePubSubMain.cxx
  examples/cpp/dds/FlowControlExample/FlowControlExamplePublisher.cxx
  examples/cpp/dds/FlowControlExample/FlowControlExamplePublisher.h
  examples/cpp/dds/FlowControlExample/FlowControlExampleSubscriber.cxx
  examples/cpp/dds/FlowControlExample/FlowControlExampleSubscriber.h
  examples/cpp/dds/FlowControlExample/README.txt
  examples/cpp/flow_control/Application.cpp
  examples/cpp/flow_control/Application.hpp
  examples/cpp/flow_control/CLIParser.hpp
  examples/cpp/flow_control/CMakeLists.txt
  examples/cpp/flow_control/FlowControl.hpp
  examples/cpp/flow_control/FlowControl.idl
  examples/cpp/flow_control/FlowControlCdrAux.hpp
  examples/cpp/flow_control/FlowControlCdrAux.ipp
  examples/cpp/flow_control/FlowControlPubSubTypes.cxx
  examples/cpp/flow_control/FlowControlPubSubTypes.hpp
  examples/cpp/flow_control/FlowControlTypeObjectSupport.cxx
  examples/cpp/flow_control/FlowControlTypeObjectSupport.hpp
  examples/cpp/flow_control/PublisherApp.cpp
  examples/cpp/flow_control/PublisherApp.hpp
  examples/cpp/flow_control/README.md
  examples/cpp/flow_control/SubscriberApp.cpp
  examples/cpp/flow_control/SubscriberApp.hpp
  examples/cpp/flow_control/flow_control_profile.xml
  examples/cpp/flow_control/main.cpp
  examples/cpp/xtypes/SubscriberApp.cpp
  test/examples/flow_control.compose.yml
  test/examples/test_flow_control.py
  versions.md
Labels: skip-ci

#5070 [21371] Change monitor service writer entity id
  src/cpp/statistics/rtps/GuidUtils.hpp
Labels: ready-to-merge

#5084 [21386] Fix lack of entity arguent issue in configuration example
  examples/cpp/configuration/CLIParser.hpp
Labels: ci-pending

#5092 Add missing DynamicType includes
  include/fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp
Labels: ready-to-merge, no-test

#5083 [21387] Fix build issues and update CI infrastructure to detect them
  .github/workflows/reusable-ubuntu-ci.yml
  .github/workflows/reusable-windows-ci.yml
  CMakeLists.txt
  examples/cpp/static_edp_discovery/CLIParser.hpp
  examples/cpp/static_edp_discovery/PublisherApp.hpp
  examples/cpp/topic_instances/CLIParser.hpp
  src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
  src/cpp/utils/UnitsParser.cpp
Labels: first-to-merge, ci-pending

#5095 [21387] Fix windows CI and add vanilla build step in ubuntu CI
  .github/workflows/reusable-ubuntu-ci.yml
  .github/workflows/reusable-windows-ci.yml
Labels: ready-to-merge, first-to-merge

#5086 [21280] Example refactor: RTPS
  examples/cpp/rtps/Application.cpp
  examples/cpp/rtps/Application.hpp
  examples/cpp/rtps/AsSocket/CMakeLists.txt
  examples/cpp/rtps/AsSocket/README.txt
  examples/cpp/rtps/AsSocket/TestReaderSocket.cpp
  examples/cpp/rtps/AsSocket/TestReaderSocket.h
  examples/cpp/rtps/AsSocket/TestWriterSocket.cpp
  examples/cpp/rtps/AsSocket/TestWriterSocket.h
  examples/cpp/rtps/AsSocket/main_RTPSTest.cpp
  examples/cpp/rtps/CLIParser.hpp
  examples/cpp/rtps/CMakeLists.txt
  examples/cpp/rtps/HelloWorld.hpp
  examples/cpp/rtps/HelloWorld.idl
  examples/cpp/rtps/Persistent/CMakeLists.txt
  examples/cpp/rtps/Persistent/README.txt
  examples/cpp/rtps/Persistent/TestReaderPersistent.cpp
  examples/cpp/rtps/Persistent/TestReaderPersistent.h
  examples/cpp/rtps/Persistent/TestWriterPersistent.cpp
  examples/cpp/rtps/Persistent/TestWriterPersistent.h
  examples/cpp/rtps/Persistent/main_RTPSTest.cpp
  examples/cpp/rtps/README.md
  examples/cpp/rtps/ReaderApp.cpp
  examples/cpp/rtps/ReaderApp.hpp
  examples/cpp/rtps/Registered/CMakeLists.txt
  examples/cpp/rtps/Registered/README.txt
  examples/cpp/rtps/Registered/TestReaderRegistered.cpp
  examples/cpp/rtps/Registered/TestReaderRegistered.h
  examples/cpp/rtps/Registered/TestWriterRegistered.cpp
  examples/cpp/rtps/Registered/TestWriterRegistered.h
  examples/cpp/rtps/Registered/main_RTPSTest.cpp
  examples/cpp/rtps/WriterApp.cpp
  examples/cpp/rtps/WriterApp.hpp
  examples/cpp/rtps/hello_world_profile.xml
  examples/cpp/rtps/main.cpp
  test/examples/rtps.compose.yml
  test/examples/test_rtps.py
  utils/scripts/update_generated_code_from_idl.sh
  versions.md
Labels: ready-to-merge

#5073 [21325] Remove all code related to FAST CDR v1
  include/fastdds/config.hpp.in
  include/fastdds/rtps/common/CdrSerialization.hpp
  src/cpp/fastdds/core/policy/QosPoliciesSerializer.hpp
  src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterExpression.cpp
  src/cpp/rtps/transport/tcp/TCPControlMessage.cpp
  src/cpp/security/cryptography/AESGCMGMAC_Transform.cpp
  test/blackbox/common/DDSBlackboxTestsDataRepresentationQos.cpp
  test/blackbox/common/RTPSAsSocketWriter.hpp
  test/blackbox/common/RTPSWithRegistrationReader.hpp
  test/blackbox/types/core/core_types.cxx
  test/blackbox/types/core/core_types.h
  test/blackbox/types/core/core_typesTypeObject.cxx
  test/blackbox/types/core/core_typesTypeObject.h
  test/realtime/UserThreadNonBlockedTest.cpp
  test/unittest/dds/subscriber/FooBoundedTypeSupport.hpp
  test/unittest/dds/subscriber/FooTypeSupport.hpp
  test/unittest/rtps/writer/RTPSWriterTests.cpp
Labels: ci-pending

#5108 [21364] Fix installation of some examples
  examples/cpp/custom_payload_pool/CMakeLists.txt
  examples/cpp/delivery_mechanisms/CMakeLists.txt
  examples/cpp/security/CMakeLists.txt
  examples/cpp/security/README.md
Labels: ready-to-merge

#4768 [20953] Support Type-Lookup Service with new new GUID-less Discovery Server
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupManager.cpp
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupManager.hpp
  src/cpp/rtps/builtin/BuiltinProtocols.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPSimpleListeners.cpp
  versions.md
Labels: ready-to-merge

#5106 [21420] Fix wait argument in configuration example
  examples/cpp/configuration/CLIParser.hpp
  examples/cpp/configuration/PublisherApp.cpp
Labels: ci-pending

#5111 [21364] Remove double // in some installation paths
  CMakeLists.txt
Labels: ready-to-merge, no-test

#4964 [21198] Add product version on Participant Discovery information
  include/fastdds/dds/core/policy/ParameterTypes.hpp
  include/fastdds/rtps/builtin/data/ParticipantBuiltinTopicData.hpp
  include/fastdds/rtps/common/ProductVersion_t.hpp
  include/fastdds/rtps/common/Types.hpp
  src/cpp/fastdds/core/policy/ParameterSerializer.hpp
  src/cpp/rtps/builtin/data/ParticipantProxyData.cpp
  src/cpp/rtps/builtin/data/ParticipantProxyData.hpp
  src/cpp/rtps/builtin/data/ProxyDataConverters.cpp
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
  versions.md
Labels: ci-pending

#5102 [21363] Migration guide
  UPGRADING.md
Labels: skip-ci

#5116 [19036] Link SHM locator kind with Fast DDS major version
  include/fastdds/rtps/common/Locator.hpp
  src/cpp/rtps/transport/shared_mem/SharedMemGlobal.hpp
  versions.md
Labels: ci-pending

#5115 [21435] Solve SecurityManager memory issue
  src/cpp/rtps/history/WriterHistory.cpp
Labels: ci-pending

#5117 [21437] Builtin data related improvements
  include/fastdds/rtps/builtin/data/PublicationBuiltinTopicData.hpp
  include/fastdds/rtps/builtin/data/SubscriptionBuiltinTopicData.hpp
  include/fastdds/rtps/participant/ParticipantDiscoveryInfo.hpp
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.cpp
  src/cpp/rtps/builtin/data/ProxyDataConverters.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.h
  test/blackbox/common/RTPSBlackboxTestsBasic.cpp
  test/blackbox/common/RTPSWithRegistrationReader.hpp
  test/blackbox/common/RTPSWithRegistrationWriter.hpp
  versions.md
Labels: ready-to-merge
