Repository eProsima/Fast-DDS, pull requests merged in 2024-03, with the labels that each got.

#4435 [20439] Expose Authentication Handshake Properties
  include/fastdds/rtps/attributes/PropertyPolicy.h
  include/fastdds/rtps/common/Property.h
  src/cpp/rtps/attributes/PropertyPolicy.cpp
  src/cpp/rtps/security/SecurityManager.cpp
  src/cpp/rtps/security/SecurityManager.h
  test/blackbox/CMakeLists.txt
  test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
  test/blackbox/api/fastrtps_deprecated/PubSubWriter.hpp
  test/blackbox/auth_handshake_props_profile.xml
  test/blackbox/common/BlackboxTestsSecurity.cpp
  versions.md
Labels: ci-pending

#4489 [20486] Avoid running GitHub CI if PR has conflicts
  .github/workflows/documentation-tests.yaml
  .github/workflows/mac-ci.yml
  .github/workflows/sanitizer-tests.yaml
  .github/workflows/thread-sanitizer.yaml
  .github/workflows/windows-ci.yml
Labels: conflicts

#4348 [20313] Allow single listening port on TCP
  src/cpp/rtps/transport/TCPv4Transport.cpp
  src/cpp/rtps/transport/TCPv6Transport.cpp
  test/blackbox/common/BlackboxTestsTransportTCP.cpp
  test/unittest/transport/TCPv4Tests.cpp
  test/unittest/transport/TCPv6Tests.cpp
Labels: ready-to-merge

#4459 [20511] Add missing virtual destructor for StatisticsAncillary
  src/cpp/statistics/rtps/StatisticsBase.hpp
Labels: ready-to-merge

#4464 [20415] Update APIs in video performance tests
  test/performance/video/CMakeLists.txt
  test/performance/video/VideoTestPublisher.cpp
  test/performance/video/VideoTestPublisher.hpp
  test/performance/video/VideoTestSubscriber.cpp
  test/performance/video/VideoTestSubscriber.hpp
  test/performance/video/VideoTestTypes.cpp
  test/performance/video/VideoTestTypes.hpp
  test/performance/video/main_VideoTest.cpp
Labels: ready-to-merge

#4300 [20120] TCPSendResources cleanup
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  src/cpp/rtps/network/NetworkFactory.cpp
  src/cpp/rtps/network/NetworkFactory.h
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.h
  src/cpp/rtps/transport/TCPSenderResource.hpp
  src/cpp/rtps/transport/TCPTransportInterface.cpp
  src/cpp/rtps/transport/TCPTransportInterface.h
  src/cpp/rtps/transport/UDPSenderResource.hpp
  src/cpp/rtps/transport/UDPTransportInterface.cpp
  src/cpp/rtps/transport/UDPTransportInterface.h
  test/blackbox/common/BlackboxTestsTransportTCP.cpp
  test/blackbox/common/DatagramInjectionTransport.cpp
  test/blackbox/common/DatagramInjectionTransport.hpp
  test/mock/rtps/RTPSParticipantImpl/rtps/participant/RTPSParticipantImpl.h
  test/unittest/rtps/discovery/CMakeLists.txt
  test/unittest/rtps/security/CMakeLists.txt
  test/unittest/statistics/rtps/CMakeLists.txt
  test/unittest/transport/CMakeLists.txt
  test/unittest/transport/TCPv4Tests.cpp
  test/unittest/transport/TCPv6Tests.cpp
  test/unittest/transport/test_UDPv4Tests.cpp
Labels: ci-pending

#4454 [20508] TCP first message loss
  include/fastdds/rtps/transport/TCPTransportDescriptor.h
  include/fastrtps/xmlparser/XMLParserCommon.h
  resources/xsd/fastRTPS_profiles.xsd
  src/cpp/rtps/attributes/RTPSParticipantAttributes.cpp
  src/cpp/rtps/transport/TCPChannelResource.cpp
  src/cpp/rtps/transport/TCPChannelResource.h
  src/cpp/rtps/transport/TCPTransportInterface.cpp
  src/cpp/rtps/transport/TCPTransportInterface.h
  src/cpp/rtps/transport/tcp/RTCPMessageManager.cpp
  src/cpp/rtps/xmlparser/XMLParser.cpp
  src/cpp/rtps/xmlparser/XMLParserCommon.cpp
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/blackbox/api/dds-pim/PubSubWriter.hpp
  test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
  test/blackbox/api/fastrtps_deprecated/PubSubWriter.hpp
  test/blackbox/common/BlackboxTestsTransportTCP.cpp
  test/mock/rtps/TCPTransportDescriptor/fastrtps/transport/TCPTransportDescriptor.h
  test/system/tools/xmlvalidation/XMLTesterExample_profile.xml
  test/system/tools/xmlvalidation/all_profile.xml
  test/unittest/transport/TCPv4Tests.cpp
  test/unittest/transport/TCPv6Tests.cpp
  test/unittest/transport/mock/MockTCPv4Transport.h
  test/unittest/transport/mock/MockTCPv6Transport.h
  test/unittest/xmlparser/XMLParserTests.cpp
Labels: ci-pending

#4458 [20511] Add missing virtual destructor for StatisticsAncillary
  src/cpp/statistics/rtps/StatisticsBase.hpp
Labels: ci-pending

#4411 [20492] OpenOutputChannels / CloseOutputChannels that receive a LocatorSelectorEntry
  include/fastdds/rtps/transport/TransportInterface.h
  src/cpp/CMakeLists.txt
  src/cpp/rtps/network/NetworkFactory.cpp
  src/cpp/rtps/transport/TCPTransportInterface.cpp
  src/cpp/rtps/transport/TCPTransportInterface.h
  src/cpp/rtps/transport/TransportInterface.cpp
  test/unittest/dds/publisher/CMakeLists.txt
  test/unittest/rtps/discovery/CMakeLists.txt
  test/unittest/rtps/network/CMakeLists.txt
  test/unittest/statistics/dds/CMakeLists.txt
  test/unittest/statistics/rtps/CMakeLists.txt
  test/unittest/transport/CMakeLists.txt
  test/unittest/transport/TCPv4Tests.cpp
  test/unittest/transport/TCPv6Tests.cpp
  versions.md
Labels: ci-pending

#4444 [20493] Extend LARGE_DATA configuration options
  include/fastdds/dds/core/policy/QosPolicies.hpp
  include/fastdds/dds/domain/qos/DomainParticipantQos.hpp
  include/fastdds/rtps/attributes/BuiltinTransports.hpp
  include/fastdds/rtps/attributes/RTPSParticipantAttributes.h
  include/fastdds/rtps/transport/ChainingTransport.h
  include/fastdds/rtps/transport/TransportInterface.h
  include/fastrtps/utils/UnitsParser.hpp
  include/fastrtps/xmlparser/XMLParser.h
  include/fastrtps/xmlparser/XMLParserCommon.h
  resources/xsd/fastRTPS_profiles.xsd
  src/cpp/CMakeLists.txt
  src/cpp/fastdds/domain/qos/DomainParticipantQos.cpp
  src/cpp/fastdds/utils/QosConverters.cpp
  src/cpp/rtps/attributes/RTPSParticipantAttributes.cpp
  src/cpp/rtps/network/NetworkFactory.cpp
  src/cpp/rtps/network/NetworkFactory.h
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/transport/TCPTransportInterface.cpp
  src/cpp/rtps/transport/TCPTransportInterface.h
  src/cpp/rtps/transport/UDPTransportInterface.cpp
  src/cpp/rtps/transport/UDPTransportInterface.h
  src/cpp/rtps/transport/shared_mem/SharedMemTransport.cpp
  src/cpp/rtps/transport/shared_mem/SharedMemTransport.h
  src/cpp/rtps/xmlparser/XMLElementParser.cpp
  src/cpp/rtps/xmlparser/XMLParser.cpp
  src/cpp/rtps/xmlparser/XMLParserCommon.cpp
  src/cpp/utils/UnitsParser.cpp
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/blackbox/api/dds-pim/PubSubWriter.hpp
  test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
  test/blackbox/api/fastrtps_deprecated/PubSubWriter.hpp
  test/blackbox/builtin_transports_profile.xml
  test/blackbox/common/BlackboxTestsTransportCustom.cpp
  test/mock/rtps/RTPSParticipantAttributes/fastdds/rtps/attributes/RTPSParticipantAttributes.h
  test/unittest/dds/participant/ParticipantTests.cpp
  test/unittest/dds/publisher/CMakeLists.txt
  test/unittest/dds/status/CMakeLists.txt
  test/unittest/dynamic_types/CMakeLists.txt
  test/unittest/rtps/network/mock/MockTransport.cpp
  test/unittest/rtps/network/mock/MockTransport.h
  test/unittest/statistics/dds/CMakeLists.txt
  test/unittest/xmlparser/CMakeLists.txt
  test/unittest/xmlparser/XMLElementParserTests.cpp
  test/unittest/xmlparser/wrapper/XMLParserTest.hpp
Labels: ready-to-merge

#4525 [20553] Fix nightly jobs
  .github/workflows/nightly-mac-ci.yml
  .github/workflows/nightly-windows-ci.yml
Labels: skip-ci

#4507 [20603] Upgrade dependency version to last patch version in .repos file
  fastrtps.repos
Labels: no-test, ci-pending

#4483 [20542] Fix CI version management
  .github/actions/fetch-fastdds-repos/action.yml
  .github/workflows/address-sanitizers.yaml
  .github/workflows/config/nightly.meta
  .github/workflows/config/nightly_2.10.x.repos
  .github/workflows/config/nightly_2.6.x.repos
  .github/workflows/documentation-tests.yaml
  .github/workflows/mac-ci.yml
  .github/workflows/nightly-mac-ci.yml
  .github/workflows/nightly-windows-ci.yml
  .github/workflows/reusable-windows-ci.yml
  .github/workflows/thread-sanitizer.yaml
  .github/workflows/windows-ci.yml
Labels: ci-pending

#4535 [20603] Remove idl parser from .repos file
  fastrtps.repos
Labels: no-test

#4506 [20603] Upgrade dependency version to last patch version in .repos file
  fastrtps.repos
Labels: ready-to-merge, no-test

#4460 [20511] Add missing virtual destructor for StatisticsAncillary
  src/cpp/statistics/rtps/StatisticsBase.hpp
Labels: ci-pending

#4508 [20603] Upgrade dependency version to last patch version in .repos file
  fastrtps.repos
Labels: no-test

#4509 [20603] Upgrade dependency version to last patch version in .repos file
  fastrtps.repos
Labels: no-test, ci-pending

#4556 [20542] Manual cherry-pick of PR #4549
  .github/workflows/config/asan_colcon.meta
  .github/workflows/config/ci.meta
  .github/workflows/config/ci.repos
  .github/workflows/config/default_ci_2.10.x.repos
  .github/workflows/config/default_ci_2.6.x.repos
  .github/workflows/config/tsan_colcon.meta
  .github/workflows/mac-ci.yml
  .github/workflows/reusable-mac-ci.yml
  .github/workflows/reusable-ubuntu-ci.yml
  .github/workflows/reusable-windows-ci.yml
  .github/workflows/ubuntu-ci.yml
  .github/workflows/windows-ci.yml
Labels: ci-pending

#4484 [20542] Fix CI version management
  .github/actions/fetch-fastdds-repos/action.yml
  .github/workflows/address-sanitizers.yaml
  .github/workflows/config/asan_colcon.meta
  .github/workflows/config/ci.meta
  .github/workflows/config/ci.repos
  .github/workflows/config/default_ci.meta
  .github/workflows/config/default_ci_2.6.x.repos
  .github/workflows/config/nightly_2.6.x.repos
  .github/workflows/config/tsan_colcon.meta
  .github/workflows/documentation-tests.yaml
  .github/workflows/mac-ci.yml
  .github/workflows/nightly-mac-ci.yml
  .github/workflows/nightly-windows-ci.yml
  .github/workflows/reusable-mac-ci.yml
  .github/workflows/reusable-ubuntu-ci.yml
  .github/workflows/reusable-windows-ci.yml
  .github/workflows/thread-sanitizer.yaml
  .github/workflows/ubuntu-ci.yml
  .github/workflows/windows-ci.yml
Labels: no-test

#4482 [20542] Fix CI version management
  .github/actions/fetch-fastdds-repos/action.yml
  .github/workflows/address-sanitizers.yaml
  .github/workflows/config/asan_colcon.meta
  .github/workflows/config/ci.meta
  .github/workflows/config/ci.repos
  .github/workflows/config/coverage.repos
  .github/workflows/config/default_ci.meta
  .github/workflows/config/default_ci_2.10.x.repos
  .github/workflows/config/default_ci_2.11.x.repos
  .github/workflows/config/default_ci_2.12.x.repos
  .github/workflows/config/default_ci_2.6.x.repos
  .github/workflows/config/default_ci_master.repos
  .github/workflows/config/nightly_2.10.x.repos
  .github/workflows/config/nightly_2.11.x.repos
  .github/workflows/config/nightly_2.12.x.repos
  .github/workflows/config/nightly_2.6.x.repos
  .github/workflows/config/nightly_master.repos
  .github/workflows/config/tsan_colcon.meta
  .github/workflows/documentation-tests.yaml
  .github/workflows/mac-ci.yml
  .github/workflows/mirror.yml
  .github/workflows/nightly-mac-ci.yml
  .github/workflows/nightly-windows-ci.yml
  .github/workflows/reusable-mac-ci.yml
  .github/workflows/reusable-ubuntu-ci.yml
  .github/workflows/reusable-windows-ci.yml
  .github/workflows/thread-sanitizer.yaml
  .github/workflows/ubuntu-ci.yml
  .github/workflows/windows-ci.yml
Labels: no-test

#4481 [20542] Fix CI version management
  .github/actions/fetch-fastdds-repos/action.yml
  .github/actions/install-apt-packages-documentation/action.yml
  .github/workflows/address-sanitizers.yaml
  .github/workflows/config/asan_colcon.meta
  .github/workflows/config/ci.meta
  .github/workflows/config/ci.repos
  .github/workflows/config/coverage.repos
  .github/workflows/config/default_ci.meta
  .github/workflows/config/default_ci_2.10.x.repos
  .github/workflows/config/default_ci_2.12.x.repos
  .github/workflows/config/default_ci_2.6.x.repos
  .github/workflows/config/default_ci_master.repos
  .github/workflows/config/documentation.meta
  .github/workflows/config/nightly_2.10.x.repos
  .github/workflows/config/nightly_2.12.x.repos
  .github/workflows/config/nightly_2.6.x.repos
  .github/workflows/config/nightly_master.repos
  .github/workflows/config/tsan_colcon.meta
  .github/workflows/documentation-tests.yaml
  .github/workflows/mac-ci.yml
  .github/workflows/mirror.yml
  .github/workflows/nightly-mac-ci.yml
  .github/workflows/nightly-windows-ci.yml
  .github/workflows/rebase-3.0.x-devel.yaml
  .github/workflows/reusable-mac-ci.yml
  .github/workflows/reusable-ubuntu-ci.yml
  .github/workflows/reusable-windows-ci.yml
  .github/workflows/thread-sanitizer.yaml
  .github/workflows/ubuntu-ci.yml
  .github/workflows/windows-ci.yml
Labels: ready-to-merge, no-test

#4549 [20542] Adapt nightly jobs for all supported versions
  .github/workflows/config/asan_colcon.meta
  .github/workflows/config/ci.meta
  .github/workflows/config/ci.repos
  .github/workflows/config/coverage.repos
  .github/workflows/config/default_ci.meta
  .github/workflows/config/default_ci_2.10.x.repos
  .github/workflows/config/default_ci_2.12.x.repos
  .github/workflows/config/default_ci_2.13.x.repos
  .github/workflows/config/default_ci_2.6.x.repos
  .github/workflows/config/default_ci_master.repos
  .github/workflows/config/nightly_2.10.x.repos
  .github/workflows/config/nightly_2.12.x.repos
  .github/workflows/config/nightly_2.13.x.repos
  .github/workflows/config/nightly_2.6.x.repos
  .github/workflows/config/nightly_master.repos
  .github/workflows/config/tsan_colcon.meta
  .github/workflows/mac-ci.yml
  .github/workflows/reusable-mac-ci.yml
  .github/workflows/reusable-ubuntu-ci.yml
  .github/workflows/reusable-windows-ci.yml
  .github/workflows/ubuntu-ci.yml
  .github/workflows/windows-ci.yml
Labels: ready-to-merge

#4571 [20630] Use correct version of GTest on DS ASan tests
  .github/workflows/address-sanitizers.yaml
Labels: ready-to-merge

#4579 [20644] Update roadmap and release support
  RELEASE_SUPPORT.md
  roadmap.md
  versions.md
Labels: ready-to-merge, skip-ci

#4581 [20662] Select reusable workflow version depending on target branch in nightly jobs
  .github/workflows/nightly-mac-ci.yml
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/nightly-windows-ci.yml
Labels: skip-ci

#4583 [20641] Explicitly pass vendor ID to readFromCdrMessage
  src/cpp/rtps/builtin/data/ParticipantProxyData.cpp
  src/cpp/rtps/builtin/data/ReaderProxyData.cpp
  src/cpp/rtps/builtin/data/WriterProxyData.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPSimpleListeners.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPListener.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServerListener.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  test/blackbox/common/BlackboxTestsDiscovery.cpp
  test/blackbox/common/BlackboxTestsTransportUDP.cpp
  test/blackbox/common/DatagramInjectionTransport.hpp
  test/blackbox/datagrams/20641.bin
Labels: first-to-merge

#4554 [20608][20610] Address XMLProfiles fuzzer regressions
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/xmlparser/XMLElementParser.cpp
  src/cpp/utils/UnitsParser.cpp
  test/unittest/xmlparser/XMLParserTests.cpp
  test/unittest/xmlparser/regressions/20608_profile_bin.xml
  test/unittest/xmlparser/regressions/20610_profile_bin.xml
Labels: ready-to-merge

#4559 [20553] Set 2.12.x as EOL
  .github/pull_request_template.md
  .github/workflows/nightly-mac-ci.yml
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/nightly-windows-ci.yml
  RELEASE_SUPPORT.md
Labels: skip-ci

#4497 [20565] Added Annotation dependencies
  src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.cpp
  src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.hpp
Labels: no-test

#4587 [20672] Use a plain switch for NetmaskFilterKind std::ostream& operator<<
  src/cpp/rtps/transport/network/NetmaskFilterKind.cpp
Labels: ci-pending

#4557 [20025] Bump version to v2.12.2
  CMakeLists.txt
  package.xml
  versions.md
Labels: no-test, ci-pending

#4598 [20679] Run Github Ubuntu CI on PRs
  .github/workflows/address-sanitizers.yaml
  .github/workflows/documentation-tests.yaml
  .github/workflows/mac-ci.yml
  .github/workflows/thread-sanitizer.yaml
  .github/workflows/ubuntu-ci.yml
  .github/workflows/windows-ci.yml
  include/fastrtps/subscriber/SubscriberHistory.h
  src/cpp/fastdds/domain/DomainParticipantImpl.hpp
  src/cpp/fastdds/publisher/DataWriterImpl.hpp
  src/cpp/fastdds/subscriber/DataReaderImpl.hpp
  src/cpp/fastrtps_deprecated/participant/ParticipantImpl.h
  src/cpp/fastrtps_deprecated/publisher/PublisherImpl.h
  src/cpp/fastrtps_deprecated/subscriber/SubscriberImpl.h
  src/cpp/rtps/DataSharing/ReaderPool.hpp
  src/cpp/rtps/DataSharing/WriterPool.hpp
  src/cpp/rtps/builtin/discovery/participant/PDPClient.h
  src/cpp/rtps/builtin/discovery/participant/PDPServer.hpp
  src/cpp/rtps/history/BasicPayloadPool_impl/Base.hpp
  src/cpp/rtps/history/BasicPayloadPool_impl/PreallocatedWithRealloc.hpp
  src/cpp/rtps/history/TopicPayloadPool_impl/Dynamic.hpp
  src/cpp/rtps/history/TopicPayloadPool_impl/DynamicReusable.hpp
  src/cpp/rtps/history/TopicPayloadPool_impl/Preallocated.hpp
  src/cpp/rtps/history/TopicPayloadPool_impl/PreallocatedWithRealloc.hpp
  src/cpp/rtps/transport/TCPTransportInterface.h
  src/cpp/rtps/transport/UDPTransportInterface.h
  src/cpp/rtps/transport/shared_mem/SharedMemTransport.h
  src/cpp/statistics/rtps/monitor-service/MonitorServiceListener.hpp
  test/blackbox/common/BlackboxTestsDiscovery.cpp
Labels: first-to-merge, ci-pending

#4187 [20351] Fix on_sample_lost notification on best-effort readers for framented samples
  src/cpp/rtps/reader/StatelessReader.cpp
  test/blackbox/common/DDSBlackboxTestsListeners.cpp
Labels: skip-ci

#4620 [20692] Make sample_lost_be_dw_be_dr_fragments test less flakey
  test/blackbox/common/DDSBlackboxTestsListeners.cpp
Labels: ci-pending

#4534 [20543] Create Participant with default profile (use environment XML configuration)
  include/fastdds/dds/domain/DomainParticipantFactory.hpp
  src/cpp/fastdds/domain/DomainParticipantFactory.cpp
  test/unittest/dds/participant/ParticipantTests.cpp
  versions.md
Labels: ready-to-merge, skip-ci

#4502 [20589] Set real TCP non_blocking_send limitation
  src/cpp/rtps/transport/TCPChannelResource.cpp
  test/unittest/transport/TCPv4Tests.cpp
  test/unittest/transport/TCPv6Tests.cpp
Labels: ready-to-merge

#4627 [20654] Increase ack waiting time in reliable_on_unack_sample_removed
  test/blackbox/common/DDSBlackboxTestsListeners.cpp
Labels: ci-pending

#4625 [20592][20679] Fix hidden overloaded virtual methods
  .github/workflows/reusable-ubuntu-ci.yml
  examples/cpp/dds/DiscoveryServerExample/DiscoveryServerPublisher.h
  examples/cpp/dds/DiscoveryServerExample/DiscoveryServerServer.h
  examples/cpp/dds/DiscoveryServerExample/DiscoveryServerSubscriber.h
  examples/cpp/dds/LivelinessQoS/LivelinessSubscriber.h
  examples/cpp/rtps/Persistent/TestReaderPersistent.h
  examples/cpp/rtps/Persistent/TestWriterPersistent.h
  examples/cpp/rtps/Registered/TestReaderRegistered.h
  examples/cpp/rtps/Registered/TestWriterRegistered.h
  include/fastrtps/subscriber/SubscriberHistory.h
  src/cpp/fastdds/domain/DomainParticipantImpl.hpp
  src/cpp/fastdds/publisher/DataWriterImpl.hpp
  src/cpp/fastdds/subscriber/DataReaderImpl.hpp
  src/cpp/fastrtps_deprecated/participant/ParticipantImpl.h
  src/cpp/fastrtps_deprecated/publisher/PublisherImpl.h
  src/cpp/fastrtps_deprecated/subscriber/SubscriberImpl.h
  src/cpp/rtps/DataSharing/ReaderPool.hpp
  src/cpp/rtps/DataSharing/WriterPool.hpp
  src/cpp/rtps/builtin/discovery/participant/PDPClient.h
  src/cpp/rtps/builtin/discovery/participant/PDPServer.hpp
  src/cpp/rtps/builtin/discovery/participant/timedevent/DSClientEvent.cpp
  src/cpp/rtps/history/BasicPayloadPool_impl/Base.hpp
  src/cpp/rtps/history/BasicPayloadPool_impl/PreallocatedWithRealloc.hpp
  src/cpp/rtps/history/TopicPayloadPool_impl/Dynamic.hpp
  src/cpp/rtps/history/TopicPayloadPool_impl/DynamicReusable.hpp
  src/cpp/rtps/history/TopicPayloadPool_impl/Preallocated.hpp
  src/cpp/rtps/history/TopicPayloadPool_impl/PreallocatedWithRealloc.hpp
  src/cpp/rtps/transport/TCPTransportInterface.h
  src/cpp/rtps/transport/UDPTransportInterface.h
  src/cpp/rtps/transport/shared_mem/SharedMemTransport.h
  src/cpp/statistics/rtps/monitor-service/MonitorServiceListener.hpp
  test/blackbox/api/dds-pim/PubSubParticipant.hpp
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/blackbox/api/dds-pim/PubSubWriter.hpp
  test/blackbox/api/dds-pim/PubSubWriterReader.hpp
  test/blackbox/common/DDSBlackboxTestsBasic.cpp
  test/blackbox/common/DDSBlackboxTestsDataRepresentationQos.cpp
  test/blackbox/common/DDSBlackboxTestsDiscovery.cpp
  test/blackbox/common/DDSBlackboxTestsFindTopic.cpp
  test/blackbox/common/RTPSWithRegistrationReader.hpp
  test/blackbox/common/RTPSWithRegistrationWriter.hpp
  test/dds/communication/PublisherDynamic.cpp
  test/dds/communication/PublisherModule.hpp
  test/dds/communication/SubscriberDynamic.cpp
  test/dds/communication/SubscriberModule.hpp
  test/dds/discovery/ParticipantModule.hpp
  test/performance/latency/LatencyTestTypes.hpp
  test/performance/throughput/ThroughputTypes.hpp
  test/unittest/dds/participant/ParticipantTests.cpp
  test/unittest/dds/publisher/DataWriterTests.cpp
  test/unittest/dds/publisher/PublisherTests.cpp
  test/unittest/dds/status/ListenerTests.cpp
  test/unittest/dds/subscriber/DataReaderHistoryTests.cpp
  test/unittest/dds/subscriber/DataReaderTests.cpp
  test/unittest/dds/subscriber/FooBoundedTypeSupport.hpp
  test/unittest/dds/subscriber/FooTypeSupport.hpp
  test/unittest/dds/topic/TopicTests.cpp
  test/unittest/statistics/dds/StatisticsDomainParticipantStatusQueryableTests.cpp
  test/unittest/statistics/dds/StatisticsDomainParticipantTests.cpp
Labels: ready-to-merge
