Repository eProsima/Fast-DDS, pull requests merged in 2024-12, with the labels that each got.

#5458 Refs #21560: Update `RELEASE_SUPPORT` ref to 2.14.4
  RELEASE_SUPPORT.md
Labels: skip-ci

#5440 [22343] Bugfix: Add pointer sanity check before accessing `ParticipantProxyData`
  src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
Labels: ci-pending

#5450 [22353] Use correct algorithm strings on PermissionsToken and IdentityToken
  src/cpp/security/accesscontrol/Permissions.cpp
  src/cpp/security/authentication/PKIDH.cpp
  src/cpp/security/authentication/PKIIdentityHandle.h
  test/blackbox/common/BlackboxTestsSecurity.cpp
Labels: ci-pending

#5461 [22055] Fix unique network flows with TCP transports
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  test/blackbox/api/dds-pim/PubSubParticipant.hpp
  test/blackbox/common/BlackboxTestsTransportTCP.cpp
Labels: ready-to-merge

#5480 [21660] Add `flow_control`, `rtps`, `custom_payload_pool` and `content_filter` to windows example ci testing
  examples/cpp/content_filter/CLIParser.hpp
  examples/cpp/content_filter/SubscriberApp.cpp
  examples/cpp/content_filter/SubscriberApp.hpp
  examples/cpp/rtps/CLIParser.hpp
  examples/cpp/rtps/WriterApp.cpp
  examples/cpp/rtps/WriterApp.hpp
  test/examples/CMakeLists.txt
  test/examples/content_filter.compose.yml
  test/examples/custom_payload_pool.compose.yml
  test/examples/rtps.compose.yml
  test/examples/test_content_filter.py
  test/examples/test_custom_payload_pool.py
  test/examples/test_flow_control.py
  test/examples/test_rtps.py
Labels: ci-pending

#5432 [22339] Fix tsan potential deadlock between `StatefulWriter` and `FlowController`
  src/cpp/rtps/writer/StatefulWriter.cpp
  test/blackbox/common/DDSBlackboxTestsBasic.cpp
Labels: ci-pending

#5460 [22321] Benchmark example updated
  examples/CMakeLists.txt
  examples/cpp/benchmark/Application.cpp
  examples/cpp/benchmark/Application.hpp
  examples/cpp/benchmark/CLIParser.hpp
  examples/cpp/benchmark/CMakeLists.txt
  examples/cpp/benchmark/PublisherApp.cpp
  examples/cpp/benchmark/PublisherApp.hpp
  examples/cpp/benchmark/README.md
  examples/cpp/benchmark/SubscriberApp.cpp
  examples/cpp/benchmark/SubscriberApp.hpp
  examples/cpp/benchmark/benchmark_profile.xml
  examples/cpp/benchmark/main.cpp
  examples/cpp/benchmark/types/Benchmark.hpp
  examples/cpp/benchmark/types/Benchmark.idl
  examples/cpp/benchmark/types/BenchmarkCdrAux.hpp
  examples/cpp/benchmark/types/BenchmarkCdrAux.ipp
  examples/cpp/benchmark/types/BenchmarkPubSubTypes.cxx
  examples/cpp/benchmark/types/BenchmarkPubSubTypes.hpp
  examples/cpp/benchmark/types/BenchmarkTypeObjectSupport.cxx
  examples/cpp/benchmark/types/BenchmarkTypeObjectSupport.hpp
  examples/cpp/benchmark/types/Benchmark_big.hpp
  examples/cpp/benchmark/types/Benchmark_big.idl
  examples/cpp/benchmark/types/Benchmark_bigCdrAux.hpp
  examples/cpp/benchmark/types/Benchmark_bigCdrAux.ipp
  examples/cpp/benchmark/types/Benchmark_bigPubSubTypes.cxx
  examples/cpp/benchmark/types/Benchmark_bigPubSubTypes.hpp
  examples/cpp/benchmark/types/Benchmark_bigTypeObjectSupport.cxx
  examples/cpp/benchmark/types/Benchmark_bigTypeObjectSupport.hpp
  examples/cpp/benchmark/types/Benchmark_medium.hpp
  examples/cpp/benchmark/types/Benchmark_medium.idl
  examples/cpp/benchmark/types/Benchmark_mediumCdrAux.hpp
  examples/cpp/benchmark/types/Benchmark_mediumCdrAux.ipp
  examples/cpp/benchmark/types/Benchmark_mediumPubSubTypes.cxx
  examples/cpp/benchmark/types/Benchmark_mediumPubSubTypes.hpp
  examples/cpp/benchmark/types/Benchmark_mediumTypeObjectSupport.cxx
  examples/cpp/benchmark/types/Benchmark_mediumTypeObjectSupport.hpp
  examples/cpp/benchmark/types/Benchmark_small.hpp
  examples/cpp/benchmark/types/Benchmark_small.idl
  examples/cpp/benchmark/types/Benchmark_smallCdrAux.hpp
  examples/cpp/benchmark/types/Benchmark_smallCdrAux.ipp
  examples/cpp/benchmark/types/Benchmark_smallPubSubTypes.cxx
  examples/cpp/benchmark/types/Benchmark_smallPubSubTypes.hpp
  examples/cpp/benchmark/types/Benchmark_smallTypeObjectSupport.cxx
  examples/cpp/benchmark/types/Benchmark_smallTypeObjectSupport.hpp
  test/examples/benchmark.compose.yml
  test/examples/test_benchmark.py
  versions.md
Labels: ready-to-merge

#5503 [22497] Regenerate types with Fast DDS Gen 4.0.3
  examples/cpp/benchmark/types/Benchmark.hpp
  examples/cpp/benchmark/types/Benchmark_big.hpp
  examples/cpp/benchmark/types/Benchmark_medium.hpp
  examples/cpp/benchmark/types/Benchmark_small.hpp
  examples/cpp/configuration/ConfigurationPubSubTypes.cxx
  examples/cpp/content_filter/HelloWorldPubSubTypes.cxx
  examples/cpp/custom_payload_pool/HelloWorldPubSubTypes.cxx
  examples/cpp/delivery_mechanisms/DeliveryMechanismsPubSubTypes.cxx
  examples/cpp/discovery_server/HelloWorldPubSubTypes.cxx
  examples/cpp/flow_control/FlowControlPubSubTypes.cxx
  examples/cpp/hello_world/HelloWorldPubSubTypes.cxx
  examples/cpp/request_reply/types/CalculatorPubSubTypes.cxx
  examples/cpp/security/HelloWorldPubSubTypes.cxx
  examples/cpp/static_edp_discovery/HelloWorldPubSubTypes.cxx
  examples/cpp/topic_instances/ShapeTypePubSubTypes.cxx
  src/cpp/fastdds/builtin/type_lookup_service/detail/TypeLookupTypesPubSubTypes.cxx
  src/cpp/fastdds/builtin/type_lookup_service/detail/rpc_typesPubSubTypes.cxx
  src/cpp/fastdds/xtypes/type_representation/dds_xtypes_typeobjectPubSubTypes.cxx
  src/cpp/statistics/types/monitorservice_typesPubSubTypes.cxx
  src/cpp/statistics/types/typesPubSubTypes.cxx
  test/blackbox/types/Data1mbPubSubTypes.cxx
  test/blackbox/types/Data64kbPubSubTypes.cxx
  test/blackbox/types/FixedSizedPubSubTypes.cxx
  test/blackbox/types/HelloWorldPubSubTypes.cxx
  test/blackbox/types/KeyedData1mbPubSubTypes.cxx
  test/blackbox/types/KeyedHelloWorldPubSubTypes.cxx
  test/blackbox/types/StringTestPubSubTypes.cxx
  test/blackbox/types/TestRegression3361PubSubTypes.cxx
  test/blackbox/types/UnboundedHelloWorldPubSubTypes.cxx
  test/blackbox/types/core/core_typesPubSubTypes.cxx
  test/blackbox/types/statistics/monitorservice_typesPubSubTypes.cxx
  test/blackbox/types/statistics/typesPubSubTypes.cxx
  test/dds/xtypes/BaseCasesIDLs/XtypesTestsType1PubSubTypes.cxx
  test/dds/xtypes/BaseCasesIDLs/XtypesTestsType2PubSubTypes.cxx
  test/dds/xtypes/BaseCasesIDLs/XtypesTestsType3PubSubTypes.cxx
  test/dds/xtypes/BaseCasesIDLs/XtypesTestsTypeBigPubSubTypes.cxx
  test/dds/xtypes/BaseCasesIDLs/XtypesTestsTypeDepPubSubTypes.cxx
  test/dds/xtypes/BaseCasesIDLs/XtypesTestsTypeNoTypeObjectPubSubTypes.cxx
  test/profiling/allocations/AllocTestTypePubSubTypes.cxx
  test/unittest/dds/topic/DDSSQLFilter/data_types/ContentFilterTestTypePubSubTypes.cxx
  test/unittest/dds/xtypes/serializers/idl/types/alias_struct/gen/alias_structPubSubTypes.cxx
  test/unittest/dds/xtypes/serializers/idl/types/array_struct/gen/array_structPubSubTypes.cxx
  test/unittest/dds/xtypes/serializers/idl/types/bitmask_struct/gen/bitmask_structPubSubTypes.cxx
  test/unittest/dds/xtypes/serializers/idl/types/bitset_struct/gen/bitset_structPubSubTypes.cxx
  test/unittest/dds/xtypes/serializers/idl/types/enum_struct/gen/enum_structPubSubTypes.cxx
  test/unittest/dds/xtypes/serializers/idl/types/extensibility_struct/gen/extensibility_structPubSubTypes.cxx
  test/unittest/dds/xtypes/serializers/idl/types/key_struct/gen/key_structPubSubTypes.cxx
  test/unittest/dds/xtypes/serializers/idl/types/map_struct/gen/map_structPubSubTypes.cxx
  test/unittest/dds/xtypes/serializers/idl/types/primitives_struct/gen/primitives_structPubSubTypes.cxx
  test/unittest/dds/xtypes/serializers/idl/types/sequence_struct/gen/sequence_structPubSubTypes.cxx
  test/unittest/dds/xtypes/serializers/idl/types/string_struct/gen/string_structPubSubTypes.cxx
  test/unittest/dds/xtypes/serializers/idl/types/struct_struct/gen/struct_structPubSubTypes.cxx
  test/unittest/dds/xtypes/serializers/idl/types/union_struct/gen/union_structPubSubTypes.cxx
  test/unittest/dds/xtypes/serializers/json/types/comprehensive_type/gen/ComprehensiveTypePubSubTypes.cxx
Labels: ci-pending

#5459 [21433] Improve PDPClients initialization
  src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  test/unittest/dds/participant/ParticipantTests.cpp
Labels: ready-to-merge

#5493 [22463] Fix Discovery CLI Tool in Windows (No privileges)
  .github/workflows/reusable-mac-ci.yml
  .github/workflows/reusable-ubuntu-ci.yml
  .github/workflows/reusable-windows-ci.yml
  test/system/tools/fastdds/CMakeLists.txt
  test/system/tools/fastdds/tests.py
  tools/fastdds/discovery/parser.py
  tools/fds/CMakeLists.txt
  tools/fds/fast-discovery-server.bat.in
Labels: ready-to-merge

#5464 [22438] Arithmetic overflow in fragment size calculations
  src/cpp/rtps/history/WriterHistory.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/writer/BaseWriter.cpp
  test/blackbox/common/DDSBlackboxTestsListeners.cpp
  test/unittest/rtps/history/CMakeLists.txt
  test/unittest/rtps/history/WriterHistoryTests.cpp
Labels: ready-to-merge

#5499 [22101] Addres `parseXMLMemberDynamicType` regression
  src/cpp/xmlparser/XMLDynamicParser.cpp
  test/unittest/xmlparser/XMLParserTests.cpp
  test/unittest/xmlparser/regressions/22101_profile_bin.xml
Labels: ci-pending
