Repository eProsima/Fast-DDS, pull requests merged in 2024-04, with the labels that each got.

#4638 [20714] Refactor Statistics module IDL
  examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfiguration.h
  examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfigurationv1.h
  examples/cpp/dds/BasicConfigurationExample/HelloWorld.h
  examples/cpp/dds/ContentFilteredTopicExample/HelloWorld.h
  examples/cpp/dds/CustomPayloadPoolExample/CustomPayloadPoolData.h
  examples/cpp/dds/DeadlineQoSExample/deadlinepayloadv1.cxx
  examples/cpp/dds/DiscoveryServerExample/types/HelloWorld.h
  examples/cpp/dds/Filtering/FilteringExample.h
  examples/cpp/dds/FlowControlExample/FlowControlExample.h
  examples/cpp/dds/HelloWorldExample/HelloWorld.h
  examples/cpp/dds/HelloWorldExample/HelloWorldv1.h
  examples/cpp/dds/HelloWorldExampleSharedMem/HelloWorld.h
  examples/cpp/dds/OwnershipStrengthQoSExample/OwnershipStrength.h
  examples/cpp/dds/RequestReplyExample/Calculator.h
  examples/cpp/dds/SecureHelloWorldExample/HelloWorld.h
  examples/cpp/dds/StaticHelloWorldExample/HelloWorld.h
  examples/cpp/dds/WriterLoansExample/LoanableHelloWorld.h
  examples/cpp/dds/ZeroCopyExample/LoanableHelloWorld.h
  examples/cpp/dds/ZeroCopyExample/LoanableHelloWorldPubSubTypes.h
  include/fastdds/statistics/types.idl
  src/cpp/statistics/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/statistics/fastdds/domain/DomainParticipantImpl.hpp
  src/cpp/statistics/fastdds/domain/DomainParticipantStatisticsListener.cpp
  src/cpp/statistics/fastdds/domain/DomainParticipantStatisticsListener.hpp
  src/cpp/statistics/rtps/GuidUtils.hpp
  src/cpp/statistics/rtps/StatisticsBase.cpp
  src/cpp/statistics/rtps/reader/StatisticsReaderImpl.cpp
  src/cpp/statistics/rtps/writer/StatisticsWriterImpl.cpp
  src/cpp/statistics/types/monitorservice_typesPubSubTypes.h
  src/cpp/statistics/types/monitorservice_typesv1.cxx
  src/cpp/statistics/types/monitorservice_typesv1.h
  src/cpp/statistics/types/types.cxx
  src/cpp/statistics/types/types.h
  src/cpp/statistics/types/typesCdrAux.hpp
  src/cpp/statistics/types/typesCdrAux.ipp
  src/cpp/statistics/types/typesPubSubTypes.cxx
  src/cpp/statistics/types/typesPubSubTypes.h
  src/cpp/statistics/types/typesv1.cxx
  src/cpp/statistics/types/typesv1.h
  test/blackbox/types/FixedSizedPubSubTypes.h
  test/blackbox/types/KeyedHelloWorldv1.cxx
  test/blackbox/types/UnboundedHelloWorldv1.h
  test/blackbox/types/statistics/monitorservice_types.h
  test/blackbox/types/statistics/monitorservice_typesPubSubTypes.h
  test/blackbox/types/statistics/monitorservice_typesv1.cxx
  test/blackbox/types/statistics/monitorservice_typesv1.h
  test/blackbox/types/statistics/types.cxx
  test/blackbox/types/statistics/types.h
  test/blackbox/types/statistics/typesCdrAux.hpp
  test/blackbox/types/statistics/typesCdrAux.ipp
  test/blackbox/types/statistics/typesPubSubTypes.cxx
  test/blackbox/types/statistics/typesPubSubTypes.h
  test/blackbox/types/statistics/typesv1.cxx
  test/blackbox/types/statistics/typesv1.h
  test/unittest/dynamic_types/idl/Testv1.cxx
  test/unittest/dynamic_types/idl/new_features_4_2.h
  test/unittest/statistics/dds/DomainParticipantStatisticsListenerTests.cpp
  test/unittest/statistics/rtps/RTPSStatisticsTests.cpp
  test/unittest/xtypes/idl/WideEnum.h
Labels: ready-to-merge

#4628 [20694] Build Fast DDS Python bindings in Fast DDS Docs Github CI job
  .github/workflows/documentation-tests.yaml
Labels: ci-pending

#4635 [20701] Enforce SHM ports open mode exclusions
  src/cpp/rtps/transport/shared_mem/SharedMemGlobal.hpp
  test/blackbox/common/BlackboxTestsTransportSHM.cpp
  test/unittest/transport/SharedMemTests.cpp
Labels: ci-pending

#4617 [20722] Force unlimited ResourceLimits if lower or equal to zero
  include/fastdds/dds/core/policy/QosPolicies.hpp
  src/cpp/fastdds/publisher/DataWriterHistory.cpp
  src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
  src/cpp/fastrtps_deprecated/publisher/PublisherHistory.cpp
  src/cpp/fastrtps_deprecated/subscriber/SubscriberHistory.cpp
  test/mock/rtps/PublisherHistory/fastdds/publisher/DataWriterHistory.hpp
  test/mock/rtps/PublisherHistory/fastrtps/publisher/PublisherHistory.h
  test/performance/throughput/ThroughputPublisher.cpp
  test/performance/throughput/ThroughputSubscriber.cpp
  test/unittest/dds/publisher/DataWriterTests.cpp
  test/unittest/dds/subscriber/DataReaderTests.cpp
  test/unittest/dds/topic/TopicTests.cpp
Labels: ci-pending

#4639 [20729] Allow processing of AckNack submessages with count == 0
  include/fastdds/rtps/writer/ReaderProxy.h
  src/cpp/rtps/writer/ReaderProxy.cpp
  test/unittest/rtps/writer/ReaderProxyTests.cpp
Labels: ready-to-merge

#4584 [20628] Fix Discovery Server over TCP using logical port
  src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.h
  src/cpp/rtps/transport/TCPTransportInterface.cpp
  test/blackbox/common/DDSBlackboxTestsDiscovery.cpp
Labels: ready-to-merge, first-to-merge

#4648 [20723] Bump version to v2.13.4
  CMakeLists.txt
  package.xml
  versions.md
Labels: ready-to-merge, skip-ci

#4658 [20750] Add check for XML API to PR template
  .github/pull_request_template.md
Labels: skip-ci

#4650 [20652] Fix test filtering in CMake files
  cmake/common/gtest.cmake
  test/CMakeLists.txt
  test/blackbox/CMakeLists.txt
  test/unittest/dds/participant/CMakeLists.txt
  test/unittest/utils/CMakeLists.txt
Labels: no-test, ci-pending

#4586 [20628] Fix Discovery Server over TCP using LocatorSelectorEntry
  include/fastdds/rtps/common/LocatorSelectorEntry.hpp
  src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
  src/cpp/rtps/network/NetworkFactory.cpp
  src/cpp/rtps/network/NetworkFactory.h
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.h
  src/cpp/rtps/transport/TCPTransportInterface.cpp
  src/cpp/rtps/transport/TCPTransportInterface.h
  test/blackbox/common/DDSBlackboxTestsDiscovery.cpp
Labels: ci-pending

#4662 [20542] Refactor Github CI sanitizer related jobs
  .github/workflows/address-sanitizers.yaml
  .github/workflows/config/asan_colcon.meta
  .github/workflows/nightly-sanitizers-ci.yml
  .github/workflows/reusable-sanitizers-ci.yml
  .github/workflows/sanitizers-ci.yml
  .github/workflows/thread-sanitizer.yaml
Labels: ready-to-merge

#4636 [20653] Increase sleep to miss the deadline in macOS flaky tests
  test/blackbox/common/DDSBlackboxTestsOwnershipQos.cpp
Labels: ready-to-merge

#4682 [20705] Fix nightly sanitizer CI workflow name
  .github/workflows/nightly-sanitizers-ci.yml
Labels: skip-ci

#4685 [20732] Improve xml loading method in fuzz_XMLProfiles
  fuzz/C++/fuzz_XMLProfiles/fuzz_XMLProfiles.cxx
  fuzz/C++/fuzz_XMLProfiles/fuzz_utils.cxx
  fuzz/C++/fuzz_XMLProfiles/fuzz_utils.h
Labels: skip-ci

#4678 [20786] Build ShapesDemo on Ubuntu Github CI
  .github/workflows/reusable-ubuntu-ci.yml
Labels: no-test, ci-pending

#3440 [18002] Internal refactor on port handling
  src/cpp/rtps/network/NetworkFactory.cpp
  src/cpp/rtps/network/NetworkFactory.h
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.h
  test/blackbox/common/BlackboxTestsTransportSHM.cpp
Labels: ready-to-merge

#4693 Removed warning
  src/cpp/fastdds/core/policy/ParameterList.cpp
Labels: ready-to-merge

#4695 [20848] Correctly set branches for reusable-sanitizers-ci
  .github/workflows/nightly-sanitizers-ci.yml
Labels: ready-to-merge

#4696 [20706] Make reader get_first_untaken_info() coherent with read()/take()
  include/fastdds/dds/subscriber/DataReader.hpp
  src/cpp/fastdds/subscriber/DataReaderImpl.hpp
  src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
  test/blackbox/common/DDSBlackboxTestsDataReader.cpp
Labels: ci-pending

#4670 MonitorService fails serializing Data(w)/Data(r) in some cases [20772]
  src/cpp/rtps/builtin/data/ReaderProxyData.cpp
  src/cpp/rtps/builtin/data/WriterProxyData.cpp
Labels: ci-pending

#4720 [20706] Bugfix in DDSBlackboxTestsDataReader test
  test/blackbox/common/DDSBlackboxTestsDataReader.cpp
Labels: skip-ci

#4673 [20658] Fix leak in `SecurityManager::participant_volatile_message_secure_writer_`
  src/cpp/rtps/security/SecurityManager.cpp
  src/cpp/rtps/security/SecurityManager.h
  test/blackbox/common/BlackboxTestsSecurity.cpp
  test/unittest/rtps/security/SecurityHandshakeProcessTests.cpp
  test/unittest/rtps/security/SecurityTests.cpp
  test/unittest/rtps/security/SecurityTests.hpp
  test/unittest/rtps/security/SecurityValidationRemoteTests.cpp
Labels: ci-pending

#4717 [20732] Fix some leaks in XML DynamicTypes Parser
  include/fastrtps/xmlparser/XMLProfileManager.h
  src/cpp/rtps/xmlparser/XMLDynamicParser.cpp
  src/cpp/rtps/xmlparser/XMLProfileManager.cpp
  test/unittest/xmlparser/XMLParserTests.cpp
  test/unittest/xmlparser/regressions/20732_profile_bin.xml
Labels: ci-pending

#4718 [20824] Bump version to v2.6.8
  CMakeLists.txt
  package.xml
  versions.md
Labels: skip-ci

#4694 [20733] Fix support for @key annotation in Dynamic types
  include/fastrtps/types/MemberDescriptor.h
  include/fastrtps/xmlparser/XMLProfileManager.h
  resources/xsd/fastRTPS_profiles.xsd
  src/cpp/dynamic-types/AnnotationDescriptor.cpp
  src/cpp/dynamic-types/DynamicType.cpp
  src/cpp/dynamic-types/MemberDescriptor.cpp
  src/cpp/rtps/xmlparser/XMLDynamicParser.cpp
  src/cpp/rtps/xmlparser/XMLProfileManager.cpp
  test/system/tools/xmlvalidation/XMLTesterExample_profile.xml
  test/system/tools/xmlvalidation/all_profile.xml
  test/system/tools/xmlvalidation/types_profile.xml
  test/unittest/dynamic_types/DynamicTypesTests.cpp
  test/unittest/dynamic_types/types_profile.xml
Labels: skip-ci
