Repository eProsima/Fast-DDS, pull requests merged in 2024-08, with the labels that each got.

#5118 [19036] Discard local SHM locators that cannot be openned
  include/fastdds/rtps/transport/ChainingTransport.hpp
  include/fastdds/rtps/transport/TransportInterface.hpp
  src/cpp/rtps/builtin/data/ParticipantProxyData.cpp
  src/cpp/rtps/builtin/data/ParticipantProxyData.hpp
  src/cpp/rtps/builtin/data/ProxyDataFilters.hpp
  src/cpp/rtps/builtin/data/ReaderProxyData.cpp
  src/cpp/rtps/builtin/data/ReaderProxyData.hpp
  src/cpp/rtps/builtin/data/WriterProxyData.cpp
  src/cpp/rtps/builtin/data/WriterProxyData.hpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPSimpleListeners.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPListener.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServerListener.cpp
  src/cpp/rtps/network/NetworkFactory.cpp
  src/cpp/rtps/network/NetworkFactory.hpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.h
  src/cpp/rtps/security/SecurityManager.cpp
  src/cpp/rtps/transport/TCPv4Transport.cpp
  src/cpp/rtps/transport/TCPv4Transport.h
  src/cpp/rtps/transport/TCPv6Transport.cpp
  src/cpp/rtps/transport/TCPv6Transport.h
  src/cpp/rtps/transport/UDPv4Transport.cpp
  src/cpp/rtps/transport/UDPv4Transport.h
  src/cpp/rtps/transport/UDPv6Transport.cpp
  src/cpp/rtps/transport/UDPv6Transport.h
  src/cpp/rtps/transport/shared_mem/SharedMemTransport.cpp
  src/cpp/rtps/transport/shared_mem/SharedMemTransport.h
  test/mock/rtps/NetworkFactory/rtps/network/NetworkFactory.hpp
  test/mock/rtps/RTPSParticipantImpl/rtps/participant/RTPSParticipantImpl.h
  test/mock/rtps/ReaderProxyData/rtps/builtin/data/ReaderProxyData.hpp
  test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
  test/unittest/rtps/network/NetworkFactoryTests.cpp
  test/unittest/rtps/network/mock/MockTransport.cpp
  test/unittest/rtps/network/mock/MockTransport.h
  test/unittest/transport/TCPv6Tests.cpp
Labels: ci-pending

#5137 [21366] Update roadmap, release support and platform support docs
  PLATFORM_SUPPORT.md
  RELEASE_SUPPORT.md
  roadmap.md
Labels: ready-to-merge, skip-ci

#5142 [21469] Fix windows issue with flow controller example
  examples/cpp/flow_control/CMakeLists.txt
  examples/cpp/flow_control/FlowControl.idl
  examples/cpp/flow_control/FlowControlTypeObjectSupport.cxx
  examples/cpp/flow_control/PublisherApp.cpp
  examples/cpp/flow_control/PublisherApp.hpp
  examples/cpp/rtps/CLIParser.hpp
Labels: ci-pending

#5152 [21366] Address some warnings when generating windows installer for v3.0.0
  include/fastdds/config/doxygen_modules.hpp
  include/fastdds/rtps/attributes/RTPSParticipantAttributes.hpp
  include/fastdds/rtps/builtin/data/ContentFilterProperty.hpp
  src/cpp/rtps/transport/shared_mem/SharedMemTransport.cpp
  test/mock/rtps/RTPSParticipantAttributes/fastdds/rtps/attributes/RTPSParticipantAttributes.hpp
Labels: ready-to-merge, no-test

#5149 [21470] Apply @Blast545 contribution: Add unsigned specification to literals (#5125)
  include/fastdds/rtps/common/InstanceHandle.h
Labels: ready-to-merge, no-test

#5163 [21442] Fix warning in oss fuzz build
  src/cpp/rtps/messages/MessageReceiver.cpp
Labels: ready-to-merge, no-test

#5173 [21495] Remove unexisting links in example READMEs
  examples/cpp/discovery_server/README.md
  examples/cpp/xtypes/README.md
Labels: skip-ci

#5141 [21366] Bump versions to v3.0.0
  README.md
  versions.md
Labels: skip-ci, last-to-merge

#5071 [20181] Hotfix: Secure simple participants with `initialpeers` over `TCP` match
  src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPSimple.h
  test/blackbox/common/BlackboxTestsSecurity.cpp
Labels: ready-to-merge
