Repository eProsima/Fast-DDS, pull requests merged in 2024-01, with the labels that each got.

#4188 [20166] Fix data race in PDPListener and SecurityManager
  src/cpp/rtps/builtin/discovery/participant/DS/PDPSecurityInitiatorListener.cpp
  src/cpp/rtps/security/SecurityManager.cpp
  test/blackbox/common/BlackboxTestsSecurity.cpp
Labels: ready-to-merge

#4211 Fix DNS filter in CMakeLists file
  test/unittest/dds/participant/CMakeLists.txt
Labels: no-test

#4215 [20215] Update PR checklist template. Backports and Description
  .github/pull_request_template.md
Labels: skip-ci

#4219 [20176] Update versions.md
  versions.md
Labels: ready-to-merge, skip-ci

#4218 [20176] Downgrade cmake version
  CMakeLists.txt
  cmake/testing/GoogleTest.cmake
  examples/cpp/dds/AdvancedConfigurationExample/CMakeLists.txt
  examples/cpp/dds/BasicConfigurationExample/CMakeLists.txt
  examples/cpp/dds/Configurability/CMakeLists.txt
  examples/cpp/dds/ContentFilteredTopicExample/CMakeLists.txt
  examples/cpp/dds/CustomListenerExample/CMakeLists.txt
  examples/cpp/dds/CustomPayloadPoolExample/CMakeLists.txt
  examples/cpp/dds/DeadlineQoSExample/CMakeLists.txt
  examples/cpp/dds/DisablePositiveACKs/CMakeLists.txt
  examples/cpp/dds/DiscoveryServerExample/CMakeLists.txt
  examples/cpp/dds/DynamicHelloWorldExample/CMakeLists.txt
  examples/cpp/dds/Filtering/CMakeLists.txt
  examples/cpp/dds/FlowControlExample/CMakeLists.txt
  examples/cpp/dds/HelloWorldExample/CMakeLists.txt
  examples/cpp/dds/HelloWorldExampleDataSharing/CMakeLists.txt
  examples/cpp/dds/HelloWorldExampleSharedMem/CMakeLists.txt
  examples/cpp/dds/HelloWorldExampleTCP/CMakeLists.txt
  examples/cpp/dds/HistoryKind/CMakeLists.txt
  examples/cpp/dds/Keys/CMakeLists.txt
  examples/cpp/dds/LateJoiners/CMakeLists.txt
  examples/cpp/dds/LifespanQoSExample/CMakeLists.txt
  examples/cpp/dds/LivelinessQoS/CMakeLists.txt
  examples/cpp/dds/OwnershipStrengthQoSExample/CMakeLists.txt
  examples/cpp/dds/RequestReplyExample/CMakeLists.txt
  examples/cpp/dds/SampleConfig_Controller/CMakeLists.txt
  examples/cpp/dds/SampleConfig_Events/CMakeLists.txt
  examples/cpp/dds/SampleConfig_Multimedia/CMakeLists.txt
  examples/cpp/dds/SecureHelloWorldExample/CMakeLists.txt
  examples/cpp/dds/StaticHelloWorldExample/CMakeLists.txt
  examples/cpp/dds/TypeLookupService/CMakeLists.txt
  examples/cpp/dds/WriterLoansExample/CMakeLists.txt
  examples/cpp/dds/ZeroCopyExample/CMakeLists.txt
  examples/cpp/rtps/AsSocket/CMakeLists.txt
  examples/cpp/rtps/Persistent/CMakeLists.txt
  examples/cpp/rtps/Registered/CMakeLists.txt
  fuzz/C++/fuzz_XMLProfiles/CMakeLists.txt
  fuzz/C++/fuzz_processCDRMsg/CMakeLists.txt
  test/CMakeLists.txt
  test/profiling/allocations/CMakeLists.txt
  test/unittest/cmake/force_cxx/CMakeLists.txt
  thirdparty/optionparser/CMakeLists.txt
  tools/fds/CMakeLists.txt
Labels: skip-ci, first-to-merge

#4227 [20022] Fix Github Windows CI (backport #3616)
  test/communication/multiple_secure_ds_pubsub_secure_crypto_communication.py
  test/communication/secure_ds_pubsub_secure_crypto_communication.py
Labels: ci-pending

#4177 [20130] Implement TypeLookupManager async_get_type
  include/fastdds/rtps/builtin/BuiltinProtocols.h
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupManager.cpp
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupManager.hpp
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupReplyListener.cpp
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupReplyListener.hpp
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupRequestListener.cpp
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupRequestListener.hpp
  src/cpp/fastdds/xtypes/type_representation/TypeIdentifierWithSizeHashSpecialization.h
  src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.cpp
  src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.hpp
  src/cpp/rtps/builtin/BuiltinProtocols.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPSimpleListeners.cpp
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.h
  test/mock/rtps/BuiltinProtocols/fastdds/rtps/builtin/BuiltinProtocols.h
  test/mock/rtps/TypeLookupManager/fastdds/builtin/type_lookup_service/TypeLookupManager.hpp
  test/unittest/dds/status/ListenerTests.cpp
  test/unittest/rtps/discovery/PDPTests.cpp
Labels: no-test, doc-pending

#4236 [20236] Improve environment variable substitution algorithm
  src/cpp/rtps/xmlparser/XMLElementParser.cpp
  test/unittest/xmlparser/XMLParserTests.cpp
  test/unittest/xmlparser/regressions/20186_profile_bin.xml
Labels: ready-to-merge

#4210 Add static cast to unused variable in RTPSParticipantAttributes
  src/cpp/rtps/attributes/RTPSParticipantAttributes.cpp
Labels: no-test

#4248 [20255] Fix max clash with Windows CI
  .github/workflows/reusable-windows-ci.yml
  include/fastdds/rtps/messages/CDRMessage.hpp
  include/fastdds/rtps/security/logging/Logging.h
  include/fastrtps/utils/fixed_size_bitmap.hpp
  src/cpp/fastdds/subscriber/history/DataReaderInstance.hpp
  src/cpp/rtps/DataSharing/WriterPool.hpp
  src/cpp/rtps/builtin/liveliness/WLP.cpp
  src/cpp/rtps/flowcontrol/FlowControllerImpl.hpp
  src/cpp/rtps/history/CacheChangePool.cpp
  src/cpp/rtps/history/TopicPayloadPool.cpp
  src/cpp/rtps/network/NetworkFactory.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/reader/StatefulReader.cpp
  src/cpp/rtps/reader/StatelessReader.cpp
  src/cpp/rtps/security/logging/Logging.cpp
  src/cpp/rtps/transport/shared_mem/test_SharedMemTransport.cpp
  src/cpp/security/cryptography/AESGCMGMAC_KeyFactory.cpp
  src/cpp/security/cryptography/AESGCMGMAC_Types.h
  test/unittest/dds/topic/DDSSQLFilter/DDSSQLFilterTests.cpp
  test/unittest/utils/BitmapRangeTests.cpp
  test/unittest/xmlparser/XMLProfileParserTests.cpp
Labels: no-test

#4250 [20023] Bump version to v2.10.3
  CMakeLists.txt
  package.xml
  versions.md
Labels: skip-ci

#4217 [20121] Remove unnecessary TCP warning
  src/cpp/rtps/transport/TCPTransportInterface.cpp
Labels: ci-pending

#4268 [20276] Discard already processed samples on PDPListener
  include/fastdds/rtps/builtin/data/ParticipantProxyData.h
  src/cpp/rtps/builtin/data/ParticipantProxyData.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPListener.cpp
Labels: ready-to-merge, skip-ci

#4291 [20306] Ignore 0x8007 if coming from other vendor
  src/cpp/rtps/builtin/data/ParticipantProxyData.cpp
  test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
Labels: no-test, ci-pending

#4271 [20283] Return const reference in get_log_resources
  src/cpp/fastdds/log/Log.cpp
  src/cpp/fastdds/log/LogResources.hpp
Labels: ready-to-merge

#4261 [20257] Add a keyed fragmented change to the reader data instance only when its completed
  src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
  src/cpp/rtps/reader/StatefulReader.cpp
  src/cpp/rtps/reader/StatelessReader.cpp
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
  test/blackbox/common/BlackboxTestsPubSubFragments.cpp
Labels: ready-to-merge

#4294 [19452] Include CI workflows for 3.0.x-devel branch
  .github/workflows/nightly-windows-ci.yml
  .github/workflows/rebase-3.0.x-devel.yaml
Labels: skip-ci

#4237 [20119] TCP socket send buffer limit
  src/cpp/rtps/attributes/RTPSParticipantAttributes.cpp
  src/cpp/rtps/transport/TCPChannelResource.cpp
  src/cpp/rtps/transport/TCPChannelResource.h
  src/cpp/rtps/transport/TCPChannelResourceBasic.cpp
  src/cpp/rtps/transport/TCPChannelResourceSecure.cpp
  src/cpp/rtps/transport/TCPTransportInterface.cpp
  src/cpp/rtps/transport/TCPTransportInterface.h
  test/unittest/transport/TCPv4Tests.cpp
  test/unittest/transport/TCPv6Tests.cpp
  test/unittest/transport/mock/MockTCPv4Transport.h
  test/unittest/transport/mock/MockTCPv6Transport.h
  versions.md
Labels: no-test, ci-pending

#4322 [19452] Fix 3.0.x workflows
  .github/workflows/nightly-windows-ci.yml
  .github/workflows/rebase-3.0.x-devel.yaml
Labels: skip-ci

#4323 [19452] Fix 3.0.x rebase workflow
  .github/workflows/rebase-3.0.x-devel.yaml
Labels: skip-ci

#4278 [19587] Include variety of terminate proccess signals handler in discovery server
  tools/fds/server.cpp
Labels: ready-to-merge
