Repository eProsima/Fast-DDS, pull requests merged in 2024-02, with the labels that each got.

#4356 [20318] Fix and refactor Windows Github CI
  .github/workflows/config/default_ci.meta
  .github/workflows/config/nightly.meta
  .github/workflows/reusable-windows-ci.yml
  .github/workflows/sanitizer-tests.yaml
  cmake/testing/GoogleTest.cmake
  test/unittest/logging/log_macros/LogMacrosDefaultTests.cpp
  thirdparty/boost/test/ThirdpartyBoostCompile_test.cpp
Labels: first-to-merge

#4319 [20262] Add non-throwing getters for socket info
  src/cpp/rtps/transport/TCPChannelResource.h
  src/cpp/rtps/transport/TCPChannelResourceBasic.cpp
  src/cpp/rtps/transport/TCPChannelResourceBasic.h
  src/cpp/rtps/transport/TCPChannelResourceSecure.cpp
  src/cpp/rtps/transport/TCPChannelResourceSecure.h
  src/cpp/rtps/transport/TCPTransportInterface.cpp
  src/cpp/rtps/transport/TCPTransportInterface.h
  test/unittest/transport/mock/MockTCPChannelResource.cpp
  test/unittest/transport/mock/MockTCPChannelResource.h
Labels: ci-pending

#4340 [20272] Update Fast DDS types with Fast DDS Gen to include <cstdint> in v1 types
  examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfiguration.cxx
  examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfigurationPubSubTypes.h
  examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfigurationv1.cxx
  examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfigurationv1.h
  examples/cpp/dds/BasicConfigurationExample/HelloWorldv1.h
  examples/cpp/dds/Configurability/samplev1.h
  examples/cpp/dds/ContentFilteredTopicExample/HelloWorldv1.h
  examples/cpp/dds/CustomListenerExample/Topicv1.h
  examples/cpp/dds/CustomPayloadPoolExample/CustomPayloadPoolDatav1.h
  examples/cpp/dds/DeadlineQoSExample/deadlinepayloadv1.h
  examples/cpp/dds/DisablePositiveACKs/Topicv1.h
  examples/cpp/dds/DiscoveryServerExample/types/HelloWorldv1.h
  examples/cpp/dds/Filtering/FilteringExamplev1.h
  examples/cpp/dds/FlowControlExample/FlowControlExamplev1.h
  examples/cpp/dds/HelloWorldExample/HelloWorldv1.h
  examples/cpp/dds/HelloWorldExampleDataSharing/HelloWorldv1.h
  examples/cpp/dds/HelloWorldExampleSharedMem/HelloWorldv1.h
  examples/cpp/dds/HelloWorldExampleTCP/HelloWorldv1.h
  examples/cpp/dds/HistoryKind/samplev1.h
  examples/cpp/dds/Keys/samplev1.h
  examples/cpp/dds/LateJoiners/samplev1.h
  examples/cpp/dds/LifespanQoSExample/Lifespanv1.h
  examples/cpp/dds/LivelinessQoS/Topicv1.h
  examples/cpp/dds/OwnershipStrengthQoSExample/OwnershipStrengthv1.h
  examples/cpp/dds/RequestReplyExample/Calculatorv1.h
  examples/cpp/dds/SampleConfig_Controller/samplev1.h
  examples/cpp/dds/SampleConfig_Events/samplev1.h
  examples/cpp/dds/SampleConfig_Multimedia/samplev1.h
  examples/cpp/dds/SecureHelloWorldExample/HelloWorldv1.h
  examples/cpp/dds/StaticHelloWorldExample/HelloWorldv1.h
  examples/cpp/dds/WriterLoansExample/LoanableHelloWorldv1.h
  examples/cpp/dds/ZeroCopyExample/LoanableHelloWorldv1.h
  src/cpp/statistics/types/monitorservice_typesv1.h
  src/cpp/statistics/types/typesv1.h
  test/blackbox/types/Data1mbv1.h
  test/blackbox/types/Data64kbv1.h
  test/blackbox/types/FixedSizedv1.h
  test/blackbox/types/HelloWorldv1.h
  test/blackbox/types/KeyedData1mbv1.h
  test/blackbox/types/KeyedHelloWorldv1.h
  test/blackbox/types/StringTestv1.h
  test/blackbox/types/TestIncludeRegression3361v1.h
  test/blackbox/types/TestRegression3361v1.h
  test/blackbox/types/statistics/typesv1.h
  test/profiling/allocations/AllocTestTypev1.h
  test/unittest/dds/topic/DDSSQLFilter/data_types/ContentFilterTestTypev1.h
  test/unittest/dynamic_types/idl/Basicv1.h
  test/unittest/dynamic_types/idl/Testv1.h
  test/unittest/dynamic_types/idl/new_features_4_2v1.h
  test/unittest/xtypes/idl/Typesv1.h
  test/unittest/xtypes/idl/WideEnumv1.h
  test/xtypes/idl/Typesv1.h
Labels: no-test, ci-pending

#4342 [20272] Avoid a maybe-uninitialized warning
  test/unittest/rtps/DataSharing/SHMSegmentTests.cpp
Labels: needs-review, skip-ci

#4366 [20400] Test report action does not run when no-test label is set
  .github/workflows/config/nightly.meta
  .github/workflows/reusable-windows-ci.yml
Labels: no-test, ci-pending

#4292 Add serialization for Log::Kind to ostream
  include/fastdds/dds/log/Log.hpp
  src/cpp/fastdds/log/Log.cpp
Labels: ready-to-merge

#4387 [20318] Add GTEST_INDIVIDUAL=ON to nightly meta
  .github/workflows/config/nightly.meta
Labels: ci-pending

#4388 [20318] Select correct repos for nightly build
  .github/workflows/reusable-windows-ci.yml
Labels: skip-ci

#4346 [20346] Bump version to v2.13.2
  CMakeLists.txt
  package.xml
Labels: ready-to-merge, skip-ci

#4293 [20024] Bump to version v2.11.3
  CMakeLists.txt
  package.xml
  versions.md
Labels: needs-review, skip-ci, versions-pending

#4376 [20413] Fix doxygen docs warnings. Prepare for compiling with Doxygen 1.10.0
  include/fastrtps/config/doxygen_modules.h
  include/fastrtps/types/AnnotationParameterValue.h
  include/fastrtps/types/TypeIdentifierTypes.h
  include/fastrtps/types/TypeObjectHashId.h
  include/fastrtps/xmlparser/XMLEndpointParser.h
  include/fastrtps/xmlparser/XMLProfileManager.h
Labels: no-test

#4235 [20234] Restore Blackbox tests names
  test/blackbox/CMakeLists.txt
  test/blackbox/xfail_tests.cmake
Labels: ready-to-merge

#4343 [20275] Set 2.11.x as EOL
  .github/pull_request_template.md
  .github/workflows/config/default_ci_2.11.x.repos
  .github/workflows/config/nightly_2.11.x.repos
  .github/workflows/windows-ci.yml
  RELEASE_SUPPORT.md
Labels: ready-to-merge, skip-ci

#4321 [20227] Prevent index overflow and correctly assert the end iterator in DataSharing
  src/cpp/rtps/DataSharing/DataSharingPayloadPool.cpp
  src/cpp/rtps/DataSharing/ReaderPool.hpp
  test/dds/communication/CMakeLists.txt
  test/dds/communication/PubSubMain.cpp
  test/dds/communication/PublisherMain.cpp
  test/dds/communication/PublisherModule.cpp
  test/dds/communication/PublisherModule.hpp
  test/dds/communication/SubscriberMain.cpp
  test/dds/communication/SubscriberModule.cpp
  test/dds/communication/SubscriberModule.hpp
  test/dds/communication/definitions_example.json
  test/dds/communication/simple_data_sharing_stress.json
  test/dds/communication/test_build.py
Labels: ready-to-merge

#4375 [20401] Check History QoS inconsistencies
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.cpp
  test/blackbox/common/DDSBlackboxTestsDataWriter.cpp
  test/unittest/dds/profiles/test_xml_profile.xml
  test/unittest/dds/publisher/DataWriterTests.cpp
  test/unittest/dds/subscriber/DataReaderTests.cpp
Labels: ready-to-merge

#4297 [20238] Enabling multiple interfaces through whitelist in TCP servers
  src/cpp/rtps/transport/TCPTransportInterface.cpp
  test/unittest/transport/TCPv4Tests.cpp
  test/unittest/transport/TCPv6Tests.cpp
  test/unittest/transport/mock/MockTCPv4Transport.h
  test/unittest/transport/mock/MockTCPv6Transport.h
Labels: ready-to-merge

#4405 [20485] Fix .repos versions
  fastrtps.repos
Labels: skip-ci

#4324 [20141] Fix TCP reconnection after open logical port failure
  src/cpp/rtps/transport/TCPChannelResource.cpp
  test/unittest/transport/TCPv4Tests.cpp
  test/unittest/transport/TCPv6Tests.cpp
  test/unittest/transport/mock/MockTCPv4Transport.h
  test/unittest/transport/mock/MockTCPv6Transport.h
Labels: ready-to-merge

#4416 [20485] Fix SecureHelloworldExample
  examples/cpp/dds/SecureHelloWorldExample/HelloWorldPublisher.cpp
Labels: ready-to-merge, skip-ci

#4369 Fix the shared memory cleaning script.
  tools/fastdds/shm/clean.py
Labels: ready-to-merge, skip-ci

#4220 [19696][20409] Fix data race on PDP
  include/fastdds/rtps/attributes/ServerAttributes.h
  src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPListener.cpp
  test/blackbox/common/DDSBlackboxTestsDiscovery.cpp
Labels: ready-to-merge

#4396 [20438] LARGE_DATA Participants logic with same listening ports
  src/cpp/rtps/transport/TCPTransportInterface.cpp
  test/unittest/transport/TCPv4Tests.cpp
  test/unittest/transport/TCPv6Tests.cpp
Labels: ci-pending

#4335 [20311] Add missing TypeLookup listeners
  include/fastdds/dds/builtin/typelookup/TypeLookupManager.hpp
  include/fastdds/dds/builtin/typelookup/TypeLookupReplyListener.hpp
  include/fastdds/dds/builtin/typelookup/TypeLookupRequestListener.hpp
  src/cpp/fastdds/builtin/typelookup/TypeLookupManager.cpp
  src/cpp/fastdds/builtin/typelookup/TypeLookupReplyListener.cpp
  src/cpp/fastdds/builtin/typelookup/TypeLookupRequestListener.cpp
Labels: ci-pending

#4417 [20504] Just show warning when inconsistency between depth and max_samples_per_instance
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.cpp
  test/blackbox/common/DDSBlackboxTestsDataReader.cpp
  test/blackbox/common/DDSBlackboxTestsDataWriter.cpp
  test/unittest/dds/publisher/DataWriterTests.cpp
  test/unittest/dds/subscriber/DataReaderTests.cpp
Labels: ci-pending

#4442 [20505] Bump version to v2.13.3
  CMakeLists.txt
  package.xml
  versions.md
Labels: skip-ci

#4439 [20414] Bump version to 2.14.0
  .github/pull_request_template.md
  .github/workflows/config/default_ci_2.13.x.repos
  .github/workflows/config/nightly_2.13.x.repos
  .github/workflows/mac-ci.yml
  .github/workflows/mirror.yml
  .github/workflows/windows-ci.yml
  CMakeLists.txt
  package.xml
Labels: skip-ci

#4299 [20307] Ignore custom PIDs defined in Fast DDS when they are received from other vendors
  include/fastdds/dds/core/policy/ParameterTypes.hpp
  include/fastdds/rtps/builtin/data/ParticipantProxyData.h
  include/fastdds/rtps/builtin/data/ReaderProxyData.h
  include/fastdds/rtps/builtin/data/WriterProxyData.h
  include/fastdds/rtps/common/CacheChange.h
  include/fastdds/rtps/common/Types.h
  include/fastdds/rtps/common/VendorId_t.hpp
  include/fastdds/rtps/messages/MessageReceiver.h
  include/fastdds/rtps/messages/RTPSMessageCreator.h
  include/fastdds/rtps/messages/RTPS_messages.h
  include/fastdds/rtps/reader/RTPSReader.h
  include/fastdds/rtps/reader/StatefulReader.h
  include/fastdds/rtps/reader/StatelessReader.h
  include/fastdds/rtps/writer/RTPSWriter.h
  include/fastdds/rtps/writer/StatefulWriter.h
  src/cpp/fastdds/core/policy/ParameterList.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl/ReadTakeCommand.hpp
  src/cpp/rtps/DataSharing/DataSharingListener.cpp
  src/cpp/rtps/builtin/data/ParticipantProxyData.cpp
  src/cpp/rtps/builtin/data/ReaderProxyData.cpp
  src/cpp/rtps/builtin/data/WriterProxyData.cpp
  src/cpp/rtps/history/CacheChangePool.cpp
  src/cpp/rtps/messages/MessageReceiver.cpp
  src/cpp/rtps/messages/RTPSMessageCreator.cpp
  src/cpp/rtps/persistence/SQLite3PersistenceService.cpp
  src/cpp/rtps/reader/StatefulReader.cpp
  src/cpp/rtps/reader/StatelessReader.cpp
  src/cpp/rtps/reader/WriterProxy.cpp
  src/cpp/rtps/transport/tcp/TCPControlMessage.cpp
  src/cpp/rtps/transport/tcp/TCPControlMessage.h
  src/cpp/rtps/writer/RTPSWriter.cpp
  src/cpp/rtps/writer/StatefulWriter.cpp
  test/mock/rtps/ParticipantProxyData/fastdds/rtps/builtin/data/ParticipantProxyData.h
  test/mock/rtps/RTPSWriter/fastdds/rtps/writer/RTPSWriter.h
  test/mock/rtps/ReaderProxyData/fastdds/rtps/builtin/data/ReaderProxyData.h
  test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
  test/unittest/rtps/common/CMakeLists.txt
  test/unittest/rtps/common/VendorIdTests.cpp
  test/unittest/rtps/history/BasicPoolsTests.cpp
Labels: ready-to-merge

#4452 [20517] Force usage of semicolon in FASTDDS_TODO_BEFORE macro
  include/fastdds/dds/domain/DomainParticipantListener.hpp
  include/fastdds/rtps/transport/TCPTransportDescriptor.h
  include/fastdds/rtps/writer/IReaderDataFilter.hpp
  include/fastrtps/config.h.in
  src/cpp/rtps/transport/TCPTransportInterface.cpp
Labels: no-test

#4415 [20502] TCP non_blocking_send moved to TCPTransportDescriptor
  include/fastdds/rtps/transport/TCPTransportDescriptor.h
  resources/xsd/fastRTPS_profiles.xsd
  src/cpp/rtps/transport/TCPChannelResourceBasic.cpp
  src/cpp/rtps/transport/TCPChannelResourceSecure.cpp
  src/cpp/rtps/transport/TCPTransportInterface.cpp
  src/cpp/rtps/transport/TCPTransportInterface.h
  src/cpp/rtps/xmlparser/XMLParser.cpp
  test/mock/rtps/TCPTransportDescriptor/fastrtps/transport/TCPTransportDescriptor.h
  test/system/tools/xmlvalidation/XMLTesterExample_profile.xml
  test/system/tools/xmlvalidation/all_profile.xml
  test/system/tools/xmlvalidation/transportDescriptor_profile.xml
  test/unittest/transport/TCPv4Tests.cpp
  test/unittest/transport/TCPv6Tests.cpp
  test/unittest/xmlparser/XMLParserTests.cpp
Labels: ready-to-merge, first-to-merge

#4296 [20339] Migrate TCPReqRepHelloWorldReplier/Requester
  test/blackbox/CMakeLists.txt
  test/blackbox/api/dds-pim/TCPReqRepHelloWorldReplier.cpp
  test/blackbox/api/dds-pim/TCPReqRepHelloWorldReplier.hpp
  test/blackbox/api/dds-pim/TCPReqRepHelloWorldRequester.cpp
  test/blackbox/api/dds-pim/TCPReqRepHelloWorldRequester.hpp
  test/blackbox/common/BlackboxTestsTransportTCP.cpp
Labels: ready-to-merge

#4461 [20187] Add catch of out-of-range exception for thread settings port
  src/cpp/rtps/xmlparser/XMLElementParser.cpp
  test/unittest/xmlparser/XMLParserTests.cpp
  test/unittest/xmlparser/regressions/20187_profile_bin.xml
Labels: ci-pending

#4109 [17513] Add nightly Ubuntu Github CI
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/reusable-ubuntu-ci.yml
Labels: skip-ci

#4443 [20494] Set fixed versions in fastrpts.repos
  fastrtps.repos
Labels: ready-to-merge, skip-ci

#4466 [19175] Ubuntu example testing automation infrastrucure
  .github/workflows/reusable-ubuntu-ci.yml
  cmake/common/eprosima_libraries.cmake
  test/CMakeLists.txt
  test/examples/CMakeLists.txt
  test/examples/basic_configuration.compose.yml
  test/examples/test_examples.py
Labels: ready-to-merge, skip-ci
