Repository eProsima/Fast-DDS, pull requests merged in 2024-06, with the labels that each got.

#4872 [21097] Remove RTPSParticipant listener overloaded callbaks
  include/fastdds/rtps/participant/RTPSParticipantListener.h
  src/cpp/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/fastdds/domain/DomainParticipantImpl.hpp
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  test/mock/rtps/RTPSParticipantImpl/rtps/participant/RTPSParticipantImpl.h
Labels: needs-review, ci-pending

#4813 Fix compilation when building static library [21059]
  src/cpp/CMakeLists.txt
Labels: no-test, ci-pending

#4896 [21144] Fix doxygen errors for versions prior to 1.8.19
  include/fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp
  src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.hpp
Labels: skip-ci

#4876 [20815] Only apply content filter to ALIVE changes
  include/fastrtps/types/DynamicLoanableSequence.hpp
  include/fastrtps/types/DynamicPubSubType.h
  src/cpp/CMakeLists.txt
  src/cpp/fastdds/publisher/filtering/ReaderFilterCollection.hpp
  src/cpp/rtps/reader/StatefulReader.cpp
  src/cpp/rtps/reader/StatelessReader.cpp
  src/cpp/rtps/reader/reader_utils.cpp
  src/cpp/rtps/reader/reader_utils.hpp
  test/blackbox/api/dds-pim/PubSubParticipant.hpp
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/blackbox/api/dds-pim/PubSubTypeTraits.hpp
  test/blackbox/api/dds-pim/PubSubWriter.hpp
  test/blackbox/api/dds-pim/PubSubWriterReader.hpp
  test/blackbox/common/DDSBlackboxTestsContentFilter.cpp
  test/blackbox/types/dynamic_types_traits.hpp
  test/unittest/dds/publisher/CMakeLists.txt
  test/unittest/statistics/dds/CMakeLists.txt
Labels: ready-to-merge

#4893 [21136] Add XML configuration for FlowControllerDescriptor to 2.x
  include/fastdds/dds/core/policy/QosPolicies.hpp
  include/fastdds/rtps/attributes/WriterAttributes.h
  include/fastdds/rtps/flowcontrol/FlowControllerDescriptor.hpp
  include/fastrtps/xmlparser/XMLParser.h
  include/fastrtps/xmlparser/XMLParserCommon.h
  resources/xsd/fastRTPS_profiles.xsd
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/xmlparser/XMLElementParser.cpp
  src/cpp/rtps/xmlparser/XMLParser.cpp
  src/cpp/rtps/xmlparser/XMLParserCommon.cpp
  test/unittest/dds/profiles/test_xml_for_string_profile.xml
  test/unittest/dds/profiles/test_xml_profile.xml
  test/unittest/dds/publisher/PublisherTests.cpp
  test/unittest/xmlparser/XMLElementParserTests.cpp
  test/unittest/xmlparser/XMLParserTests.cpp
  test/unittest/xmlparser/XMLProfileParserTests.cpp
  test/unittest/xmlparser/test_xml_deprecated.xml
  test/unittest/xmlparser/test_xml_profile.xml
  test/unittest/xmlparser/test_xml_profile_env_var.xml
  test/unittest/xmlparser/test_xml_rooted_deprecated.xml
  test/unittest/xmlparser/wrapper/XMLParserTest.hpp
  versions.md
Labels: ready-to-merge

#4890 [21086] Remove `string_convert` header and source
  include/fastrtps/utils/string_convert.hpp
  src/cpp/CMakeLists.txt
  src/cpp/utils/string_convert.cpp
  test/unittest/dds/publisher/CMakeLists.txt
  test/unittest/dds/status/CMakeLists.txt
  test/unittest/dds/topic/DDSSQLFilter/CMakeLists.txt
  test/unittest/rtps/builtin/CMakeLists.txt
  test/unittest/rtps/discovery/CMakeLists.txt
  test/unittest/rtps/network/CMakeLists.txt
  test/unittest/statistics/dds/CMakeLists.txt
  test/unittest/statistics/rtps/CMakeLists.txt
  test/unittest/xmlparser/CMakeLists.txt
Labels: ready-to-merge, ci-pending

#4897 [21100] Bump to v2.13.5
  CMakeLists.txt
  package.xml
  versions.md
Labels: ready-to-merge

#4891 [20816] Properly delete builtin statistics writers upon `delete_contained_entities()`
  src/cpp/statistics/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/statistics/fastdds/domain/DomainParticipantImpl.hpp
  test/blackbox/common/DDSBlackboxTestsStatistics.cpp
Labels: ready-to-merge

#4911 [21136] Bugfix: Revert XML Flow controller names to `const char*`
  include/fastdds/dds/core/policy/QosPolicies.hpp
  include/fastdds/rtps/attributes/WriterAttributes.h
  include/fastdds/rtps/flowcontrol/FlowControllerDescriptor.hpp
  include/fastrtps/xmlparser/XMLParser.h
  src/cpp/rtps/xmlparser/XMLElementParser.cpp
  src/cpp/rtps/xmlparser/XMLParser.cpp
  src/cpp/rtps/xmlparser/XMLProfileManager.cpp
  test/unittest/dds/publisher/PublisherTests.cpp
  test/unittest/xmlparser/XMLProfileParserTests.cpp
Labels: ready-to-merge

#4918 [20815] Fix doxygen warning about undocumented param in deleted functions
  CMakeLists.txt
  include/fastrtps/types/DynamicLoanableSequence.hpp
Labels: ready-to-merge, no-test

#4921 [21162] Split example tests in different ctest tests
  test/examples/CMakeLists.txt
  test/examples/test_configuration.py
  test/examples/test_hello_world.py
Labels: ci-pending

#4901 [20953] Fix Proxy block in TypeLookup Service
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupManager.cpp
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupManager.hpp
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupReplyListener.cpp
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupRequestListener.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPSimpleListeners.cpp
Labels: ready-to-merge

#4922 [21165] Correctly initialize `MatchingFailureMask` constants to be used with the `std::bitset` API
  src/cpp/rtps/builtin/discovery/endpoint/EDP.h
  test/unittest/rtps/discovery/EdpTests.cpp
Labels: ready-to-merge

#4931 [21168] Use token for ccache action
  .github/workflows/documentation-tests.yaml
  .github/workflows/reusable-mac-ci.yml
  .github/workflows/reusable-sanitizers-ci.yml
  .github/workflows/reusable-ubuntu-ci.yml
Labels: ready-to-merge

#4932 [21120] Fix EDP build warning wihtout security
  src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
Labels: skip-ci

#4939 [21153, 21154] Address XMLDynamicParser Fuzzer regressions
  src/cpp/xmlparser/XMLDynamicParser.cpp
  test/unittest/xmlparser/XMLParserTests.cpp
  test/unittest/xmlparser/regressions/21153_profile_bin.xml
  test/unittest/xmlparser/regressions/21154_profile_bin.xml
Labels: ci-pending

#4740 [20936] Change backup restore order
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  src/cpp/rtps/builtin/discovery/participant/PDP.h
  src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer.hpp
Labels: ci-pending

#4945 Fix compilation warning
  src/cpp/rtps/messages/RTPSMessageGroup.cpp
Labels: no-test, ci-pending

#4941 [21170] Fix DS servers not connecting due to ports logic
  src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  test/blackbox/api/dds-pim/PubSubParticipant.hpp
  test/blackbox/common/DDSBlackboxTestsDiscovery.cpp
Labels: ci-pending

#4962 [21130] Migrate ResourceManagement to rtps attributes API
  include/fastdds/dds/core/policy/QosPolicies.hpp
  include/fastdds/rtps/attributes/HistoryAttributes.h
  include/fastdds/rtps/attributes/RTPSParticipantAttributes.h
  include/fastdds/rtps/attributes/ResourceManagement.hpp
  src/cpp/fastdds/publisher/DataWriterHistory.hpp
  src/cpp/fastdds/subscriber/history/DataReaderHistory.hpp
  src/cpp/rtps/DataSharing/ReaderPool.hpp
  src/cpp/rtps/DataSharing/WriterPool.hpp
  src/cpp/rtps/history/CacheChangePool.h
  src/cpp/rtps/history/PoolConfig.h
  src/cpp/rtps/history/TopicPayloadPool.hpp
  src/cpp/statistics/fastdds/subscriber/qos/DataReaderQos.cpp
  src/cpp/xmlparser/attributes/PublisherAttributes.hpp
  src/cpp/xmlparser/attributes/SubscriberAttributes.hpp
  test/mock/dds/DataWriterHistory/fastdds/publisher/DataWriterHistory.hpp
  test/mock/rtps/RTPSParticipantAttributes/fastdds/rtps/attributes/RTPSParticipantAttributes.h
  test/unittest/statistics/rtps/mock/Publisher/fastdds/publisher/DataWriterHistory.hpp
  versions.md
Labels: skip-ci

#4963 [21182] Migrate fastrtps.rc
  src/cpp/CMakeLists.txt
  src/cpp/fastdds.rc
  test/unittest/xmlparser/XMLLoadFileTests.cpp
Labels: no-test, ci-pending

#4961 [21181] Fix parse XML dynamic type fuzzer issue
  src/cpp/xmlparser/XMLDynamicParser.cpp
  test/unittest/xmlparser/XMLParserTests.cpp
  test/unittest/xmlparser/regressions/21181_profile_bin.xml
Labels: ready-to-merge

#4842 [21077] Update Fast DDS docs QoS examples
  examples/cpp/configuration/SubscriberApp.cpp
  include/fastdds/dds/publisher/qos/DataWriterQos.hpp
  include/fastdds/dds/subscriber/qos/DataReaderQos.hpp
  include/fastdds/rtps/attributes/PropertyPolicy.h
  src/cpp/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.cpp
  src/cpp/fastdds/subscriber/qos/DataReaderQos.cpp
  src/cpp/fastdds/utils/QosConverters.cpp
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/unittest/dds/subscriber/SubscriberTests.cpp
Labels: ci-pending

#4971 [21158] CI - Avoid CCache in workflows and nightlys
  .github/workflows/mac-ci.yml
  .github/workflows/nightly-mac-ci.yml
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/reusable-mac-ci.yml
  .github/workflows/reusable-sanitizers-ci.yml
Labels: no-test, ci-pending

#4979 [21158] Update README.md with GitHub actions Ubuntu CI nightly
  README.md
Labels: skip-ci

#4969 Only signed integers are permited in Dynamic Language Binding enumerations [21201]
  examples/cpp/dds/RequestReplyExample/Calculator.hpp
  include/fastdds/dds/xtypes/dynamic_types/detail/dynamic_language_binding.hpp
  src/cpp/fastdds/builtin/type_lookup_service/detail/rpc_types.hpp
  src/cpp/fastdds/xtypes/dynamic_types/MemberDescriptorImpl.cpp
  src/cpp/statistics/types/monitorservice_types.hpp
  test/blackbox/types/statistics/monitorservice_types.hpp
  test/feature/dynamic_types/DynamicTypesTests.cpp
  test/unittest/dds/topic/DDSSQLFilter/data_types/ContentFilterTestType.hpp
Labels: ready-to-merge

#4986 [21219] Remove Valgrind build dependency for profiling tests
  .github/workflows/reusable-ubuntu-ci.yml
  test/CMakeLists.txt
  test/profiling/CMakeLists.txt
Labels: no-test, ci-pending

#4987 Fix compilation in Ubuntu 24.04 platforms
  src/cpp/utils/UnitsParser.hpp
Labels: no-test, ci-pending

#4989 [21219] Build profiling tests as alternate build in Ubuntu CI
  .github/workflows/reusable-ubuntu-ci.yml
  test/CMakeLists.txt
  test/profiling/CMakeLists.txt
  test/profiling/MemoryTestTypes.cpp
  test/profiling/MemoryTestTypes.h
Labels: ready-to-merge, no-test

#4953 [21131] Make Blackbox tests not include any private API
  include/fastdds/rtps/transport/shared_mem/SharedMemTransportDescriptor.h
  include/fastdds/rtps/transport/shared_mem/test_SharedMemTransportDescriptor.h
  include/fastdds/rtps/transport/test_UDPv4TransportDescriptor.h
  src/cpp/rtps/transport/shared_mem/test_SharedMemTransport.h
  src/cpp/rtps/transport/test_UDPv4Transport.cpp
  src/cpp/rtps/transport/test_UDPv4Transport.h
  test/blackbox/CMakeLists.txt
  test/blackbox/common/BlackboxTests.hpp
  test/blackbox/common/BlackboxTestsDiscovery.cpp
  test/blackbox/common/BlackboxTestsKeys.cpp
  test/blackbox/common/BlackboxTestsLivelinessQos.cpp
  test/blackbox/common/BlackboxTestsPubSubFragments.cpp
  test/blackbox/common/BlackboxTestsPubSubHistory.cpp
  test/blackbox/common/BlackboxTestsReliability.cpp
  test/blackbox/common/BlackboxTestsSecurity.cpp
  test/blackbox/common/BlackboxTestsTransportSHM.cpp
  test/blackbox/common/BlackboxTestsVolatile.cpp
  test/blackbox/common/DDSBlackboxTestsAckPositive.cpp
  test/blackbox/common/DDSBlackboxTestsBasic.cpp
  test/blackbox/common/DDSBlackboxTestsContentFilter.cpp
  test/blackbox/common/DDSBlackboxTestsDataReader.cpp
  test/blackbox/common/DDSBlackboxTestsDataWriter.cpp
  test/blackbox/common/DDSBlackboxTestsDiscovery.cpp
  test/blackbox/common/DDSBlackboxTestsListeners.cpp
  test/blackbox/common/DDSBlackboxTestsTransportSHMUDP.cpp
  test/blackbox/common/RTPSBlackboxTestsBasic.cpp
  test/blackbox/types/core/core_types.cxx
  test/blackbox/types/core/core_types.h
  test/blackbox/types/core/core_types.hpp
  test/blackbox/types/core/core_types.idl
  test/blackbox/types/core/core_typesCdrAux.hpp
  test/blackbox/types/core/core_typesCdrAux.ipp
  test/blackbox/types/core/core_typesPubSubTypes.cxx
  test/blackbox/types/core/core_typesPubSubTypes.h
  test/blackbox/types/core/core_typesTypeObject.cxx
  test/blackbox/types/core/core_typesTypeObject.h
  test/blackbox/types/core/core_typesTypeObjectSupport.cxx
  test/blackbox/types/core/core_typesTypeObjectSupport.hpp
  test/blackbox/utils/filter_helpers.hpp
  test/unittest/statistics/rtps/RTPSStatisticsTests.cpp
  utils/scripts/update_generated_code_from_idl.sh
  versions.md
Labels: ready-to-merge, ci-pending

#4990 [21224] Update release support table
  .github/pull_request_template.md
  README.md
  RELEASE_SUPPORT.md
Labels: skip-ci

#4995 [21224] Update version support documentation (backport #4990)
  .github/pull_request_template.md
  README.md
  RELEASE_SUPPORT.md
Labels: skip-ci

#4946 [20650] Create InitialConnection for TCP initial peers 3.x & 2.14
  src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
  src/cpp/rtps/transport/UDPTransportInterface.cpp
  src/cpp/rtps/transport/UDPTransportInterface.h
  src/cpp/rtps/transport/shared_mem/SharedMemTransport.cpp
  src/cpp/rtps/transport/shared_mem/SharedMemTransport.h
  test/blackbox/common/BlackboxTestsTransportTCP.cpp
Labels: ready-to-merge

#4947 [20650] Create InitialConnection for TCP initial peers 2.13 & 2.10 & 2.6
  src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
  test/blackbox/common/BlackboxTestsTransportTCP.cpp
Labels: ready-to-merge

#4959 [20650] Examples refactor: Delivery mechanisms
  examples/CMakeLists.txt
  examples/cpp/delivery_mechanisms/Application.cpp
  examples/cpp/delivery_mechanisms/Application.hpp
  examples/cpp/delivery_mechanisms/CLIParser.hpp
  examples/cpp/delivery_mechanisms/CMakeLists.txt
  examples/cpp/delivery_mechanisms/DeliveryMechanisms.hpp
  examples/cpp/delivery_mechanisms/DeliveryMechanisms.idl
  examples/cpp/delivery_mechanisms/DeliveryMechanismsCdrAux.hpp
  examples/cpp/delivery_mechanisms/DeliveryMechanismsCdrAux.ipp
  examples/cpp/delivery_mechanisms/DeliveryMechanismsPubSubTypes.cxx
  examples/cpp/delivery_mechanisms/DeliveryMechanismsPubSubTypes.hpp
  examples/cpp/delivery_mechanisms/DeliveryMechanismsTypeObjectSupport.cxx
  examples/cpp/delivery_mechanisms/DeliveryMechanismsTypeObjectSupport.hpp
  examples/cpp/delivery_mechanisms/PubSubApp.cpp
  examples/cpp/delivery_mechanisms/PubSubApp.hpp
  examples/cpp/delivery_mechanisms/PublisherApp.cpp
  examples/cpp/delivery_mechanisms/PublisherApp.hpp
  examples/cpp/delivery_mechanisms/README.md
  examples/cpp/delivery_mechanisms/SubscriberApp.cpp
  examples/cpp/delivery_mechanisms/SubscriberApp.hpp
  examples/cpp/delivery_mechanisms/main.cpp
  test/examples/delivery_mechanisms.compose.yml
  test/examples/delivery_mechanisms_isolated.compose.yml
  test/examples/test_configuration.py
  test/examples/test_delivery_mechanisms.py
  test/examples/test_delivery_mechanisms_isolated.py
  test/examples/test_hello_world.py
  versions.md
Labels: ready-to-merge
