Repository eProsima/Fast-DDS, pull requests merged in 2024-05, with the labels that each got.

#4750 [20945] Fix SecurityTest unittests memory error
  test/unittest/rtps/security/SecurityHandshakeProcessTests.cpp
  test/unittest/rtps/security/SecurityTests.cpp
  test/unittest/rtps/security/SecurityTests.hpp
  test/unittest/rtps/security/SecurityValidationRemoteTests.cpp
Labels: ci-pending

#4719 [20861] Implement copy_from_topic_qos method
  include/fastdds/dds/publisher/Publisher.hpp
  include/fastdds/dds/publisher/qos/DataWriterQos.hpp
  include/fastdds/dds/subscriber/Subscriber.hpp
  include/fastdds/dds/subscriber/qos/DataReaderQos.hpp
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/publisher/DataWriterImpl.hpp
  src/cpp/fastdds/publisher/Publisher.cpp
  src/cpp/fastdds/publisher/PublisherImpl.cpp
  src/cpp/fastdds/publisher/PublisherImpl.hpp
  src/cpp/fastdds/publisher/qos/DataWriterQos.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.hpp
  src/cpp/fastdds/subscriber/Subscriber.cpp
  src/cpp/fastdds/subscriber/SubscriberImpl.cpp
  src/cpp/fastdds/subscriber/SubscriberImpl.hpp
  src/cpp/fastdds/subscriber/qos/DataReaderQos.cpp
  test/blackbox/common/DDSBlackboxTestsDataReader.cpp
  test/blackbox/common/DDSBlackboxTestsDataWriter.cpp
  test/unittest/dds/publisher/PublisherTests.cpp
  test/unittest/dds/subscriber/SubscriberTests.cpp
Labels: ready-to-merge

#4681 [20742] Run `is_plain` method with the corresponding data representation
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl/SampleLoanManager.hpp
  test/unittest/dds/participant/ParticipantTests.cpp
  test/unittest/dds/publisher/DataWriterTests.cpp
  test/unittest/dds/publisher/PublisherTests.cpp
  test/unittest/dds/subscriber/DataReaderTests.cpp
Labels: ready-to-merge

#4753 Address compilation issue for GLIBC version prior to 2.30
  src/cpp/utils/threading/threading_pthread.ipp
Labels: no-test

#4723 [20893] Prepare 3.0.x-devel to become master
  .github/pull_request_template.md
  .github/workflows/documentation-tests.yaml
  .github/workflows/mac-ci.yml
  .github/workflows/mirror.yml
  .github/workflows/nightly-mac-ci.yml
  .github/workflows/nightly-sanitizers-ci.yml
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/nightly-windows-ci.yml
  .github/workflows/rebase-3.0.x-devel.yaml
  .github/workflows/reusable-sanitizers-ci.yml
  .github/workflows/reusable-ubuntu-ci.yml
  .github/workflows/sanitizers-ci.yml
  .github/workflows/ubuntu-ci.yml
  .github/workflows/windows-ci.yml
  README.md
Labels: skip-ci

#4759 [20965] Fix Python Installation version in Github CI. Address failing system tests environment issues.
  .github/workflows/reusable-ubuntu-ci.yml
  .github/workflows/reusable-windows-ci.yml
  test/system/tools/fastdds/CMakeLists.txt
  tools/fastdds/fastdds.bat
  tools/fastdds/ros-discovery.bat
Labels: skip-ci

#4775 [20994] Consider library behavior changes as ABI breaks in the PR template checklist
  .github/pull_request_template.md
Labels: ready-to-merge, skip-ci

#4790 [20893] Update mirror job
  .github/workflows/mirror.yml
Labels: skip-ci

#4785 [20893] Update .repos to use 'master' branches
  fastdds.repos
Labels: ready-to-merge, skip-ci

#4791 [20893] Update mirror job
  .github/workflows/mirror.yml
Labels: skip-ci

#4760 [20976] Handle errors when setting socket buffer sizes
  include/fastdds/rtps/transport/TransportInterface.h
  include/fastrtps/transport/TransportInterface.h
  src/cpp/rtps/transport/TCPChannelResource.cpp
  src/cpp/rtps/transport/TCPChannelResource.h
  src/cpp/rtps/transport/TCPChannelResourceBasic.cpp
  src/cpp/rtps/transport/TCPChannelResourceSecure.cpp
  src/cpp/rtps/transport/TCPTransportInterface.cpp
  src/cpp/rtps/transport/UDPTransportInterface.cpp
  src/cpp/rtps/transport/UDPTransportInterface.h
  src/cpp/rtps/transport/UDPv4Transport.cpp
  src/cpp/rtps/transport/UDPv6Transport.cpp
  src/cpp/rtps/transport/asio_helpers.hpp
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/blackbox/api/dds-pim/PubSubWriter.hpp
  test/blackbox/common/DDSBlackboxTestsListeners.cpp
  test/unittest/transport/TCPv4Tests.cpp
  test/unittest/transport/TCPv6Tests.cpp
  test/unittest/transport/UDPv4Tests.cpp
  test/unittest/transport/UDPv6Tests.cpp
Labels: needs-review, ci-pending

#4770 [21009] Do not require PYTHON_VERSION to be defined in .bat files
  tools/fastdds/fastdds.bat
  tools/fastdds/ros-discovery.bat
Labels: ready-to-merge

#4800 [19452] Update GitHub workflows
  .github/workflows/documentation-tests.yaml
  .github/workflows/mac-ci.yml
  .github/workflows/nightly-mac-ci.yml
  .github/workflows/nightly-sanitizers-ci.yml
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/nightly-windows-ci.yml
  .github/workflows/rebase-3.0.x-devel.yaml
  .github/workflows/reusable-ubuntu-ci.yml
  .github/workflows/sanitizers-ci.yml
  .github/workflows/ubuntu-ci.yml
  .github/workflows/windows-ci.yml
Labels: no-test, ci-pending

#4761 [20933] Set DataSharing in Writer|ReaderProxyData
  src/cpp/fastdds/core/policy/QosPoliciesSerializer.hpp
  src/cpp/rtps/builtin/data/ReaderProxyData.cpp
  src/cpp/rtps/builtin/data/WriterProxyData.cpp
  test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
Labels: ready-to-merge, skip-ci

#4799 [19452] Update repos file
  fastrtps.repos
Labels: no-test, ci-pending

#4671 [20708] Make NetworkConfiguration private
  src/cpp/rtps/builtin/data/NetworkConfiguration.hpp
  src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
Labels: ready-to-merge

#4777 [20849] New `max_message_size` property to limit output datagrams size
  include/fastdds/rtps/writer/RTPSWriter.h
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.h
  src/cpp/rtps/writer/RTPSWriter.cpp
  test/blackbox/common/DDSBlackboxTestsBasic.cpp
  test/blackbox/common/RTPSBlackboxTestsBasic.cpp
Labels: ready-to-merge

#4796 [21036] Handle errors when setting socket buffer sizes (backport #4760)
  include/fastdds/rtps/transport/TransportInterface.h
  include/fastrtps/transport/TransportInterface.h
  src/cpp/rtps/transport/TCPChannelResource.cpp
  src/cpp/rtps/transport/TCPChannelResource.h
  src/cpp/rtps/transport/TCPChannelResourceBasic.cpp
  src/cpp/rtps/transport/TCPChannelResourceSecure.cpp
  src/cpp/rtps/transport/TCPTransportInterface.cpp
  src/cpp/rtps/transport/UDPTransportInterface.cpp
  src/cpp/rtps/transport/UDPTransportInterface.h
  src/cpp/rtps/transport/UDPv4Transport.cpp
  src/cpp/rtps/transport/UDPv6Transport.cpp
  src/cpp/rtps/transport/asio_helpers.hpp
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/blackbox/api/dds-pim/PubSubWriter.hpp
  test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
  test/blackbox/api/fastrtps_deprecated/PubSubWriter.hpp
  test/blackbox/common/DDSBlackboxTestsListeners.cpp
  test/unittest/transport/TCPv4Tests.cpp
  test/unittest/transport/TCPv6Tests.cpp
  test/unittest/transport/UDPv4Tests.cpp
  test/unittest/transport/UDPv6Tests.cpp
Labels: ci-pending

#4776 [20652] Add DNS entries to hosts files on github workflows
  .github/workflows/reusable-mac-ci.yml
  .github/workflows/reusable-sanitizers-ci.yml
  .github/workflows/reusable-ubuntu-ci.yml
Labels: ready-to-merge, ci-pending

#4814 [21037] Use `%*` instead of loop in `.bat` scripts
  tools/fastdds/fastdds.bat
  tools/fastdds/ros-discovery.bat
Labels: ci-pending

#4824 [20995] Bump version to 2.10.4
  CMakeLists.txt
  package.xml
  versions.md
Labels: skip-ci

#4751 [10173] Use absolute paths when loading XML files
  src/cpp/xmlparser/XMLParser.cpp
  src/cpp/xmlparser/XMLParser.h
  src/cpp/xmlparser/XMLParserCommon.cpp
  src/cpp/xmlparser/XMLParserCommon.h
  src/cpp/xmlparser/XMLProfileManager.cpp
  src/cpp/xmlparser/XMLProfileManager.h
  test/unittest/dds/status/CMakeLists.txt
  test/unittest/logging/mock/MockConsumer.h
  test/unittest/xmlparser/CMakeLists.txt
  test/unittest/xmlparser/XMLLoadFileTests.cpp
Labels: ready-to-merge, ci-pending

#4727 [20819] Make TimedEvent private
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.cpp
  src/cpp/rtps/builtin/data/ParticipantProxyData.cpp
  src/cpp/rtps/builtin/discovery/participant/DS/PDPSecurityInitiatorListener.cpp
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPListener.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
  src/cpp/rtps/builtin/discovery/participant/timedevent/DSClientEvent.h
  src/cpp/rtps/builtin/discovery/participant/timedevent/DServerEvent.hpp
  src/cpp/rtps/builtin/liveliness/WLP.cpp
  src/cpp/rtps/reader/WriterProxy.cpp
  src/cpp/rtps/resources/TimedEvent.cpp
  src/cpp/rtps/resources/TimedEvent.h
  src/cpp/rtps/resources/TimedEventImpl.h
  src/cpp/rtps/security/SecurityManager.h
  src/cpp/rtps/writer/LivelinessManager.hpp
  src/cpp/rtps/writer/ReaderProxy.cpp
  src/cpp/rtps/writer/StatefulWriter.cpp
  src/cpp/statistics/rtps/monitor-service/MonitorService.hpp
  test/mock/rtps/TimedEvent/rtps/resources/TimedEvent.h
  test/unittest/rtps/reader/WriterProxyAcknackTests.cpp
  test/unittest/rtps/reader/WriterProxyStopTest.cpp
  test/unittest/rtps/reader/WriterProxyTests.cpp
  test/unittest/rtps/resources/timedevent/mock/MockEvent.h
  test/unittest/statistics/rtps/mock/StatisticsBase/statistics/rtps/monitor-service/MonitorService.hpp
Labels: ready-to-merge, ci-pending

#4833 [20989] Don't require Fast CDR v2 in examples
  examples/cpp/dds/AdvancedConfigurationExample/CMakeLists.txt
  examples/cpp/dds/BasicConfigurationExample/CMakeLists.txt
  examples/cpp/dds/Configurability/CMakeLists.txt
  examples/cpp/dds/ContentFilteredTopicExample/CMakeLists.txt
  examples/cpp/dds/CustomListenerExample/CMakeLists.txt
  examples/cpp/dds/CustomPayloadPoolExample/CMakeLists.txt
  examples/cpp/dds/DeadlineQoSExample/CMakeLists.txt
  examples/cpp/dds/DisablePositiveACKs/CMakeLists.txt
  examples/cpp/dds/DiscoveryServerExample/CMakeLists.txt
  examples/cpp/dds/DynamicHelloWorldExample/CMakeLists.txt
  examples/cpp/dds/Filtering/CMakeLists.txt
  examples/cpp/dds/FlowControlExample/CMakeLists.txt
  examples/cpp/dds/HelloWorldExample/CMakeLists.txt
  examples/cpp/dds/HelloWorldExampleDataSharing/CMakeLists.txt
  examples/cpp/dds/HelloWorldExampleSharedMem/CMakeLists.txt
  examples/cpp/dds/HelloWorldExampleTCP/CMakeLists.txt
  examples/cpp/dds/HistoryKind/CMakeLists.txt
  examples/cpp/dds/Keys/CMakeLists.txt
  examples/cpp/dds/LateJoiners/CMakeLists.txt
  examples/cpp/dds/LifespanQoSExample/CMakeLists.txt
  examples/cpp/dds/LivelinessQoS/CMakeLists.txt
  examples/cpp/dds/OwnershipStrengthQoSExample/CMakeLists.txt
  examples/cpp/dds/RequestReplyExample/CMakeLists.txt
  examples/cpp/dds/SampleConfig_Controller/CMakeLists.txt
  examples/cpp/dds/SampleConfig_Events/CMakeLists.txt
  examples/cpp/dds/SampleConfig_Multimedia/CMakeLists.txt
  examples/cpp/dds/SecureHelloWorldExample/CMakeLists.txt
  examples/cpp/dds/StaticHelloWorldExample/CMakeLists.txt
  examples/cpp/dds/TypeLookupService/CMakeLists.txt
  examples/cpp/dds/WriterLoansExample/CMakeLists.txt
  examples/cpp/dds/ZeroCopyExample/CMakeLists.txt
  examples/cpp/rtps/AsSocket/CMakeLists.txt
  examples/cpp/rtps/Persistent/CMakeLists.txt
  examples/cpp/rtps/Registered/CMakeLists.txt
Labels: ready-to-merge, no-test

#4815 [20991] Fix sanitizers CI test summary report
  .github/workflows/utils/log_parser.py
Labels: ready-to-merge

#4816 [20989] Set fallback branch for get_related_branch_from_repo correctly
  .github/workflows/reusable-ubuntu-ci.yml
Labels: ready-to-merge

#4823 [21053] Move DR TypeConsistencyEnforcement & DataRepresentation from TypeConsistency to DataReaderQos
  include/fastdds/dds/subscriber/qos/DataReaderQos.hpp
  src/cpp/fastdds/subscriber/DataReaderImpl.cpp
  src/cpp/fastdds/subscriber/SubscriberImpl.cpp
  src/cpp/fastdds/subscriber/qos/DataReaderQos.cpp
  src/cpp/fastdds/utils/QosConverters.cpp
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/blackbox/common/DDSBlackboxTestsDataReader.cpp
  test/unittest/dds/subscriber/DataReaderTests.cpp
  test/unittest/dds/subscriber/SubscriberTests.cpp
  versions.md
Labels: ready-to-merge

#4674 [20765] Make RTPS reader implementations private
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupManager.cpp
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupRequestListener.cpp
  src/cpp/fastdds/domain/DomainParticipantImpl.hpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPServer.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPSimple.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPSimpleListeners.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPUtils.hpp
  src/cpp/rtps/builtin/discovery/participant/DS/DiscoveryServerPDPEndpoints.hpp
  src/cpp/rtps/builtin/discovery/participant/DS/DiscoveryServerPDPEndpointsSecure.hpp
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
  src/cpp/rtps/builtin/discovery/participant/simple/SimplePDPEndpoints.hpp
  src/cpp/rtps/builtin/discovery/participant/simple/SimplePDPEndpointsSecure.hpp
  src/cpp/rtps/builtin/liveliness/WLP.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/reader/StatefulPersistentReader.cpp
  src/cpp/rtps/reader/StatefulPersistentReader.hpp
  src/cpp/rtps/reader/StatefulReader.cpp
  src/cpp/rtps/reader/StatefulReader.hpp
  src/cpp/rtps/reader/StatelessPersistentReader.cpp
  src/cpp/rtps/reader/StatelessPersistentReader.hpp
  src/cpp/rtps/reader/StatelessReader.cpp
  src/cpp/rtps/reader/StatelessReader.hpp
  src/cpp/rtps/reader/WriterProxy.cpp
  src/cpp/rtps/security/SecurityManager.cpp
  test/mock/rtps/RTPSParticipant/fastdds/rtps/participant/RTPSParticipant.h
  test/mock/rtps/StatefulReader/rtps/reader/StatefulReader.hpp
  test/mock/rtps/StatelessReader/rtps/reader/StatelessReader.hpp
  test/unittest/dds/subscriber/DataReaderHistoryTests.cpp
  test/unittest/rtps/history/ReaderHistoryTests.cpp
  test/unittest/rtps/reader/WriterProxyAcknackTests.cpp
  test/unittest/rtps/reader/WriterProxyStopTest.cpp
  test/unittest/rtps/reader/WriterProxyTests.cpp
  test/unittest/rtps/security/SecurityTests.hpp
Labels: ci-pending

#4817 [21055] Automatically unmatch remote participants on participant deletion
  src/cpp/rtps/builtin/BuiltinProtocols.cpp
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  src/cpp/rtps/builtin/discovery/participant/PDP.h
  test/blackbox/common/DDSBlackboxTestsBasic.cpp
Labels: ready-to-merge

#4771 [20993] Fix ShmTransport buffer recovery MacOS flaky test
  test/unittest/transport/SharedMemTests.cpp
Labels: ready-to-merge

#4705 [20818] Make ResourceEvent private
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer.hpp
  src/cpp/rtps/builtin/discovery/participant/timedevent/DSClientEvent.cpp
  src/cpp/rtps/builtin/discovery/participant/timedevent/DServerEvent.cpp
  src/cpp/rtps/builtin/liveliness/WLP.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.h
  src/cpp/rtps/reader/RTPSReader.cpp
  src/cpp/rtps/resources/ResourceEvent.cpp
  src/cpp/rtps/resources/ResourceEvent.h
  src/cpp/rtps/resources/TimedEvent.cpp
  src/cpp/rtps/writer/StatefulWriter.cpp
  test/mock/dds/DomainParticipantImpl/fastdds/domain/DomainParticipantImpl.hpp
  test/mock/rtps/RTPSParticipant/fastdds/rtps/participant/RTPSParticipant.h
  test/mock/rtps/RTPSParticipantImpl/rtps/participant/RTPSParticipantImpl.h
  test/mock/rtps/ResourceEvent/rtps/resources/ResourceEvent.h
  test/mock/rtps/StatefulReader/rtps/reader/StatefulReader.hpp
  test/unittest/rtps/reader/WriterProxyStopTest.cpp
  test/unittest/rtps/resources/timedevent/TimedEventTests.cpp
  test/unittest/rtps/writer/LivelinessManagerTests.cpp
  test/unittest/statistics/rtps/MonitorServiceTests.cpp
Labels: ready-to-merge

#4854 [21092] Run selected VS tool on Windows CI
  .github/workflows/reusable-windows-ci.yml
Labels: ready-to-merge

#4853 [21092] Remove Windows v141 / VS 2017 build from master / 3.x CI
  .github/workflows/reusable-windows-ci.yml
Labels: needs-review

#4862 [21055] Minor fix in DDSBlackboxTestsBasic.cpp
  test/blackbox/common/DDSBlackboxTestsBasic.cpp
Labels: ready-to-merge

#4701 [20817] Remove unnecessary header and make private SecurityException and Exception
  examples/cpp/rtps/AsSocket/TestReaderSocket.h
  examples/cpp/rtps/AsSocket/TestWriterSocket.h
  examples/cpp/rtps/Persistent/TestReaderPersistent.h
  examples/cpp/rtps/Persistent/TestWriterPersistent.h
  examples/cpp/rtps/Registered/TestReaderRegistered.h
  examples/cpp/rtps/Registered/TestWriterRegistered.h
  include/fastdds/dds/core/policy/ParameterTypes.hpp
  include/fastdds/dds/domain/DomainParticipant.hpp
  include/fastdds/rtps/common/Property.h
  include/fastdds/rtps/common/all_common.h
  include/fastdds/rtps/network/SenderResource.h
  include/fastdds/rtps/rtps_fwd.h
  include/fastrtps/qos/ParameterTypes.h
  src/cpp/CMakeLists.txt
  src/cpp/fastdds/domain/DomainParticipant.cpp
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.cpp
  src/cpp/rtps/exceptions/Exception.cpp
  src/cpp/rtps/exceptions/Exception.h
  src/cpp/rtps/messages/MessageReceiver.h
  src/cpp/rtps/security/SecurityManager.cpp
  src/cpp/rtps/security/authentication/Authentication.h
  src/cpp/rtps/security/cryptography/CryptoKeyExchange.h
  src/cpp/rtps/security/cryptography/CryptoKeyFactory.h
  src/cpp/rtps/security/cryptography/CryptoTransform.h
  src/cpp/rtps/security/cryptography/CryptoTypes.h
  src/cpp/rtps/security/exceptions/SecurityException.cpp
  src/cpp/rtps/security/exceptions/SecurityException.h
  src/cpp/rtps/security/logging/Logging.cpp
  src/cpp/rtps/security/logging/Logging.h
  src/cpp/rtps/security/logging/LoggingLevel.cpp
  src/cpp/rtps/security/logging/LoggingLevel.h
  src/cpp/rtps/transport/tcp/RTCPMessageManager.h
  src/cpp/security/cryptography/AESGCMGMAC_KeyExchange.cpp
  src/cpp/security/cryptography/AESGCMGMAC_Types.h
  src/cpp/security/logging/LogTopic.h
  test/blackbox/common/RTPSAsSocketReader.hpp
  test/blackbox/common/RTPSWithRegistrationReader.hpp
  test/mock/rtps/MessageReceiver/rtps/messages/MessageReceiver.h
  test/performance/video/VideoTestTypes.hpp
  test/unittest/dds/publisher/CMakeLists.txt
  test/unittest/rtps/security/CMakeLists.txt
  test/unittest/security/accesscontrol/CMakeLists.txt
  test/unittest/security/authentication/CMakeLists.txt
  test/unittest/security/logging/CMakeLists.txt
  test/unittest/statistics/dds/CMakeLists.txt
Labels: ready-to-merge

#4871 Fix PDP & EDP unittest compilation
  test/unittest/rtps/discovery/EdpTests.cpp
  test/unittest/rtps/discovery/PDPTests.cpp
Labels: ready-to-merge

#4869 [20821] Make rtps writer impl private
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupManager.cpp
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPClient.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPServer.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPServerListeners.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPSimple.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPSimpleListeners.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPUtils.hpp
  src/cpp/rtps/builtin/discovery/participant/DS/DiscoveryServerPDPEndpoints.hpp
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
  src/cpp/rtps/builtin/discovery/participant/simple/SimplePDPEndpoints.hpp
  src/cpp/rtps/builtin/discovery/participant/simple/SimplePDPEndpointsSecure.hpp
  src/cpp/rtps/builtin/liveliness/WLP.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/security/SecurityManager.cpp
  src/cpp/rtps/transport/tcp/RTCPMessageManager.h
  src/cpp/rtps/writer/PersistentWriter.cpp
  src/cpp/rtps/writer/PersistentWriter.hpp
  src/cpp/rtps/writer/ReaderProxy.cpp
  src/cpp/rtps/writer/StatefulPersistentWriter.cpp
  src/cpp/rtps/writer/StatefulPersistentWriter.hpp
  src/cpp/rtps/writer/StatefulWriter.cpp
  src/cpp/rtps/writer/StatefulWriter.hpp
  src/cpp/rtps/writer/StatelessPersistentWriter.cpp
  src/cpp/rtps/writer/StatelessPersistentWriter.hpp
  src/cpp/rtps/writer/StatelessWriter.cpp
  src/cpp/rtps/writer/StatelessWriter.hpp
  src/cpp/statistics/rtps/monitor-service/MonitorService.hpp
  test/mock/rtps/MessageReceiver/rtps/messages/MessageReceiver.h
  test/mock/rtps/StatefulWriter/rtps/writer/StatefulWriter.hpp
  test/mock/rtps/StatelessWriter/rtps/writer/StatelessWriter.hpp
  test/unittest/dds/publisher/DataWriterTests.cpp
  test/unittest/rtps/security/SecurityTests.hpp
  test/unittest/rtps/writer/CMakeLists.txt
  test/unittest/rtps/writer/ReaderProxyTests.cpp
  test/unittest/statistics/rtps/mock/StatisticsBase/statistics/rtps/monitor-service/MonitorService.hpp
Labels: ci-pending

#4822 [21065] Bugfix: correct liveliness state in a multiple reader - one writer scenario
  src/cpp/rtps/builtin/liveliness/WLP.cpp
  src/cpp/rtps/reader/StatefulReader.cpp
  src/cpp/rtps/reader/StatelessReader.cpp
  src/cpp/rtps/writer/LivelinessManager.cpp
  src/cpp/rtps/writer/LivelinessManager.hpp
  test/blackbox/common/BlackboxTestsLivelinessQos.cpp
  test/unittest/rtps/writer/LivelinessManagerTests.cpp
Labels: ready-to-merge

#4835 [20815] Only apply content filter to ALIVE changes
  src/cpp/CMakeLists.txt
  src/cpp/fastdds/publisher/filtering/ReaderFilterCollection.hpp
  src/cpp/rtps/reader/StatefulReader.cpp
  src/cpp/rtps/reader/StatelessReader.cpp
  src/cpp/rtps/reader/reader_utils.cpp
  src/cpp/rtps/reader/reader_utils.hpp
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/blackbox/api/dds-pim/PubSubWriter.hpp
  test/blackbox/common/DDSBlackboxTestsContentFilter.cpp
  test/unittest/dds/publisher/CMakeLists.txt
  test/unittest/statistics/dds/CMakeLists.txt
Labels: ready-to-merge

#4843 [21081] AllocTest in 3.x
  test/profiling/allocations/AllocTestPublisher.cpp
  test/profiling/allocations/AllocTestPublisher.hpp
  test/profiling/allocations/AllocTestSubscriber.cpp
  test/profiling/allocations/AllocTestSubscriber.hpp
  test/profiling/allocations/test_xml_profile.xml
Labels: no-test, ci-pending
