Repository eProsima/Fast-DDS, pull requests merged in 2024-11, with the labels that each got.

#5355 [21959] Check if `SHM` transport is disabled in `LARGE_DATA` modes
  src/cpp/rtps/attributes/RTPSParticipantAttributes.cpp
Labels: ready-to-merge

#5360 [21725] Update examples CMakeList to force default CMAKE_BUILD_TYPE
  examples/cpp/configuration/CMakeLists.txt
  examples/cpp/content_filter/CMakeLists.txt
  examples/cpp/custom_payload_pool/CMakeLists.txt
  examples/cpp/delivery_mechanisms/CMakeLists.txt
  examples/cpp/discovery_server/CMakeLists.txt
  examples/cpp/flow_control/CMakeLists.txt
  examples/cpp/hello_world/CMakeLists.txt
  examples/cpp/request_reply/CMakeLists.txt
  examples/cpp/rtps/CMakeLists.txt
  examples/cpp/security/CMakeLists.txt
  examples/cpp/static_edp_discovery/CMakeLists.txt
  examples/cpp/topic_instances/CMakeLists.txt
  examples/cpp/xtypes/CMakeLists.txt
Labels: ci-pending

#5345 [21841] Extended Incompatible QoS for Monitor Service Feature implementation
  src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDP.h
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  src/cpp/rtps/builtin/discovery/participant/PDP.h
  src/cpp/statistics/rtps/monitor-service/MonitorService.cpp
  src/cpp/statistics/rtps/monitor-service/MonitorService.hpp
  src/cpp/statistics/rtps/monitor-service/MonitorServiceListener.cpp
  src/cpp/statistics/rtps/monitor-service/MonitorServiceListener.hpp
  src/cpp/statistics/rtps/monitor-service/interfaces/IProxyObserver.hpp
  test/mock/rtps/PDP/rtps/builtin/discovery/participant/PDP.h
  test/unittest/statistics/rtps/mock/StatisticsBase/statistics/rtps/StatisticsBase.hpp
  test/unittest/statistics/rtps/mock/StatisticsBase/statistics/rtps/monitor-service/MonitorService.hpp
Labels: versions-pending, ci-pending

#5383 [22054] Address `XMLDynamicParser` regression
  src/cpp/xmlparser/XMLDynamicParser.cpp
  test/unittest/xmlparser/XMLParserTests.cpp
  test/unittest/xmlparser/regressions/22054_profile_bin.xml
Labels: ci-pending

#5385 [21706] Feature: Extended incompatible QoS for monitor service
  include/fastdds/statistics/monitorservice_types.idl
  src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDP.h
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  src/cpp/rtps/builtin/discovery/participant/PDP.h
  src/cpp/statistics/rtps/monitor-service/MonitorService.cpp
  src/cpp/statistics/rtps/monitor-service/MonitorService.hpp
  src/cpp/statistics/rtps/monitor-service/MonitorServiceListener.cpp
  src/cpp/statistics/rtps/monitor-service/MonitorServiceListener.hpp
  src/cpp/statistics/rtps/monitor-service/interfaces/IProxyObserver.hpp
  src/cpp/statistics/types/monitorservice_types.hpp
  src/cpp/statistics/types/monitorservice_typesCdrAux.hpp
  src/cpp/statistics/types/monitorservice_typesCdrAux.ipp
  src/cpp/statistics/types/monitorservice_typesPubSubTypes.cxx
  src/cpp/statistics/types/monitorservice_typesPubSubTypes.hpp
  src/cpp/statistics/types/monitorservice_typesTypeObjectSupport.cxx
  src/cpp/statistics/types/monitorservice_typesTypeObjectSupport.hpp
  test/blackbox/common/DDSBlackboxTestsMonitorService.cpp
  test/blackbox/types/statistics/monitorservice_types.hpp
  test/blackbox/types/statistics/monitorservice_typesCdrAux.hpp
  test/blackbox/types/statistics/monitorservice_typesCdrAux.ipp
  test/blackbox/types/statistics/monitorservice_typesPubSubTypes.cxx
  test/blackbox/types/statistics/monitorservice_typesPubSubTypes.hpp
  test/blackbox/types/statistics/monitorservice_typesTypeObjectSupport.cxx
  test/blackbox/types/statistics/monitorservice_typesTypeObjectSupport.hpp
  test/mock/rtps/PDP/rtps/builtin/discovery/participant/PDP.h
  test/unittest/statistics/rtps/mock/StatisticsBase/statistics/rtps/StatisticsBase.hpp
  test/unittest/statistics/rtps/mock/StatisticsBase/statistics/rtps/monitor-service/MonitorService.hpp
  versions.md
Labels: ci-pending

#5386 [22033] Release `participant_stateless` secure builtin writer history change when authentication has finished
  src/cpp/rtps/security/SecurityManager.cpp
  src/cpp/rtps/security/SecurityManager.h
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/blackbox/api/dds-pim/PubSubWriter.hpp
  test/blackbox/common/BlackboxTestsSecurity.cpp
Labels: ci-pending

#5395 [21755] Bump version to 2.10.6
  CMakeLists.txt
  package.xml
Labels: skip-ci

#5384 [22024] Improve `OpenSSL` lifecycle handling
  src/cpp/rtps/RTPSDomainImpl.hpp
  src/cpp/rtps/security/SecurityManager.cpp
  src/cpp/security/OpenSSLInit.hpp
  test/blackbox/common/BlackboxTestsSecurity.cpp
Labels: ci-pending

#5407 [21755] Update latest 2.10.x to 2.10.6
  RELEASE_SUPPORT.md
Labels: skip-ci

#5382 [22056] Transform locators using new machine_id PID
  include/fastdds/dds/core/policy/ParameterTypes.hpp
  src/cpp/CMakeLists.txt
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupManager.cpp
  src/cpp/rtps/builtin/data/ParticipantProxyData.cpp
  src/cpp/rtps/builtin/data/ParticipantProxyData.hpp
  src/cpp/rtps/builtin/data/ReaderProxyData.cpp
  src/cpp/rtps/builtin/data/ReaderProxyData.hpp
  src/cpp/rtps/builtin/data/WriterProxyData.cpp
  src/cpp/rtps/builtin/data/WriterProxyData.hpp
  src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPSimple.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPSimpleListeners.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPStatic.cpp
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPClient.h
  src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
  src/cpp/rtps/builtin/liveliness/WLP.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/security/SecurityManager.cpp
  src/cpp/rtps/transport/TCPTransportInterface.cpp
  src/cpp/rtps/transport/TCPTransportInterface.h
  src/cpp/rtps/transport/tcp/RTCPMessageManager.cpp
  src/cpp/utils/Host.cpp
  src/cpp/utils/Host.hpp
  src/cpp/utils/SystemInfo.hpp
  test/mock/rtps/ParticipantProxyData/rtps/builtin/data/ParticipantProxyData.hpp
  test/mock/rtps/ReaderProxyData/rtps/builtin/data/ReaderProxyData.hpp
  test/mock/rtps/WriterProxyData/rtps/builtin/data/WriterProxyData.hpp
  test/unittest/dds/publisher/CMakeLists.txt
  test/unittest/dds/status/CMakeLists.txt
  test/unittest/dds/xtypes/type_lookup_service/CMakeLists.txt
  test/unittest/dds/xtypes/type_lookup_service/TypeLookupServiceTests.cpp
  test/unittest/rtps/attributes/CMakeLists.txt
  test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
  test/unittest/rtps/builtin/CMakeLists.txt
  test/unittest/rtps/common/CMakeLists.txt
  test/unittest/rtps/discovery/CMakeLists.txt
  test/unittest/rtps/network/CMakeLists.txt
  test/unittest/rtps/reader/CMakeLists.txt
  test/unittest/security/authentication/CMakeLists.txt
  test/unittest/statistics/dds/CMakeLists.txt
  test/unittest/statistics/rtps/CMakeLists.txt
  test/unittest/transport/CMakeLists.txt
  test/unittest/transport/TCPv4Tests.cpp
  test/unittest/utils/CMakeLists.txt
  test/unittest/utils/SystemInfoTests.cpp
  tools/fds/server.cpp
  versions.md
Labels: ready-to-merge

#5401 [21698] Add -v or --version to cli command tool
  package.xml
  test/system/tools/fastdds/CMakeLists.txt
  test/system/tools/fastdds/tests.py
  tools/fastdds/discovery/parser.py
  tools/fastdds/fastdds.py
  tools/fds/server.cpp
  tools/fds/server.h
Labels: ci-pending

#5341 Fix `-Werror=template-id-cdtor`
  thirdparty/filewatch/FileWatch.hpp
Labels: ready-to-merge, no-test

#5397 [21886] Feature: Windows ci example testing
  .github/workflows/reusable-windows-ci.yml
  examples/cpp/hello_world/CLIParser.hpp
  examples/cpp/hello_world/PublisherApp.cpp
  examples/cpp/hello_world/PublisherApp.hpp
  test/examples/CMakeLists.txt
  test/examples/configuration.compose.yml
  test/examples/content_filter.compose.yml
  test/examples/custom_payload_pool.compose.yml
  test/examples/delivery_mechanisms.compose.yml
  test/examples/delivery_mechanisms_isolated.compose.yml
  test/examples/discovery_server.compose.yml
  test/examples/flow_control.compose.yml
  test/examples/hello_world.compose.yml
  test/examples/request_reply.compose.yml
  test/examples/request_reply_isolated.compose.yml
  test/examples/rtps.compose.yml
  test/examples/security.compose.yml
  test/examples/static_edp_discovery.compose.yml
  test/examples/test_hello_world.py
  test/examples/topic_instances.compose.yml
  test/examples/windows/Dockerfile
  test/examples/xtypes_complete.compose.yml
  test/examples/xtypes_minimal.compose.yml
  versions.md
Labels: needs-review, ci-pending

#5424 [21891] Correct examples on README
  README.md
Labels: skip-ci

#5410 [22056] Fix TCP discovery server locators translation (backport #5382)
  src/cpp/rtps/security/SecurityManager.cpp
  src/cpp/rtps/transport/TCPTransportInterface.cpp
  src/cpp/rtps/transport/TCPTransportInterface.h
  src/cpp/rtps/transport/tcp/RTCPMessageManager.cpp
  test/unittest/transport/TCPv4Tests.cpp
  tools/fds/server.cpp
Labels: needs-review, ci-pending

#5427 Regenerate types with Fast DDS-Gen v3.3.1
  examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfigurationPubSubTypes.cxx
  examples/cpp/dds/BasicConfigurationExample/HelloWorldPubSubTypes.cxx
  examples/cpp/dds/Configurability/samplePubSubTypes.cxx
  examples/cpp/dds/ContentFilteredTopicExample/HelloWorldPubSubTypes.cxx
  examples/cpp/dds/CustomListenerExample/TopicPubSubTypes.cxx
  examples/cpp/dds/CustomPayloadPoolExample/CustomPayloadPoolDataPubSubTypes.cxx
  examples/cpp/dds/DeadlineQoSExample/deadlinepayloadPubSubTypes.cxx
  examples/cpp/dds/DisablePositiveACKs/TopicPubSubTypes.cxx
  examples/cpp/dds/DiscoveryServerExample/types/HelloWorldPubSubTypes.cxx
  examples/cpp/dds/Filtering/FilteringExamplePubSubTypes.cxx
  examples/cpp/dds/FlowControlExample/FlowControlExample.h
  examples/cpp/dds/FlowControlExample/FlowControlExamplePubSubTypes.cxx
  examples/cpp/dds/HelloWorldExample/HelloWorldPubSubTypes.cxx
  examples/cpp/dds/HelloWorldExampleDataSharing/HelloWorldPubSubTypes.cxx
  examples/cpp/dds/HelloWorldExampleSharedMem/HelloWorld.h
  examples/cpp/dds/HelloWorldExampleSharedMem/HelloWorldPubSubTypes.cxx
  examples/cpp/dds/HelloWorldExampleTCP/HelloWorldPubSubTypes.cxx
  examples/cpp/dds/HistoryKind/samplePubSubTypes.cxx
  examples/cpp/dds/Keys/samplePubSubTypes.cxx
  examples/cpp/dds/LateJoiners/samplePubSubTypes.cxx
  examples/cpp/dds/LifespanQoSExample/LifespanPubSubTypes.cxx
  examples/cpp/dds/LivelinessQoS/TopicPubSubTypes.cxx
  examples/cpp/dds/OwnershipStrengthQoSExample/OwnershipStrengthPubSubTypes.cxx
  examples/cpp/dds/RequestReplyExample/CalculatorPubSubTypes.cxx
  examples/cpp/dds/RequestReplyExample/CalculatorPubSubTypes.h
  examples/cpp/dds/SampleConfig_Controller/samplePubSubTypes.cxx
  examples/cpp/dds/SampleConfig_Events/samplePubSubTypes.cxx
  examples/cpp/dds/SampleConfig_Multimedia/samplePubSubTypes.cxx
  examples/cpp/dds/SecureHelloWorldExample/HelloWorldPubSubTypes.cxx
  examples/cpp/dds/StaticHelloWorldExample/HelloWorldPubSubTypes.cxx
  examples/cpp/dds/WriterLoansExample/LoanableHelloWorldPubSubTypes.cxx
  examples/cpp/dds/ZeroCopyExample/LoanableHelloWorldPubSubTypes.cxx
  src/cpp/statistics/types/monitorservice_typesPubSubTypes.cxx
  src/cpp/statistics/types/typesPubSubTypes.cxx
  test/blackbox/types/Data1mbPubSubTypes.cxx
  test/blackbox/types/Data64kbPubSubTypes.cxx
  test/blackbox/types/FixedSizedPubSubTypes.cxx
  test/blackbox/types/HelloWorldPubSubTypes.cxx
  test/blackbox/types/KeyedData1mbPubSubTypes.cxx
  test/blackbox/types/KeyedHelloWorldPubSubTypes.cxx
  test/blackbox/types/StringTestPubSubTypes.cxx
  test/blackbox/types/TestRegression3361PubSubTypes.cxx
  test/blackbox/types/UnboundedHelloWorldPubSubTypes.cxx
  test/blackbox/types/statistics/typesPubSubTypes.cxx
  test/profiling/allocations/AllocTestTypePubSubTypes.cxx
  test/unittest/dds/topic/DDSSQLFilter/data_types/ContentFilterTestTypePubSubTypes.cxx
  test/unittest/dynamic_types/idl/BasicPubSubTypes.cxx
  test/unittest/dynamic_types/idl/BasicPubSubTypes.h
  test/unittest/dynamic_types/idl/TestPubSubTypes.cxx
  test/unittest/dynamic_types/idl/new_features_4_2PubSubTypes.cxx
  test/unittest/xtypes/idl/TypesPubSubTypes.cxx
  test/unittest/xtypes/idl/TypesPubSubTypes.h
  test/unittest/xtypes/idl/WideEnumPubSubTypes.cxx
  test/unittest/xtypes/idl/WideEnumPubSubTypes.h
  test/xtypes/idl/TypesPubSubTypes.cxx
  test/xtypes/idl/TypesPubSubTypes.h
Labels: ready-to-merge

#5413 [22280] New property to select preferred key agreement algorithm
  src/cpp/security/authentication/PKIDH.cpp
  test/blackbox/common/BlackboxTestsSecurity.cpp
  test/dds/communication/security/secure_msg_crypto_besteffort_pub_profile.xml
  test/dds/communication/security/secure_msg_submsg_crypto_besteffort_pub_profile.xml
  test/dds/communication/security/secure_msg_submsg_crypto_besteffort_sub_profile.xml
  test/dds/communication/security/secure_submsg_crypto_besteffort_pub_profile.xml
  test/dds/communication/security/secure_submsg_crypto_besteffort_sub_profile.xml
  test/dds/communication/security/simple_secure_besteffort_pub_profile.xml
  test/dds/communication/security/simple_secure_besteffort_sub_profile.xml
  test/unittest/security/authentication/AuthenticationPluginTests.hpp
  test/unittest/security/authentication/BuiltinPKIDHTests.cpp
  versions.md
Labels: ready-to-merge

#5429 [21506] Allow domain names (DNS) when parsing TCP locators XML elements
  src/cpp/utils/IPLocator.cpp
  src/cpp/xmlparser/XMLElementParser.cpp
  test/unittest/utils/LocatorTests.cpp
  test/unittest/xmlparser/CMakeLists.txt
  test/unittest/xmlparser/XMLElementParserTests.cpp
Labels: ci-pending

#5435 [22341] Fix `cmake` generator evaluation
  src/cpp/CMakeLists.txt
Labels: no-test, ci-pending

#5412 [21924] Roadmap update
  roadmap.md
Labels: skip-ci
