Repository eProsima/Fast-DDS, pull requests merged in 2024-10, with the labels that each got.

#5285 Bump version to 3.1.0
  .github/pull_request_template.md
  .github/workflows/mirror.yml
  .github/workflows/nightly-mac-ci.yml
  .github/workflows/nightly-sanitizers-ci.yml
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/nightly-windows-ci.yml
  CMakeLists.txt
  package.xml
  src/cpp/rtps/messages/MessageReceiver.cpp
Labels: ready-to-merge, no-test, first-to-merge

#5286 Branch out 3.0.x
  .github/workflows/mac-ci.yml
  .github/workflows/mirror.yml
  .github/workflows/nightly-mac-ci.yml
  .github/workflows/nightly-sanitizers-ci.yml
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/nightly-windows-ci.yml
  .github/workflows/reusable-ubuntu-ci.yml
  .github/workflows/sanitizers-ci.yml
  .github/workflows/ubuntu-ci.yml
  .github/workflows/weekly-mac-ci.yml
  .github/workflows/weekly-sanitizers-ci.yml
  .github/workflows/weekly-ubuntu-ci.yml
  .github/workflows/weekly-windows-ci.yml
  .github/workflows/windows-ci.yml
  fastdds.repos
Labels: no-test, first-to-merge, ci-pending

#5220 [21479] Allow runing CI on external contributions
  .github/workflows/reusable-mac-ci.yml
  .github/workflows/reusable-sanitizers-ci.yml
  .github/workflows/reusable-ubuntu-ci.yml
  .github/workflows/reusable-windows-ci.yml
  .github/workflows/ubuntu-ci.yml
Labels: skip-ci

#5224 [21538] Allow all `durability` configurations
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.cpp
  src/cpp/fastdds/topic/TopicImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/blackbox/api/dds-pim/PubSubWriter.hpp
  test/blackbox/common/DDSBlackboxTestsListeners.cpp
  test/blackbox/common/DDSBlackboxTestsPersistence.cpp
  test/blackbox/common/RTPSBlackboxTestsPersistence.cpp
  test/blackbox/common/RTPSBlackboxTestsPersistenceNonIntraprocess.cpp
  test/blackbox/common/RTPSWithRegistrationReader.hpp
  test/blackbox/common/RTPSWithRegistrationWriter.hpp
  test/unittest/dds/participant/ParticipantTests.cpp
  test/unittest/dds/publisher/DataWriterTests.cpp
  test/unittest/dds/subscriber/DataReaderTests.cpp
  versions.md
Labels: ready-to-merge

#5292 [21789] Split nightly jobs to one per workflow
  .github/workflows/nightly-mac-2.10.x.yml
  .github/workflows/nightly-mac-2.14.x.yml
  .github/workflows/nightly-mac-3.0.x.yml
  .github/workflows/nightly-mac-ci.yml
  .github/workflows/nightly-mac-master.yml
  .github/workflows/nightly-sanitizers-2.10.x.yml
  .github/workflows/nightly-sanitizers-2.14.x.yml
  .github/workflows/nightly-sanitizers-3.0.x.yml
  .github/workflows/nightly-sanitizers-ci.yml
  .github/workflows/nightly-sanitizers-master.yml
  .github/workflows/nightly-ubuntu-2.10.x.yml
  .github/workflows/nightly-ubuntu-2.14.x.yml
  .github/workflows/nightly-ubuntu-3.0.x.yml
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/nightly-ubuntu-master.yml
  .github/workflows/nightly-windows-2.10.x.yml
  .github/workflows/nightly-windows-2.14.x.yml
  .github/workflows/nightly-windows-3.0.x.yml
  .github/workflows/nightly-windows-ci.yml
  .github/workflows/nightly-windows-master.yml
  .github/workflows/weekly-mac-2.6.x.yml
  .github/workflows/weekly-sanitizers-2.6.x.yml
  .github/workflows/weekly-ubuntu-2.14.x.yml
  .github/workflows/weekly-ubuntu-2.6.x.yml
  .github/workflows/weekly-windows-2.6.x.yml
Labels: skip-ci

#5293 [21790] Add references to new nightly jobs per supported branch in README
  README.md
Labels: skip-ci

#5140 [21564] [21666] Change `xsd` files installation directory to `share/fastdds` and remove icons on windows uninstall
  CMakeLists.txt
  tools/fastdds/xml_ci/parser.py
  tools/fds/CMakeLists.txt
Labels: ready-to-merge, no-test

#5282 [17283] Fix issues in Dynamic Network Interfaces
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  src/cpp/rtps/builtin/discovery/participant/PDP.h
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  test/dds/communication/CMakeLists.txt
  test/dds/communication/PubSubMain.cpp
  test/dds/communication/PublisherMain.cpp
  test/dds/communication/PublisherModule.cpp
  test/dds/communication/PublisherModule.hpp
  test/dds/communication/SubscriberMain.cpp
  test/dds/communication/SubscriberModule.cpp
  test/dds/communication/SubscriberModule.hpp
  test/dds/communication/dyn_network/CMakeLists.txt
  test/dds/communication/dyn_network/Dockerfile
  test/dds/communication/dyn_network/dynamic_interfaces.compose.yml
  test/dds/communication/dyn_network/launch_subscriber.bash
  test/dds/communication/security/PublisherMain.cpp
  test/dds/communication/security/PublisherModule.cpp
  test/dds/communication/security/PublisherModule.hpp
  test/dds/communication/security/SubscriberMain.cpp
  test/dds/communication/security/SubscriberModule.cpp
  test/dds/communication/security/SubscriberModule.hpp
Labels: ready-to-merge

#5187 Update json.hpp
  thirdparty/nlohmann-json/nlohmann/json.hpp
Labels: ready-to-merge

#5295 [21745] Fix flow_controllers comparison in DomainParticipantQos equality operator
  include/fastdds/dds/domain/qos/DomainParticipantQos.hpp
  include/fastdds/rtps/flowcontrol/FlowControllerDescriptor.hpp
  src/cpp/fastdds/domain/qos/DomainParticipantQos.cpp
  test/unittest/dds/participant/ParticipantTests.cpp
  versions.md
Labels: ci-pending

#5307 [21802] Fix CreateTopicWithDifferentTypeName_negative flaky test
  test/unittest/dds/participant/ParticipantTests.cpp
Labels: ci-pending

#5264 [21710] DataWriter/Reader get_matched_publication/subscription() Test implementation
  include/fastdds/rtps/participant/RTPSParticipant.h
  include/fastdds/rtps/reader/RTPSReader.h
  include/fastdds/rtps/writer/RTPSWriter.h
  src/cpp/rtps/participant/RTPSParticipant.cpp
  src/cpp/rtps/reader/RTPSReader.cpp
  src/cpp/rtps/writer/RTPSWriter.cpp
  test/blackbox/api/dds-pim/PubSubParticipant.hpp
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/blackbox/api/dds-pim/PubSubWriter.hpp
  test/blackbox/common/BlackboxTests.cpp
  test/blackbox/common/BlackboxTests.hpp
  test/blackbox/common/BlackboxTestsDiscovery.cpp
  test/blackbox/common/BlackboxTestsPubSubBasic.cpp
  test/blackbox/common/BlackboxTestsSecurity.cpp
  test/blackbox/common/DDSBlackboxTestsDataReader.cpp
  test/blackbox/common/DDSBlackboxTestsDataWriter.cpp
  test/blackbox/common/DDSBlackboxTestsPersistence.cpp
  test/blackbox/common/RTPSBlackboxTests.cpp
  test/blackbox/common/RTPSBlackboxTestsBasic.cpp
  test/blackbox/common/RTPSBlackboxTestsReader.cpp
  test/blackbox/common/RTPSBlackboxTestsWriter.cpp
  test/blackbox/common/RTPSWithRegistrationReader.hpp
  test/blackbox/common/RTPSWithRegistrationWriter.hpp
  test/mock/rtps/RTPSParticipant/fastdds/rtps/participant/RTPSParticipant.h
Labels: no-test, ci-pending

#5306 [21783] Regenerate types with latest Fast DDS-Gen v4.0.2
  include/fastdds/dds/xtypes/type_representation/detail/dds_xtypes_typeobject.hpp
  src/cpp/fastdds/builtin/type_lookup_service/detail/TypeLookupTypes.hpp
  src/cpp/statistics/types/monitorservice_types.hpp
  src/cpp/statistics/types/types.hpp
  test/blackbox/types/core/core_types.hpp
  test/blackbox/types/statistics/monitorservice_types.hpp
  test/blackbox/types/statistics/types.hpp
  test/dds-types-test/declarations.hpp
  test/dds-types-test/external.hpp
  test/dds-types-test/helpers/basic_inner_types.hpp
  test/dds-types-test/unions.hpp
  test/unittest/dds/xtypes/serializers/idl/types/union_struct/gen/union_struct.hpp
  test/unittest/dds/xtypes/serializers/json/types/comprehensive_type/gen/ComprehensiveType.hpp
Labels: ready-to-merge

#5284 [21711] DataWriter/Reader `get_matched_publication/subscription...()` Feature implementation
  include/fastdds/dds/publisher/DataWriter.hpp
  include/fastdds/dds/subscriber/DataReader.hpp
  include/fastdds/rtps/participant/RTPSParticipant.h
  include/fastdds/rtps/reader/RTPSReader.h
  include/fastdds/rtps/reader/StatefulReader.h
  include/fastdds/rtps/reader/StatelessReader.h
  include/fastdds/rtps/writer/RTPSWriter.h
  include/fastdds/rtps/writer/StatefulWriter.h
  include/fastdds/rtps/writer/StatelessWriter.h
  src/cpp/CMakeLists.txt
  src/cpp/fastdds/publisher/DataWriter.cpp
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/publisher/DataWriterImpl.hpp
  src/cpp/fastdds/subscriber/DataReader.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.hpp
  src/cpp/rtps/builtin/data/ProxyDataConverters.cpp
  src/cpp/rtps/builtin/data/ProxyDataConverters.hpp
  src/cpp/rtps/participant/RTPSParticipant.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.h
  src/cpp/rtps/reader/RTPSReader.cpp
  src/cpp/rtps/reader/StatefulReader.cpp
  src/cpp/rtps/reader/StatelessReader.cpp
  src/cpp/rtps/writer/StatefulWriter.cpp
  src/cpp/rtps/writer/StatelessWriter.cpp
  test/blackbox/api/fastrtps_deprecated/PubSubWriter.hpp
  test/mock/rtps/RTPSReader/fastdds/rtps/reader/RTPSReader.h
  test/mock/rtps/RTPSWriter/fastdds/rtps/writer/RTPSWriter.h
  test/unittest/dds/publisher/CMakeLists.txt
  test/unittest/dds/publisher/DataWriterTests.cpp
  test/unittest/dds/subscriber/DataReaderTests.cpp
  test/unittest/statistics/dds/CMakeLists.txt
  test/unittest/statistics/dds/StatisticsDomainParticipantStatusQueryableTests/mock/fastdds/publisher/DataWriterImpl.hpp
  versions.md
Labels: ci-pending

#5310 [21828] Warn instead of fail when `dds.communication.dynamic_interfaces` cannot be built
  test/dds/communication/dyn_network/CMakeLists.txt
Labels: ready-to-merge

#5256 [21745] Add QoS getters from raw XML
  include/fastdds/dds/domain/DomainParticipant.hpp
  include/fastdds/dds/domain/DomainParticipantFactory.hpp
  include/fastdds/dds/publisher/Publisher.hpp
  include/fastdds/dds/subscriber/Subscriber.hpp
  src/cpp/fastdds/domain/DomainParticipant.cpp
  src/cpp/fastdds/domain/DomainParticipantFactory.cpp
  src/cpp/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/fastdds/domain/DomainParticipantImpl.hpp
  src/cpp/fastdds/publisher/Publisher.cpp
  src/cpp/fastdds/publisher/PublisherImpl.cpp
  src/cpp/fastdds/publisher/PublisherImpl.hpp
  src/cpp/fastdds/subscriber/Subscriber.cpp
  src/cpp/fastdds/subscriber/SubscriberImpl.cpp
  src/cpp/fastdds/subscriber/SubscriberImpl.hpp
  src/cpp/xmlparser/XMLProfileManager.cpp
  src/cpp/xmlparser/XMLProfileManager.h
  test/mock/dds/DomainParticipantImpl/fastdds/domain/DomainParticipantImpl.hpp
  test/unittest/dds/participant/CMakeLists.txt
  test/unittest/dds/participant/ParticipantTests.cpp
  test/unittest/dds/profiles/test_xml_profile.xml
  test/unittest/dds/publisher/CMakeLists.txt
  test/unittest/dds/publisher/PublisherTests.cpp
  test/unittest/dds/subscriber/CMakeLists.txt
  test/unittest/dds/subscriber/SubscriberTests.cpp
  test/utils/FileUtils.hpp
Labels: ready-to-merge

#5315 Fix wrong Data type referred in flow control example README
  examples/cpp/flow_control/README.md
Labels: skip-ci

#5318 [21783] Update roadmap, release support and versions for `v3.1.0` release
  RELEASE_SUPPORT.md
  roadmap.md
  versions.md
Labels: skip-ci

#5320 [21890] Update commercial support section in readme
  README.md
Labels: skip-ci

#5325 [21856] Address `oss fuzz` `XMLParser` regression
  src/cpp/xmlparser/XMLDynamicParser.cpp
  test/unittest/xmlparser/XMLParserTests.cpp
  test/unittest/xmlparser/regressions/21856_profile_bin.xml
Labels: ci-pending

#5327 [21900] Fix DataReaderHistory regression
  src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
Labels: ready-to-merge

#5336 [21882] Branch out 3.2.x
  .github/pull_request_template.md
  .github/workflows/mirror.yml
  .github/workflows/nightly-mac-3.1.x.yml
  .github/workflows/nightly-sanitizers-3.1.x.yml
  .github/workflows/nightly-ubuntu-3.1.x.yml
  .github/workflows/nightly-windows-3.1.x.yml
  CMakeLists.txt
  package.xml
Labels: skip-ci

#5337 [21882] Branch out 3.1.x
  .github/workflows/mac-ci.yml
  .github/workflows/mirror.yml
  .github/workflows/nightly-mac-2.10.x.yml
  .github/workflows/nightly-mac-2.14.x.yml
  .github/workflows/nightly-mac-3.0.x.yml
  .github/workflows/nightly-mac-master.yml
  .github/workflows/nightly-sanitizers-2.10.x.yml
  .github/workflows/nightly-sanitizers-2.14.x.yml
  .github/workflows/nightly-sanitizers-3.0.x.yml
  .github/workflows/nightly-sanitizers-master.yml
  .github/workflows/nightly-ubuntu-2.10.x.yml
  .github/workflows/nightly-ubuntu-2.14.x.yml
  .github/workflows/nightly-ubuntu-3.0.x.yml
  .github/workflows/nightly-ubuntu-master.yml
  .github/workflows/nightly-windows-2.10.x.yml
  .github/workflows/nightly-windows-2.14.x.yml
  .github/workflows/nightly-windows-3.0.x.yml
  .github/workflows/nightly-windows-master.yml
  .github/workflows/reusable-ubuntu-ci.yml
  .github/workflows/sanitizers-ci.yml
  .github/workflows/ubuntu-ci.yml
  .github/workflows/weekly-mac-2.6.x.yml
  .github/workflows/weekly-sanitizers-2.6.x.yml
  .github/workflows/weekly-ubuntu-2.14.x.yml
  .github/workflows/weekly-ubuntu-2.6.x.yml
  .github/workflows/weekly-windows-2.6.x.yml
  .github/workflows/windows-ci.yml
  README.md
  fastdds.repos
Labels: skip-ci

#5339 Revert bump to 3.2.0
  CMakeLists.txt
  package.xml
Labels: skip-ci

#5351 Legacy redundunt TypeLookupSettings removed from mock
  test/mock/rtps/RTPSParticipantAttributes/fastdds/rtps/attributes/RTPSParticipantAttributes.hpp
Labels: ci-pending

#5312 [21808] DataWriter/Reader `get_matched_publication/subscription()` Tests & Feature 3.x
  include/fastdds/rtps/participant/RTPSParticipant.hpp
  include/fastdds/rtps/reader/RTPSReader.hpp
  include/fastdds/rtps/writer/RTPSWriter.hpp
  src/cpp/fastdds/publisher/DataWriter.cpp
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/publisher/DataWriterImpl.hpp
  src/cpp/fastdds/subscriber/DataReader.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.hpp
  src/cpp/rtps/participant/RTPSParticipant.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.h
  src/cpp/rtps/reader/StatefulReader.cpp
  src/cpp/rtps/reader/StatefulReader.hpp
  src/cpp/rtps/reader/StatelessReader.cpp
  src/cpp/rtps/reader/StatelessReader.hpp
  src/cpp/rtps/writer/StatefulWriter.cpp
  src/cpp/rtps/writer/StatefulWriter.hpp
  src/cpp/rtps/writer/StatelessWriter.cpp
  src/cpp/rtps/writer/StatelessWriter.hpp
  test/blackbox/api/dds-pim/PubSubParticipant.hpp
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/blackbox/api/dds-pim/PubSubWriter.hpp
  test/blackbox/common/BlackboxTests.cpp
  test/blackbox/common/BlackboxTests.hpp
  test/blackbox/common/BlackboxTestsDiscovery.cpp
  test/blackbox/common/BlackboxTestsPubSubBasic.cpp
  test/blackbox/common/BlackboxTestsSecurity.cpp
  test/blackbox/common/DDSBlackboxTestsDataReader.cpp
  test/blackbox/common/DDSBlackboxTestsDataWriter.cpp
  test/blackbox/common/DDSBlackboxTestsPersistence.cpp
  test/blackbox/common/RTPSBlackboxTests.cpp
  test/blackbox/common/RTPSBlackboxTestsBasic.cpp
  test/blackbox/common/RTPSBlackboxTestsReader.cpp
  test/blackbox/common/RTPSBlackboxTestsWriter.cpp
  test/blackbox/common/RTPSWithRegistrationReader.hpp
  test/blackbox/common/RTPSWithRegistrationWriter.hpp
  test/mock/rtps/RTPSParticipant/fastdds/rtps/participant/RTPSParticipant.hpp
  test/mock/rtps/RTPSReader/fastdds/rtps/reader/RTPSReader.hpp
  test/mock/rtps/RTPSWriter/fastdds/rtps/writer/RTPSWriter.hpp
  test/unittest/dds/publisher/DataWriterTests.cpp
  test/unittest/dds/subscriber/DataReaderTests.cpp
  test/unittest/statistics/dds/StatisticsDomainParticipantStatusQueryableTests/mock/fastdds/publisher/DataWriterImpl.hpp
  versions.md
Labels: ready-to-merge

#5356 [21997] Rename `RTPSParticipantImpl.h` to `RTPSParticipantImpl.hpp`
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupManager.cpp
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupReplyListener.cpp
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupRequestListener.cpp
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.cpp
  src/cpp/rtps/RTPSDomain.cpp
  src/cpp/rtps/builtin/BuiltinProtocols.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPSimpleListeners.h
  src/cpp/rtps/builtin/discovery/endpoint/EDPStatic.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDPUtils.hpp
  src/cpp/rtps/builtin/discovery/participant/DS/FakeWriter.hpp
  src/cpp/rtps/builtin/discovery/participant/DS/PDPSecurityInitiatorListener.cpp
  src/cpp/rtps/builtin/discovery/participant/DirectMessageSender.cpp
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPClientListener.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPEndpoints.hpp
  src/cpp/rtps/builtin/discovery/participant/PDPListener.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServerListener.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
  src/cpp/rtps/builtin/discovery/participant/timedevent/DSClientEvent.cpp
  src/cpp/rtps/builtin/discovery/participant/timedevent/DServerEvent.cpp
  src/cpp/rtps/builtin/liveliness/WLP.cpp
  src/cpp/rtps/flowcontrol/FlowControllerImpl.hpp
  src/cpp/rtps/messages/MessageReceiver.cpp
  src/cpp/rtps/messages/RTPSMessageGroup.cpp
  src/cpp/rtps/messages/SendBuffersManager.cpp
  src/cpp/rtps/participant/RTPSParticipant.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.hpp
  src/cpp/rtps/reader/BaseReader.cpp
  src/cpp/rtps/reader/RTPSReader.cpp
  src/cpp/rtps/reader/StatefulReader.cpp
  src/cpp/rtps/reader/StatelessReader.cpp
  src/cpp/rtps/reader/WriterProxy.cpp
  src/cpp/rtps/security/SecurityManager.cpp
  src/cpp/rtps/writer/BaseWriter.cpp
  src/cpp/rtps/writer/RTPSWriter.cpp
  src/cpp/rtps/writer/ReaderLocator.cpp
  src/cpp/rtps/writer/ReaderProxy.cpp
  src/cpp/rtps/writer/StatefulWriter.cpp
  src/cpp/rtps/writer/StatelessWriter.cpp
  src/cpp/statistics/rtps/StatisticsBase.cpp
  test/mock/rtps/RTPSParticipantImpl/rtps/participant/RTPSParticipantImpl.hpp
  test/unittest/dds/xtypes/type_lookup_service/TypeLookupServiceTests.cpp
  test/unittest/rtps/discovery/EdpTests.cpp
  test/unittest/rtps/discovery/PDPTests.cpp
  test/unittest/rtps/reader/WriterProxyAcknackTests.cpp
  test/unittest/rtps/reader/WriterProxyStopTest.cpp
  test/unittest/rtps/reader/WriterProxyTests.cpp
  test/unittest/rtps/security/SecurityTests.hpp
  test/unittest/statistics/rtps/RTPSStatisticsTests.cpp
Labels: ready-to-merge

#5034 [21293] Fix destruction data-race on participant removal in intra-process
  src/cpp/rtps/RTPSDomain.cpp
  src/cpp/rtps/RTPSDomainImpl.hpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.hpp
  src/cpp/rtps/reader/BaseReader.cpp
  src/cpp/rtps/reader/BaseReader.hpp
  src/cpp/rtps/reader/LocalReaderPointer.hpp
  src/cpp/rtps/writer/ReaderLocator.cpp
  src/cpp/rtps/writer/ReaderLocator.hpp
  src/cpp/rtps/writer/ReaderProxy.hpp
  src/cpp/rtps/writer/StatefulWriter.cpp
  src/cpp/rtps/writer/StatelessWriter.cpp
  src/cpp/utils/RefCountedPointer.hpp
  test/blackbox/common/DDSBlackboxTestsBasic.cpp
  test/mock/rtps/ReaderLocator/rtps/writer/ReaderLocator.hpp
  test/unittest/utils/CMakeLists.txt
  test/unittest/utils/RefCountedPointerTests.cpp
Labels: ready-to-merge

#5329 [21696] Fix `SecurityManager` assertion in `Secure DS`
  src/cpp/rtps/security/SecurityManager.cpp
  test/dds/communication/security/CMakeLists.txt
  test/dds/communication/security/multiple_secure_ds_pubsub_secure_crypto_communication.py
Labels: ready-to-merge

#5257 [21696] Fix Secure Discovery Server client disposals guid and handshake_handle assertion
  src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
  src/cpp/rtps/security/SecurityManager.cpp
  test/dds/communication/security/CMakeLists.txt
  test/dds/communication/security/PublisherMain.cpp
  test/dds/communication/security/PublisherModule.cpp
  test/dds/communication/security/PublisherModule.hpp
  test/dds/communication/security/multiple_secure_ds_pubsub_secure_crypto_communication.py
Labels: ci-pending
