Repository eProsima/Fast-DDS, pull requests merged in 2024-09, with the labels that each got.

#5179 [21512] Set string arguments as const references
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
Labels: ci-pending

#5018 [21314] Improve resilience against clock adjustments
  src/cpp/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/fastdds/domain/DomainParticipantImpl.hpp
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.cpp
  src/cpp/rtps/writer/StatefulWriter.cpp
  src/cpp/rtps/writer/StatefulWriter.hpp
  src/cpp/utils/SystemInfo.cpp
  src/cpp/utils/time_t_helpers.hpp
Labels: ready-to-merge

#5178 [21514] Make Fast DDS build compatible with gcc9
  src/cpp/fastdds/xtypes/dynamic_types/AnnotationDescriptorImpl.hpp
Labels: ready-to-merge

#5181 [21563] TypeLookupService: also register the minimal created from the received complete TypeObject
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupReplyListener.cpp
  src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.cpp
  test/unittest/dds/xtypes/type_representation/TypeObjectUtilsTests.cpp
Labels: ready-to-merge

#5186 [21535] Use eProsima-CI action to install Qt
  .github/workflows/reusable-ubuntu-ci.yml
Labels: needs-review, ci-pending

#5213 [21609] Revert behavior change on `current_time_since_unix_epoch`
  src/cpp/utils/time_t_helpers.hpp
Labels: ci-pending

#5182 [21519] Fix issue with exclusive ownership and unordered samples
  src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
  test/blackbox/common/DDSBlackboxTestsOwnershipQos.cpp
  test/unittest/dds/subscriber/DataReaderHistoryTests.cpp
Labels: ready-to-merge

#5217 [21624] Fix compilation errors in Ubuntu 24.04 using `-Werror`
  CMakeLists.txt
  test/mock/rtps/NetworkFactory/rtps/network/NetworkFactory.hpp
  test/mock/rtps/RTPSParticipantImpl/rtps/participant/RTPSParticipantImpl.h
  test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
  test/unittest/rtps/discovery/CMakeLists.txt
  test/unittest/rtps/discovery/EdpTests.cpp
  test/unittest/rtps/security/SecurityTests.hpp
Labels: ready-to-merge

#5223 [21636] Regenerate types with Fast DDS-Gen v4.0.1
  include/fastdds/dds/xtypes/type_representation/detail/dds_xtypes_typeobject.hpp
  src/cpp/fastdds/builtin/type_lookup_service/detail/TypeLookupTypes.hpp
  src/cpp/statistics/types/monitorservice_types.hpp
  src/cpp/statistics/types/types.hpp
  test/blackbox/types/core/core_types.hpp
  test/blackbox/types/statistics/monitorservice_types.hpp
  test/blackbox/types/statistics/types.hpp
  test/dds-types-test/constants.hpp
  test/dds-types-test/declarations.hpp
  test/dds-types-test/external.hpp
  test/dds-types-test/helpers/basic_inner_types.hpp
  test/dds-types-test/unions.hpp
  test/unittest/dds/xtypes/serializers/idl/types/union_struct/gen/union_struct.hpp
  test/unittest/dds/xtypes/serializers/json/types/comprehensive_type/gen/ComprehensiveType.hpp
Labels: ready-to-merge

#5226 [21649] Correct iterator increment after erasing elements in `connected_servers_list`
  src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
Labels: ready-to-merge

#5227 [21561] Bump version to 3.0.1
  CMakeLists.txt
  package.xml
Labels: skip-ci

#5237 [21671] Update request reply example `README`
  examples/cpp/request_reply/README.md
Labels: skip-ci

#5243 [21652] Fix xtypes example segfault if xml env var is not set
  examples/cpp/xtypes/PublisherApp.cpp
Labels: ready-to-merge

#5245 [21706] Remove unused `validMatching` methods in `EDP`
  src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDP.h
Labels: ready-to-merge, no-test

#5246 [21720] Modify help command of XML CLI tool
  tools/fastdds/xml_ci/parser.py
Labels: ready-to-merge, no-test

#5253 [21740] Register and propagate MonitorService status type object
  src/cpp/statistics/rtps/monitor-service/MonitorService.cpp
Labels: ci-pending

#5263 [21557] Bump version to 2.10.5
  CMakeLists.txt
  package.xml
  versions.md
Labels: skip-ci

#5268 [21557] Update latest 2.10.x to 2.10.5
  RELEASE_SUPPORT.md
Labels: skip-ci

#5262 [21751] Discard changes with big key-only payload and no key hash
  src/cpp/rtps/messages/MessageReceiver.cpp
  src/cpp/rtps/reader/reader_utils.cpp
  test/blackbox/common/BlackboxTestsTransportUDP.cpp
Labels: ci-pending

#5273 [21760] Fix memory leak deleting TypeLookupManager
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupManager.cpp
Labels: ready-to-merge

#5281 [21471] Convert Fast DDS v2 to v3 Migration Changes into a Step-by-Step User Guide
  UPGRADING.md
Labels: ready-to-merge
