Repository eProsima/Fast-DDS, pull requests merged in 2025-02, with the labels that each got.

#5618 [22648] Unacknowledged sample removed in KeepAll mode
  src/cpp/fastdds/publisher/DataWriterHistory.cpp
  test/blackbox/common/DDSBlackboxTestsListeners.cpp
Labels: ci-pending

#5592 [22735] Make the machine id the physical data host info
  src/cpp/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/statistics/fastdds/domain/DomainParticipantImpl.cpp
Labels: ready-to-merge

#5611 [22624] System Log error: infinite loop when setting thread affinity fails
  src/cpp/utils/threading/thread_logging.hpp
  src/cpp/utils/threading/threading_osx.ipp
  src/cpp/utils/threading/threading_pthread.ipp
  src/cpp/utils/threading/threading_win32.ipp
  test/unittest/logging/LogTests.cpp
Labels: ci-pending

#5600 [22704] Support compiler MSYS2-MinGW
  CMakeLists.txt
  include/fastdds/fastdds_dll.hpp
  include/fastdds/utils/TimedMutex.hpp
  src/cpp/fastdds/xtypes/serializers/json/dynamic_data_json.cpp
  src/cpp/utils/SystemInfo.cpp
  src/cpp/utils/TimedConditionVariable.cpp
  src/cpp/utils/shared_memory/RobustExclusiveLock.hpp
  src/cpp/utils/shared_memory/RobustSharedLock.hpp
  thirdparty/filewatch/FileWatch.hpp
Labels: ready-to-merge

#5631 [22756] Fix error handling logic in `try_setting_buffer_size`
  src/cpp/rtps/transport/asio_helpers.hpp
Labels: ci-pending

#5640 [22651] Update dds-types-test submodule instead of fail build
  test/feature/idl_parser/CMakeLists.txt
Labels: skip-ci

#5639 [22514] Bump version to 3.1.2
  CMakeLists.txt
  package.xml
  versions.md
Labels: no-test

#5646 [22809] Avoid redefinition warning for `OPENSSL_API_COMPAT`
  src/cpp/rtps/transport/TCPAcceptorSecure.h
  src/cpp/rtps/transport/TCPChannelResourceSecure.h
  src/cpp/rtps/transport/TCPTransportInterface.h
  src/cpp/security/artifact_providers/Pkcs11Provider.cpp
  src/cpp/security/authentication/PKIDH.cpp
  test/unittest/security/authentication/BuiltinPKIDHTests.cpp
Labels: ci-pending

#5637 Fix for DDS Examples: Configurability
  examples/cpp/dds/Configurability/ConfigurabilityPublisher.cpp
Labels: no-test

#5653 [21627] Bump version to v3.0.2
  CMakeLists.txt
  package.xml
  versions.md
Labels: no-test, ci-pending

#5656 [21627] Update `RELEASE_SUPPORT` ref to 3.0.2
  RELEASE_SUPPORT.md
Labels: skip-ci

#5604 [22604] Filter interested readers on PDP writer
  src/cpp/CMakeLists.txt
  src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
  src/cpp/rtps/builtin/discovery/participant/simple/PDPStatelessWriter.cpp
  src/cpp/rtps/builtin/discovery/participant/simple/PDPStatelessWriter.hpp
  src/cpp/rtps/builtin/discovery/participant/simple/SimplePDPEndpoints.hpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/writer/StatelessWriter.cpp
  src/cpp/rtps/writer/StatelessWriter.hpp
  test/blackbox/common/BlackboxTestsDiscovery.cpp
  test/blackbox/common/DDSBlackboxTestsMonitorService.cpp
  test/unittest/dds/publisher/CMakeLists.txt
  test/unittest/rtps/reader/CMakeLists.txt
  test/unittest/statistics/dds/CMakeLists.txt
Labels: ci-pending

#5419 Remove repeated header include & Fix log
  src/cpp/rtps/transport/TCPTransportInterface.cpp
Labels: no-test, ci-pending

#5665 [22627] Fix build after #5593
  test/unittest/dds/participant/ParticipantTests.cpp
Labels: no-test, ci-pending
