Repository eProsima/Fast-DDS, pull requests merged in 2025-03, with the labels that each got.

#5668 [22843]+[22844] Solve fuzz XMLParser Null-dereference
  src/cpp/xmlparser/XMLDynamicParser.cpp
  test/unittest/xmlparser/XMLParserTests.cpp
  test/unittest/xmlparser/regressions/22843_profile_bin.xml
  test/unittest/xmlparser/regressions/22844_profile_bin.xml
Labels: ci-pending

#5681 Review `FASTDDS_TODO_BEFORE` for release 3.2.0
  include/fastdds/rtps/common/Types.hpp
  src/cpp/fastdds/core/policy/ParameterList.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl/ReadTakeCommand.hpp
  src/cpp/rtps/messages/MessageReceiver.cpp
Labels: no-test, ci-pending

#5673 [22729] Flush logs in CliDiscoveryManager
  tools/fds/CliDiscoveryManager.cpp
  tools/fds/CliDiscoveryManager.hpp
Labels: ready-to-merge

#5319 Fix cleanup race condition with exclusive and shared lock files
  src/cpp/utils/shared_memory/RobustExclusiveLock.hpp
  src/cpp/utils/shared_memory/RobustSharedLock.hpp
Labels: ci-pending

#5696 [22903] Remove SHM option from discovery server example
  examples/cpp/discovery_server/CLIParser.hpp
  examples/cpp/discovery_server/ClientPublisherApp.cpp
  examples/cpp/discovery_server/ClientSubscriberApp.cpp
  examples/cpp/discovery_server/Helpers.hpp
  examples/cpp/discovery_server/ServerApp.cpp
Labels: ci-pending

#5702 [21614] Fix Security tag in DS CLI
  tools/fds/server.cpp
Labels: needs-review, ci-pending

#5706 [22938] Add missing `psutil` python module in sanitizers ci
  .github/workflows/reusable-sanitizers-ci.yml
Labels: ci-pending

#5672 [22710] Filter interested readers on PDP writer (backport #5604)
  include/fastdds/rtps/writer/StatelessWriter.h
  src/cpp/CMakeLists.txt
  src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
  src/cpp/rtps/builtin/discovery/participant/simple/PDPStatelessWriter.cpp
  src/cpp/rtps/builtin/discovery/participant/simple/PDPStatelessWriter.hpp
  src/cpp/rtps/builtin/discovery/participant/simple/SimplePDPEndpoints.hpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/writer/StatelessWriter.cpp
  test/blackbox/api/dds-pim/PubSubParticipant.hpp
  test/blackbox/api/fastrtps_deprecated/PubSubParticipant.hpp
  test/blackbox/common/BlackboxTestsDiscovery.cpp
  test/blackbox/common/DDSBlackboxTestsListeners.cpp
  test/blackbox/common/DDSBlackboxTestsMonitorService.cpp
  test/unittest/dds/publisher/CMakeLists.txt
  test/unittest/statistics/dds/CMakeLists.txt
Labels: ci-pending

#5689 [22872] Configure ROS 2 Easy Mode via C++ and XML
  include/fastdds/dds/core/policy/QosPolicies.hpp
  include/fastdds/rtps/attributes/RTPSParticipantAttributes.hpp
  resources/xsd/fastdds_profiles.xsd
  src/cpp/fastdds/utils/QosConverters.cpp
  src/cpp/rtps/attributes/ServerAttributes.cpp
  src/cpp/rtps/attributes/ServerAttributes.hpp
  src/cpp/xmlparser/XMLParser.cpp
  src/cpp/xmlparser/XMLParserCommon.cpp
  src/cpp/xmlparser/XMLParserCommon.h
  test/blackbox/common/DDSBlackboxTestsDSEasyMode.cpp
  test/mock/rtps/RTPSParticipantAttributes/fastdds/rtps/attributes/RTPSParticipantAttributes.hpp
  test/unittest/xmlparser/XMLParserTests.cpp
  test/unittest/xmlparser/XMLProfileParserTests.cpp
  test/unittest/xmlparser/test_xml_deprecated.xml
  test/unittest/xmlparser/test_xml_profile.xml
  test/unittest/xmlparser/test_xml_profile_env_var.xml
  test/unittest/xmlparser/test_xml_rooted_deprecated.xml
  test/unittest/xmlparser/test_xml_rooted_profile.xml
  versions.md
Labels: ci-pending

#5680 [22849] Builtin flow controller
  include/fastdds/rtps/attributes/RTPSParticipantAttributes.hpp
  resources/xsd/fastdds_profiles.xsd
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupManager.cpp
  src/cpp/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  src/cpp/rtps/builtin/discovery/participant/PDP.h
  src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
  src/cpp/rtps/builtin/liveliness/WLP.cpp
  src/cpp/rtps/flowcontrol/FlowControllerImpl.hpp
  src/cpp/xmlparser/XMLElementParser.cpp
  test/blackbox/api/dds-pim/PubSubParticipant.hpp
  test/blackbox/api/dds-pim/PubSubWriter.hpp
  test/blackbox/common/BlackboxTestsDiscovery.cpp
  test/blackbox/common/BlackboxTestsPubSubFlowControllers.cpp
  test/dds/xtypes/BaseCases/Case11.json
  test/dds/xtypes/BaseCases/Case12.json
  test/dds/xtypes/TypeLookupServicePublisher.cpp
  test/dds/xtypes/TypeLookupServicePublisher.h
  test/dds/xtypes/TypeLookupServiceSubscriber.cpp
  test/dds/xtypes/TypeLookupServiceSubscriber.h
  test/dds/xtypes/TypeLookupService_main.cpp
  test/dds/xtypes/test_build.py
  test/mock/rtps/RTPSParticipantAttributes/fastdds/rtps/attributes/RTPSParticipantAttributes.hpp
  versions.md
Labels: ci-pending

#5716 [22937] Fix `several_writers_on_unack_sample_removed` flaky test
  test/blackbox/common/DDSBlackboxTestsListeners.cpp
Labels: ci-pending

#5720 [22858] Update types with Fast DDS Gen v4.0.4
  test/dds-types-test/aliasesPubSubTypes.cxx
  test/dds-types-test/annotationsPubSubTypes.cxx
  test/dds-types-test/appendablePubSubTypes.cxx
  test/dds-types-test/arraysPubSubTypes.cxx
  test/dds-types-test/bitsetsPubSubTypes.cxx
  test/dds-types-test/constantsPubSubTypes.cxx
  test/dds-types-test/declarationsPubSubTypes.cxx
  test/dds-types-test/enumerationsPubSubTypes.cxx
  test/dds-types-test/externalPubSubTypes.cxx
  test/dds-types-test/finalPubSubTypes.cxx
  test/dds-types-test/helpers/basic_inner_typesPubSubTypes.cxx
  test/dds-types-test/inheritancePubSubTypes.cxx
  test/dds-types-test/keyPubSubTypes.cxx
  test/dds-types-test/mapsPubSubTypes.cxx
  test/dds-types-test/member_idPubSubTypes.cxx
  test/dds-types-test/mutablePubSubTypes.cxx
  test/dds-types-test/optionalPubSubTypes.cxx
  test/dds-types-test/primitivesPubSubTypes.cxx
  test/dds-types-test/sequencesPubSubTypes.cxx
  test/dds-types-test/stringsPubSubTypes.cxx
  test/dds-types-test/structuresPubSubTypes.cxx
  test/dds-types-test/unionsPubSubTypes.cxx
Labels: ci-pending

#5691 [22893] Add modules support to idl_serialize
  src/cpp/fastdds/xtypes/serializers/idl/dynamic_type_idl.cpp
  src/cpp/fastdds/xtypes/serializers/idl/dynamic_type_idl.hpp
  test/unittest/dds/xtypes/serializers/idl/DynTypeIDLTests.cpp
  test/unittest/dds/xtypes/serializers/idl/types/alias_struct/alias_struct.idl
  test/unittest/dds/xtypes/serializers/idl/types/alias_struct/gen/alias_structTypeObjectSupport.cxx
  test/unittest/dds/xtypes/serializers/idl/types/all_types.hpp
  test/unittest/dds/xtypes/serializers/idl/types/array_struct/array_struct.idl
  test/unittest/dds/xtypes/serializers/idl/types/array_struct/gen/array_structTypeObjectSupport.cxx
  test/unittest/dds/xtypes/serializers/idl/types/bitmask_struct/bitmask_struct.idl
  test/unittest/dds/xtypes/serializers/idl/types/bitmask_struct/gen/bitmask_structTypeObjectSupport.cxx
  test/unittest/dds/xtypes/serializers/idl/types/bitset_struct/bitset_struct.idl
  test/unittest/dds/xtypes/serializers/idl/types/bitset_struct/gen/bitset_structTypeObjectSupport.cxx
  test/unittest/dds/xtypes/serializers/idl/types/enum_struct/enum_struct.idl
  test/unittest/dds/xtypes/serializers/idl/types/enum_struct/gen/enum_structTypeObjectSupport.cxx
  test/unittest/dds/xtypes/serializers/idl/types/extensibility_struct/extensibility_struct.idl
  test/unittest/dds/xtypes/serializers/idl/types/extensibility_struct/gen/extensibility_structTypeObjectSupport.cxx
  test/unittest/dds/xtypes/serializers/idl/types/key_struct/gen/key_structTypeObjectSupport.cxx
  test/unittest/dds/xtypes/serializers/idl/types/key_struct/key_struct.idl
  test/unittest/dds/xtypes/serializers/idl/types/map_struct/gen/map_structTypeObjectSupport.cxx
  test/unittest/dds/xtypes/serializers/idl/types/map_struct/map_struct.idl
  test/unittest/dds/xtypes/serializers/idl/types/module_struct/gen/module_struct.hpp
  test/unittest/dds/xtypes/serializers/idl/types/module_struct/gen/module_structCdrAux.hpp
  test/unittest/dds/xtypes/serializers/idl/types/module_struct/gen/module_structCdrAux.ipp
  test/unittest/dds/xtypes/serializers/idl/types/module_struct/gen/module_structPubSubTypes.cxx
  test/unittest/dds/xtypes/serializers/idl/types/module_struct/gen/module_structPubSubTypes.hpp
  test/unittest/dds/xtypes/serializers/idl/types/module_struct/gen/module_structTypeObjectSupport.cxx
  test/unittest/dds/xtypes/serializers/idl/types/module_struct/gen/module_structTypeObjectSupport.hpp
  test/unittest/dds/xtypes/serializers/idl/types/module_struct/module_struct.idl
  test/unittest/dds/xtypes/serializers/idl/types/primitives_struct/gen/primitives_structTypeObjectSupport.cxx
  test/unittest/dds/xtypes/serializers/idl/types/primitives_struct/primitives_struct.idl
  test/unittest/dds/xtypes/serializers/idl/types/sequence_struct/gen/sequence_structTypeObjectSupport.cxx
  test/unittest/dds/xtypes/serializers/idl/types/sequence_struct/sequence_struct.idl
  test/unittest/dds/xtypes/serializers/idl/types/string_struct/gen/string_structTypeObjectSupport.cxx
  test/unittest/dds/xtypes/serializers/idl/types/string_struct/string_struct.idl
  test/unittest/dds/xtypes/serializers/idl/types/struct_struct/gen/struct_structTypeObjectSupport.cxx
  test/unittest/dds/xtypes/serializers/idl/types/struct_struct/struct_struct.idl
  test/unittest/dds/xtypes/serializers/idl/types/union_struct/gen/union_structTypeObjectSupport.cxx
  test/unittest/dds/xtypes/serializers/idl/types/union_struct/union_struct.idl
Labels: ci-pending

#5724 [22964] Refactor builtin writers & readers creation (backport #5723)
  include/fastdds/rtps/builtin/discovery/participant/PDP.h
  src/cpp/fastdds/builtin/typelookup/TypeLookupManager.cpp
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
  src/cpp/rtps/builtin/liveliness/WLP.cpp
Labels: ci-pending

#5723 [22964] Refactor builtin writers & readers creation
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupManager.cpp
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  src/cpp/rtps/builtin/discovery/participant/PDP.h
  src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
  src/cpp/rtps/builtin/liveliness/WLP.cpp
Labels: ready-to-merge, ci-pending

#5725 [22974] Improve SHM configuration on large data transports
  include/fastdds/rtps/transport/shared_mem/SharedMemTransportDescriptor.hpp
  src/cpp/rtps/attributes/RTPSParticipantAttributes.cpp
  src/cpp/rtps/transport/shared_mem/SharedMemTransport.cpp
Labels: ci-pending

#5722 [22858] Bump version to 3.2.0
  CMakeLists.txt
  package.xml
Labels: ready-to-merge, no-test, ci-pending

#5733 Reduce trace category when failing to unregister type
  src/cpp/fastdds/domain/DomainParticipantImpl.cpp
Labels: ci-pending

#5701 [22873] Setup ROS 2 Easy Mode at participant creation
  include/fastdds/rtps/RTPSDomain.hpp
  src/cpp/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/rtps/RTPSDomain.cpp
  src/cpp/rtps/RTPSDomainImpl.hpp
  test/blackbox/api/dds-pim/PubSubParticipant.hpp
  test/blackbox/common/DDSBlackboxTestsDSEasyMode.cpp
  test/unittest/dds/participant/CMakeLists.txt
  test/unittest/dds/participant/ParticipantTests.cpp
  test/unittest/dds/profiles/test_xml_easy_mode_config.xml
Labels: ci-pending
