Repository eProsima/Fast-DDS, pull requests merged in 2025-04, with the labels that each got.

#5738 [22995] Fix `MacOS` nightly flaky tests
  test/blackbox/common/BlackboxTestsDiscovery.cpp
  test/blackbox/common/DDSBlackboxTestsMonitorService.cpp
Labels: ci-pending

#5735 IDL parsing tests included paths
  test/feature/idl_parser/CMakeLists.txt
  test/feature/idl_parser/IdlParserTests.cpp
  test/feature/idl_parser/no_path_included.idl
Labels: ready-to-merge

#5730 [22955] Get correct Fast CDR related branch in CI
  .github/workflows/reusable-mac-ci.yml
  .github/workflows/reusable-sanitizers-ci.yml
  .github/workflows/reusable-windows-ci.yml
Labels: ready-to-merge, no-test

#5750 Update excluded idl files from fastdds gen CI
  utils/scripts/update_generated_code_from_idl.sh
Labels: no-test, ci-pending

#5751 [23011] Fix `monitor_service_advanced_extended_incompatible_qos` test
  test/blackbox/common/DDSBlackboxTestsMonitorService.cpp
Labels: ci-pending

#5754 [22959] Bump version to 3.2.1
  CMakeLists.txt
  package.xml
Labels: skip-ci

#5749 [23008] Update CLI commands for Easy Mode
  test/system/tools/fastdds/CMakeLists.txt
  test/system/tools/fastdds/test_discovery_parser.py
  tools/fastdds/discovery/fastdds_daemon/process_handler/process_handler.py
  tools/fastdds/discovery/parser.py
  tools/fds/CliDiscoveryEntrypoint.cpp
  tools/fds/CliDiscoveryManager.cpp
  tools/fds/CliDiscoveryManager.hpp
  tools/fds/CliDiscoveryParser.hpp
Labels: ready-to-merge

#5744 [22592] Fix windows example tests in `Debug` and mitigate `rtps` example flakiness
  examples/cpp/hello_world/PublisherApp.cpp
  examples/cpp/hello_world/hello_world_profile.xml
  examples/cpp/rtps/ReaderApp.cpp
  examples/cpp/rtps/WriterApp.cpp
  test/examples/windows/Dockerfile
Labels: ci-pending

#5760 [23048] Fix `related_sample_identity` handling in RPC entities
  src/cpp/fastdds/rpc/ReplierImpl.cpp
  src/cpp/fastdds/rpc/RequesterImpl.cpp
  test/blackbox/api/dds-pim/ReqRepHelloWorldRequester.cpp
  test/blackbox/api/dds-pim/ReqRepHelloWorldRequester.hpp
  test/blackbox/common/BlackboxTestsPubSubBasic.cpp
Labels: ci-pending

#5761 [23030] Fix oss-fuzz `XMLParserTest` over `wstring_builder` being `nullptr`
  src/cpp/xmlparser/XMLDynamicParser.cpp
  test/unittest/xmlparser/XMLParserTests.cpp
  test/unittest/xmlparser/regressions/23030_profile_bin.xml
Labels: ci-pending

#5771 [21559] Bump version to 2.6.10
  CMakeLists.txt
  package.xml
Labels: skip-ci

#5769 [23082] Force Asio Thirdparty in MacOS CI
  .github/workflows/mac-ci.yml
  .github/workflows/nightly-mac-2.10.x.yml
  .github/workflows/nightly-mac-2.14.x.yml
  .github/workflows/nightly-mac-3.1.x.yml
  .github/workflows/reusable-mac-ci.yml
  .github/workflows/weekly-mac-2.6.x.yml
Labels: no-test, ci-pending

#5770 [21559] Upgrade 2.6.x weekly Ubuntu image to 22.04
  .github/workflows/weekly-ubuntu-2.6.x.yml
Labels: ready-to-merge

#5776 [23082] Force Asio THIRDPARTY in Mac nightly master
  .github/workflows/nightly-mac-master.yml
Labels: skip-ci

#5763 [22972] Support sequences in IDL Parser
  src/cpp/fastdds/xtypes/dynamic_types/idl_parser/IdlGrammar.hpp
  src/cpp/fastdds/xtypes/dynamic_types/idl_parser/IdlParser.hpp
  test/feature/idl_parser/IdlParserTests.cpp
  versions.md
Labels: ci-pending

#5764 [22814] Improve DS routines
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantsAckStatus.cpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantsAckStatus.hpp
  src/cpp/rtps/builtin/discovery/database/DiscoverySharedInfo.cpp
  src/cpp/rtps/builtin/discovery/database/DiscoverySharedInfo.hpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer.hpp
  test/blackbox/api/dds-pim/PubSubParticipant.hpp
  test/blackbox/common/BlackboxTestsDiscovery.cpp
Labels: ready-to-merge

#5766 [23047] Always copy 'type_information' in ProxyDatas
  src/cpp/rtps/builtin/data/ReaderProxyData.cpp
  src/cpp/rtps/builtin/data/WriterProxyData.cpp
Labels: ci-pending

#5772 [21559] Update 2.6.x `RELEASE_SUPPORT` to 2.6.10
  RELEASE_SUPPORT.md
Labels: skip-ci

#5789 Move `SimpleCommunication` and `system` tests in Windows nightly
  .github/workflows/nightly-windows-master.yml
Labels: skip-ci
