Repository eProsima/Fast-DDS, pull requests merged in 2025-01, with the labels that each got.

#4943 [21397] Parse IDL file on `DynamicTypeBuilderFactory::create_type_w_uri`
  CMakeLists.txt
  include/fastdds/dds/xtypes/dynamic_types/DynamicTypeBuilderFactory.hpp
  src/cpp/fastdds/xtypes/dynamic_types/DynamicTypeBuilderFactoryImpl.cpp
  src/cpp/fastdds/xtypes/dynamic_types/DynamicTypeBuilderFactoryImpl.hpp
  src/cpp/fastdds/xtypes/dynamic_types/idl_parser/Idl.hpp
  src/cpp/fastdds/xtypes/dynamic_types/idl_parser/IdlGrammar.hpp
  src/cpp/fastdds/xtypes/dynamic_types/idl_parser/IdlModule.hpp
  src/cpp/fastdds/xtypes/dynamic_types/idl_parser/IdlParser.hpp
  src/cpp/fastdds/xtypes/dynamic_types/idl_parser/IdlPreprocessor.hpp
  test/feature/CMakeLists.txt
  test/feature/idl_parser/CMakeLists.txt
  test/feature/idl_parser/IdlParserTests.cpp
  test/feature/idl_parser/IdlParserTests.hpp.in
  test/unittest/rtps/discovery/CMakeLists.txt
  test/unittest/rtps/network/CMakeLists.txt
  test/unittest/rtps/reader/CMakeLists.txt
  test/unittest/statistics/dds/CMakeLists.txt
  test/unittest/statistics/rtps/CMakeLists.txt
  test/unittest/xmlparser/CMakeLists.txt
  versions.md
Labels: ci-pending

#5540 [22537] Fix EDP reliability timings
  src/cpp/rtps/builtin/discovery/endpoint/EDPSimple.cpp
  test/blackbox/common/DDSBlackboxTestsStatistics.cpp
Labels: ci-pending

#5550 [22545] Add test for security initialization error
  src/cpp/rtps/security/SecurityManager.cpp
  test/unittest/rtps/security/SecurityInitializationTests.cpp
Labels: ci-pending

#5558 [22596] Update submodules when cloning Fast DDS on CI
  .github/workflows/reusable-mac-ci.yml
  .github/workflows/reusable-sanitizers-ci.yml
  .github/workflows/reusable-ubuntu-ci.yml
Labels: ci-pending

#5549 [21861] Enable Datasharing segments clean from CLI
  test/system/tools/fastdds/CMakeLists.txt
  test/system/tools/fastdds/tests.py
  tools/fastdds/shm/clean.py
  tools/fastdds/shm/parser.py
  versions.md
Labels: ready-to-merge, skip-ci

#5498 [22277] Split Windows nightly tests using name filter regex
  .github/workflows/nightly-windows-master.yml
Labels: skip-ci

#5565 [22608] Fix null-dereference in `parseXMLMemberDynamicType`
  src/cpp/xmlparser/XMLDynamicParser.cpp
  test/unittest/xmlparser/XMLParserTests.cpp
  test/unittest/xmlparser/regressions/22535_profile_bin.xml
Labels: ci-pending

#5583 [22519] Decouple transport receivers creation using unique network flows
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.hpp
  test/blackbox/common/BlackboxTestsNetworkConf.cpp
Labels: high-priority, ci-pending

#5585 [22657] Fix log category name macro collision in `MacOS`
  src/cpp/fastdds/domain/DomainParticipantFactory.cpp
  src/cpp/rtps/RTPSDomain.cpp
  test/blackbox/common/DDSBlackboxTestsBasic.cpp
Labels: ci-pending

#5608 [22713] Add `replace` tag to `package.xml`
  package.xml
Labels: skip-ci

#5606 [22658] Reliable volatile change dropped when all history acked
  src/cpp/rtps/writer/StatefulWriter.cpp
  test/blackbox/api/dds-pim/PubSubWriter.hpp
  test/blackbox/common/DDSBlackboxTestsListeners.cpp
Labels: ci-pending

#5617 [22721] Increase 'max_blocking_time' in Easy Mode
  src/cpp/rtps/RTPSDomain.cpp
  test/blackbox/common/BlackboxTestsTransportCustom.cpp
  test/blackbox/common/DDSBlackboxTestsDSEasyMode.cpp
  test/unittest/dds/participant/CMakeLists.txt
  test/unittest/dds/participant/ParticipantTests.cpp
  test/unittest/dds/profiles/test_xml_service_easy_mode.xml
Labels: ready-to-merge
