Repository eProsima/Fast-DDS, pull requests merged in 2025-07, with the labels that each got.

#5897 [23372] Process key-only payloads
  include/fastdds/rtps/common/CacheChange.hpp
  include/fastdds/rtps/common/SerializedPayload.hpp
  src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
  src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterExpression.cpp
  src/cpp/rtps/DataSharing/DataSharingPayloadPool.cpp
  src/cpp/rtps/DataSharing/ReaderPool.hpp
  src/cpp/rtps/DataSharing/WriterPool.hpp
  src/cpp/rtps/common/SerializedPayload.cpp
  src/cpp/rtps/history/TopicPayloadPool.cpp
  src/cpp/rtps/messages/MessageReceiver.cpp
  src/cpp/rtps/reader/reader_utils.cpp
  test/blackbox/common/BlackboxTestsKeys.cpp
  test/unittest/dds/topic/DDSSQLFilter/DDSSQLFilterTests.cpp
  test/unittest/rtps/common/CacheChangeTests.cpp
  versions.md
Labels: ci-pending

#5909 Use WINDOWS 2022 in CI
  .github/workflows/reusable-windows-ci.yml
Labels: ci-pending

#5910 [23355] Add VS143 toolset
  .github/workflows/reusable-windows-ci.yml
  PLATFORM_SUPPORT.md
Labels: ci-pending

#5918 [23444] Install Fix OpenSSL version in windows example testing
  test/examples/windows/Dockerfile
Labels: ci-pending

#5743 [23001] 2.14.x - Avoid sending statistics msg with big msgs and no fragmentation
  src/cpp/rtps/messages/RTPSMessageGroup.cpp
  test/blackbox/CMakeLists.txt
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/blackbox/api/dds-pim/PubSubWriter.hpp
  test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
  test/blackbox/api/fastrtps_deprecated/PubSubWriter.hpp
  test/blackbox/common/BlackboxTests.hpp
  test/blackbox/common/BlackboxTestsTransportCustom.cpp
  test/blackbox/common/BlackboxTestsTransportTCP.cpp
  test/blackbox/types/Data100kb.cxx
  test/blackbox/types/Data100kb.h
  test/blackbox/types/Data100kb.idl
  test/blackbox/types/Data100kbCdrAux.hpp
  test/blackbox/types/Data100kbCdrAux.ipp
  test/blackbox/types/Data100kbPubSubTypes.cxx
  test/blackbox/types/Data100kbPubSubTypes.h
  test/blackbox/types/Data100kbv1.cxx
  test/blackbox/types/Data100kbv1.h
  test/blackbox/utils/data_generators.cpp
  test/blackbox/utils/lambda_functions.cpp
  test/blackbox/utils/print_functions.cpp
Labels: ready-to-merge

#5553 [22202] JSON to DynamicData deserializer
  include/fastdds/dds/xtypes/utils.hpp
  src/cpp/CMakeLists.txt
  src/cpp/fastdds/xtypes/CMakeLists.txt
  src/cpp/fastdds/xtypes/serializers/json/dynamic_data_json.cpp
  src/cpp/fastdds/xtypes/serializers/json/dynamic_data_json.hpp
  src/cpp/fastdds/xtypes/serializers/json/json_dynamic_data.cpp
  src/cpp/fastdds/xtypes/serializers/json/json_dynamic_data.hpp
  src/cpp/fastdds/xtypes/utils.cpp
  test/feature/dynamic_types/DynamicTypesTests.cpp
  test/unittest/dds/xtypes/serializers/json/DynDataJSONTests.cpp
  test/unittest/dds/xtypes/serializers/json/types/comprehensive_type/implementation/ComprehensiveTypeImpl.cpp
  test/unittest/dds/xtypes/serializers/json/types/comprehensive_type/json/ComprehensiveType_Filled_EPROSIMA_1.json
  test/unittest/dds/xtypes/serializers/json/types/comprehensive_type/json/ComprehensiveType_Filled_EPROSIMA_2.json
  test/unittest/dds/xtypes/serializers/json/types/comprehensive_type/json/ComprehensiveType_Filled_EPROSIMA_3.json
  test/unittest/dds/xtypes/serializers/json/types/comprehensive_type/json/ComprehensiveType_Filled_OMG_1.json
  test/unittest/dds/xtypes/serializers/json/types/comprehensive_type/json/ComprehensiveType_Filled_OMG_2.json
  test/unittest/dds/xtypes/serializers/json/types/comprehensive_type/json/ComprehensiveType_Filled_OMG_3.json
  versions.md
Labels: ci-pending

#5924 [23269] Prepare for release v3.3.0
  RELEASE_SUPPORT.md
  roadmap.md
  versions.md
Labels: skip-ci

#5926 [23459] Fix/socket buffer size handling
  src/cpp/rtps/transport/asio_helpers.hpp
  src/cpp/rtps/transport/test_UDPv4Transport.cpp
  test/blackbox/common/DDSBlackboxTestsListeners.cpp
Labels: ready-to-merge, ci-pending

#5938 [23482] Fix latency & troughput tests names
  test/performance/latency/CMakeLists.txt
  test/performance/latency/xml/interprocess_best_effort_shm_profile.xml
  test/performance/latency/xml/interprocess_best_effort_tcp_profile.xml
  test/performance/latency/xml/interprocess_best_effort_udp_profile.xml
  test/performance/latency/xml/interprocess_reliable_shm_profile.xml
  test/performance/latency/xml/interprocess_reliable_tcp_profile.xml
  test/performance/latency/xml/interprocess_reliable_udp_profile.xml
  test/performance/latency/xml/intraprocess_best_effort_profile.xml
  test/performance/latency/xml/intraprocess_reliable_profile.xml
  test/performance/throughput/CMakeLists.txt
  test/performance/throughput/xml/interprocess_best_effort_shm_profile.xml
  test/performance/throughput/xml/interprocess_best_effort_tcp_profile.xml
  test/performance/throughput/xml/interprocess_best_effort_udp_profile.xml
  test/performance/throughput/xml/interprocess_reliable_shm_profile.xml
  test/performance/throughput/xml/interprocess_reliable_tcp_profile.xml
  test/performance/throughput/xml/interprocess_reliable_udp_profile.xml
  test/performance/throughput/xml/intraprocess_best_effort_profile.xml
  test/performance/throughput/xml/intraprocess_reliable_profile.xml
Labels: no-test, ci-pending

#5940 [23515] Branch out 3.4.x
  .github/pull_request_template.md
  .github/workflows/mirror.yml
  .github/workflows/nightly-mac-3.3.x.yml
  .github/workflows/nightly-sanitizers-3.3.x .yml
  .github/workflows/nightly-ubuntu-3.3.x.yml
  .github/workflows/nightly-windows-3.3.x.yml
  RELEASE_SUPPORT.md
Labels: ci-pending

#5944 [23531] Add `--quiet` to `git submodule` invocations
  cmake/common/eprosima_libraries.cmake
Labels: no-test, ci-pending

#5933 [23432] Pass value of `TransportPriorityQosPolicy` to transport layer
  include/fastdds/dds/builtin/topic/TopicBuiltinTopicData.hpp
  include/fastdds/dds/core/policy/QosPolicies.hpp
  include/fastdds/dds/publisher/qos/DataWriterQos.hpp
  include/fastdds/dds/publisher/qos/WriterQos.hpp
  include/fastdds/dds/topic/qos/TopicQos.hpp
  include/fastdds/rtps/attributes/WriterAttributes.hpp
  include/fastdds/rtps/transport/ChainingTransport.hpp
  include/fastdds/rtps/transport/SenderResource.hpp
  include/fastdds/rtps/transport/test_UDPv4TransportDescriptor.hpp
  include/fastdds/rtps/writer/RTPSWriter.hpp
  resources/xsd/fastdds_profiles.xsd
  src/cpp/fastdds/core/policy/QosPoliciesSerializer.hpp
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/publisher/qos/DataWriterQos.cpp
  src/cpp/fastdds/utils/QosConverters.cpp
  src/cpp/rtps/builtin/data/WriterProxyData.cpp
  src/cpp/rtps/builtin/discovery/participant/DirectMessageSender.cpp
  src/cpp/rtps/builtin/discovery/participant/simple/PDPStatelessWriter.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.hpp
  src/cpp/rtps/reader/StatefulReader.cpp
  src/cpp/rtps/transport/ChainingSenderResource.hpp
  src/cpp/rtps/transport/TCPSenderResource.hpp
  src/cpp/rtps/transport/TCPTransportInterface.cpp
  src/cpp/rtps/transport/TCPTransportInterface.h
  src/cpp/rtps/transport/UDPSenderResource.hpp
  src/cpp/rtps/transport/UDPTransportInterface.cpp
  src/cpp/rtps/transport/UDPTransportInterface.h
  src/cpp/rtps/transport/shared_mem/SharedMemSenderResource.hpp
  src/cpp/rtps/transport/shared_mem/SharedMemTransport.cpp
  src/cpp/rtps/transport/shared_mem/SharedMemTransport.h
  src/cpp/rtps/transport/shared_mem/test_SharedMemTransport.cpp
  src/cpp/rtps/transport/shared_mem/test_SharedMemTransport.h
  src/cpp/rtps/transport/test_UDPv4Transport.cpp
  src/cpp/rtps/transport/test_UDPv4Transport.h
  src/cpp/rtps/writer/BaseWriter.cpp
  src/cpp/rtps/writer/BaseWriter.hpp
  src/cpp/rtps/writer/ReaderLocator.cpp
  src/cpp/rtps/writer/StatefulWriter.cpp
  src/cpp/rtps/writer/StatelessWriter.cpp
  src/cpp/rtps/writer/StatelessWriter.hpp
  src/cpp/xmlparser/XMLElementParser.cpp
  src/cpp/xmlparser/attributes/PublisherAttributes.hpp
  test/blackbox/CMakeLists.txt
  test/blackbox/api/dds-pim/PubSubWriter.hpp
  test/blackbox/common/BlackboxTestsDiscovery.cpp
  test/blackbox/common/BlackboxTestsTransportCustom.cpp
  test/blackbox/common/DDSBlackboxTestsDataWriter.cpp
  test/blackbox/common/DDSBlackboxTestsDiscovery.cpp
  test/blackbox/common/DDSBlackboxTestsTransportSHMUDP.cpp
  test/blackbox/common/DatagramInjectionTransport.hpp
  test/blackbox/transport_priority_profile.xml
  test/mock/rtps/RTPSWriter/fastdds/rtps/writer/RTPSWriter.hpp
  test/unittest/dds/publisher/PublisherTests.cpp
  test/unittest/transport/SharedMemTests.cpp
  test/unittest/transport/TCPv4Tests.cpp
  test/unittest/transport/UDPv4Tests.cpp
  test/unittest/transport/UDPv6Tests.cpp
  versions.md
Labels: ready-to-merge

#5949 [23085] Remove deprecated windows 2019 from ci in favor of 2022
  .github/workflows/reusable-windows-ci.yml
Labels: ready-to-merge

#5952 Increase the announcement period in liveliness test
  test/blackbox/common/BlackboxTestsLivelinessQos.cpp
Labels: ci-pending

#5958 [22814] Fix compatibility with Fast CDR v1
  test/blackbox/utils/filter_helpers.hpp
Labels: ready-to-merge

#5959 Add missing IDL to code generator script
  utils/scripts/update_generated_code_from_idl.sh
Labels: skip-ci
