Repository eProsima/Fast-DDS, pull requests merged in 2025-09, with the labels that each got.

#5983 [23592] Add 'tcp_negotiation_timeout' to .xsd
  resources/xsd/fastdds_profiles.xsd
Labels: ci-pending

#5974 [23569] Improve signal handling in RPC example
  examples/cpp/rpc/Application.hpp
  examples/cpp/rpc/ClientApp.hpp
  examples/cpp/rpc/ServerApp.hpp
  examples/cpp/rpc/main.cpp
Labels: ci-pending

#5977 [23573] Using original writer in statistics when possible
  src/cpp/rtps/reader/StatefulReader.cpp
  src/cpp/rtps/reader/StatelessReader.cpp
Labels: ci-pending

#6001 [23571] Removing empty qos_list from original writer as indicated in RTPS standard 2.5
  include/fastdds/rtps/common/OriginalWriterInfo.hpp
  src/cpp/fastdds/core/policy/ParameterSerializer.hpp
  versions.md
Labels: ci-pending

#5996 Fix topic argument in Discovery Server example
  examples/cpp/discovery_server/CLIParser.hpp
Labels: ci-pending

#5999 [23435] Add support for ethernet locator kind
  include/fastdds/rtps/common/Locator.hpp
  resources/xsd/fastdds_profiles.xsd
  src/cpp/CMakeLists.txt
  src/cpp/rtps/common/LocatorWithMask.cpp
  src/cpp/rtps/network/utils/external_locators.cpp
  src/cpp/utils/IPLocator.cpp
  src/cpp/xmlparser/XMLElementParser.cpp
  src/cpp/xmlparser/XMLParser.cpp
  src/cpp/xmlparser/XMLParser.h
  src/cpp/xmlparser/XMLParserCommon.cpp
  src/cpp/xmlparser/XMLParserCommon.h
  src/cpp/xmlparser/XMLParserExtras.cpp
  test/CMakeLists.txt
  test/system/tools/xmlvalidation/eth_participant_profile.xml
  test/unittest/dds/collections/CMakeLists.txt
  test/unittest/dds/core/condition/CMakeLists.txt
  test/unittest/dds/core/entity/CMakeLists.txt
  test/unittest/dds/publisher/CMakeLists.txt
  test/unittest/dds/status/CMakeLists.txt
  test/unittest/dds/subscriber/CMakeLists.txt
  test/unittest/dds/topic/DDSSQLFilter/CMakeLists.txt
  test/unittest/dds/xtypes/type_lookup_service/CMakeLists.txt
  test/unittest/logging/CMakeLists.txt
  test/unittest/logging/log_macros/CMakeLists.txt
  test/unittest/rtps/attributes/CMakeLists.txt
  test/unittest/rtps/builtin/CMakeLists.txt
  test/unittest/rtps/common/CMakeLists.txt
  test/unittest/rtps/discovery/CMakeLists.txt
  test/unittest/rtps/flowcontrol/CMakeLists.txt
  test/unittest/rtps/history/CMakeLists.txt
  test/unittest/rtps/network/CMakeLists.txt
  test/unittest/rtps/persistence/CMakeLists.txt
  test/unittest/rtps/reader/CMakeLists.txt
  test/unittest/rtps/resources/timedevent/CMakeLists.txt
  test/unittest/rtps/security/CMakeLists.txt
  test/unittest/rtps/writer/CMakeLists.txt
  test/unittest/security/accesscontrol/CMakeLists.txt
  test/unittest/security/authentication/CMakeLists.txt
  test/unittest/security/cryptography/CMakeLists.txt
  test/unittest/security/logging/CMakeLists.txt
  test/unittest/statistics/dds/CMakeLists.txt
  test/unittest/statistics/rtps/CMakeLists.txt
  test/unittest/transport/CMakeLists.txt
  test/unittest/utils/CMakeLists.txt
  test/unittest/utils/LocatorTests.cpp
  test/unittest/xmlparser/CMakeLists.txt
  versions.md
Labels: ci-pending, fast dds pro

#6031 [23647] Prepare RTPSDomainImpl to be extended
  include/fastdds/dds/domain/DomainParticipantFactory.hpp
  src/cpp/CMakeLists.txt
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupManager.cpp
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupReplyListener.cpp
  src/cpp/fastdds/builtin/type_lookup_service/TypeLookupRequestListener.cpp
  src/cpp/fastdds/domain/DomainParticipantFactory.cpp
  src/cpp/fastdds/domain/DomainParticipantImpl.cpp
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/subscriber/DataReaderImpl.cpp
  src/cpp/fastdds/xtypes/dynamic_types/DynamicPubSubType.cpp
  src/cpp/fastdds/xtypes/dynamic_types/DynamicTypeBuilderFactoryImpl.cpp
  src/cpp/fastdds/xtypes/type_representation/TypeObjectUtils.cpp
  src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
  src/cpp/rtps/domain/IDomainImpl.hpp
  src/cpp/rtps/domain/RTPSDomain.cpp
  src/cpp/rtps/domain/RTPSDomainExtras.cpp
  src/cpp/rtps/domain/RTPSDomainImpl.hpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/reader/StatefulReader.cpp
  src/cpp/rtps/reader/StatelessReader.cpp
  src/cpp/rtps/reader/WriterProxy.cpp
  src/cpp/rtps/writer/ReaderLocator.cpp
  src/cpp/rtps/writer/StatefulWriter.cpp
  src/cpp/rtps/writer/StatelessWriter.cpp
  src/cpp/source.cmake
  src/cpp/statistics/rtps/monitor-service/MonitorService.cpp
  test/blackbox/common/DDSBlackboxTestsDiscovery.cpp
  test/blackbox/common/RTPSBlackboxTestsBasic.cpp
  test/dds/communication/dyn_network/CMakeLists.txt
  test/dds/communication/dyn_network/cli.Dockerfile
  test/dds/communication/dyn_network/ds_init_no_interfaces.compose.yml
  test/dds/communication/dyn_network/dynamic_interfaces.compose.yml
  test/dds/communication/dyn_network/net-tools.Dockerfile
  test/mock/dds/DomainParticipantFactory/fastdds/dds/domain/DomainParticipantFactory.hpp
  test/mock/rtps/RTPSDomainImpl/rtps/RTPSDomainImpl.hpp
  test/mock/rtps/RTPSDomainImpl/rtps/domain/RTPSDomainImpl.hpp
  test/unittest/dds/publisher/CMakeLists.txt
  test/unittest/dds/xtypes/type_lookup_service/TypeLookupServiceTests.cpp
  test/unittest/rtps/reader/CMakeLists.txt
  test/unittest/statistics/dds/CMakeLists.txt
Labels: ready-to-merge, fast dds pro
