Repository eProsima/Fast-DDS, pull requests merged in 2025-05, with the labels that each got.

#5780 [23088] Solve Discovery Server race conditions
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
  src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
  src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
  test/blackbox/common/BlackboxTestsDiscovery.cpp
Labels: ready-to-merge

#5797 [23142] Add regression test checking type_information is always copied in `ProxyDatas` copies
  test/blackbox/common/DDSBlackboxTestsDiscovery.cpp
Labels: ci-pending

#5796 [23110] Address some compilation warnings with GCC latest
  src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterCompoundCondition.hpp
  src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterPredicate.hpp
  src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterValue.hpp
  src/cpp/rtps/reader/BaseReader.cpp
Labels: ready-to-merge

#5799 [23139] Add compilation with `GCC` latest to `fastdds_alternative_builds` Ubuntu CI
  .github/workflows/docker/ubuntu/alternative_builds/fastdds_gcc_latest.Dockerfile
  .github/workflows/reusable-ubuntu-ci.yml
Labels: ready-to-merge

#5813 [23183] Allow ResourceLimitsQos serialization method compatibility
  src/cpp/fastdds/core/policy/QosPoliciesSerializer.hpp
  src/cpp/rtps/builtin/data/ReaderProxyData.cpp
  src/cpp/rtps/builtin/data/WriterProxyData.cpp
  test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
Labels: ready-to-merge

#5818 [23169] Add `WireProtocolConfigQos` to optionals serialization and make `Monitor Service` always serialize optionals
  include/fastdds/rtps/attributes/RTPSParticipantAttributes.hpp
  src/cpp/fastdds/core/policy/ParameterSerializer.hpp
  src/cpp/fastdds/core/policy/QosPoliciesSerializer.hpp
  src/cpp/rtps/builtin/data/ParticipantProxyData.cpp
  src/cpp/rtps/builtin/data/ParticipantProxyData.hpp
  src/cpp/rtps/builtin/data/ReaderProxyData.cpp
  src/cpp/rtps/builtin/data/ReaderProxyData.hpp
  src/cpp/rtps/builtin/data/WriterProxyData.cpp
  src/cpp/rtps/builtin/data/WriterProxyData.hpp
  src/cpp/rtps/builtin/discovery/participant/PDP.cpp
  src/cpp/rtps/messages/CDRMessage.cpp
  src/cpp/rtps/messages/CDRMessage.hpp
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  src/cpp/rtps/participant/RTPSParticipantImpl.hpp
  src/cpp/statistics/rtps/messages/RTPSStatisticsMessages.hpp
  test/blackbox/common/DDSBlackboxTestsMonitorService.cpp
  test/blackbox/common/DDSBlackboxTestsParticipant.cpp
  test/mock/rtps/RTPSParticipantImpl/rtps/participant/RTPSParticipantImpl.hpp
  test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
  test/unittest/rtps/discovery/PDPTests.cpp
  versions.md
Labels: ci-pending

#5814 [23042] Bugfix: Properly delete secure endpoints if registration fails
  src/cpp/rtps/participant/RTPSParticipantImpl.cpp
  test/blackbox/CMakeLists.txt
  test/blackbox/common/RTPSBlackboxTests.cpp
  test/blackbox/common/RTPSBlackboxTestsSecurity.cpp
  test/blackbox/common/RTPSWithRegistrationReader.hpp
  test/blackbox/common/RTPSWithRegistrationWriter.hpp
Labels: ready-to-merge

#5817 [21427] Add references to documentation in mds
  PLATFORM_SUPPORT.md
  RELEASE_SUPPORT.md
Labels: ready-to-merge, no-test

#5821 [23196] Fix oss-fuzz `XMLParserTest` over `string_builder` being `nullptr` because `bound` was 0
  src/cpp/xmlparser/XMLDynamicParser.cpp
  test/unittest/xmlparser/XMLParserTests.cpp
  test/unittest/xmlparser/regressions/23196_profile_bin.xml
Labels: ci-pending

#5830 readme: update ROSin img links
  README.md
Labels: skip-ci

#5836 [22188] Remove 2.10.x from PR template
  .github/pull_request_template.md
Labels: skip-ci

#5837 [23230] Bugfix: Create RPC example participants with default profile
  examples/cpp/rpc/ClientApp.cpp
  examples/cpp/rpc/ServerApp.cpp
Labels: ci-pending
