Repository eProsima/Fast-DDS, pull requests merged in 2025-06, with the labels that each got.

#5842 [23252] Hotfix `add_multicast_locator` in readerproxydata
  src/cpp/rtps/builtin/data/ReaderProxyData.cpp
  test/blackbox/api/dds-pim/PubSubReader.hpp
  test/blackbox/api/dds-pim/PubSubWriter.hpp
  test/blackbox/common/BlackboxTestsDiscovery.cpp
  test/blackbox/common/BlackboxTestsPubSubBasic.cpp
  test/blackbox/common/DDSBlackboxTestsDiscovery.cpp
  test/blackbox/common/DDSBlackboxTestsPersistence.cpp
Labels: ci-pending

#5843 [23043] Fix ParticipantGenericMessage serialization
  src/cpp/rtps/messages/CDRMessage.cpp
  src/cpp/rtps/security/SecurityManager.cpp
  test/blackbox/CMakeLists.txt
  test/blackbox/common/BlackboxTestsSecurity.cpp
  test/blackbox/security_bug_participant_generic_message.xml
  test/certs/test_router/governance.smime
  test/certs/test_router/local_pub1_cert.pem
  test/certs/test_router/local_pub1_key.pem
  test/certs/test_router/main_ca_cert.pem
  test/certs/test_router/permissions.smime
  test/certs/test_router/router_cert.pem
  test/certs/test_router/router_key.pem
Labels: needs-review, ci-pending

#5853 [23269] Branch out 3.3.x
  .github/pull_request_template.md
  .github/workflows/mirror.yml
  .github/workflows/nightly-mac-3.2.x.yml
  .github/workflows/nightly-sanitizers-3.2.x.yml
  .github/workflows/nightly-ubuntu-3.2.x.yml
  .github/workflows/nightly-windows-3.2.x.yml
Labels: skip-ci

#5861 [23264] Feature: `DataWriter` sample prefilter
  include/fastdds/dds/publisher/DataWriter.hpp
  include/fastdds/dds/topic/IContentFilter.hpp
  include/fastdds/rtps/common/WriteParams.hpp
  src/cpp/fastdds/publisher/DataWriter.cpp
  src/cpp/fastdds/publisher/DataWriterImpl.cpp
  src/cpp/fastdds/publisher/DataWriterImpl.hpp
  test/blackbox/api/dds-pim/PubSubWriter.hpp
  test/blackbox/common/DDSBlackboxTestsContentFilter.cpp
  test/blackbox/common/DDSBlackboxTestsDataWriter.cpp
  test/unittest/statistics/dds/StatisticsDomainParticipantStatusQueryableTests/mock/fastdds/publisher/DataWriterImpl.hpp
  versions.md
Labels: ci-pending

#5863 Add ParticipantBuiltinTopicData header in Statistics DomainParticipant
  include/fastdds/statistics/dds/domain/DomainParticipant.hpp
Labels: ci-pending

#5867 [23265] Allow creation of built-in content filters with different type name
  src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterFactory.cpp
  test/blackbox/common/DDSBlackboxTestsContentFilter.cpp
  test/unittest/dds/topic/DDSSQLFilter/DDSSQLFilterTests.cpp
Labels: ci-pending

#5849 [23253] Split windows workflow in different test suites
  .github/workflows/nightly-windows-master.yml
  .github/workflows/reusable-windows-ci.yml
  .github/workflows/windows-ci.yml
Labels: ci-pending

#5879 [23253] Split windows workflow (3.2.x backport)
  .github/workflows/reusable-windows-ci.yml
  .github/workflows/windows-ci.yml
Labels: ci-pending

#5884 Correct CI Python fallback branch in 3.2.x
  .github/workflows/reusable-ubuntu-ci.yml
Labels: no-test, ci-pending

#5492 [22469] Avoid calling setIPv4 in TCPTransportInterface
  include/fastdds/utils/IPLocator.hpp
  src/cpp/rtps/transport/TCPTransportInterface.cpp
  src/cpp/utils/IPLocator.cpp
  test/unittest/transport/TCPv4Tests.cpp
  test/unittest/transport/TCPv6Tests.cpp
  test/unittest/utils/LocatorTests.cpp
Labels: needs-review, ci-pending

#5885 [23346] Add get_complete_type_object to `ITypeObjectRegistry`
  include/fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp
  src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterFactory.cpp
  src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.cpp
  src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.hpp
  test/mock/xtypes/TypeObjectRegistry/fastdds/xtypes/type_representation/TypeObjectRegistry.hpp
  test/unittest/dds/xtypes/type_representation/TypeObjectRegistryTests.cpp
  versions.md
Labels: ci-pending

#5891 [23362] Apply changes of uncrustify to all IPP files
  src/cpp/utils/thread_impl/thread_impl_win32.ipp
  src/cpp/utils/threading/threading_pthread.ipp
Labels: no-test, ci-pending

#5890 [22973] Support modules in IDL Parser
  src/cpp/fastdds/xtypes/dynamic_types/idl_parser/IdlGrammar.hpp
  src/cpp/fastdds/xtypes/dynamic_types/idl_parser/IdlModule.hpp
  src/cpp/fastdds/xtypes/dynamic_types/idl_parser/IdlParser.hpp
  test/feature/idl_parser/CMakeLists.txt
  test/feature/idl_parser/IdlParserTests.cpp
  test/feature/idl_parser/idl_extra_cases/extra_structures.idl
  test/feature/idl_parser/idl_extra_cases/extra_unions.idl
  versions.md
Labels: ci-pending

#5889 [23268] Add methods for TypeObject registration of RPC types
  include/fastdds/dds/rpc/RPCTypeObjectSupport.hpp
  src/cpp/CMakeLists.txt
  src/cpp/fastdds/rpc/RPCTypeObjectSupport.cpp
  src/cpp/fastdds/rpc/RPC_idl.md
  versions.md
Labels: ci-pending

#5851 [22593] Include all example tests in windows CI
  examples/cpp/benchmark/PublisherApp.cpp
  examples/cpp/configuration/CLIParser.hpp
  examples/cpp/delivery_mechanisms/CLIParser.hpp
  examples/cpp/delivery_mechanisms/PubSubApp.cpp
  examples/cpp/delivery_mechanisms/PubSubApp.hpp
  examples/cpp/delivery_mechanisms/PublisherApp.cpp
  examples/cpp/delivery_mechanisms/PublisherApp.hpp
  examples/cpp/discovery_server/ClientPublisherApp.cpp
  examples/cpp/xtypes/CLIParser.hpp
  examples/cpp/xtypes/PublisherApp.cpp
  examples/cpp/xtypes/PublisherApp.hpp
  test/examples/CMakeLists.txt
  test/examples/benchmark.compose.yml
  test/examples/configuration.compose.yml
  test/examples/delivery_mechanisms.compose.yml
  test/examples/delivery_mechanisms_isolated.compose.yml
  test/examples/discovery_server.compose.yml
  test/examples/security.compose.yml
  test/examples/static_edp_discovery.compose.yml
  test/examples/test_benchmark.py
  test/examples/test_configuration-I.py
  test/examples/test_configuration-II.py
  test/examples/test_configuration-III.py
  test/examples/test_configuration.py
  test/examples/test_delivery_mechanisms.py
  test/examples/test_delivery_mechanisms_isolated.py
  test/examples/test_discovery_server.py
  test/examples/test_security.py
  test/examples/test_static_edp_discovery.py
  test/examples/test_topic_instances.py
  test/examples/test_xtypes_complete.py
  test/examples/test_xtypes_minimal.py
  test/examples/topic_instances.compose.yml
  test/examples/xtypes_complete.compose.yml
  test/examples/xtypes_minimal.compose.yml
Labels: ci-pending

#5894 Update RPC example types and code
  examples/cpp/rpc/ServerApp.cpp
  examples/cpp/rpc/ServerApp.hpp
  examples/cpp/rpc/types/calculatorClient.cxx
  examples/cpp/rpc/types/calculatorPubSubTypes.cxx
  examples/cpp/rpc/types/calculatorServer.cxx
  examples/cpp/rpc/types/calculatorServer.hpp
  examples/cpp/rpc/types/calculatorServerImpl.hpp
  examples/cpp/rpc/types/calculatorTypeObjectSupport.cxx
  examples/cpp/rpc/types/calculatorTypeObjectSupport.hpp
Labels: ci-pending
